-- seed-gavlebukten.sql
-- Gavlebukten och Hoga kusten seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'gavlebukten';
DELETE FROM restaurants WHERE name IN (
  'Gavle Gasthamn', 'Soderhamn Gasthamn', 'Hudiksvall Gasthamn',
  'Sundsvall Gasthamn', 'Harnosand Gasthamn', 'Ulvon Gasthamn', 'Ornskoldsvik Gasthamn',
  'Ulvon Naturhamn', 'Hoga Kusten Naturhamn', 'Baronskar Naturhamn', 'Norrfallsviken Naturhamn',
  'Ulvon Vardshus', 'Harnosand Hamkrog', 'Sundsvall Restaurang', 'Gavle Hamnkrog',
  'Gavle Bunkring', 'Sundsvall Bunkring', 'Harnosand Bunkring', 'Ulvon Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Gavle Gasthamn', 'Gavle', 60.6749, 17.1413,
 'Gasthamn i Gavle, Norrlands port mot havet. Stor och valutrustad hamn med bra service och nara till stadens utbud.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['gavle','gasthamn','norrland','service'],
 'Norrlands port mot havet med bra service och stadsnara lage.',
 'marina', 'gavle-gasthamn', 'gavlebukten',
 ARRAY['marina','harbor_stop','stad'],
 ARRAY['transitseglare','familjer','norrlandsseglar'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Soderhamn Gasthamn', 'Soderhamn', 61.3003, 17.0603,
 'Gasthamn i Soderhamn vid Gavlebukten. Mellanstation langs Norrlandskusten med bra service och trivsam miljo.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['soderhamn','gasthamn','norrlandskusten','mellanstation'],
 'Bekam mellanstation langs Norrlandskusten.',
 'marina', 'soderhamn-gasthamn', 'gavlebukten',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['transitseglare','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hudiksvall Gasthamn', 'Hudiksvall', 61.7283, 17.1083,
 'Gasthamn i Hudiksvall, kand for sin vackra tradbebyggelse och levande kulturliv. Nara Halsninglands natur och kust.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['hudiksvall','gasthamn','kulturstad','tradbebyggelse'],
 'Charming norrlandsstad med tradbebyggelse och aktiv kulturscen.',
 'marina', 'hudiksvall-gasthamn', 'gavlebukten',
 ARRAY['marina','harbor_stop','kulturstad'],
 ARRAY['kulturintresserade','familjer','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Sundsvall Gasthamn', 'Sundsvall', 62.3908, 17.3069,
 'Gasthamn i Sundsvall, Norrlands metropol. Stor och modern stad med fullservice for seglare och bra utbud av restauranger.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['sundsvall','gasthamn','norrland','storstad'],
 'Norrlands storsta stad med modern gasthamn och bra service.',
 'marina', 'sundsvall-gasthamn', 'gavlebukten',
 ARRAY['marina','harbor_stop','storstad'],
 ARRAY['transitseglare','familjer','stadssokare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Harnosand Gasthamn', 'Harnosand', 62.6333, 17.9333,
 'Gasthamn i Harnosand, belaegen dar Angermanaven moeter Hoga kustenomradet. Liten charming stad med bra lage for Hoga kustenturister.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['harnosand','gasthamn','angermanaven','hoga_kusten'],
 'Porten till Hoga kusten vid Angermanavens mynning.',
 'marina', 'harnosand-gasthamn', 'gavlebukten',
 ARRAY['marina','harbor_stop','hoga_kusten'],
 ARRAY['naturintresserade','familjer','historieintresserade'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ulvon Gasthamn', 'Ulvon', 63.0167, 18.6500,
 'Gasthamn pa Ulvon, den kanda surastrommings-on. Autentisk fiskemiljo och folklig sommartradition. Populart mal for seglare.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['ulvon','gasthamn','surastromming','traditionsrik'],
 'Surastrommings-on med autentisk fiskemiljo och stark folklig tradition.',
 'marina', 'ulvon-gasthamn', 'gavlebukten',
 ARRAY['marina','harbor_stop','traditionsrik'],
 ARRAY['kulturintresserade','mat_intresserade','seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ornskoldsvik Gasthamn', 'Ornskoldsvik', 63.2908, 18.7156,
 'Gasthamn i Ornskoldsvik vid Hoga kusten. Bra utgangspunkt for seglatser i Hoga kustens klippiga skargard.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['ornskoldsvik','gasthamn','hoga_kusten','skargard'],
 'Norra Hoga kustens hamn med tillgang till dramatisk klippskargard.',
 'marina', 'ornskoldsvik-gasthamn', 'gavlebukten',
 ARRAY['marina','harbor_stop','hoga_kusten'],
 ARRAY['naturintresserade','seglare','aventyrare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ulvon Naturhamn', 'Ulvon', 63.0050, 18.6600,
 'Naturhamn pa sodra Ulvon med skyddade vikar och vacker kustmiljo.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['ulvon','naturhamn','ankring','kust'],
 'Naturhamn med vacker kustmiljo pa Ulvon.',
 'anchorage', 'ulvon-naturhamn', 'gavlebukten',
 ARRAY['anchorage','nature'],
 ARRAY['naturintresserade','seglare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hoga Kusten Naturhamn', 'Hoga Kusten', 62.8000, 18.1000,
 'Naturhamn i Hoga kustens UNESCO-omrade. Dramatiska klippor och djupa fjordar skapar unika ankringsmojligheter.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['hoga_kusten','naturhamn','ankring','unesco'],
 'Dramatisk ankring i UNESCO-omrade med Skandinaviens hogsta kustklippor.',
 'anchorage', 'hoga-kusten-naturhamn', 'gavlebukten',
 ARRAY['anchorage','nature','unesco'],
 ARRAY['naturintresserade','aventyrare','fotografer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Baronskar Naturhamn', 'Baronskar', 62.9000, 18.4000,
 'Avlagen naturhamn pa Baronskar i Angermanlanden. Ostord natur och tystnad mitt i Hoga kustens skargard.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['baronskar','naturhamn','ankring','ostord'],
 'Ostord naturankring i Angermanlanden med vildmark och tystnad.',
 'anchorage', 'baronskar-naturhamn', 'gavlebukten',
 ARRAY['anchorage','nature','remote'],
 ARRAY['aventyrare','naturintresserade','lugnsokande'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Norrfallsviken Naturhamn', 'Norrfallsviken', 62.7500, 17.9500,
 'Naturhamn i Norrfallsviken, en av Hoga kustens vackraste vikar. Skyddad ankring med imponerande klippomgivning.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['norrfallsviken','naturhamn','ankring','klippor'],
 'Vacker fjordvik med Hoga kustens dramatiska klipplandskap.',
 'anchorage', 'norrfallsviken-naturhamn', 'gavlebukten',
 ARRAY['anchorage','nature','fjord'],
 ARRAY['naturintresserade','fotografer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ulvon Vardshus', 'Ulvon', 63.0169, 18.6503,
 'Traditionsrikt vardshus pa Ulvon kand for surstrommingskiva och enkel norrlandsk mat. Folklig sommaratmosfar.',
 'Juni-Augusti: 11:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['ulvon','vardshus','surstrommingskiva','folklig'],
 'Surstrommingskiva och norrlandsk mat i folklig sommaratmosfar.',
 'restaurant', 'ulvon-vardshus', 'gavlebukten',
 ARRAY['restaurang','traditionsrik','lokalmad'],
 ARRAY['kulturintresserade','mat_intresserade','seglare'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Harnosand Hamkrog', 'Harnosand', 62.6335, 17.9336,
 'Hamkrog i Harnosand med norrlandsk mat och utsikt mot Angermanaven. Bra mat for seglare pa vag mot Hoga kusten.',
 'Juni-Augusti: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['harnosand','hamkrog','norrlandsmad','angermanaven'],
 'Norrlandsk mat med utsikt over Angermanaven.',
 'restaurant', 'harnosand-hamkrog', 'gavlebukten',
 ARRAY['restaurang','norrlandsmad'],
 ARRAY['seglare','naturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Sundsvall Restaurang', 'Sundsvall', 62.3910, 17.3072,
 'Restaurang i Sundsvalls hamn med god mat och levande stadsmiljo. Bra val for seglare som soker stadsutsatta.',
 'Helaret: 11:00-22:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['sundsvall','restaurang','hamn','stadsmiljo'],
 'God mat i Norrlands storsta stads hamnmiljo.',
 'restaurant', 'sundsvall-restaurang', 'gavlebukten',
 ARRAY['restaurang'],
 ARRAY['stadssokare','transitseglare'],
 ARRAY['restaurang','bar'],
 'year_round', 'high'),

(gen_random_uuid(), 'Gavle Hamnkrog', 'Gavle', 62.6751, 17.1416,
 'Krog i Gavles hamn med god mat och norrlandsk karaktar. Populart sommarstopp vid Norrlands porten.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['gavle','hamnkrog','norrland','sommar'],
 'God mat vid Norrlands porten mot havet.',
 'restaurant', 'gavle-hamnkrog', 'gavlebukten',
 ARRAY['restaurang'],
 ARRAY['seglare','familjer'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Gavle Bunkring', 'Gavle', 60.6746, 17.1409,
 'Marinbunkring i Gavle. Aret-runt-bransle for seglare vid Norrlandskustens storsta hamn.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['gavle','bransle','helaret'],
 NULL,
 'fuel_station', 'gavle-bunkring', 'gavlebukten',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Sundsvall Bunkring', 'Sundsvall', 62.3905, 17.3065,
 'Branslestation i Sundsvall for seglare pa Norrlandskusten.',
 'April-Oktober: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['sundsvall','bransle','norrland'],
 NULL,
 'fuel_station', 'sundsvall-bunkring', 'gavlebukten',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'year_round', 'high'),

(gen_random_uuid(), 'Harnosand Bunkring', 'Harnosand', 62.6330, 17.9329,
 'Branslestopp i Harnosand pa vagen mot Hoga kusten och Ulvon.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['harnosand','bransle','hoga_kusten_led'],
 NULL,
 'fuel_station', 'harnosand-bunkring', 'gavlebukten',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ulvon Bunkring', 'Ulvon', 63.0163, 18.6496,
 'Branslestation pa Ulvon. Viktigt tankstopp i norra Hoga kustens skargard.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['ulvon','bransle','hoga_kusten'],
 NULL,
 'fuel_station', 'ulvon-bunkring', 'gavlebukten',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
