DELETE FROM restaurants WHERE archipelago_region = 'stockholm';

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Sandhamns Gasthamn', 'Sandhamn', 59.2872, 18.9136,
 'Stor gasthamn med fullservice, barer och restauranger. KSSS har sitt sate har.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['sandhamn','ksss','gasthamn','fullservice'],
 'Att lagga till i Sandhamn en varm sommarnatt med hela flottan runt dig.',
 'marina', 'sandhamns-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','social'],
 ARRAY['boaters','couples','friends'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','bar','fuel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Uto Gasthamn', 'Uto', 58.9569, 18.3014,
 'Valorganiserad gasthamn pa Uto. Cykelvanlig o med gruva och naturstigar.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['uto','sodra skargarden','cykel','gruva'],
 'Cykla runt Uto och avsluta med en ol i hamnen.',
 'marina', 'uto-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','nature'],
 ARRAY['boaters','family','cyclists'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','bike_rental'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Vaxholms Gasthamn', 'Vaxholm', 59.4024, 18.3519,
 'Gasthamn i Vaxholms stad, porten till skargarden. Nara butiker och Vaxholms fastning.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['vaxholm','fastning','gasthamn','service'],
 'Perfekt startpunkt eller stopphamn i en levande skargårdsstad.',
 'marina', 'vaxholms-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','town'],
 ARRAY['boaters','family','tourists'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Dalaro Gasthamn', 'Dalaro', 59.1283, 18.3967,
 'Charmig gasthamn i Dalaro. Historisk smastad med trabatar och stämning fran forr.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['dalaro','gasthamn','historisk','trabatar'],
 'Tidlosa kanslan av gammalt skargardsliv.',
 'marina', 'dalaro-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','historic'],
 ARRAY['boaters','family','history'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Finnhamnens Gasthamn', 'Finnhamn', 59.4908, 18.8183,
 'Naturskon gasthamn i mellersta skargarden. Vandrarhem, cafe och fantastiska klippor.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['finnhamn','mellanskargarden','vandrarhem','klippor'],
 'Simma fran klipporna och kak en bulle pa kafeet.',
 'marina', 'finnhamnens-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','nature'],
 ARRAY['boaters','hikers','budget'],
 ARRAY['guest_dock','electricity','water','shower','toilet','cafe','hostel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grinda Gasthamn', 'Grinda', 59.3875, 18.7044,
 'Naturreservat i mellanskargarden med valskott gasthamn. Egen gard och mysigt vardshus.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['grinda','naturreservat','vardshus','mellanskargarden'],
 'Klappa lamm pa garden, bada och at middag pa vardshuset.',
 'marina', 'grinda-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','nature','family'],
 ARRAY['family','boaters','hikers'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Moja Gasthamn', 'Moja', 59.4494, 18.9092,
 'Lantlig o i yttre mellanskargarden. Lanthandel, cafe och genuint obo-liv.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['moja','lanthandel','genuint','yttre skargard'],
 'En av de fa oar med fastboende och lanthandel.',
 'marina', 'moja-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','authentic'],
 ARRAY['boaters','family','solo'],
 ARRAY['guest_dock','electricity','water','toilet','cafe','shop'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nynashamns Gasthamn', 'Nynashamn', 58.9044, 17.9467,
 'Stor genomfartsgasthamn. Perfekt for Ostersjöpassage mot Gotland och Aland.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800'],
 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
 ARRAY['nynashamn','gasthamn','ostersjо','genomfart'],
 'Sista hamnen med full service innan du lamnar skargarden.',
 'marina', 'nynashamns-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','provisioning'],
 ARRAY['boaters','offshore','passage'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','fuel'],
 'year_round', 'high'),

(gen_random_uuid(), 'Bulleron Gasthamn', 'Bulleron', 59.2625, 18.7883,
 'Avlagsen gasthamn i ytterskargarden. Naturreservat med minimal service och maximal natur.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['bulleron','ytterskargard','naturreservat','avlagsen'],
 'Ytterskårgardens tystnad – havet oppnar sig mot Ostersjön.',
 'marina', 'bulleron-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','nature','remote'],
 ARRAY['boaters','solo','adventurous'],
 ARRAY['guest_dock','toilet','outhouse'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Fjaderholmarnas Gasthamn', 'Fjaderholmarna', 59.3283, 18.2233,
 'Stockholms narmaste skargardso, 25 minuter fran Slussen. Bryggeri och utsikt mot Nacka.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1568454537842-d933259bb258?w=800'],
 'https://images.unsplash.com/photo-1568454537842-d933259bb258?w=800',
 ARRAY['fjaderholmarna','stockholm','nara','bryggeri'],
 'Hang kvar i Stockholm men anda ute i skargard pa 25 minuter.',
 'marina', 'fjaderholmarnas-gasthamn', 'stockholm',
 ARRAY['marina','harbor_stop','day_trip'],
 ARRAY['day_trippers','boaters','city'],
 ARRAY['guest_dock','electricity','water','toilet','restaurant','bar','shop'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Enskar Naturhamn', 'Enskar', 58.8942, 18.5578,
 'Isolerad klippo i sodra ytterskargarden. Ingen el, inget vatten – bara natur.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['enskar','naturhamn','vild','ytterskargard'],
 'Fortoj vid en klippa utan en manniska i sikte.',
 'anchorage', 'enskar-naturhamn', 'stockholm',
 ARRAY['anchorage','nature','remote'],
 ARRAY['adventurous','solo','sailing'],
 ARRAY['outhouse'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Huvudskar Naturhamn', 'Huvudskar', 58.9633, 18.6514,
 'En av de mest avlagsna oarna i Stockholmsskargarden. Fyr och naturreservat.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800'],
 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
 ARRAY['huvudskar','fyr','ytterskargard','avlagsen'],
 'Att na Huvudskar ar en prestation – tystnaden och fyren ar belöningen.',
 'anchorage', 'huvudskar-naturhamn', 'stockholm',
 ARRAY['anchorage','nature','remote','lighthouse'],
 ARRAY['adventurous','offshore','experienced'],
 ARRAY['outhouse'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Svenska Hogarna Naturhamn', 'Svenska Hogarna', 59.4442, 19.5019,
 'Extrem ytterskargard, 5 timmars segling fran Stockholm. Fyr och unik natur.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['svenska hogarna','fyr','ytterskargard','avlagsen'],
 'Komma in i la vid Hogarna och se fyren lysa ar magisk.',
 'anchorage', 'svenska-hogarna-naturhamn', 'stockholm',
 ARRAY['anchorage','nature','remote','lighthouse','extreme'],
 ARRAY['experienced','offshore','adventurous'],
 ARRAY['outhouse'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Rodloga Naturhamn', 'Rodloga', 59.5506, 18.9092,
 'Popular ankringsplats i norra skargarden och ett av Roslagens parlhalsband.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['rodloga','roslagen','naturhamn','norra skargarden'],
 'Roslagens bast bevarade hemlighet.',
 'anchorage', 'rodloga-naturhamn', 'stockholm',
 ARRAY['anchorage','nature','hidden_gem'],
 ARRAY['boaters','nature_lovers','couples'],
 ARRAY['outhouse'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Arholma Naturhamn', 'Arholma', 59.8528, 19.1375,
 'Nordligaste utposten i Stockholms skargard. O med lotsstation och fyr.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['arholma','nordligaste','lots','fyr','roslagen'],
 'Slutpunkten for den som seglar norrut i Roslagen.',
 'anchorage', 'arholma-naturhamn', 'stockholm',
 ARRAY['anchorage','nature','lighthouse','remote'],
 ARRAY['adventurous','sailing','history'],
 ARRAY['guest_dock','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Sandhamns Vardshus', 'Sandhamn', 59.2883, 18.9117,
 'Anrikt vardshus i hjartat av Sandhamn. Klassisk skargårdsmat och frukostbuffe.',
 'Maj-September: dagligen 08-22.', 'Frukostbuffe, rakor, stromming, husmanskost.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['sandhamn','vardshus','klassisk','frukost'],
 'Morgonfrukost pa Sandhamns Vardshus med havet precis utanfor.',
 'restaurant', 'sandhamns-vardshus', 'stockholm',
 ARRAY['restaurant','breakfast','harbor_stop'],
 ARRAY['boaters','tourists','couples'],
 ARRAY['restaurant','bar','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grinda Vardshus', 'Grinda', 59.3883, 18.7061,
 'Stilfullt vardshus pa Grinda. Sasongsmat fran gardens odlingar, vilt och fisk.',
 'Maj-September: dagligen 12-21.', 'Gardens gronsaker, vilt, fisk, sasongsratter.',
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['grinda','gard','naturreservat','sasongsmat','vilt'],
 'Middag pa Grindas vardshus – narodlat fran ons egna odlingar.',
 'restaurant', 'grinda-vardshus', 'stockholm',
 ARRAY['restaurant','farm_to_table','nature'],
 ARRAY['food_lovers','couples','boaters'],
 ARRAY['restaurant','toilet','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fjaderholmarnas Krog', 'Fjaderholmarna', 59.3267, 18.2217,
 'Stockholms basta skargårdsrestaurang. Klassisk fisk och skaldjur med utsikt mot Stockholm.',
 'Maj-September: dagligen 11-22.', 'Rakor, hummer, stromming, sasongsratter.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['fjaderholmarna','stockholmsvy','rakor','hummer'],
 'Rakmacka med vy mot Nackafjarden och Stockholms silhuett.',
 'restaurant', 'fjaderholmarnas-krog', 'stockholm',
 ARRAY['restaurant','fish','harbor_stop','iconic'],
 ARRAY['day_trippers','couples','boaters','food_lovers'],
 ARRAY['restaurant','bar','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Uto Vardshus', 'Uto', 58.9581, 18.3028,
 'Klassiskt vardshus pa Uto med skargårdsmat. Nara gruvan och cykelleder.',
 'Maj-September: dagligen 11-21.', 'Husmanskost, fisk, rakor, lokalt ol.',
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['uto','vardshus','gruva','historia','cykling'],
 'Lunch pa Uto Vardshus efter en cykelrunda till gruvan.',
 'restaurant', 'uto-vardshus', 'stockholm',
 ARRAY['restaurant','harbor_stop','historic'],
 ARRAY['cyclists','boaters','family'],
 ARRAY['restaurant','toilet','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Moja Lanthandel och Cafe', 'Moja', 59.4503, 18.9083,
 'En av Skårgardens sista lanthandlar med kafe. Hembakat och genuint obo-bemotande.',
 'Maj-September: dagligen 09-18.', 'Hembakade bullar, smorgas, kaffe, glass.',
 ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800'],
 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
 ARRAY['moja','lanthandel','kafe','hembakat','genuint'],
 'Ta en fika pa Mojas lanthandel – en av de sista i sitt slag.',
 'restaurant', 'moja-lanthandel-cafe', 'stockholm',
 ARRAY['restaurant','cafe','shop','authentic'],
 ARRAY['boaters','locals','family'],
 ARRAY['shop','cafe','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Waxholms Hotell och Restaurang', 'Vaxholm', 59.4031, 18.3511,
 'Vaxholms klassiska hotellrestaurang direkt vid kajen med utsikt mot fastningen.',
 'April-Oktober: dagligen 11-22.', 'Rakor, fisk, husmanskost, burgare.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['vaxholm','hotell','uteservering','fastning','klassisk'],
 'Lunch i Vaxholm med fastningen som kuliss.',
 'restaurant', 'waxholms-hotell-restaurang', 'stockholm',
 ARRAY['restaurant','harbor_stop','classic'],
 ARRAY['tourists','boaters','family'],
 ARRAY['restaurant','bar','toilet','hotel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Sandhamn Marin Bransle', 'Sandhamn', 59.2869, 18.9128,
 'Branslestation i Sandhamns gasthamn. Diesel och bensin for fritidsbatar.',
 'Maj-September: 07-20.', NULL,
 ARRAY['https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800'],
 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800',
 ARRAY['sandhamn','bransle','diesel','bensin'],
 NULL,
 'fuel_station', 'sandhamn-marin-bransle', 'stockholm',
 ARRAY['fuel','marina'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','petrol'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Vaxholm Bransle och Marina', 'Vaxholm', 59.4019, 18.3508,
 'Branslestation och marin service i Vaxholms hamn.',
 'April-Oktober: 07-19.', NULL,
 ARRAY['https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800'],
 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800',
 ARRAY['vaxholm','bransle','marinaservice','diesel'],
 NULL,
 'fuel_station', 'vaxholm-bransle-marina', 'stockholm',
 ARRAY['fuel','marina','service'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','petrol','boat_service'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nynashamn Marinbransle', 'Nynashamn', 58.9039, 17.9472,
 'Fullsortimentstation i Nynashamns gasthamn. Bra infor Ostersjöpassage.',
 'April-Oktober: 06-21.', NULL,
 ARRAY['https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800'],
 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800',
 ARRAY['nynashamn','bransle','diesel','fullservice'],
 NULL,
 'fuel_station', 'nynashamn-marinbransle', 'stockholm',
 ARRAY['fuel','marina','provisioning'],
 ARRAY['boaters','offshore'],
 ARRAY['fuel','diesel','petrol','water'],
 'year_round', 'high'),

(gen_random_uuid(), 'Dalaro Marina Bransle', 'Dalaro', 59.1278, 18.3961,
 'Branslestation i Dalaro marina. Diesel och bensin.',
 'Maj-September: 07-19.', NULL,
 ARRAY['https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800'],
 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800',
 ARRAY['dalaro','bransle','diesel'],
 NULL,
 'fuel_station', 'dalaro-marina-bransle', 'stockholm',
 ARRAY['fuel','marina'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','petrol'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Uto Marina Bransle', 'Uto', 58.9572, 18.3022,
 'Bransle i Uto gasthamn. Diesel och bensin.',
 'Maj-September: 08-18.', NULL,
 ARRAY['https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800'],
 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800',
 ARRAY['uto','bransle','diesel'],
 NULL,
 'fuel_station', 'uto-marina-bransle', 'stockholm',
 ARRAY['fuel','marina'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','petrol'],
 'summer_only', 'high');
