-- seed-aland.sql
-- Alands skargard seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'aland';
DELETE FROM restaurants WHERE name IN (
  'Mariehamn Gasthamn', 'Eckero Gasthamn', 'Kokar Gasthamn',
  'Foglo Gasthamn', 'Kumlinge Gasthamn', 'Brando Gasthamn', 'Langnäs Gasthamn',
  'Kokar Naturhamn', 'Brando Naturhamn', 'Eckero Naturhamn', 'Foglo Naturhamn',
  'Mariehamn Hamn Bar', 'Kokar Vardshus', 'Kumlinge Krog', 'Eckero Restaurang',
  'Mariehamn Bunkring', 'Langnäs Bunkring', 'Kokar Bunkring', 'Eckero Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Mariehamn Gasthamn', 'Aland', 60.0972, 19.9347,
 'Stor gasthamn i Mariehamn, Alands huvudstad. Viktig knutpunkt for seglare i Ostersjön med bra service, restorer och levande hamnmiljo.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['mariehamn','gasthamn','aland','knutpunkt'],
 'Alands huvudstad och seglarknutpunkt i mitten av Ostersjön.',
 'marina', 'mariehamn-gasthamn', 'aland',
 ARRAY['marina','harbor_stop','service','stad'],
 ARRAY['alla_seglare','transitseglare','turister'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Eckero Gasthamn', 'Aland', 60.2239, 19.5553,
 'Gasthamn i Eckero pa vaestra Aland. Post- och tullhuset fran 1828 ar ett av Nordens basta exempel pa empire-arkitektur. Faerja till Sverige.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['eckero','gasthamn','posthuset','klassisk'],
 'Vaestersta Aland med historiskt posthus och faerja till Sverige.',
 'marina', 'eckero-gasthamn', 'aland',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['kulturintresserade','transitseglare','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kokar Gasthamn', 'Kokar', 59.9167, 20.9000,
 'Gasthamn pa Kokar, den avsides alandska on med stark sjofartstradition. Unik miljo med medeltida kyrkoruin och ostord natur.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['kokar','gasthamn','medeltid','avskild'],
 'Avskild ytterö med medeltida kyrkoruin och autentisk sjöfartsmiljo.',
 'marina', 'kokar-gasthamn', 'aland',
 ARRAY['marina','harbor_stop','historisk','avskild'],
 ARRAY['historieintresserade','aventyrare','naturintresserade'],
 ARRAY['guest_dock','electricity','water','shower','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Foglo Gasthamn', 'Foglo', 60.0333, 20.4000,
 'Gasthamn pa Foglo i ostra Aland. Obefolkad natur, breda vikar och fin fiskemiljo. En av Alands skonaste ogrupper.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['foglo','gasthamn','natur','ogrupp'],
 'En av Alands skonaste ogrupper med ostord natur.',
 'marina', 'foglo-gasthamn', 'aland',
 ARRAY['marina','harbor_stop','natur'],
 ARRAY['naturintresserade','fiskare','lugnsokande'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kumlinge Gasthamn', 'Kumlinge', 60.2500, 20.8167,
 'Gasthamn pa Kumlinge i ostra Alands skargard. Pittoresk by med kyrka och levande bygdeatmosfar.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['kumlinge','gasthamn','pittoresk','bygd'],
 'Pittoresk alandsby med kyrka och autentisk bygdestämning.',
 'marina', 'kumlinge-gasthamn', 'aland',
 ARRAY['marina','harbor_stop','pittoresk'],
 ARRAY['kulturintresserade','par','lugnsokande'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Brando Gasthamn', 'Brando', 60.4167, 21.0500,
 'Gasthamn pa Brando i nordostra Aland. Yttersta bebodda omradet mot Aboskargarden med stark sjofartshistoria.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['brando','gasthamn','ytterst','sjöfartshistoria'],
 'Yttersta Aland mot Abo med stark sjofartshistoria.',
 'marina', 'brando-gasthamn', 'aland',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['historieintresserade','aventyrare','seglare'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Langnäs Gasthamn', 'Aland', 60.1167, 20.2833,
 'Gasthamn i Langnäs pa ostra Aland. Viktig faerjeterminal och tankstopp for seglare pa vag mot Finland och Sverige.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['langnäs','gasthamn','farjeterminal','tankstopp'],
 'Praktisk faerjeterminal och tankstopp i ostra Aland.',
 'marina', 'langnäs-gasthamn', 'aland',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['transitseglare','alla_seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kokar Naturhamn', 'Kokar', 59.9100, 20.9100,
 'Naturankring runt Kokar med dramatisk ytterskargardsmiljo och ostord natur.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['kokar','naturhamn','ankring','ostord'],
 'Ostord naturankring pa avskild ytterö.',
 'anchorage', 'kokar-naturhamn', 'aland',
 ARRAY['anchorage','nature','remote'],
 ARRAY['aventyrare','naturintresserade','lugnsokande'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Brando Naturhamn', 'Brando', 60.4100, 21.0600,
 'Naturankring pa Brando med vacker natur och skyddade vikar i nordostra Aland.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['brando','naturhamn','ankring','nordost'],
 'Naturankring i yttre nordostra Aland.',
 'anchorage', 'brando-naturhamn', 'aland',
 ARRAY['anchorage','nature'],
 ARRAY['naturintresserade','aventyrare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Eckero Naturhamn', 'Aland', 60.2200, 19.5400,
 'Naturankring vid Eckerostrand med sandstrand och skyddad ankring i vaestra Aland.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['eckero','naturhamn','ankring','sandstrand'],
 'Sandstrand och skyddad naturankring i vaestra Aland.',
 'anchorage', 'eckero-naturhamn', 'aland',
 ARRAY['anchorage','nature','sandstrand'],
 ARRAY['familjer','badglada'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Foglo Naturhamn', 'Foglo', 60.0300, 20.4100,
 'Naturankring pa Foglo med ostord alandsk skargardsnatur.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['foglo','naturhamn','ankring','ostord'],
 'Ostord alandsk skargard med tystnad och vild natur.',
 'anchorage', 'foglo-naturhamn', 'aland',
 ARRAY['anchorage','nature'],
 ARRAY['lugnsokande','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Mariehamn Hamn Bar', 'Aland', 60.0974, 19.9350,
 'Bar och restaurang i Mariehamns gasthamn. Levande sommaratmosfar med internationell seglarpublik och god mat.',
 'April-Oktober: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['mariehamn','hamnbar','internationell','seglare'],
 'Levande hamnbar med internationell seglarpublik i Alands huvudstad.',
 'restaurant', 'mariehamn-hamn-bar', 'aland',
 ARRAY['restaurang','bar'],
 ARRAY['seglare','turister','par'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kokar Vardshus', 'Kokar', 59.9169, 20.9003,
 'Traditionsrikt vardshus pa Kokar med alandsk husmanskost. Genuint och avskilt med stark lokal karaktar.',
 'Juni-Augusti: 12:00-20:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['kokar','vardshus','husmanskost','genuint'],
 'Genuint alandskt vardshus med husmanskost pa avskild ytterö.',
 'restaurant', 'kokar-vardshus', 'aland',
 ARRAY['restaurang','traditionsrik','lokalmad'],
 ARRAY['aventyrare','mat_intresserade','kulturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kumlinge Krog', 'Kumlinge', 60.2503, 20.8170,
 'Liten lokal krog i Kumlinge med alandsk mat och genuint bygdelivs-stämning.',
 'Juni-Augusti: 12:00-20:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['kumlinge','krog','lokalt','bygdeliv'],
 'Lokal krog med genuint alandskt bygdelivs-stämning.',
 'restaurant', 'kumlinge-krog', 'aland',
 ARRAY['restaurang','lokalmad'],
 ARRAY['kulturintresserade','par'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Eckero Restaurang', 'Aland', 60.2241, 19.5556,
 'Restaurang i Eckero med alandsk mat och havsutsikt. Nara det historiska posthuset.',
 'Maj-September: 11:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['eckero','restaurang','posthus','havsutsikt'],
 'Alandsk mat med havsutsikt nara historiska posthuset.',
 'restaurant', 'eckero-restaurang', 'aland',
 ARRAY['restaurang'],
 ARRAY['turister','kulturintresserade','familjer'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Mariehamn Bunkring', 'Aland', 60.0969, 19.9341,
 'Marinbunkring i Mariehamn. Aret-runt-service och ett av Ostersjöns viktigaste tankstopp.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['mariehamn','bransle','helaret','ostersjon'],
 NULL,
 'fuel_station', 'mariehamn-bunkring', 'aland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Langnäs Bunkring', 'Aland', 60.1163, 20.2826,
 'Branslestation i Langnäs. Populart tankstopp vid faerjeterminalen i ostra Aland.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['langnäs','bransle','farjeterminal'],
 NULL,
 'fuel_station', 'langnäs-bunkring', 'aland',
 ARRAY['bransle'],
 ARRAY['alla_seglare','transitseglare'],
 ARRAY['bransle','diesel','bensin'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kokar Bunkring', 'Kokar', 59.9163, 20.8994,
 'Branslestopp pa Kokar for seglare i yttre Alands skargard.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['kokar','bransle','ytterst'],
 NULL,
 'fuel_station', 'kokar-bunkring', 'aland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Eckero Bunkring', 'Aland', 60.2235, 19.5547,
 'Branslestation i Eckero for seglare pa vag mot Sverige.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['eckero','bransle','sverige_led'],
 NULL,
 'fuel_station', 'eckero-bunkring', 'aland',
 ARRAY['bransle'],
 ARRAY['alla_seglare','transitseglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high');
