-- seed-bohuslan-mitt.sql
-- Mellersta Bohuslan seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'bohuslan_mitt';
DELETE FROM restaurants WHERE name IN (
  'Lysekil Gasthamn', 'Smogen Gasthamn', 'Kungshamn Gasthamn',
  'Fiskebackskil Gasthamn', 'Grundsund Gasthamn', 'Hunnebostrand Gasthamn', 'Bovallstrand Gasthamn',
  'Koster Sund Naturhamn', 'Lysekil Naturhamn', 'Brastads Naturhamn', 'Hallo Naturhamn',
  'Smogen Fiskekrog', 'Lysekil Hamn Bar', 'Fiskebackskil Vardshus', 'Kungshamn Restaurang',
  'Lysekil Bunkring', 'Smogen Bunkring', 'Kungshamn Bunkring', 'Hunnebostrand Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Lysekil Gasthamn', 'Lysekil', 58.2747, 11.4358,
 'Stor gasthamn i Lysekil vid Gullmarsfjorden. Havsforskarnas stad med marinbiologisk station. Bra service och aktiv sommarmiljo.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['lysekil','gasthamn','marinbiologi','gullmarfjorden'],
 'Havsforskarnas stad med marinbiologisk station och dramatisk fjordmiljo.',
 'marina', 'lysekil-gasthamn', 'bohuslan_mitt',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['familjer','naturintresserade','turister'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Smogen Gasthamn', 'Smogen', 58.3528, 11.2233,
 'Ikonisk gasthamn pa Smogen med farglada sjobodarna langs bryggan. En av Sveriges mest fotograferade hamnmiljoer. Levande sommaratmosfar.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['smogen','gasthamn','sjobodarna','ikonisk'],
 'Sveriges mest fotograferade hamnbild med fargglada sjobodarna langs havsbryggan.',
 'marina', 'smogen-gasthamn', 'bohuslan_mitt',
 ARRAY['marina','harbor_stop','iconic','pittoresk'],
 ARRAY['turister','par','fotografer','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','bar','wifi','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kungshamn Gasthamn', 'Kungshamn', 58.3667, 11.2500,
 'Gasthamn i Kungshamn, grannorten till Smogen. Mer lugnt alternativ med bra service och nara till Smogen for dagsturer.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['kungshamn','gasthamn','lugnt','smogen_nara'],
 'Lugnt alternativ till Smogen med bra service.',
 'marina', 'kungshamn-gasthamn', 'bohuslan_mitt',
 ARRAY['marina','harbor_stop','lugn'],
 ARRAY['familjer','lugnsokande','transitseglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fiskebackskil Gasthamn', 'Fiskebackskil', 58.2450, 11.4550,
 'Charmig gasthamn i Fiskebackskil vid Gullmarsfjorden. Konstnarskolonins hemort med pittoresk traahusmiljo och bra mat.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['fiskebackskil','gasthamn','konstnarsby','pittoresk'],
 'Historisk konstnarsby med pittoresk traahusmiljo och god mat.',
 'marina', 'fiskebackskil-gasthamn', 'bohuslan_mitt',
 ARRAY['marina','harbor_stop','kulturstad'],
 ARRAY['par','kulturintresserade','naturintresserade'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grundsund Gasthamn', 'Grundsund', 58.1833, 11.4833,
 'Liten gasthamn i Grundsund med autentisk fiskehamnsanda. En av de minst kanda men vackraste hamnarna i mellersta Bohuslan.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['grundsund','gasthamn','autentisk','fiskehamn'],
 'Autentisk fiskehamn med pittoresk karaktar och lite turism.',
 'marina', 'grundsund-gasthamn', 'bohuslan_mitt',
 ARRAY['marina','harbor_stop','autentisk'],
 ARRAY['par','naturintresserade','lugnsokande'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hunnebostrand Gasthamn', 'Hunnebostrand', 58.4167, 11.3000,
 'Gasthamn i Hunnebostrand med bra service och narheten till Kosterhavets nationalpark. Bra bas for dykning och naturupplevelser.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['hunnebostrand','gasthamn','kosterhavet','dykning'],
 'Bas for Kosterhavets nationalpark med bra service och dykningsmojligheter.',
 'marina', 'hunnebostrand-gasthamn', 'bohuslan_mitt',
 ARRAY['marina','harbor_stop','nationalpark'],
 ARRAY['dykare','naturintresserade','seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','dive_shop'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Bovallstrand Gasthamn', 'Bovallstrand', 58.7000, 11.3000,
 'Liten och trivsam gasthamn i Bovallstrand. Lugn Bohuslan-atmosfar med bra natur i omgivningen.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['bovallstrand','gasthamn','lugn','bohuslan'],
 'Lugn hamn med typisk Bohuslan-karaktar.',
 'marina', 'bovallstrand-gasthamn', 'bohuslan_mitt',
 ARRAY['marina','harbor_stop','lugn'],
 ARRAY['familjer','lugnsokande'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Koster Sund Naturhamn', 'Koster', 58.8800, 11.0500,
 'Naturhamn i Koster sund vid nationalparken. Rik marin fauna och utmarkta dykningsmojligheter i Europas frodigaste hav.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['koster','naturhamn','nationalpark','dykning'],
 'Nationalpark med Europas frodigaste hav och utmarkt dykning.',
 'anchorage', 'koster-sund-naturhamn', 'bohuslan_mitt',
 ARRAY['anchorage','nature','nationalpark','diving'],
 ARRAY['dykare','naturintresserade','aventyrare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Lysekil Naturhamn', 'Lysekil', 58.2600, 11.4200,
 'Naturankring vid Gullmarsfjordens vaestra strand. Dramatisk fjordmiljo med djupt vatten och klippor.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['lysekil','naturhamn','ankring','gullmarfjorden'],
 'Dramatisk fjordankring med djupt vatten och klippomgivning.',
 'anchorage', 'lysekil-naturhamn', 'bohuslan_mitt',
 ARRAY['anchorage','nature','fjord'],
 ARRAY['naturintresserade','dykare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Brastads Naturhamn', 'Brastad', 58.3500, 11.4500,
 'Skyddad naturankring nara Brastad. Typisk Bohuslan innerskargard med ronn och klipphall.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['brastad','naturhamn','ankring','innerskargard'],
 'Skyddad ankring med typisk Bohuslan innerskargardsmiljo.',
 'anchorage', 'brastads-naturhamn', 'bohuslan_mitt',
 ARRAY['anchorage','nature'],
 ARRAY['familjer','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Hallo Naturhamn', 'Hallo', 58.3500, 11.1500,
 'Naturhamn pa Hallo i ytterkusten. Bilfri naturreservats-o med sjofaglar och dramatisk ytterskargardsmiljo.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['hallo','naturhamn','ankring','naturreservat'],
 'Naturreservat med bilfri o och rik fagelliv i ytterskargarden.',
 'anchorage', 'hallo-naturhamn', 'bohuslan_mitt',
 ARRAY['anchorage','nature','birdwatching'],
 ARRAY['fagelskadare','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Smogen Fiskekrog', 'Smogen', 58.3530, 11.2236,
 'Klassisk fiskekrog pa Smogen direkt vid hamnbryggan. Dagsfangst av rakor, krabba och fisk serveras i typisk Bohuslan-stil.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['smogen','fiskekrog','dagsfangst','rakor'],
 'Dagsfangad fisk och rakor vid Smogens ikoniska hamnbrygga.',
 'restaurant', 'smogen-fiskekrog', 'bohuslan_mitt',
 ARRAY['restaurang','fisk','skaldjur','ikonisk'],
 ARRAY['turister','mat_intresserade','familjer'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Lysekil Hamn Bar', 'Lysekil', 58.2749, 11.4361,
 'Bar och restaurang i Lysekils hamn med utsikt over Gullmarsfjorden. God mat och sommarlig stadsambians.',
 'April-Oktober: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['lysekil','hamnbar','gullmarfjorden','sommar'],
 'Sommarbar med fjordutsikt i Lysekil.',
 'restaurant', 'lysekil-hamn-bar', 'bohuslan_mitt',
 ARRAY['restaurang','bar'],
 ARRAY['par','turister','seglare'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fiskebackskil Vardshus', 'Fiskebackskil', 58.2452, 11.4553,
 'Traditionsrikt vardshus i Fiskebackskil med god mat och havsutsikt. Omgivet av konstnarsbyns pittoreska traahusmiljo.',
 'Maj-September: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['fiskebackskil','vardshus','konstnarsby','havsutsikt'],
 'God mat i traditionsrik konstnarsmiljo.',
 'restaurant', 'fiskebackskil-vardshus', 'bohuslan_mitt',
 ARRAY['restaurang','traditionsrik'],
 ARRAY['kulturintresserade','par','naturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kungshamn Restaurang', 'Kungshamn', 58.3669, 11.2503,
 'Restaurang i Kungshamn med fokus pa lokala skaldjur och fisk. Lugnt alternativ till det fullpackade Smogen.',
 'Juni-Augusti: 12:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['kungshamn','restaurang','skaldjur','lugnt'],
 'God skaldjursmat i lugnt alternativ nara Smogen.',
 'restaurant', 'kungshamn-restaurang', 'bohuslan_mitt',
 ARRAY['restaurang','skaldjur'],
 ARRAY['familjer','par','lugnsokande'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Lysekil Bunkring', 'Lysekil', 58.2744, 11.4354,
 'Marinbunkring i Lysekil. Aret-runt-service for seglare vid Gullmarsfjorden.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['lysekil','bransle','helaret'],
 NULL,
 'fuel_station', 'lysekil-bunkring', 'bohuslan_mitt',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Smogen Bunkring', 'Smogen', 58.3525, 11.2230,
 'Branslestation i Smogen. Viktigt tankstopp vid en av Bohuslands populaeraste hamnar.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['smogen','bransle','popular'],
 NULL,
 'fuel_station', 'smogen-bunkring', 'bohuslan_mitt',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kungshamn Bunkring', 'Kungshamn', 58.3664, 11.2496,
 'Branslestation i Kungshamn for seglare i mellanbohuslan.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['kungshamn','bransle'],
 NULL,
 'fuel_station', 'kungshamn-bunkring', 'bohuslan_mitt',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hunnebostrand Bunkring', 'Hunnebostrand', 58.4163, 11.2996,
 'Branslestopp i Hunnebostrand for seglare pa vag mot Kosterhavets nationalpark.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['hunnebostrand','bransle','kosterhavet'],
 NULL,
 'fuel_station', 'hunnebostrand-bunkring', 'bohuslan_mitt',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
