DELETE FROM restaurants WHERE archipelago_region = 'blekinge';
DELETE FROM restaurants WHERE name IN ('Karlskrona Gasthamn', 'Aspoe Naturhamn', 'Tjurkoe Gasthamn', 'Hassloe Gasthamn', 'Torhamn Gasthamn', 'Kristianopel Gasthamn', 'Hanoe Naturhamn', 'Utlaengan Naturhamn', 'Karlshamn Gasthamn', 'Nogersund Naturhamn', 'Karlskrona Restaurang', 'Aspoe Krogen', 'Hanoe Fishshack', 'Torhamn Restaurang', 'Karlskrona Bensin', 'Torhamn Bensin', 'Kristianopel Bensin', 'Karlskrona Naturreservat', 'Hanoe Naturreservat');

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Karlskrona Gasthamn', 'Karlskrona', 56.1611, 15.5898,
 'Huvudgasthamn for Blekinge skaergarden. Fullservice med elektricitet och dusch. Centralt belaegen med bra butiker och restauranger.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['karlskrona','gasthamn','fullservice','huvudhamn'],
 'Starta din Blekinge-tur fran denna porten till skaergarden.',
 'marina', 'karlskrona-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop','town'],
 ARRAY['boaters','family','tourists'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','fuel','supermarket'],
 'year_round', 'high'),

(gen_random_uuid(), 'Aspoe Gasthamn', 'Aspoe', 56.2645, 15.3287,
 'Valkott gasthamn pa Aspoe. Bra restaurang och fint att lagga till for natten.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['aspoe','gasthamn','restaurang','mellanskargarden'],
 'Rosta din fisk och at under stammarna pa Aspoe.',
 'marina', 'aspoe-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop','dining'],
 ARRAY['boaters','families','foodies'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Tjurkoe Gasthamn', 'Tjurkoe', 56.3412, 15.2156,
 'Traditionell gasthamn med gammal arbetarstad-kaensla. Verkstad for mindre repationer.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['tjurkoe','gasthamn','verkstad','traditionell'],
 'Uppleva autentisk obo-kultur fran forr.',
 'marina', 'tjurkoe-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop','historic'],
 ARRAY['boaters','history','authentic'],
 ARRAY['guest_dock','water','toilet','repair','fuel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hassloe Gasthamn', 'Hassloe', 56.2987, 15.4521,
 'Liten valkott gasthamn pa Hassloe. Perfekt stopphamn pa vagen till Hanoe.',
 'Maj-September: 06:00-22:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['hassloe','gasthamn','liten','familjevannlig'],
 'Stanna till och bada innan vidare fard.',
 'marina', 'hassloe-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop','family'],
 ARRAY['boaters','family','couples'],
 ARRAY['guest_dock','water','toilet','swimming'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Torhamn Gasthamn', 'Torhamn', 56.0845, 15.6732,
 'Gasthamn med aktiviteter och badsporter. Kite- och windsurfing-centrum.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['torhamn','gasthamn','vind','sportklubb'],
 'Vind- och kitesurfing paradis i sydost.',
 'marina', 'torhamn-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop','sports'],
 ARRAY['boaters','water_sports','families'],
 ARRAY['guest_dock','electricity','water','shower','toilet','equipment_rental'],
 'year_round', 'high'),

(gen_random_uuid(), 'Kristianopel Gasthamn', 'Kristianopel', 56.3845, 14.9876,
 'Gasthamn i gamla Kristianopels hamn. Forsvunnen stad nu uppataeckt genom badforsok.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['kristianopel','gasthamn','historisk','forsvunnen'],
 'Dyka pa forsvunnen stad fran 1656.',
 'marina', 'kristianopel-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop','historic','diving'],
 ARRAY['boaters','divers','history'],
 ARRAY['guest_dock','water','toilet','dive_shop'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Karlshamn Gasthamn', 'Karlshamn', 56.1456, 15.7234,
 'Gasthamn i Karlshamns innerstad. Stora butiker och restauranger i promenaden.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['karlshamn','gasthamn','stad','shopping'],
 'Huvudstad i syd-Blekinge med bra handel och noje.',
 'marina', 'karlshamn-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop','town','shopping'],
 ARRAY['boaters','family','tourists'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket'],
 'year_round', 'high'),

(gen_random_uuid(), 'Nogersund Naturhamn', 'Nogersund', 56.0234, 15.5467,
 'Naturhamn for mindre fartyg. Vilt och ostort men fralsande for dem som soeker stillhet.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['nogersund','naturhamn','vild','fridfullt'],
 'Naturens egen hamn for fridfullt ankarchet.',
 'anchorage', 'nogersund-naturhamn', 'blekinge',
 ARRAY['anchorage','nature','quiet'],
 ARRAY['boaters','nature_lovers','solo'],
 ARRAY['natural_anchor','diving'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Aspoe Naturhamn', 'Aspoe', 56.2645, 15.3287,
 'Naturhamn i Aspoe skaergarden. Bada och fiska. Ingen service men autentisk obo-kaensla.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['aspoe','naturhamn','autentisk','fiske'],
 'Fiska och bada under Aspoes stjarnor.',
 'anchorage', 'aspoe-naturhamn', 'blekinge',
 ARRAY['anchorage','nature','fishing'],
 ARRAY['boaters','fishermen','nature_lovers'],
 ARRAY['natural_anchor','fishing_ground'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Hanoe Naturhamn', 'Hanoe', 56.4123, 15.1234,
 'Ostort naturhamn pa Hanoe. Bada fran vita sandstrander och ta en promenad genom naturreservatet.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['hanoe','naturhamn','sandstrand','naturreservat'],
 'Vita strandliv och naturstigar pa Hanoe.',
 'anchorage', 'hanoe-naturhamn', 'blekinge',
 ARRAY['anchorage','nature','beach','hiking'],
 ARRAY['boaters','hikers','families','nature_lovers'],
 ARRAY['natural_anchor','swimming','nature_trails'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Utlaengan Naturhamn', 'Utlaengan', 56.3567, 15.0456,
 'Vild och vacker naturhamn. Endast for frodyga sjomans hjarta. Spannande utflykt for den modig.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['utlaengan','naturhamn','vild','aventyr'],
 'Utforska Blekings vildaste skaergard.',
 'anchorage', 'utlaengan-naturhamn', 'blekinge',
 ARRAY['anchorage','nature','adventure'],
 ARRAY['boaters','adventurers','nature_lovers'],
 ARRAY['natural_anchor'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Karlskrona Restaurang', 'Karlskrona', 56.1611, 15.5898,
 'Klassisk skaergardsrestaurang med hemlagad mat och lokalt fisk. Utsikt over hamnen.',
 'Tisdags-Sondag: 11:00-22:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['karlskrona','restaurang','fisk','hemlagad'],
 'Dilig och aepplig till sjoman hemma fran havet.',
 'restaurant', 'karlskrona-restaurang', 'blekinge',
 ARRAY['restaurant','dining','seafood'],
 ARRAY['boaters','families','foodies'],
 ARRAY['seating','bar','parking'],
 'year_round', 'high'),

(gen_random_uuid(), 'Aspoe Krogen', 'Aspoe', 56.2645, 15.3287,
 'Lantlig krog med aepplock och rust. God hemlagad mat och varmt mottagande.',
 'Fredags-Sondag: 17:00-23:00, Sommaren: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['aspoe','krog','lantlig','hemlagad'],
 'Frisk skaergardsmat i rustik miljo.',
 'restaurant', 'aspoe-krogen', 'blekinge',
 ARRAY['restaurant','dining','authentic'],
 ARRAY['boaters','families','locals'],
 ARRAY['seating','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hanoe Fishshack', 'Hanoe', 56.4123, 15.1234,
 'Liten fiskkoket pa Hanoe strand. Ferskfangad fisk grilld dagligt. Bord utomhus vid stranden.',
 'Maj-September: 11:00-20:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['hanoe','fiskkoket','grill','strand'],
 'Ferskfangad fisk direkt fran baeten.',
 'restaurant', 'hanoe-fishshack', 'blekinge',
 ARRAY['restaurant','dining','seafood','casual'],
 ARRAY['boaters','families','beachgoers'],
 ARRAY['outdoor_seating','beach_access'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Torhamn Restaurang', 'Torhamn', 56.0845, 15.6732,
 'Modern restaurang vid hamnen med havsutsikt. Bra vindselskrivning och lokal mat.',
 'April-Oktober: 17:00-23:00, Sommaren: 11:00-23:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['torhamn','restaurang','modern','lokal'],
 'Dina efter spannande dag av vind och salt.',
 'restaurant', 'torhamn-restaurang', 'blekinge',
 ARRAY['restaurant','dining','modern','waterfront'],
 ARRAY['boaters','water_sports','families','foodies'],
 ARRAY['seating','bar','parking'],
 'year_round', 'high'),

(gen_random_uuid(), 'Karlskrona Bensin', 'Karlskrona', 56.1611, 15.5898,
 'Bensinstationen vid huvudhamnen. Diesel och bensin for motorbatar.',
 'April-Oktober: 07:00-19:00, Juli: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['karlskrona','bensin','diesel','bransle'],
 NULL,
 'fuel_station', 'karlskrona-bensin', 'blekinge',
 ARRAY['fuel','service'],
 ARRAY['boaters'],
 ARRAY['fuel_dock','payment_systems'],
 'year_round', 'high'),

(gen_random_uuid(), 'Torhamn Bensin', 'Torhamn', 56.0845, 15.6732,
 'Bensinstationen vid Torhamns hamn. Diesel och bensin. Oppet sommaren.',
 'Maj-September: 08:00-18:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['torhamn','bensin','diesel','bransle'],
 NULL,
 'fuel_station', 'torhamn-bensin', 'blekinge',
 ARRAY['fuel','service'],
 ARRAY['boaters'],
 ARRAY['fuel_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kristianopel Bensin', 'Kristianopel', 56.3845, 14.9876,
 'Liten bensinstoppad vid Kristianopels hamn. Bransle for motorbatar.',
 'Juni-Augusti: 09:00-17:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['kristianopel','bensin','diesel','liten'],
 NULL,
 'fuel_station', 'kristianopel-bensin', 'blekinge',
 ARRAY['fuel','service'],
 ARRAY['boaters'],
 ARRAY['fuel_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Karlskrona Naturreservat', 'Karlskrona', 56.1611, 15.5898,
 'Naturreservat pa fastlandet intill Karlskrona. Vandringstigar, fagelornitologi och fint landskapp.',
 'Oppet aaret runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['karlskrona','naturreservat','vandringsled','fagelornitologi'],
 'Utforska Blekings enastaaende natur.',
 'nature', 'karlskrona-naturreservat', 'blekinge',
 ARRAY['nature','hiking','birdwatching'],
 ARRAY['hikers','nature_lovers','photographers'],
 ARRAY['nature_trails','parking','viewpoints'],
 'year_round', 'high'),

(gen_random_uuid(), 'Hanoe Naturreservat', 'Hanoe', 56.4123, 15.1234,
 'Skyddat naturomrade med vackra sand- och grusstrander. Rik fagelfauna och vandringstigar.',
 'Oppet aaret runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['hanoe','naturreservat','fagelfauna','strand'],
 'Natur och faglar pa en underbar o.',
 'nature', 'hanoe-naturreservat', 'blekinge',
 ARRAY['nature','hiking','birdwatching','beach'],
 ARRAY['hikers','nature_lovers','photographers','families'],
 ARRAY['nature_trails','beaches','viewpoints'],
 'year_round', 'high');
