-- seed-halland.sql
-- Halland vastkysten seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'halland';
DELETE FROM restaurants WHERE name IN (
  'Varberg Gasthamn', 'Falkenberg Gasthamn', 'Halmstad Gasthamn',
  'Tylösand Gasthamn', 'Asa Gasthamn', 'Traslovslage Gasthamn', 'Getteroe Gasthamn',
  'Getteroe Naturhamn', 'Bua Naturhamn', 'Skrea Strand Naturhamn', 'Tylösand Naturhamn',
  'Varberg Hamn Bar', 'Falkenberg Restaurang', 'Halmstad Hamnkrog', 'Tylösand Havsbad',
  'Varberg Bunkring', 'Falkenberg Bunkring', 'Halmstad Bunkring', 'Asa Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Varberg Gasthamn', 'Varberg', 57.1058, 12.2508,
 'Gasthamn i Varberg, kand for sin festning och kallbadhuset. Aktiv semesterstad med levande sommaratmosfar och bra service for seglare.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['varberg','gasthamn','festning','kallbadhus'],
 'Hallands viktigaste hamnstad med festning, kallbadhus och levande stadsambians.',
 'marina', 'varberg-gasthamn', 'halland',
 ARRAY['marina','harbor_stop','stad'],
 ARRAY['familjer','turister','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Falkenberg Gasthamn', 'Falkenberg', 56.9058, 12.4911,
 'Charmig gasthamn i Falkenberg vid Ätrans mynning. Gammalt stadscentrum med medeltida stenkyrka och bra laxfiskemojligheter.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['falkenberg','gasthamn','historisk','laxfiske'],
 'Historisk stad vid avmynning med klassisk bebyggelse och bra laxfiske.',
 'marina', 'falkenberg-gasthamn', 'halland',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['familjer','historieintresserade','fiskare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Halmstad Gasthamn', 'Halmstad', 56.6742, 12.8578,
 'Stor gasthamn i Halmstad vid Nidans mynning. Hallands storsta stad med bra service, handel och kustliv.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['halmstad','gasthamn','storstad','handel'],
 'Hallands metropol med stor gasthamn och fullservice vid Nidans mynning.',
 'marina', 'halmstad-gasthamn', 'halland',
 ARRAY['marina','harbor_stop','storstad'],
 ARRAY['transitseglare','familjer','stadssokare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Tylosand Gasthamn', 'Tylosand', 56.6500, 12.7333,
 'Gasthamn vid Tylosand, Hallands lyxigaste semesterort. Beromda hotell, vita sandstrander och aktiv sommarmiljo.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['tylosand','gasthamn','lyxort','sandstrand'],
 'Lyxig semesterort med vita sandstrander och beromda havshotellet.',
 'marina', 'tylosand-gasthamn', 'halland',
 ARRAY['marina','harbor_stop','lyxort'],
 ARRAY['par','lyxsokande','turister'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','bar','spa'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Asa Gasthamn', 'Asa', 57.3500, 12.1333,
 'Populart sommarstopp vid Asa norr om Varberg. Kombination av kust och landsbygd med bra badmojligheter.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['asa','gasthamn','sommarstopp','bad'],
 'Sommarstopp med bra bad och kustmiljo norr om Varberg.',
 'marina', 'asa-gasthamn', 'halland',
 ARRAY['marina','harbor_stop','bad'],
 ARRAY['familjer','badglada','sommarseglar'],
 ARRAY['guest_dock','electricity','water','toilet','badstrand'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Traslovslage Gasthamn', 'Traslovslage', 57.0500, 12.2000,
 'Charmig fiskehamn vid Traslovslage soer om Varberg. Autentisk miljo med sjobodarna och hantverksbutiker.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['traslovslage','gasthamn','fiskehamn','sjobodarna'],
 'Autentisk fiskehamn med sjobodsmiljo och hantverksbutiker.',
 'marina', 'traslovslage-gasthamn', 'halland',
 ARRAY['marina','harbor_stop','autentisk'],
 ARRAY['par','kulturintresserade','lugnsokande'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Getteroe Gasthamn', 'Getteroe', 57.1200, 12.2000,
 'Gasthamn pa Getteroe naturreservat nara Varberg. Skyddad natur och bra simstallen omger hamnen.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['getteroe','gasthamn','naturreservat','simning'],
 'Naturreservat med skyddad hamn och bra bad.',
 'marina', 'getteroe-gasthamn', 'halland',
 ARRAY['marina','harbor_stop','naturreservat'],
 ARRAY['naturintresserade','familjer'],
 ARRAY['guest_dock','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Getteroe Naturhamn', 'Getteroe', 57.1150, 12.1950,
 'Naturhamn pa Getteroe naturreservat. Skyddat ankringsomrade med naturupplevelser.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['getteroe','naturhamn','ankring','naturreservat'],
 'Skyddad ankring i naturreservat.',
 'anchorage', 'getteroe-naturhamn', 'halland',
 ARRAY['anchorage','nature','naturreservat'],
 ARRAY['naturintresserade','familjer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Bua Naturhamn', 'Bua', 57.0800, 12.2200,
 'Naturankring vid Bua fiskehamn. Typisk Hallandskust med sandstrand och lugna vikar.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['bua','naturhamn','ankring','sandstrand'],
 'Naturankring vid sandstrand pa Hallandskusten.',
 'anchorage', 'bua-naturhamn', 'halland',
 ARRAY['anchorage','nature','sandstrand'],
 ARRAY['familjer','badglada'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Skrea Strand Naturhamn', 'Falkenberg', 56.8800, 12.4700,
 'Naturankring vid Skrea strand soer om Falkenberg. En av Hallands finaste sandstrander som bakgrund.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['skrea','naturhamn','ankring','sandstrand'],
 'Ankring vid Hallands vackraste sandstrand.',
 'anchorage', 'skrea-strand-naturhamn', 'halland',
 ARRAY['anchorage','nature','sandstrand'],
 ARRAY['badglada','familjer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Tylosand Naturhamn', 'Tylosand', 56.6450, 12.7200,
 'Naturankring vid Tylosands nordliga sida. Vit sandstrand och oppen Kattegatt-utsikt.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['tylosand','naturhamn','ankring','sandstrand'],
 'Oppen ankring vid vita sandstrander.',
 'anchorage', 'tylosand-naturhamn', 'halland',
 ARRAY['anchorage','nature','sandstrand'],
 ARRAY['par','badglada'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Varberg Hamn Bar', 'Varberg', 57.1060, 12.2511,
 'Bar och restaurang i Varbergs hamn med utsikt mot festningen. God mat och levande sommarambians.',
 'April-Oktober: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['varberg','hamnbar','festningsutsikt','sommar'],
 'God mat och festningsutsikt i Varbergs levande hamn.',
 'restaurant', 'varberg-hamn-bar', 'halland',
 ARRAY['restaurang','bar'],
 ARRAY['par','turister','familjer'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Falkenberg Restaurang', 'Falkenberg', 56.9060, 12.4914,
 'Restaurang i Falkenberg med lokal mat och laxen fran avan. God kvalitet i historisk miljo.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['falkenberg','restaurang','lax','lokalmad'],
 'Lokal mat med lax fran Atran i historisk miljo.',
 'restaurant', 'falkenberg-restaurang', 'halland',
 ARRAY['restaurang','lokalmad'],
 ARRAY['par','familjer','mat_intresserade'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Halmstad Hamnkrog', 'Halmstad', 56.6744, 12.8581,
 'Krog i Halmstads hamn med bred meny och havsutsikt. Populart tillhall for bade seglare och stadsbor.',
 'Helaret: 11:00-22:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['halmstad','hamnkrog','bred_meny','havsutsikt'],
 'Bred meny och havsutsikt i Hallands storsta stad.',
 'restaurant', 'halmstad-hamnkrog', 'halland',
 ARRAY['restaurang'],
 ARRAY['transitseglare','stadssokare','familjer'],
 ARRAY['restaurang','bar'],
 'year_round', 'high'),

(gen_random_uuid(), 'Tylosand Havsbad', 'Tylosand', 56.6502, 12.7336,
 'Beromda havshotell och restaurang pa Tylosand. Fine dining med havsutsikt och lyxig atmosfar.',
 'Maj-September: 12:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['tylosand','havsbad','fine_dining','lyxig'],
 'Lyxig fine dining med havsutsikt pa Hallands mest exklusiva semesterort.',
 'restaurant', 'tylosand-havsbad', 'halland',
 ARRAY['restaurang','fine_dining','lyxig'],
 ARRAY['par','lyxsokande','specialtillfallen'],
 ARRAY['restaurang','bar','spa'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Varberg Bunkring', 'Varberg', 57.1055, 12.2504,
 'Marinbunkring i Varberg. Helaret-service for seglare langs Hallandskusten.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['varberg','bransle','helaret'],
 NULL,
 'fuel_station', 'varberg-bunkring', 'halland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Falkenberg Bunkring', 'Falkenberg', 56.9055, 12.4908,
 'Branslestation i Falkenberg for seglare pa vag langs Hallandskusten.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['falkenberg','bransle'],
 NULL,
 'fuel_station', 'falkenberg-bunkring', 'halland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Halmstad Bunkring', 'Halmstad', 56.6739, 12.8574,
 'Marinbunkring i Halmstad. Aret-runt-station i Hallands storsta stad.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['halmstad','bransle','helaret'],
 NULL,
 'fuel_station', 'halmstad-bunkring', 'halland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Asa Bunkring', 'Asa', 57.3496, 12.1329,
 'Branslestopp vid Asa norr om Varberg.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['asa','bransle'],
 NULL,
 'fuel_station', 'asa-bunkring', 'halland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
