-- seed-sodra-ostersjon.sql
-- Sodra Ostersjon (Hanobukten, Skane) seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'sodra_ostersjon';
DELETE FROM restaurants WHERE name IN (
  'Simrishamn Gasthamn', 'Ystad Gasthamn', 'Ahus Gasthamn',
  'Kristianstad Gasthamn', 'Kiviks Hamn', 'Brantevik Gasthamn', 'Falsterbo Gasthamn',
  'Hanobukten Naturhamn', 'Ravlunda Naturhamn', 'Kaseberga Naturhamn', 'Abbekas Naturhamn',
  'Simrishamn Fiskekrog', 'Ystad Hamn Bar', 'Ahus Restaurang', 'Kaseberga Krog',
  'Simrishamn Bunkring', 'Ystad Bunkring', 'Ahus Bunkring', 'Falsterbo Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Simrishamn Gasthamn', 'Simrishamn', 55.5567, 14.3550,
 'Gasthamn i Simrishamn, en av Skanes vackraste kuststaeder. Rikt konstliv, bra restauranger och levande hamnmiljo vid Ostersjons oppna vatten.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['simrishamn','gasthamn','konststad','skaane'],
 'Konstig kuststad med levande hamn och rikt kulturliv.',
 'marina', 'simrishamn-gasthamn', 'sodra_ostersjon',
 ARRAY['marina','harbor_stop','kulturstad'],
 ARRAY['kulturintresserade','par','turister'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Ystad Gasthamn', 'Ystad', 55.4286, 13.8200,
 'Gasthamn i Ystad, kand fran Wallander-serien. Medeltida stad med korsvirkeshus och aktiv hamnmiljo. Farja till Bornholm och Polen.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['ystad','gasthamn','wallander','medeltid'],
 'Wallander-stadens hamn med medeltida miljo och aktivt farjelage.',
 'marina', 'ystad-gasthamn', 'sodra_ostersjon',
 ARRAY['marina','harbor_stop','kulturstad'],
 ARRAY['kulturintresserade','turister','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','ferry'],
 'year_round', 'high'),

(gen_random_uuid(), 'Ahus Gasthamn', 'Ahus', 55.9272, 14.3083,
 'Gasthamn i Ahus vid Helge as mynning. Sommarhampnad kand for absolut vodka och vita sandstrander. Aktiv sommaratmosfar.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['ahus','gasthamn','sandstrand','absolutvodka'],
 'Sommarhamn med vita sandstrander och stark sommartradition.',
 'marina', 'ahus-gasthamn', 'sodra_ostersjon',
 ARRAY['marina','harbor_stop','sommarmiljo'],
 ARRAY['badglada','familjer','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','badstrand'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kristianstad Gasthamn', 'Kristianstad', 56.0333, 14.1500,
 'Gasthamn i Kristianstad vid Helge a. Storstoer stad med rik historia som startpunkt for seglatser langs nordost-Skanes kust.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['kristianstad','gasthamn','historisk','startpunkt'],
 'Historisk stad vid Helge a med bra hamn for kustseglats.',
 'marina', 'kristianstad-gasthamn', 'sodra_ostersjon',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['historieintresserade','transitseglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kiviks Hamn', 'Kivik', 55.6833, 14.2000,
 'Liten gasthamn i Kivik, kand for aepplen och Kiviks musteri. Charmig kustort med bra bade- och kulturupplevelser.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['kivik','gasthamn','aepplen','musteri'],
 'Charmig aappleort med musteri och vacker kustnatur.',
 'marina', 'kiviks-hamn', 'sodra_ostersjon',
 ARRAY['marina','harbor_stop','aepple'],
 ARRAY['par','mat_intresserade','naturintresserade'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Brantevik Gasthamn', 'Brantevik', 55.5100, 14.3500,
 'Pittoresk liten fiskehamn vid Brantevik soer om Simrishamn. En av Skanes mest charmiga fiskeby med autentisk atmosfar.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['brantevik','gasthamn','fiskeby','pittoresk'],
 'En av Skanes vackraste fiskehysbyar med autentisk atmosfar.',
 'marina', 'brantevik-gasthamn', 'sodra_ostersjon',
 ARRAY['marina','harbor_stop','pittoresk'],
 ARRAY['par','fotografer','kulturintresserade'],
 ARRAY['guest_dock','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Falsterbo Gasthamn', 'Falsterbo', 55.3833, 12.8333,
 'Gasthamn pa Falsterboneset, Sveriges sydvaestligaste kust. Kand for fagelsafari och sandstrand. Transithamn pa vag in och ut ur Ostersjon.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['falsterbo','gasthamn','fagelsafari','sydvastligast'],
 'Sydvaestligaste kustpunkten med fagelsafari och sandstrand.',
 'marina', 'falsterbo-gasthamn', 'sodra_ostersjon',
 ARRAY['marina','harbor_stop','faglar'],
 ARRAY['fagelskadare','naturintresserade','transitseglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hanobukten Naturhamn', 'Hanobukten', 55.9500, 14.5000,
 'Naturankring i Hanobukten med oppen Ostersjomiljo. Dramatisk kust med klipphall och sandstrand.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['hanobukten','naturhamn','ankring','ostersjon'],
 'Oppen Ostersjomiljo med dramatisk kust.',
 'anchorage', 'hanobukten-naturhamn', 'sodra_ostersjon',
 ARRAY['anchorage','nature','ostersjon'],
 ARRAY['erfarna_seglare','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Ravlunda Naturhamn', 'Ravlunda', 55.7500, 14.2000,
 'Naturankring vid Ravlundas kust med oppen sandstrandsmiljo och vindskyddade vikar.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['ravlunda','naturhamn','ankring','sandstrand'],
 'Naturankring vid sandstrand pa skaansk ost-kust.',
 'anchorage', 'ravlunda-naturhamn', 'sodra_ostersjon',
 ARRAY['anchorage','nature','sandstrand'],
 ARRAY['familjer','badglada'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kaseberga Naturhamn', 'Kaseberga', 55.3833, 14.0500,
 'Naturankring vid Kaseberga nedanfor Ales stenar. UNESCO-narheten ger unik kulturell kontext till ankringen.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['kaseberga','naturhamn','ankring','ales_stenar'],
 'Ankring nedanfor Ales stenar, ett av Sveriges mest dramatiska fornminnen.',
 'anchorage', 'kaseberga-naturhamn', 'sodra_ostersjon',
 ARRAY['anchorage','nature','kulturarv'],
 ARRAY['historieintresserade','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Abbekas Naturhamn', 'Abbekas', 55.4500, 13.6000,
 'Liten naturankring vid Abbekas pa sydkusten. Typisk Skanekust med sandstrand och oppen Ostersjoutsikt.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['abbekas','naturhamn','ankring','sydkusten'],
 'Liten naturankring pa Skanes sydkust.',
 'anchorage', 'abbekas-naturhamn', 'sodra_ostersjon',
 ARRAY['anchorage','nature'],
 ARRAY['lugnsokande','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Simrishamn Fiskekrog', 'Simrishamn', 55.5569, 14.3553,
 'Klassisk fiskekrog i Simrishamn med dagsfangst fran lokala fiskebatar. Torsk, sill och skaldjur serveras enkelt och gott.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['simrishamn','fiskekrog','dagsfangst','torsk'],
 'Autentisk fiskekrog med dagsfangst fran Simrishamns batar.',
 'restaurant', 'simrishamn-fiskekrog', 'sodra_ostersjon',
 ARRAY['restaurang','fisk','autentisk'],
 ARRAY['mat_intresserade','par','seglare'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ystad Hamn Bar', 'Ystad', 55.4288, 13.8203,
 'Bar och restaurang i Ystads hamn med utsikt mot Ostersjons horisont. God mat och levande ambians i Wallander-stadens hamn.',
 'April-Oktober: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['ystad','hamnbar','wallander','ostersjoutsikt'],
 'Hamn-bar i Wallander-stads historiska hamn med Ostersjoutsikt.',
 'restaurant', 'ystad-hamn-bar', 'sodra_ostersjon',
 ARRAY['restaurang','bar'],
 ARRAY['turister','par','stadssokare'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ahus Restaurang', 'Ahus', 55.9274, 14.3086,
 'Restaurang i Ahus med lokalmeny och sandstrandsatmosfar. Serverar havsmat och grillat i levande sommarmiljo.',
 'Juni-Augusti: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['ahus','restaurang','sommar','sandstrand'],
 'Sommarrestaurang med havsmat och sandstrandsambians.',
 'restaurant', 'ahus-restaurang', 'sodra_ostersjon',
 ARRAY['restaurang','sommarmad'],
 ARRAY['badglada','familjer','par'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kaseberga Krog', 'Kaseberga', 55.3835, 14.0503,
 'Liten krog vid Kaseberga fiskehamn nedanfor Ales stenar. Enkel mat i unikt lage med dramatisk utsikt.',
 'Juni-Augusti: 11:00-20:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['kaseberga','krog','ales_stenar','dramatisk_utsikt'],
 'Enkel mat i unikt lage nedanfor Ales stenar.',
 'restaurant', 'kaseberga-krog', 'sodra_ostersjon',
 ARRAY['restaurang','unikt_lage'],
 ARRAY['historieintresserade','naturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Simrishamn Bunkring', 'Simrishamn', 55.5563, 14.3546,
 'Marinbunkring i Simrishamn. Diesel och bensin for seglare vid Skanes ostkust.',
 'April-Oktober: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['simrishamn','bransle','ostkust'],
 NULL,
 'fuel_station', 'simrishamn-bunkring', 'sodra_ostersjon',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Ystad Bunkring', 'Ystad', 55.4283, 13.8196,
 'Branslestation i Ystad. Aret-runt-service vid aktivt farjelage.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['ystad','bransle','helaret','farjelage'],
 NULL,
 'fuel_station', 'ystad-bunkring', 'sodra_ostersjon',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Ahus Bunkring', 'Ahus', 55.9269, 14.3079,
 'Branslestopp i Ahus for seglare i Hanobukten.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['ahus','bransle','hanobukten'],
 NULL,
 'fuel_station', 'ahus-bunkring', 'sodra_ostersjon',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Falsterbo Bunkring', 'Falsterbo', 55.3830, 12.8329,
 'Branslestopp vid Falsterbo for seglare pa vag in i eller ut ur Ostersjon.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['falsterbo','bransle','ostersjon_porten'],
 NULL,
 'fuel_station', 'falsterbo-bunkring', 'sodra_ostersjon',
 ARRAY['bransle'],
 ARRAY['alla_seglare','transitseglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high');
