INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Smögens Hamnkrog', 'Smögen', 58.3554, 11.2302,
 'Bohuslänsk klassiker direkt vid den långa bryggan i Smögen. Havsutsikt, färsk fisk och räkor är självklara inslag.',
 'Maj–September: dagligen 11–22.', 'Räkor, hummer, torsk, hummergryta, smörgåsar.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['räkor','fisk','brygga','bohuslän','hummer'],
 'En kvälls-räksmörgås på bryggan i Smögen med solnedgång över Bohuslänsskärgården – svårt att slå.',
 'restaurant', 'smogens-hamnkrog', 'west_coast',
 ARRAY['restaurant','harbor_stop','fish'],
 ARRAY['boaters','family','couples'],
 ARRAY['guest_dock','restaurant','toilet','fuel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Marstrand Värdshus', 'Marstrand', 57.8836, 11.5893,
 'Anrikt värdshus på Marstrands ö med utsikt mot fästningen Carlstens skans. Klassisk husmanskost och skärgårdsmat.',
 'April–Oktober: dagligen 11–21.', 'Husmanskost, fisk, räkor, frikadeller, dessert.',
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['marstrand','historisk','husmanskost','fästning'],
 'Lunch i skuggan av Carlstens fästning – historia, mat och saltvatten i perfekt kombination.',
 'restaurant', 'marstrand-vardshus', 'west_coast',
 ARRAY['restaurant','historic','harbor_stop'],
 ARRAY['family','couples','tourists'],
 ARRAY['restaurant','toilet','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Marstrands Gästhamn', 'Marstrand', 57.8824, 11.5901,
 'Välskött gästhamn på Marstrands södra sida. Fullservice med el, vatten, duschar och bekväm landförbindelse med färja.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['gästhamn','marstrand','el','vatten','fullservice'],
 'En av västkustens mest populära gästhamnar – båtliv, folkfest och Carlstens fästning på promenadavstånd.',
 'marina', 'marstrands-gasthamn', 'west_coast',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gullholmens Krog', 'Gullholmen', 58.0178, 11.5489,
 'Gammal fiskelägemiljö på Gullholmen – en av Bohusläns bäst bevarade trähusmiljöer. Krogen serverar enkel mat i sagomiljö.',
 'Juni–Augusti: dagligen 12–20.', 'Enkel mat, fisk, räkor, kaffe och kaka.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['historisk','fiskeläge','trähus','bohuslän','naturhamn'],
 'En av Bohusläns mest pittoreska platser – vita och röda trähus, smala gränder och lugnt vatten.',
 'restaurant', 'gullholmens-krog', 'west_coast',
 ARRAY['restaurant','hidden_gem','historic'],
 ARRAY['couples','family','boaters'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Lysekils Fiskrökeri', 'Lysekil', 58.2785, 11.4401,
 'Rökeri och fiskbutik vid Lysekils hamn. Rökt lax, makrill och sill från lokalt fiskare direkt vid kajen.',
 'Maj–September: mån–lör 9–17.', 'Rökt lax, makrill, sill, räksmörgås, fiskbullar.',
 ARRAY['https://images.unsplash.com/photo-1559847844-5315695dadae?w=800'],
 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800',
 ARRAY['rökeri','fisk','lysekil','lokal','take-away'],
 'Köp direkt från rökeriets lucka – varm rökt lax att äta med fingrarna på kajen.',
 'restaurant', 'lysekils-fiskrokeri', 'west_coast',
 ARRAY['fish','take_away','local'],
 ARRAY['boaters','family'],
 ARRAY['restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Fjällbacka Värdshus', 'Fjällbacka', 58.5942, 11.2858,
 'Charmigt värdshus i Fjällbacka – byn som Ingrid Bergman älskade och Camilla Läckberg skriver om. Havsutsikt och god mat.',
 'April–Oktober: dagligen 12–21.', 'Lokal fisk, räkor, kött, vegetariskt, husmanskost.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['fjällbacka','bergman','historisk','mysig','krog'],
 'Fjällbacka är obligatorisk – vacker natur, kulturhistoria och god mat i ett.',
 'restaurant', 'fjallbacka-vardshus', 'west_coast',
 ARRAY['restaurant','historic','harbor_stop'],
 ARRAY['tourists','couples','family'],
 ARRAY['restaurant','toilet','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hamburgsunds Gästhamn', 'Hamburgsund', 58.5438, 11.2772,
 'Lugn gästhamn i Hamburgsund med goda faciliteter. Bra startpunkt för turer norrut mot Fjällbacka eller söderut mot Smögen.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['gästhamn','hamburgsund','bohuslän','lugnt'],
 'Liten men välskött hamn – perfekt mellanstation längs västkusten.',
 'marina', 'hamburgsunds-gasthamn', 'west_coast',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters'],
 ARRAY['guest_dock','electricity','water','shower','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Grundsunds Krog', 'Grundsund', 58.1063, 11.4989,
 'Pittoresk krog i det välbevarade fiskeläget Grundsund på Orust. Gamla röda sjöbodar och fiskebåtar sätter stämningen.',
 'Juni–Augusti: dagligen 12–21.', 'Skaldjur, fisk, enkel mat.',
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['grundsund','fiskeläge','bohuslän','historisk'],
 'En av Bohusläns hemligaste pärlor – intakt fiskeläge från 1800-talet med röda sjöbodar och stilla vatten.',
 'restaurant', 'grundsunds-krog', 'west_coast',
 ARRAY['restaurant','hidden_gem','historic'],
 ARRAY['couples','boaters'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Hönö Gästhamn', 'Hönö', 57.6914, 11.6095,
 'Välutrustad gästhamn på Hönö i Göteborgs norra skärgård. Nära Göteborg men ändå skärgård – populär utgångspunkt.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['gästhamn','hönö','göteborg','norra skärgård'],
 'Snabbaste vägen ut i skärgården från Göteborg – bra hamn och lokalt fiske.',
 'marina', 'hono-gasthamn', 'west_coast',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel'],
 'year_round', 'high'),

(gen_random_uuid(), 'Styrsö Skäret', 'Styrsö', 57.6209, 11.7687,
 'Populärt uteservering och café på Styrsö i södra Göteborgs skärgård. Fantastisk utsikt, räkor och klippbad intill.',
 'Maj–September: dagligen 10–20.', 'Räkor, smörgåsar, glass, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['styrsö','göteborg','utsikt','klippbad','räkor'],
 'Ta färjan från Saltholmen och ät räkor med utsikt – enkelt nöje, svårslagen känsla.',
 'restaurant', 'styrso-skaret', 'west_coast',
 ARRAY['restaurant','sunset_stop','swimming'],
 ARRAY['family','couples','day_trip'],
 ARRAY['restaurant','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Donsö Fiskrökeri', 'Donsö', 57.5962, 11.8122,
 'Familjeägt rökeri på Donsö – en av Göteborgs sydliga öar. Rökt makrill och lax att äta på kajen.',
 'Juni–Augusti: dagligen 10–18.', 'Rökt lax, makrill, räkor, sill.',
 ARRAY['https://images.unsplash.com/photo-1559847844-5315695dadae?w=800'],
 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800',
 ARRAY['donsö','rökeri','fisk','göteborg','lokal'],
 'Färskt rökt fisk direkt från rökeriet på en av Göteborgs sydligaste öar.',
 'restaurant', 'donso-fiskrokeri', 'west_coast',
 ARRAY['fish','take_away','local'],
 ARRAY['boaters','family'],
 ARRAY['restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Vrångö Naturhamn', 'Vrångö', 57.5561, 11.8434,
 'Naturhamn och ankarplats på Vrångö – södersta ön i Göteborgs södra skärgård. Vild natur och klapperstenstränder.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['naturhamn','vrångö','vild','klippor','ankring'],
 'Göteborgsskärgårdens sydligaste pärla – klapperstensstränder, vild natur och nästan inga turister.',
 'nature_harbor', 'vrango-naturhamn', 'west_coast',
 ARRAY['anchorage','swimming','nature'],
 ARRAY['boaters','adventurers'],
 ARRAY['anchorage'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Åstol Hamnkrog', 'Åstol', 57.9296, 11.5601,
 'Välbevarat fiskesamhälle på Åstol med pittoresk hamn och enkel krog. Rödmålade bodar och vita hus i lågt skärgårdslandskap.',
 'Juni–Augusti: dagligen 11–19.', 'Fisk, räkor, smörgåsar, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['åstol','fiskeläge','pittoresk','bohuslän'],
 'Åstol är som en inramad tavla – gå längs kajen och känn hur fiskesamhällets historia lever kvar.',
 'restaurant', 'astol-hamnkrog', 'west_coast',
 ARRAY['restaurant','historic','harbor_stop'],
 ARRAY['couples','boaters','family'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Käringön Krog', 'Käringön', 58.1015, 11.5603,
 'Levande fiskeläge och gästhamn på Käringön. Krogen serverar fisk och skaldjur medan båtar och fiskare sätter scenen.',
 'Maj–September: dagligen 12–21.', 'Räkor, fisk, hummer, skaldjursbricka.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['käringön','fiskeläge','skaldjur','gästhamn'],
 'Käringön kombinerar autentiskt fiskeliv med god mat – en favorit längs Bohuslänskusten.',
 'restaurant', 'karingon-krog', 'west_coast',
 ARRAY['restaurant','harbor_stop','fish'],
 ARRAY['boaters','family','couples'],
 ARRAY['guest_dock','restaurant','toilet','electricity','water'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Mollösunds Värdshus', 'Mollösund', 58.0672, 11.4648,
 'Charmigt värdshus i Mollösund på Orust – ett av Bohusläns äldsta fiskelägen. Stämningsfull mat i historisk miljö.',
 'April–Oktober: dagligen 12–21.', 'Husmanskost, fisk, skaldjur.',
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['mollösund','historisk','fiskeläge','orust'],
 'Mollösund är tidlöst vackert – träbodar, hamn och ett värdshus som serverat mat i generationer.',
 'restaurant', 'mollosunds-vardshus', 'west_coast',
 ARRAY['restaurant','historic','harbor_stop'],
 ARRAY['couples','boaters','family'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kungshamns Marina', 'Kungshamn', 58.3695, 11.2591,
 'Praktisk gästhamn i Kungshamn nära Smögen. Bra faciliteter och nära till allt som Smögenkysten har att erbjuda.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['marina','kungshamn','smögen','gästhamn'],
 'Kungshamn är grannhamn till Smögen och ett lugnt alternativ med alla bekvämligheter.',
 'marina', 'kungshamns-marina', 'west_coast',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Björkö Gästhamn', 'Björkö', 57.7556, 11.6498,
 'Gästhamn på Björkö i Göteborgs norra skärgård. Lugnt läge med badmöjligheter och naturstigen runt ön.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['björkö','göteborg','natur','bad','gästhamn'],
 'Björkö är lättillgänglig men ändå riktig skärgård – bra bad och vacker natur.',
 'marina', 'bjorko-gasthamn', 'west_coast',
 ARRAY['marina','swimming','nature'],
 ARRAY['family','boaters'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Nösunds Värdshus', 'Nösund', 58.1667, 11.5012,
 'Anrik sommarkrog på Orust nära havet. Populär stoppunkt med enkla rätter och sommarstämning.',
 'Juni–Augusti: dagligen 12–21.', 'Husmanskost, fisk, smörgåsar.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['nösund','orust','sommar','bohuslän'],
 'Nösund är den lilla hamnen som ingen turistguide har hittat – än.',
 'restaurant', 'nosunds-vardshus', 'west_coast',
 ARRAY['restaurant','hidden_gem'],
 ARRAY['boaters','couples'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kristinebergs Marina', 'Kristineberg', 58.2543, 11.4521,
 'Havsforskarstation och marina vid Gullmarn. Unik plats att förtöja – hav, forskning och vacker natur.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['marina','havsforskning','gullmarn','unik'],
 'Kristineberg kombinerar marina med en av Sveriges äldsta havsforskarstationer – för den vetgirige seglaren.',
 'marina', 'kristinebergs-marina', 'west_coast',
 ARRAY['marina','nature'],
 ARRAY['boaters','adventurers'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Karlskrona Gästhamn', 'Karlskrona', 56.1612, 15.5869,
 'UNESCO-listad örlogsbas och en av Östersjöns finaste marinor. Välkommen till marinens stad med imposant historia.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['karlskrona','blekinge','unesco','örlogsstad','marina'],
 'Förtöj i Karlskrona och promenera bland kanonbåtar, admiralshus och barockgator – Östersjöns mest historiska stad.',
 'marina', 'karlskrona-gasthamn', 'blekinge',
 ARRAY['marina','historic','harbor_stop'],
 ARRAY['boaters','tourists','family'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel','restaurant'],
 'year_round', 'high'),

(gen_random_uuid(), 'Handelshamnen Karlskrona', 'Karlskrona', 56.1634, 15.5812,
 'Restaurang och bar i gamla handelshuset vid Karlskronas hamn. Hav, historia och god mat i en och samma byggnad.',
 'Maj–September: dagligen 11–22.', 'Lokal fisk, östersjömat, husmanskost.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['karlskrona','historisk','blekinge','havsmat','restaurang'],
 'Östersjöns smaker i historiska lokaler – torsken och strömmingen har alltid varit Blekinges signum.',
 'restaurant', 'handelshamnen-karlskrona', 'blekinge',
 ARRAY['restaurant','historic'],
 ARRAY['tourists','family','couples'],
 ARRAY['restaurant','bar','toilet'],
 'year_round', 'high'),

(gen_random_uuid(), 'Hanö Naturhamn', 'Hanö', 56.0217, 14.8445,
 'Enslig ö i Östersjön utanför Kristianstad. Gammal brittisk kyrkogård, klippkust och ett av Blekinges vildaste ankringslägen.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['hanö','naturhamn','ö','blekinge','ankring','vild'],
 'Hanö är mystisk – en ö med brittisk kyrkogård, klapperstensstrand och Östersjöns storhet i all sin härlighet.',
 'nature_harbor', 'hano-naturhamn', 'blekinge',
 ARRAY['anchorage','nature','swimming'],
 ARRAY['boaters','adventurers'],
 ARRAY['anchorage'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Utlängan Fyr & Krog', 'Utlängan', 55.9551, 15.7897,
 'Enslig plats på östra Blekingekusten med fyr, café och naturhamn. Klippor, havsörnar och tyst vatten.',
 'Juni–Augusti: dagligen 10–18.', 'Kaffe, smörgåsar, glass.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['utlängan','fyr','blekinge','naturhamn','havsörn'],
 'En av Blekinges mest avlägsna platser – havsörnarna cirklar, fyren pekar mot havet och tystnaden är total.',
 'restaurant', 'utlangan-fyr', 'blekinge',
 ARRAY['restaurant','nature','hidden_gem'],
 ARRAY['boaters','adventurers'],
 ARRAY['anchorage','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kristianopels Gästhamn', 'Kristianopel', 56.2548, 15.7834,
 'Medeltida stadsruin och naturhamn på Blekingekusten. En av Östersjöns märkligaste platser – historia möter öppet hav.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['kristianopel','medeltida','blekinge','historisk','gästhamn'],
 'Kristianopel är ett av Östersjöns minst kända underverk – medeltida ruiner, fiskarbysromantik och bra hamn.',
 'marina', 'kristianopels-gasthamn', 'blekinge',
 ARRAY['marina','historic','harbor_stop'],
 ARRAY['boaters','tourists'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Aspö Naturhamn', 'Aspö', 56.1534, 15.7012,
 'Lång ö i Blekinges östra skärgård med flera naturhamnar. Natur i orört skick och lite mötad av turister.',
 NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['aspö','blekinge','naturhamn','vild','ostörda'],
 'Aspö är Blekinges ostörda pärla – lång kuststräcka, naturhamnar och lite folk.',
 'nature_harbor', 'aspo-naturhamn', 'blekinge',
 ARRAY['anchorage','nature','swimming'],
 ARRAY['boaters','adventurers'],
 ARRAY['anchorage'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Sturkö Gästhamn', 'Sturkö', 56.1423, 15.6478,
 'Gästhamn på Sturkö i Blekinges inre skärgård. Lugnt vatten, fina badrunden och enkla faciliteter.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['sturkö','blekinge','gästhamn','bad','lugnt'],
 'Sturkö är det orörda alternativet till Karlskrona – alldeles intill men tusen gånger lugnare.',
 'marina', 'sturko-gasthamn', 'blekinge',
 ARRAY['marina','swimming','nature'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Karlshamns Gästhamn', 'Karlshamn', 56.1708, 14.8642,
 'Välkänd hamnstad i Blekinge med charmig stadskärna. Punchstämpeln Karlshamns punch är stadsbornas stolthet.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['karlshamn','blekinge','punsch','stad','gästhamn'],
 'Karlshamn är Karlshamns punchs hemstad – förtöj och smaka historia och handel.',
 'marina', 'karlshamns-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters','tourists'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel'],
 'year_round', 'high'),

(gen_random_uuid(), 'Nogersunds Krog', 'Nogersund', 56.0112, 14.5623,
 'Genuint litet fiskeläge i västra Blekinge. Maten är enkel, priset lågt och utsikten värd resan.',
 'Juni–Augusti: dagligen 11–19.', 'Räkor, sill, smörgåsar, fisk.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['nogersund','fiskeläge','blekinge','enkel','lokal'],
 'Nogersund är det Bohuslän ingen snackar om – genuint fiskeliv och inga turister.',
 'restaurant', 'nogersunds-krog', 'blekinge',
 ARRAY['restaurant','hidden_gem','local'],
 ARRAY['boaters','couples'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Mölle Hamn & Krog', 'Mölle', 56.2820, 12.4976,
 'Välkänd Kulla-halvö-destination med dramatisk klippkust och Kullaberg bakom sig. Restaurang vid hamnen.',
 'April–Oktober: dagligen 11–21.', 'Fisk, skaldjur, husmanskost.',
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['mölle','kullaberg','kullabygden','öresund','klippkust'],
 'Kullaberg är spektakulärt – förtöj i Mölle och klättra bland klipporna eller ät skaldjur vid hamnen.',
 'restaurant', 'molle-hamn-krog', 'oresund',
 ARRAY['restaurant','harbor_stop','nature'],
 ARRAY['tourists','couples','boaters'],
 ARRAY['guest_dock','restaurant','bar','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Vikens Gästhamn', 'Viken', 56.1408, 12.5686,
 'Lugn liten hamn i Viken norr om Helsingborg. Idyllisk fiskebyatmosfär med sandstrand och bra service.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['viken','öresund','sandstrand','lugnt','gästhamn'],
 'Viken är en paus från storstadens trafik – sandstrand, lugna vatten och liten fiskebyatmosfär.',
 'marina', 'vikens-gasthamn', 'oresund',
 ARRAY['marina','swimming','harbor_stop'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','electricity','water','shower','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Arild Hamn', 'Arild', 56.2571, 12.5654,
 'Pytteliten fiskehamn vid Kullahalvöns norra kust. Konstnärsby med charm och utsikt mot Kattegatt.',
 'Maj–September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['arild','konstnärsby','kattegatt','liten','charm'],
 'Arild är konstnärernas och fotografernas hemliga plats – pittoresk liten hamn och dramatisk natur.',
 'marina', 'arild-hamn', 'oresund',
 ARRAY['marina','hidden_gem','nature'],
 ARRAY['couples','boaters','artists'],
 ARRAY['guest_dock','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Ven Krog & Naturhamn', 'Ven', 55.9185, 12.6987,
 'Tycho Brahes ö i Öresund – cykla runt, besök observatorierumerna och äta på krogen med dansk kust i bakgrunden.',
 'April–Oktober: dagligen 11–20.', 'Enkel mat, glass, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['ven','tycho brahe','öresund','cykel','historia'],
 'Ven är unik – åk dit med båt, cykla runt hela ön på en timme och känn hur Tycho Brahes era lever kvar.',
 'restaurant', 'ven-krog-naturhamn', 'oresund',
 ARRAY['restaurant','historic','nature','cycling'],
 ARRAY['tourists','family','couples'],
 ARRAY['guest_dock','restaurant','toilet','cycling'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Landskrona Marina', 'Landskrona', 55.8703, 12.8312,
 'Stor välutrustad marina i Landskrona med fullservice. Bra utgångspunkt för Öresundskryssning eller besök på Ven.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['landskrona','öresund','marina','fullservice','ven'],
 'Landskrona Marina är välskött och bekvämt – perfekt bas för Öresundsseglingen.',
 'marina', 'landskrona-marina', 'oresund',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel','restaurant'],
 'year_round', 'high'),

(gen_random_uuid(), 'Höganäs Hamnkrog', 'Höganäs', 56.1988, 12.5583,
 'Keramikstaden Höganäs med charmig hamn och krog. Känd för keramik, klippor och friska västliga vindar.',
 'April–Oktober: dagligen 11–21.', 'Fisk, skaldjur, husmanskost.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['höganäs','keramik','kattegatt','klippor','hamn'],
 'Höganäs är keramikens stad – men också en bra hamn med bra mat och frisk luft.',
 'restaurant', 'hoganas-hamnkrog', 'oresund',
 ARRAY['restaurant','harbor_stop'],
 ARRAY['tourists','boaters','family'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Barsebäck Marina', 'Barsebäck', 55.7618, 12.9090,
 'Stor marina mitt i Öresund med fantastisk utsikt mot Danmark. Väl rustad och centralt belägen.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['barsebäck','öresund','marina','danmark','utsikt'],
 'Barsebäck Marina har utsikt mot Danmark och Kungssten kärnkraftverket – en plats utanför det vanliga.',
 'marina', 'barseback-marina', 'oresund',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel'],
 'year_round', 'high'),

(gen_random_uuid(), 'Fjällbacka Gästhamn', 'Fjällbacka', 58.5938, 11.2872,
 'Välkänd gästhamn vid Fjällbacka med utsikt mot Vetteberget. Sommartid myllrar det av både fartygsgäster och turister.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['fjällbacka','vetteberget','bergman','gästhamn','bohuslän'],
 'Fjällbacka gästhamn är omgiven av dramatisk natur – Vettebergets klippvägg reser sig direkt bakom hamnen.',
 'marina', 'fjallbacka-gasthamn', 'west_coast',
 ARRAY['marina','harbor_stop','historic'],
 ARRAY['boaters','tourists','family'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Lysekil Gästhamn', 'Lysekil', 58.2790, 11.4388,
 'Stor gästhamn i Lysekil med full service. Stadens centrum och havsbadet är inom gångavstånd.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['lysekil','gästhamn','bohuslän','fullservice'],
 'Lysekil är mer än en hamn – havsbad, fiskemarknad och livlig stadsgata väntar när du kliver av.',
 'marina', 'lysekil-gasthamn', 'west_coast',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Orust Stocken Marina', 'Stocken', 58.1422, 11.5778,
 'Marina och gästhamn på Orusts västra sida. Perfekt för turer till Käringön eller Gullholmen.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['orust','stocken','marina','gästhamn','startpunkt'],
 'Stocken Marina är den perfekta basen för att utforska Gullmarns mynning och Bohusläns yttre skärgård.',
 'marina', 'orust-stocken-marina', 'west_coast',
 ARRAY['marina','harbor_stop'],
 ARRAY['boaters'],
 ARRAY['guest_dock','electricity','water','shower','toilet','fuel'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Smögen Brygghus', 'Smögen', 58.3556, 11.2312,
 'Craft-bryggeri och taproom alldeles vid den långa Smögenbryggans norra ände. Hantverksöl med havsutsikt.',
 'Juni–Augusti: dagligen 14–22.', 'Hantverksöl, pale ale, IPA, enkla tilltugg.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['öl','bryggeri','smögen','hantverksöl','kväll'],
 'Smögen Brygghus brygger i det saltaste klimatet i Sverige – ölen smakar hav.',
 'bar', 'smogen-brygghus', 'west_coast',
 ARRAY['bar','hidden_gem','sunset_stop'],
 ARRAY['boaters','friends'],
 ARRAY['bar','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Sölvesborgs Gästhamn', 'Sölvesborg', 56.0519, 14.5836,
 'Trevlig gästhamn i lilla Sölvesborg – känd som Sveriges kulturhuvudstad med många konstverk i stadsmiljön.',
 'April–Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['sölvesborg','blekinge','kultur','gästhamn','konststad'],
 'Sölvesborg kallas Sveriges kulturhuvudstad – förtöj och promenera bland stadens unika gaturum.',
 'marina', 'solvesborgs-gasthamn', 'blekinge',
 ARRAY['marina','harbor_stop'],
 ARRAY['tourists','boaters'],
 ARRAY['guest_dock','electricity','water','shower','toilet'],
 'year_round', 'medium'),

(gen_random_uuid(), 'Åhus Gästhamn', 'Åhus', 55.9241, 14.3211,
 'Absolut vodkas hemstad vid Hanöbukten. Sandstränder, hamn och den lilla stadens charm.',
 'Maj–September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['åhus','blekinge','absolut','sandstrand','gästhamn'],
 'Absolut vodka kommer härifrån – men Åhus är också en charmig liten hamnstad med sandstrand.',
 'marina', 'ahus-gasthamn', 'blekinge',
 ARRAY['marina','swimming','harbor_stop'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','electricity','water','shower','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Flatöns Krog', 'Flatön', 58.2456, 11.5201,
 'Sommarkrog på den lilla ön Flatön i Gullmarns mynning. Enkelt och gott med fantastisk utsikt mot fjordens mynning.',
 'Juni–Augusti: dagligen 12–20.', 'Enkel husmanskost, fisk, smörgåsar.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['flatön','gullmarn','bohuslän','utsikt','sommar'],
 'Flatön är den lilla ön ingen läser om – men Gullmarns utsikt därifrån är bland Bohusläns vackraste.',
 'restaurant', 'flatons-krog', 'west_coast',
 ARRAY['restaurant','hidden_gem','nature'],
 ARRAY['boaters','couples'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'low'),

(gen_random_uuid(), 'Hamburgsunds Värdshus', 'Hamburgsund', 58.5434, 11.2768,
 'Gammalt värdshus vid Hamburgsunds sund med utomhusbord precis vid vattnet.',
 'Juni–Augusti: dagligen 12–21.', 'Husmanskost, räkor, fisk.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['hamburgsund','värdshus','bohuslän','sund'],
 'Bordet vid vattnet i Hamburgsund är en av Bohusläns enkla glädjer.',
 'restaurant', 'hamburgsunds-vardshus', 'west_coast',
 ARRAY['restaurant','harbor_stop'],
 ARRAY['boaters','family'],
 ARRAY['restaurant','toilet'],
 'summer_only', 'medium')

ON CONFLICT (name) DO UPDATE SET
  island             = EXCLUDED.island,
  latitude           = EXCLUDED.latitude,
  longitude          = EXCLUDED.longitude,
  description        = EXCLUDED.description,
  type               = EXCLUDED.type,
  archipelago_region = EXCLUDED.archipelago_region,
  source_confidence  = EXCLUDED.source_confidence;
