-- seed-bohuslan-syd.sql
-- Sodra Bohuslan (Gothenburg archipelago) seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'bohuslan_syd';
DELETE FROM restaurants WHERE name IN (
  'Marstrand Gasthamn', 'Gothenburg Marina Lilla Bommen', 'Styrso Gasthamn',
  'Donso Gasthamn', 'Vrangoe Gasthamn', 'Ockero Gasthamn', 'Kungsbacka Gasthamn',
  'Styrsoe Naturhamn', 'Vrangoe Naturhamn', 'Astol Naturhamn', 'Kooen Naturhamn',
  'Marstrand Restaurang', 'Donso Fiskekrogen', 'Gothenburg Hamn Bar', 'Ockero Krog',
  'Marstrand Bunkring', 'Gothenburg Marina Bunkring', 'Donso Bunkring', 'Styrso Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Marstrand Gasthamn', 'Marstrand', 57.8897, 11.5844,
 'Ikonisk gasthamn vid Marstrand, en av Sveriges mest besokta sommarplatser. Carlstens fastning tronar over hamnen. Fullservice och levande atmosfar.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['marstrand','gasthamn','ikonisk','fastning'],
 'Sveriges mest kanda skargardshamn med Carlstens fastning och livlig sommarstamning.',
 'marina', 'marstrand-gasthamn', 'bohuslan_syd',
 ARRAY['marina','harbor_stop','iconic'],
 ARRAY['familjer','par','turister','segelsallskap'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','bar','wifi','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gothenburg Marina Lilla Bommen', 'Goteborg', 57.7089, 11.9746,
 'Centralt belagen marina i Goteborg nara Lilla Bommen. Bra utgangspunkt for skalgardsseglats och dagsutflykter till Bohuslan.',
 'Helaret: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['goteborg','marina','stad','urban'],
 'Urban marina i Sveriges andrastad med enkel tillgang till skargarden.',
 'marina', 'gothenburg-marina-lilla-bommen', 'bohuslan_syd',
 ARRAY['marina','harbor_stop','stad'],
 ARRAY['stadsbor','transitseglare','turister'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','wifi','kollektivtrafik'],
 'year_round', 'high'),

(gen_random_uuid(), 'Styrso Gasthamn', 'Styrso', 57.6333, 11.7667,
 'Gasthamn pa Styrso i Goteborgs skar. Bilfri o med skargardsstamning nara storstan. Bra farg- och badmojligheter.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['styrso','gasthamn','bilfri','goteborg'],
 'Bilfri o i Goteborgs skar med autentisk skargardsstamning.',
 'marina', 'styrso-gasthamn', 'bohuslan_syd',
 ARRAY['marina','harbor_stop','bilfri'],
 ARRAY['familjer','naturintresserade','stadsseglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Donso Gasthamn', 'Donso', 57.6000, 11.7333,
 'Gasthamn pa Donso, ett av de levande fiskeoarna i Goteborgs skar. Autentisk fiskemiljo och god seafood.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['donso','gasthamn','fiskehamn','autentisk'],
 'Levande fiskehamn med autentisk skargardskultur och fresh seafood.',
 'marina', 'donso-gasthamn', 'bohuslan_syd',
 ARRAY['marina','harbor_stop','fiskehamn'],
 ARRAY['mat_intresserade','kulturintresserade','seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Vrangoe Gasthamn', 'Vrangoe', 57.5833, 11.7167,
 'Sydligaste gasthamnen i Goteborgs skar pa Vrangoe. Naturskont lage med klippor och oppen horisont mot Kattegatt.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['vrangoe','gasthamn','sydligast','klippor'],
 'Yttersta holmen i Goteborgs skar med storstamma klippor och oppen utsikt.',
 'marina', 'vrangoe-gasthamn', 'bohuslan_syd',
 ARRAY['marina','harbor_stop','ytterhamn'],
 ARRAY['naturintresserade','aventyrare','seglare'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ockero Gasthamn', 'Ockero', 57.7167, 11.6500,
 'Gasthamn pa Ockero med bra service och livlig ost-bohuslansk karaktar. Nara Goteborg men med tydlig skargardsanda.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['ockero','gasthamn','service','bohuslan'],
 'Levande skargardshamn nara Goteborg med stark lokal karaktar.',
 'marina', 'ockero-gasthamn', 'bohuslan_syd',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['familjer','lokala_seglare','transitseglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kungsbacka Gasthamn', 'Kungsbacka', 57.5000, 12.0667,
 'Gasthamn i Kungsbacka fjaerd. Lugnt alternativ soer om Goteborg med bra service och narheten till naturreservat.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['kungsbacka','gasthamn','fjaerd','lugn'],
 'Lugn fjaerdhamn soer om Goteborg med bra natur i omgivningen.',
 'marina', 'kungsbacka-gasthamn', 'bohuslan_syd',
 ARRAY['marina','harbor_stop','lugn'],
 ARRAY['familjer','lugnsokande','naturintresserade'],
 ARRAY['guest_dock','electricity','water','shower','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Styrsoe Naturhamn', 'Styrso', 57.6200, 11.7800,
 'Naturhamn pa sodra Styrso med skyddad vik och bra simmoejlighet fran klipporna.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['styrso','naturhamn','ankring','simning'],
 'Skyddad naturhavn med bra simning nara Goteborg.',
 'anchorage', 'styrsoe-naturhamn', 'bohuslan_syd',
 ARRAY['anchorage','nature','simning'],
 ARRAY['familjer','naturintresserade','stadsseglare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Vrangoe Naturhamn', 'Vrangoe', 57.5750, 11.7100,
 'Ankringsplats runt Vrangoe med oppen ytterskargardsmiljo. Dramatisk klipplandskap och tystnad.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['vrangoe','naturhamn','ankring','dramatisk'],
 'Dramatisk klippnatur pa ytterskargarden soer om Goteborg.',
 'anchorage', 'vrangoe-naturhamn', 'bohuslan_syd',
 ARRAY['anchorage','nature','klippa'],
 ARRAY['naturintresserade','aventyrare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Astol Naturhamn', 'Astol', 57.9333, 11.5833,
 'Naturskon naturhamn pa Astol. Bilfri o med fargglada sjobodsstamning och bra simning.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['astol','naturhamn','bilfri','sjobodsmiljo'],
 'Pittoresk bilfri o med sjobodsmiljo och klassisk Bohuslan-karaktar.',
 'anchorage', 'astol-naturhamn', 'bohuslan_syd',
 ARRAY['anchorage','nature','pittoresk'],
 ARRAY['par','naturintresserade','fotografer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kooen Naturhamn', 'Kooen', 57.8500, 11.6000,
 'Skyddad naturhamn pa Ko-on. Lugn ankringsplats med trevlig natur i Bohuslan innerhamn.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['kooen','naturhamn','ankring','skyddad'],
 'Skyddad ankringsplats med lugn Bohuslan-karaktar.',
 'anchorage', 'kooen-naturhamn', 'bohuslan_syd',
 ARRAY['anchorage','nature','lugn'],
 ARRAY['familjer','lugnsokande'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Marstrand Restaurang', 'Marstrand', 57.8899, 11.5847,
 'Klassisk sommarrestaurang i Marstrand med utsikt mot Carlstens fastning. Serverar fisk och skaldjur samt traditionsrik svensk mat.',
 'Maj-September: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['marstrand','restaurang','utsikt','fastning'],
 'Sommarrestaurang med utsikt mot Carlstens fastning och levande hamnstamning.',
 'restaurant', 'marstrand-restaurang', 'bohuslan_syd',
 ARRAY['restaurang','skaldjur','middag'],
 ARRAY['par','turister','familjer'],
 ARRAY['restaurang','uteservering','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Donso Fiskekrogen', 'Donso', 57.6002, 11.7336,
 'Autentisk fiskekrog pa Donso med dagsfangst direkt fran hamnens batar. Enkel och god mat i fiskehamnsanda.',
 'Juni-Augusti: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['donso','fiskekrog','dagsfangst','autentisk'],
 'Autentisk fiskehamnskrog med dagsfangst och genuint Bohuslan-kok.',
 'restaurant', 'donso-fiskekrogen', 'bohuslan_syd',
 ARRAY['restaurang','fisk','autentisk'],
 ARRAY['mat_intresserade','kulturintresserade','seglare'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gothenburg Hamn Bar', 'Goteborg', 57.7091, 11.9749,
 'Hamn-bar och restaurang vid Lilla Bommen i Goteborg. Bra uteservering med utsikt over alven och enkel mat.',
 'April-Oktober: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['goteborg','hamnbar','uteservering','alv'],
 'Urban hamnbar med alvutsikt i Goteborg centrum.',
 'restaurant', 'gothenburg-hamn-bar', 'bohuslan_syd',
 ARRAY['restaurang','bar','urban'],
 ARRAY['stadsbor','turister','par'],
 ARRAY['restaurang','bar','uteservering'],
 'year_round', 'high'),

(gen_random_uuid(), 'Ockero Krog', 'Ockero', 57.7169, 11.6503,
 'Trivsam krog pa Ockero med lokal mat och havsutsikt. Populart tillhall for bade oboende och sommarseglar.',
 'Maj-September: 12:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['ockero','krog','lokal','havsutsikt'],
 'Trivsam lokalkrog med havsutsikt pa Ockero.',
 'restaurant', 'ockero-krog', 'bohuslan_syd',
 ARRAY['restaurang','lokal'],
 ARRAY['lokalinvanare','seglare','familjer'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Marstrand Bunkring', 'Marstrand', 57.8895, 11.5841,
 'Branslestation i Marstrand. Diesel och bensin for seglare i en av Sveriges mest besokta hamnstader.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['marstrand','bransle','diesel'],
 NULL,
 'fuel_station', 'marstrand-bunkring', 'bohuslan_syd',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gothenburg Marina Bunkring', 'Goteborg', 57.7087, 11.9743,
 'Marinbunkring vid Goteborgs marina. Tillgangligt aret runt for seglare och motorbatar.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['goteborg','bransle','marina','helaret'],
 NULL,
 'fuel_station', 'gothenburg-marina-bunkring', 'bohuslan_syd',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Donso Bunkring', 'Donso', 57.5998, 11.7330,
 'Branslestation pa Donso fiskehamn. Diesel for bat- och yrkestrafiken.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['donso','bransle','fiskehamn'],
 NULL,
 'fuel_station', 'donso-bunkring', 'bohuslan_syd',
 ARRAY['bransle'],
 ARRAY['alla_seglare','yrkesfiskare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Styrso Bunkring', 'Styrso', 57.6330, 11.7664,
 'Branslestation pa Styrso for seglare i Goteborgs skar.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['styrso','bransle','goteborg_skar'],
 NULL,
 'fuel_station', 'styrso-bunkring', 'bohuslan_syd',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
