-- seed-ostergotland.sql
-- Ostergotlands skargard seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'ostergotland';
DELETE FROM restaurants WHERE name IN (
  'Arkosund Gasthamn', 'Gryt Gasthamn', 'Fyrudden Gasthamn',
  'Harstena Gasthamn', 'Soderkoping Gasthamn', 'Valdemarsvik Gasthamn', 'Tyrislot Gasthamn',
  'Arkoe Naturhamn', 'Gryt Naturhamn', 'Harstena Naturhamn', 'Finno Naturhamn',
  'Arkosund Hamkrog', 'Fyrudden Restaurang', 'Harstena Krog', 'Soderkoping Krog',
  'Arkosund Bunkring', 'Fyrudden Bunkring', 'Valdemarsvik Bunkring', 'Gryt Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Arkosund Gasthamn', 'Arkosund', 58.4856, 16.9444,
 'Valkand gasthamn i Arkosund, porten till Ostergotlands skargard. Bra service och trevlig by med handel och restauranger nara.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['arkosund','gasthamn','ostergotland','service'],
 'Porten till Ostergotlands skargard med bra service och trivsam miljo.',
 'marina', 'arkosund-gasthamn', 'ostergotland',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['familjer','transitseglare','boaters'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gryt Gasthamn', 'Gryt', 58.4833, 16.6667,
 'Populart stopp i Gryts skargard. Genuin skargardskaraktar med oar och vikar i alla riktningar. Bra mat och service.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['gryt','gasthamn','skargard','popular'],
 'Hjarta av Gryts skargard med tusentals oar runt knuten.',
 'marina', 'gryt-gasthamn', 'ostergotland',
 ARRAY['marina','harbor_stop','skargard'],
 ARRAY['familjer','naturintresserade','seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fyrudden Gasthamn', 'Fyrudden', 58.2500, 16.8333,
 'Gasthamn i sodra Ostergotland vid Fyrudden. Utpost mot Ostersjons oppna vatten med vacker natur och bra fiskemojligheter.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['fyrudden','gasthamn','ytterskargard','fiske'],
 'Ytterskargard med oppen Ostersjostamning och bra fiske.',
 'marina', 'fyrudden-gasthamn', 'ostergotland',
 ARRAY['marina','harbor_stop','ytterhamn'],
 ARRAY['erfarna_seglare','fiskare','naturintresserade'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Harstena Gasthamn', 'Harstena', 58.5167, 17.0167,
 'Charmig gasthamn pa Harstena, en levande o med fastboende. Autentisk skargardskultur och omgivande naturreservat.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['harstena','gasthamn','levande_o','naturreservat'],
 'Levande o med fastboende och omgivande naturreservat i yttre skargarden.',
 'marina', 'harstena-gasthamn', 'ostergotland',
 ARRAY['marina','harbor_stop','autentisk'],
 ARRAY['naturintresserade','kulturintresserade','erfarna_seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Soderkoping Gasthamn', 'Soderkoping', 58.4806, 16.3222,
 'Gasthamn i Soderkoping vid Gota kanal. Medeltida stad med kanal, sluss och vacker arkitektur. Bra start for kanalresor.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['soderkoping','gasthamn','gotakanal','medeltid'],
 'Medeltidsstad vid Gota kanal med charm och historia.',
 'marina', 'soderkoping-gasthamn', 'ostergotland',
 ARRAY['marina','harbor_stop','kanal'],
 ARRAY['familjer','historieintresserade','kanalresenarer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Valdemarsvik Gasthamn', 'Valdemarsvik', 58.2028, 16.5972,
 'Gasthamn i Valdemarsvik vid innersta viken. Naturskon miljo med sommarstamning och bra service for seglare.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['valdemarsvik','gasthamn','vik','sommarmiljo'],
 'Naturskon fjardhamn med omgivande skog och rolig sommarstamning.',
 'marina', 'valdemarsvik-gasthamn', 'ostergotland',
 ARRAY['marina','harbor_stop','natur'],
 ARRAY['familjer','lugnsokande','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Tyrislot Gasthamn', 'Tyrislot', 58.5333, 16.5833,
 'Liten gasthamn pa Tyrislot i Gryts skargard. Fridfullt lage och bra bas for dagsturer i omgivande skargard.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['tyrislot','gasthamn','fridfullt','skargard'],
 'Lugnt lage i hjarta av Gryts skargard.',
 'marina', 'tyrislot-gasthamn', 'ostergotland',
 ARRAY['marina','harbor_stop','lugn'],
 ARRAY['familjer','lugnsokande'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Arkoe Naturhamn', 'Arko', 58.4667, 17.0000,
 'Naturhamn pa yttre Arko med dramatisk skargardsmiljo. Bra ankring i skyddade vikar med imponerande klipplandskap.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['arko','naturhamn','ankring','ytterhamn'],
 'Dramatisk ytterskargard med klipplandskap och oppen horisont.',
 'anchorage', 'arkoe-naturhamn', 'ostergotland',
 ARRAY['anchorage','nature','ytterskargard'],
 ARRAY['erfarna_seglare','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gryt Naturhamn', 'Gryt', 58.4700, 16.6800,
 'En av manga vackra naturhamnar i Gryts skargard. Skyddad vik med klipphall och bra simstalle.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['gryt','naturhamn','ankring','simning'],
 'Klassisk Gryt-skargard med klipphall och lugna vikar.',
 'anchorage', 'gryt-naturhamn', 'ostergotland',
 ARRAY['anchorage','nature','simning'],
 ARRAY['familjer','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Harstena Naturhamn', 'Harstena', 58.5100, 17.0300,
 'Naturhamn runt Harstena med rik fagelliv och vacker natur. Bra ankring i lugna vikar.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['harstena','naturhamn','ankring','faglar'],
 'Naturreservat med rik fauna och lugna ankringsvikar.',
 'anchorage', 'harstena-naturhamn', 'ostergotland',
 ARRAY['anchorage','nature','birdwatching'],
 ARRAY['naturintresserade','fagelskadare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Finno Naturhamn', 'Finno', 58.4000, 16.7500,
 'Liten naturhamn pa avlagna Finno med ostord natur. Typisk Ostergotland ytterskargard utan service men med stor skonshet.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['finno','naturhamn','ostord','ankring'],
 'Ostord ytterskargard med ursprunglig natur och tystnad.',
 'anchorage', 'finno-naturhamn', 'ostergotland',
 ARRAY['anchorage','nature','remote'],
 ARRAY['aventyrare','naturintresserade','lugnsokande'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Arkosund Hamkrog', 'Arkosund', 58.4858, 16.9447,
 'Populart krogstopp direkt vid gasthamnen i Arkosund. Serverar fisk och skaldjur samt husmanskost med utsikt mot hamnen.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['arkosund','restaurang','fisk','hamnutsikt'],
 'God mat med hamnutsikt vid porten till Ostergotlands skargard.',
 'restaurant', 'arkosund-hamkrog', 'ostergotland',
 ARRAY['restaurang','middag'],
 ARRAY['familjer','par','transitseglare'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fyrudden Restaurang', 'Fyrudden', 58.2502, 16.8336,
 'Enkel restaurang vid Fyruddens gasthamn. God mat i naturskont lage vid ytterskargarden.',
 'Juni-Augusti: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['fyrudden','restaurang','ytterskargard','enkel'],
 'Enkel god mat vid ytterskargarden.',
 'restaurant', 'fyrudden-restaurang', 'ostergotland',
 ARRAY['restaurang'],
 ARRAY['seglare','familjer'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Harstena Krog', 'Harstena', 58.5169, 17.0170,
 'Autentisk krog pa levande on Harstena. Mat lagad pa lokala ravaror med genuint skargardsarv.',
 'Juni-Augusti: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['harstena','krog','autentisk','lokalmad'],
 'Genuint skargardskok pa en av Ostergotlands levande oar.',
 'restaurant', 'harstena-krog', 'ostergotland',
 ARRAY['restaurang','lokalmad'],
 ARRAY['kulture_intresserade','naturintresserade','seglare'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Soderkoping Krog', 'Soderkoping', 58.4808, 16.3225,
 'Krog i Soderkoping med mat inspirerad av kanalstaden och Ostergotlands traditioner. Bra vin och god husmanskost.',
 'Helaret: 11:00-22:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['soderkoping','krog','husmanskost','kanal'],
 'God mat i en av Ostergotlands vackraste kanal-staeder.',
 'restaurant', 'soderkoping-krog', 'ostergotland',
 ARRAY['restaurang','husmanskost'],
 ARRAY['familjer','kanalresenarer','historieintresserade'],
 ARRAY['restaurang','bar'],
 'year_round', 'high'),

(gen_random_uuid(), 'Arkosund Bunkring', 'Arkosund', 58.4854, 16.9441,
 'Marinbunkring i Arkosund. Diesel och bensin for seglare pa vag in eller ut ur Ostergotlands skargard.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['arkosund','bransle','diesel'],
 NULL,
 'fuel_station', 'arkosund-bunkring', 'ostergotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fyrudden Bunkring', 'Fyrudden', 58.2498, 16.8330,
 'Branslestopp vid Fyrudden. Viktigt tankningsalternativ i Ostergotlands ytterskargard.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['fyrudden','bransle','diesel','ytterhamn'],
 NULL,
 'fuel_station', 'fyrudden-bunkring', 'ostergotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Valdemarsvik Bunkring', 'Valdemarsvik', 58.2025, 16.5968,
 'Branslestation i Valdemarsvik for seglare i sodra Ostergotland.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['valdemarsvik','bransle','diesel'],
 NULL,
 'fuel_station', 'valdemarsvik-bunkring', 'ostergotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gryt Bunkring', 'Gryt', 58.4830, 16.6663,
 'Marinbunkring i Gryt. Central plats for branslepastoppning i hjarta av Gryts skargard.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['gryt','bransle','diesel','central'],
 NULL,
 'fuel_station', 'gryt-bunkring', 'ostergotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high');
