DELETE FROM restaurants WHERE archipelago_region = 'bohuslan_nord';
DELETE FROM restaurants WHERE name IN ('Stromstad Gasthamn', 'Nord-Koster Naturhamn', 'Syd-Koster Gasthamn', 'Fjallbacka Gasthamn', 'Fjallbacka Restaurang', 'Hamburgsund Gasthamn', 'Grebbestad Gasthamn', 'Grebbestad Restaurang', 'Havstenssund Naturhamn', 'Kastinget Marina', 'Kosterfjaorden Anchorage', 'Karingoen Gasthamn', 'Ramsvik Naturhamn', 'Nordvik Marina', 'Stromstad Bensinstation', 'Fjallbacka Bensinstation', 'Grebbestad Bensinstation', 'Karingoen Restaurang', 'Stromstad Restaurang');

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Stromstad Gasthamn', 'Stromstad', 58.9456, 11.1823,
 'Stor och valkand gasthamn i Stromstad. Fullservice, restaurang och bra liggplatser.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['stromstad','gasthamn','fullservice','bohuslaan'],
 'Central hamn med allt du behover for en langre vistelese.',
 'marina', 'stromstad-gasthamn', 'bohuslan_nord',
 ARRAY['marina','harbor_stop','service','food'],
 ARRAY['boaters','families','couples'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','fuel','WiFi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Nord-Koster Naturhamn', 'Nord-Koster', 58.9867, 11.0634,
 'Skyddad naturhamn pa Nord-Koster on. Vacker natur och enkla faciliteter.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['nord-koster','naturhamn','skyddad','koster'],
 'Naturkansla i en fredlig lagom till smaoegruppen.',
 'anchorage', 'nord-koster-naturhamn', 'bohuslan_nord',
 ARRAY['anchorage','nature','remote'],
 ARRAY['boaters','nature-lovers','divers'],
 ARRAY['anchorage','toilet','nature_reserve'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Syd-Koster Gasthamn', 'Syd-Koster', 58.8956, 11.0334,
 'Storre hamn pa Syd-Koster med restaurang och service. Bast pa Kosteroarna.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['syd-koster','gasthamn','koster','huvudhamn'],
 'Puls och liv pa Syd-Koster med god mat och bra liggplatser.',
 'marina', 'syd-koster-gasthamn', 'bohuslan_nord',
 ARRAY['marina','harbor_stop','food','family'],
 ARRAY['boaters','families','tourists'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fjallbacka Gasthamn', 'Fjallbacka', 58.9234, 11.2512,
 'Charmig gasthamn i pittoreska Fjallbacka. Nara konstgallerier och cafeer.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['fjallbacka','gasthamn','konststad','konstgallerier'],
 'Konstnaarlig miljoe i ett av Sveriges vackraste sma samhallen.',
 'marina', 'fjallbacka-gasthamn', 'bohuslan_nord',
 ARRAY['marina','harbor_stop','culture','art'],
 ARRAY['boaters','artists','couples'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','art_gallery'],
 'year_round', 'high'),

(gen_random_uuid(), 'Hamburgsund Gasthamn', 'Hamburgsund', 58.9678, 11.2234,
 'Gasthamn mitt i Hamburgsund. Mysig hamn med restaurang och bar.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['hamburgsund','gasthamn','kuststad','restaurang'],
 'Trivsamt samhalle med god seafood och vanlig atmosfar.',
 'marina', 'hamburgsund-gasthamn', 'bohuslan_nord',
 ARRAY['marina','harbor_stop','food','authentic'],
 ARRAY['boaters','families','food-lovers'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grebbestad Gasthamn', 'Grebbestad', 58.9012, 11.3234,
 'Valkand gasthamn med fullservice i Grebbestad. God utgangspunkt for utflyktare.',
 'Maj-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['grebbestad','gasthamn','fullservice','kust'],
 'Popular hamn med flera restauranger och shoppar inom gangavstand.',
 'marina', 'grebbestad-gasthamn', 'bohuslan_nord',
 ARRAY['marina','harbor_stop','food','shopping'],
 ARRAY['boaters','families','tourists'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Havstenssund Naturhamn', 'Havstenssund', 58.8734, 11.2901,
 'Fredlig naturhamn mellan holmarna. Perfekt for segling och fiske.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['havstenssund','naturhamn','holmgrupp','fiske'],
 'Vacker ankringsplats bland sma holmar med god fiskemoejlighet.',
 'anchorage', 'havstenssund-naturhamn', 'bohuslan_nord',
 ARRAY['anchorage','nature','fishing'],
 ARRAY['boaters','fishermen','nature-lovers'],
 ARRAY['anchorage','nature_reserve'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kastinget Marina', 'Karingoen', 58.8123, 11.2567,
 'Modern marina pa Karingoen. Teknik och service for moderna baataaagare.',
 'April-Oktober: 08:00-18:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['karingoen','marina','modern','teknik'],
 'Fullt utrustad marina med forsa¨ljning av baattilbehör och service.',
 'marina', 'kastinget-marina', 'bohuslan_nord',
 ARRAY['marina','service','shopping','tech'],
 ARRAY['boaters','power-boat'],
 ARRAY['guest_dock','electricity','water','shower','fuel','boat_repair','shop'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kosterfjaorden Anchorage', 'Kosteröarna', 58.9145, 11.0845,
 'Vacker ankarplats mitt i Kosterfjorden. Naturreservat med utmaarkta villkor.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['kosterfjorden','anchorage','naturreservat','holmgrupp'],
 'Naturreservat med varldsklaa segling och snorkling.',
 'anchorage', 'kosterfjaorden-anchorage', 'bohuslan_nord',
 ARRAY['anchorage','nature','diving','fishing'],
 ARRAY['boaters','divers','nature-lovers'],
 ARRAY['anchorage','nature_reserve','diving_site'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Karingoen Gasthamn', 'Karingoen', 58.8134, 11.2478,
 'Gasthamn pa Karingoen med restaurang och mysiga installationer.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['karingoen','gasthamn','restaurang','holmoe'],
 'Hemtrevlig hamn pa liten holmoe med goda matmoejligheter.',
 'marina', 'karingoen-gasthamn', 'bohuslan_nord',
 ARRAY['marina','harbor_stop','food','cozy'],
 ARRAY['boaters','families','foodies'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ramsvik Naturhamn', 'Ramsvik', 58.8456, 11.3678,
 'Vildmarksarmn pa fastlandet. Naturskon och fredlig ankarplats.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['ramsvik','naturhamn','fastland','vildmark'],
 'Avlagsna ankringsplats med ursprunglig natur.',
 'anchorage', 'ramsvik-naturhamn', 'bohuslan_nord',
 ARRAY['anchorage','nature','remote','hiking'],
 ARRAY['boaters','hikers','nature-lovers'],
 ARRAY['anchorage','nature_reserve','hiking_trails'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Nordvik Marina', 'Nordvik', 59.0123, 11.1567,
 'Ny marina med modern service och teknik. Ideell for langtiidsliggning.',
 'Januar-December: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['nordvik','marina','ny','moderna'],
 'Modernt marina-center med alla faciliteter och restaurang.',
 'marina', 'nordvik-marina', 'bohuslan_nord',
 ARRAY['marina','modern','service','food'],
 ARRAY['boaters','families','long-term'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','laundry','WiFi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Fjallbacka Restaurang', 'Fjallbacka', 58.9234, 11.2512,
 'Restaurang med medelhavsmat och utsikt over fjorden.',
 'Juni-Augusti: 11:00-22:00, Resten: 12:00-20:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['fjallbacka','restaurang','medelhavsmat','utsikt'],
 'Fin restaurang med chef fran Italienska Vastkusten.',
 'restaurant', 'fjallbacka-restaurang', 'bohuslan_nord',
 ARRAY['restaurant','food','view','fine_dining'],
 ARRAY['couples','foodies','diners'],
 ARRAY['restaurant','bar','view','parking'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grebbestad Restaurang', 'Grebbestad', 58.9012, 11.3234,
 'Kustrestaurang med fokus pa lokala rakor och fisk.',
 'Juni-Augusti: 12:00-23:00, Resten: closed.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['grebbestad','restaurang','skaldjur','fisk'],
 'Skaldljursfestival pa talriken varje dag sommaren.',
 'restaurant', 'grebbestad-restaurang', 'bohuslan_nord',
 ARRAY['restaurant','food','seafood','summer'],
 ARRAY['families','foodies','seafood-lovers'],
 ARRAY['restaurant','bar','terrace','parking'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Karingoen Restaurang', 'Karingoen', 58.8134, 11.2478,
 'Intim och hemtrevlig restaurang med klassisk svensk husmankost.',
 'Juni-September: 12:00-20:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['karingoen','restaurang','husmankost','klassisk'],
 'Aakt svensk husmankost i varm atmosfar pa liten holmoe.',
 'restaurant', 'karingoen-restaurang', 'bohuslan_nord',
 ARRAY['restaurant','food','swedish','cozy'],
 ARRAY['families','traditionalists','boaters'],
 ARRAY['restaurant','bar','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Stromstad Restaurang', 'Stromstad', 58.9456, 11.1823,
 'Modernt fiskrestaurang mitt i hamnen. Chef fran Norge.',
 'April-Oktober: 11:00-22:00, November-Mars: closed.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['stromstad','restaurang','fisk','norsk'],
 'Skandinavisk fiskmat med fokus pa torskeraatt och gravlax.',
 'restaurant', 'stromstad-restaurang', 'bohuslan_nord',
 ARRAY['restaurant','food','seafood','scandinavian'],
 ARRAY['couples','foodies','families'],
 ARRAY['restaurant','bar','waterfront','parking'],
 'year_round', 'high'),

(gen_random_uuid(), 'Stromstad Bensinstation', 'Stromstad', 58.9456, 11.1823,
 'Baatbensin och dieselstation. Snabb service och bra priser.',
 'April-Oktober: 08:00-18:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['stromstad','bensin','diesel','service'],
 'Tillforlaetlig braenselstation for alla baattyper.',
 'fuel_station', 'stromstad-bensinstation', 'bohuslan_nord',
 ARRAY['fuel','service','tech'],
 ARRAY['boaters','power-boats'],
 ARRAY['fuel','water','air_pump'],
 'year_round', NULL),

(gen_random_uuid(), 'Fjallbacka Bensinstation', 'Fjallbacka', 58.9234, 11.2512,
 'Bensinstation oepen aaret om. Diesel och bensinkvalitet A95.',
 'Januar-December: 07:00-19:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['fjallbacka','bensin','diesel','station'],
 'Gott sortiment och snabb service aaret runt.',
 'fuel_station', 'fjallbacka-bensinstation', 'bohuslan_nord',
 ARRAY['fuel','service','shop'],
 ARRAY['boaters','all'],
 ARRAY['fuel','water','shop','air_pump'],
 'year_round', NULL),

(gen_random_uuid(), 'Grebbestad Bensinstation', 'Grebbestad', 58.9012, 11.3234,
 'Baatbraensle och servicestation i centrum av Grebbestad.',
 'Maj-Oktober: 08:00-18:00, November-April: closed.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['grebbestad','bensin','service','sommar'],
 'Sommarstation med allt for baatmotorn och lite extra.',
 'fuel_station', 'grebbestad-bensinstation', 'bohuslan_nord',
 ARRAY['fuel','service','seasonal'],
 ARRAY['boaters','tourists'],
 ARRAY['fuel','water','oil','air_pump'],
 'summer_only', NULL);
