-- seed-stockholm-sodra.sql
-- Sodra Stockholms skargard seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'stockholm_sodra';
DELETE FROM restaurants WHERE name IN (
  'Dalaro Gasthamn', 'Orno Gasthamn', 'Musko Gasthamn',
  'Namndö Gasthamn', 'Haro Gasthamn', 'Oja Gasthamn', 'Huvudskar Gasthamn',
  'Dalaro Naturhamn', 'Orno Naturhamn', 'Huvudskar Naturhamn', 'Oja Naturhamn',
  'Dalaro Vardshus', 'Haro Fiskekrog', 'Namndö Restaurang', 'Orno Krog',
  'Dalaro Bunkring', 'Musko Bunkring', 'Haro Bunkring', 'Oja Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Dalaro Gasthamn', 'Dalaro', 59.1333, 18.4000,
 'Gasthamn i Dalaro, porten till sodra Stockholms skargard. Klassisk sommarort med levande hamnmiljo och bra service.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['dalaro','gasthamn','porten','sodra_skargard'],
 'Porten till sodra skargarden med klassisk sommaratmosfar.',
 'marina', 'dalaro-gasthamn', 'stockholm_sodra',
 ARRAY['marina','harbor_stop','klassisk'],
 ARRAY['familjer','stockholmare','seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Orno Gasthamn', 'Orno', 58.9667, 18.5333,
 'Gasthamn pa Orno i yttre sodra skargarden. Stor o med bra vandringsleder och fin natur. Populart utflyktsmaal.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['orno','gasthamn','vandring','natur'],
 'Stor skargardsö med bra vandringsleder och levande sommarliv.',
 'marina', 'orno-gasthamn', 'stockholm_sodra',
 ARRAY['marina','harbor_stop','vandring'],
 ARRAY['naturintresserade','familjer','vandrare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Musko Gasthamn', 'Musko', 59.0667, 18.1833,
 'Gasthamn pa Musko i norra Haningeskargarden. Historisk marinbas nu omgjord till civila bruk. Unik miljo med stora hallar i berget.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['musko','gasthamn','marinbas','historisk'],
 'Unik miljo vid fd marinbas med hallar i berget.',
 'marina', 'musko-gasthamn', 'stockholm_sodra',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['historieintresserade','seglare','nyfikna'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Namndö Gasthamn', 'Namndö', 59.0167, 18.6167,
 'Gasthamn pa Namndö i sodra mellerskargarden. Bilfri o med naturskona vandringsleder och autentisk skargardskaraktar.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['namndö','gasthamn','bilfri','autentisk'],
 'Bilfri o med autentisk skargardskaraktar och fin vandringsnatur.',
 'marina', 'namndö-gasthamn', 'stockholm_sodra',
 ARRAY['marina','harbor_stop','bilfri'],
 ARRAY['naturintresserade','lugnsokande','par'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Haro Gasthamn', 'Haro', 58.9333, 18.2500,
 'Gasthamn pa Haro i yttre sodra skargarden. Lummig och naturskona o med bra bad och fiske.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['haro','gasthamn','natur','bad'],
 'Naturskön o med bra bad och avslappnad stämning.',
 'marina', 'haro-gasthamn', 'stockholm_sodra',
 ARRAY['marina','harbor_stop','bad'],
 ARRAY['familjer','badglada','naturintresserade'],
 ARRAY['guest_dock','electricity','water','shower','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Oja Gasthamn', 'Oja', 58.8667, 17.9167,
 'Gasthamn pa Oja med fyrtorn och dramatisk ytterskargardsmiljo. Avskild o med autentisk miljö och oppen Ostersjö.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['oja','gasthamn','fyrtorn','ytterskargard'],
 'Avskild ytterö med fyrtorn och dramatisk Ostersjömiljo.',
 'marina', 'oja-gasthamn', 'stockholm_sodra',
 ARRAY['marina','harbor_stop','ytterhamn'],
 ARRAY['aventyrare','erfarna_seglare','naturintresserade'],
 ARRAY['guest_dock','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Huvudskar Gasthamn', 'Huvudskar', 58.9833, 18.7833,
 'Gasthamn pa Huvudskar, yttersta beboddas-utposten i Stockholms sodra skargard. Dramatisk miljo med Ostersjöns oppen horisont.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['huvudskar','gasthamn','ytterst','ostersjon'],
 'Yttersta utposten med dramatisk Ostersjöutsikt.',
 'marina', 'huvudskar-gasthamn', 'stockholm_sodra',
 ARRAY['marina','harbor_stop','ytterhamn'],
 ARRAY['erfarna_seglare','aventyrare'],
 ARRAY['guest_dock','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Dalaro Naturhamn', 'Dalaro', 59.1200, 18.4200,
 'Naturankring i Dalaro-omradet med skyddade vikar och typisk sodra skargardsmiljo.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['dalaro','naturhamn','ankring','skyddad'],
 'Skyddade ankringsvikar i nara Dalaro.',
 'anchorage', 'dalaro-naturhamn', 'stockholm_sodra',
 ARRAY['anchorage','nature'],
 ARRAY['familjer','stockholmare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Orno Naturhamn', 'Orno', 58.9500, 18.5500,
 'Naturankring pa Ornö med skyddade vikar och ostord natur i yttre sodra skargarden.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['orno','naturhamn','ankring','ostord'],
 'Ostord naturankring pa Ornö med fin natur.',
 'anchorage', 'orno-naturhamn', 'stockholm_sodra',
 ARRAY['anchorage','nature'],
 ARRAY['naturintresserade','lugnsokande'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Huvudskar Naturhamn', 'Huvudskar', 58.9750, 18.7900,
 'Naturankring runt Huvudskar med dramatisk ytterskargardsmiljo och oppen Ostersjö.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['huvudskar','naturhamn','ankring','ytterst'],
 'Dramatisk ytterskargards-ankring vid Ostersjöns horisont.',
 'anchorage', 'huvudskar-naturhamn', 'stockholm_sodra',
 ARRAY['anchorage','nature','ytterhamn'],
 ARRAY['erfarna_seglare','aventyrare'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Oja Naturhamn', 'Oja', 58.8600, 17.9100,
 'Naturankring runt Oja med dramatisk kust och avskild miljo.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['oja','naturhamn','ankring','dramatisk'],
 'Avskild naturankring pa ytterö med vildmarkskansla.',
 'anchorage', 'oja-naturhamn', 'stockholm_sodra',
 ARRAY['anchorage','nature','remote'],
 ARRAY['aventyrare','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Dalaro Vardshus', 'Dalaro', 59.1335, 18.4003,
 'Traditionsrikt vardshus i Dalaro med klassisk skargardskost. Aret runt-restaurang som serverar lokala smaker och sasongsmat.',
 'Helaret: 12:00-21:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['dalaro','vardshus','traditionsrik','skargardskost'],
 'Traditionsrikt vardshus med klassisk skargardskost aret runt.',
 'restaurant', 'dalaro-vardshus', 'stockholm_sodra',
 ARRAY['restaurang','traditionsrik'],
 ARRAY['par','familjer','seglare'],
 ARRAY['restaurang','uteservering'],
 'year_round', 'high'),

(gen_random_uuid(), 'Haro Fiskekrog', 'Haro', 58.9335, 18.2503,
 'Enkel fiskekrog pa Haro med dagsfangst och avslappnad miljo. Populart tillhall for seglare i yttre sodra skargarden.',
 'Juni-Augusti: 11:00-20:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['haro','fiskekrog','dagsfangst','enkel'],
 'Enkel fiskekrog med dagsfangst i avslappnad ytterskargardsmiljo.',
 'restaurant', 'haro-fiskekrog', 'stockholm_sodra',
 ARRAY['restaurang','fisk'],
 ARRAY['seglare','naturintresserade'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Namndö Restaurang', 'Namndö', 59.0169, 18.6170,
 'Restaurang pa Namndö med lokal mat och fin skargardsvy. God mat pa bilfri skargardsö.',
 'Juni-Augusti: 12:00-20:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['namndö','restaurang','bilfri','skargardsvy'],
 'God mat med skargardsvy pa bilfri o.',
 'restaurant', 'namndö-restaurang', 'stockholm_sodra',
 ARRAY['restaurang'],
 ARRAY['familjer','naturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Orno Krog', 'Orno', 58.9669, 18.5336,
 'Lokal krog pa Ornö med enkel mat och avslappnad skargardsstämning.',
 'Juni-Augusti: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['orno','krog','lokal','enkel'],
 'Enkel lokal krog med avslappnad skargardsstamning.',
 'restaurant', 'orno-krog', 'stockholm_sodra',
 ARRAY['restaurang'],
 ARRAY['seglare','naturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Dalaro Bunkring', 'Dalaro', 59.1329, 18.3994,
 'Marinbunkring i Dalaro. Aret-runt-service vid porten till sodra Stockholms skargard.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['dalaro','bransle','helaret'],
 NULL,
 'fuel_station', 'dalaro-bunkring', 'stockholm_sodra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Musko Bunkring', 'Musko', 59.0663, 18.1826,
 'Branslestation pa Musko for seglare i norra Haningeskargarden.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['musko','bransle'],
 NULL,
 'fuel_station', 'musko-bunkring', 'stockholm_sodra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Haro Bunkring', 'Haro', 58.9329, 18.2494,
 'Branslestopp pa Haro for seglare i yttre sodra skargarden.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['haro','bransle','yttre'],
 NULL,
 'fuel_station', 'haro-bunkring', 'stockholm_sodra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Oja Bunkring', 'Oja', 58.8663, 17.9163,
 'Branslestopp pa Oja for seglare i ytterskargarden.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['oja','bransle','ytterst'],
 NULL,
 'fuel_station', 'oja-bunkring', 'stockholm_sodra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
