DELETE FROM restaurants WHERE archipelago_region = 'skargaardshavet';
DELETE FROM restaurants WHERE name IN ('Korpo Gasthamn', 'Nagu Gasthamn', 'Pargas Gasthamn', 'Houtskaar Gasthamn', 'Inio Gasthamn', 'Turku Aboa Gasthamn', 'Berghamn Gasthamn', 'Korpo Naturhamn', 'Bjorko Naturhamn', 'Aland Channel Naturhamn', 'Lemland Naturhamn', 'Nagu Restaurant & Cafe', 'Korpo Sea Kitchen', 'Pargas Archipelago Table', 'Houtskaar Fishermans Grill', 'Turku Marina Fuel', 'Nagu Harbor Fuel', 'Pargas Fuel Station');

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Korpo Gasthamn', 'Korpo', 60.0842, 21.7236,
 'Etablerad gasthamn i hjaartat av Korpo. Full service med el, vatten och dusch.',
 'Juni-Augusti: 08:00-21:00, Maj och September: 09:00-18:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['korpo','gasthamn','fullservice','skargaardshavet'],
 'Grunda vatten och varm sommarnattemot skargarden.',
 'marina', 'korpo-gasthamn', 'skargaardshavet',
 ARRAY['marina','harbor_stop','guesthouse'],
 ARRAY['boaters','families','sailors'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nagu Gasthamn', 'Nagu', 60.2014, 21.5631,
 'Charmig gasthamn i Nagu med butiker och traditioner. Mycken historia pa denna o.',
 'Juni-Augusti: dygnet runt, Maj och September: 09:00-20:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['nagu','gasthamn','tradition','handelskaj'],
 'Traditioner och salt fran gamla handelsdagar pa Nagu.',
 'marina', 'nagu-gasthamn', 'skargaardshavet',
 ARRAY['marina','harbor_stop','cultural'],
 ARRAY['boaters','history','families'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','shop'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Pargas Gasthamn', 'Pargas', 60.2342, 21.7158,
 'Ordnad gasthamn i Pargas hamn. Traditionsrik ort med gammalt kustliv.',
 'Juni-Augusti: dygnet runt, Maj och September: 08:00-19:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['pargas','gasthamn','kuststad','handelskaj'],
 'En av de stora handelsorterna i den finska skargarden.',
 'marina', 'pargas-gasthamn', 'skargaardshavet',
 ARRAY['marina','harbor_stop','commercial'],
 ARRAY['boaters','traders','families'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','shop'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Houtskaar Gasthamn', 'Houtskaar', 60.3614, 21.6497,
 'Mysig gasthamn pa Houtskaar. Lugnt tillhall med traditionsrik kutur och atmosfar.',
 'Juni-Augusti: 08:00-20:00, Maj och September: 10:00-18:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['houtskaar','gasthamn','lugn','kustkultur'],
 'Houtskaar med dess gamla kultur och lugna vaxter.',
 'marina', 'houtskaar-gasthamn', 'skargaardshavet',
 ARRAY['marina','harbor_stop','cultural'],
 ARRAY['boaters','quiet-seekers','families'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Inio Gasthamn', 'Inio', 60.3864, 21.4256,
 'Liten gasthamn pa Inio. Naturskont omrade med vandringsmoijligheter och fiskle.',
 'Juni-Augusti: 09:00-19:00, Maj och September: 10:00-17:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['inio','gasthamn','natur','vandringsmoijlighet'],
 'Naturskont Inio for lugna seglare och vandrare.',
 'marina', 'inio-gasthamn', 'skargaardshavet',
 ARRAY['marina','harbor_stop','nature'],
 ARRAY['boaters','hikers','nature-lovers'],
 ARRAY['guest_dock','water','toilet','cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Turku Aboa Gasthamn', 'Turku', 60.4352, 22.2642,
 'Moderna gasthamnen i Turkus hamn. Full service och nara stadskaj med restauranger.',
 'Ganzajrig: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['turku','gasthamn','stad','fullservice'],
 'Urban skargardserlebnis i Finlands gamla huvudstad.',
 'marina', 'turku-aboa-gasthamn', 'skargaardshavet',
 ARRAY['marina','harbor_stop','urban'],
 ARRAY['boaters','foodies','city-lovers'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','shop','bar'],
 'year_round', 'high'),

(gen_random_uuid(), 'Berghamn Gasthamn', 'Berghamn', 60.1536, 21.6064,
 'Charterbase och gasthamn pa Berghamn. Sjalbetjaning och traditionsrik matservering.',
 'Juni-Augusti: 08:00-20:00, Maj och September: 09:00-18:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800'],
 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800',
 ARRAY['berghamn','gasthamn','charter','traditionsrik'],
 'Berghamns charm med charter och traditionsrik mat.',
 'marina', 'berghamn-gasthamn', 'skargaardshavet',
 ARRAY['marina','harbor_stop','charter'],
 ARRAY['boaters','charter-sailors','families'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','charter'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Korpo Naturhamn', 'Korpo', 60.0568, 21.6841,
 'Vild och vacker naturhamn among skargardsskallar. Ankring for naturseglare.',
 'Juni-September: Olimitat ankoringssasonf.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['korpo','naturhamn','anchorage','natur'],
 'Ursprunglig ankringplats among klippor och natur.',
 'anchorage', 'korpo-naturhamn', 'skargaardshavet',
 ARRAY['anchorage','nature','wild'],
 ARRAY['boaters','explorers','nature-lovers'],
 ARRAY['natural_anchorage','wilderness'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Bjorko Naturhamn', 'Bjorko', 60.2756, 21.8542,
 'Skyddad naturhamn pa Bjorko omgivet av skog och klippor.',
 'Juni-September: Ankringmoijligheter hela dagen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['bjorko','naturhamn','anchorage','skydd'],
 'Skyddad ankringplats bland och forest och klippor.',
 'anchorage', 'bjorko-naturhamn', 'skargaardshavet',
 ARRAY['anchorage','nature','shelter'],
 ARRAY['boaters','explorers','peaceful-seekers'],
 ARRAY['natural_anchorage','forest_shelter'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Aland Channel Naturhamn', 'Nagu', 60.2478, 21.3856,
 'Naturskont ankringplats i Alands kanal. Lugn och skyddad hamn.',
 'Juni-September: Fri ankring.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['aland','naturhamn','anchorage','kanal'],
 'Ankringplats pa vagen till Aland.',
 'anchorage', 'aland-channel-naturhamn', 'skargaardshavet',
 ARRAY['anchorage','nature','passage'],
 ARRAY['boaters','explorers','transit-sailors'],
 ARRAY['natural_anchorage'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Lemland Naturhamn', 'Inio', 60.4108, 21.2914,
 'Vildmark ankringplats pa yttre skargarden. Forunderlig natur och tystnad.',
 'Juni-September: Ankringmoijligheter.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['lemland','naturhamn','anchorage','yttre'],
 'Yttersta skargarden med vildmark och tystnad.',
 'anchorage', 'lemland-naturhamn', 'skargaardshavet',
 ARRAY['anchorage','nature','remote'],
 ARRAY['boaters','adventurers','solitude-seekers'],
 ARRAY['natural_anchorage','remote'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Nagu Restaurant & Cafe', 'Nagu', 60.2042, 21.5667,
 'Fisk och skaldjur fran lokala fiskare. Skandinavisk kukknad med finsk twist.',
 'Juni-Augusti: 12:00-22:00 dagligt, Maj och September: 12:00-20:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800'],
 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
 ARRAY['nagu','restaurant','fisk','skaldjur','nordisk'],
 'Traditionsrik fiskmatt och skaldjur i gammalt fiskarlage.',
 'restaurant', 'nagu-restaurant-cafe', 'skargaardshavet',
 ARRAY['restaurant','seafood','nordic'],
 ARRAY['foodies','couples','boaters'],
 ARRAY['restaurant','parking','terrace'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Korpo Sea Kitchen', 'Korpo', 60.0875, 21.7312,
 'Moderne kukknad med traditionella skargardsakojningar. Muskler och krabba.',
 'Juni-Augusti: 11:00-22:00 dagligt, Maj och September: 12:00-20:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800'],
 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
 ARRAY['korpo','restaurant','skaldjur','modernfiskmat'],
 'Moderna redningar av klassisk skargardsfiskmat.',
 'restaurant', 'korpo-sea-kitchen', 'skargaardshavet',
 ARRAY['restaurant','seafood','modern'],
 ARRAY['foodies','adventurers','boaters'],
 ARRAY['restaurant','bar','terrace','parking'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Pargas Archipelago Table', 'Pargas', 60.2358, 21.7212,
 'Fine dining med utsikt over Pargas hamn. Nordisk kukknad med Baltiska influenser.',
 'Juni-Augusti: 17:00-23:00 dagligt, Maj och September: 17:00-22:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1504674900768-8d27db3ce345?w=800'],
 'https://images.unsplash.com/photo-1504674900768-8d27db3ce345?w=800',
 ARRAY['pargas','finedinning','nordisk','utsikt','baltisk'],
 'Elegant middag med utsikt over den levande hamnen.',
 'restaurant', 'pargas-archipelago-table', 'skargaardshavet',
 ARRAY['restaurant','fine_dining','nordic'],
 ARRAY['couples','foodies','special_occasions'],
 ARRAY['restaurant','bar','reservations','view'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Houtskaar Fishermans Grill', 'Houtskaar', 60.3648, 21.6547,
 'Rustikalt serveringsstad. Grillad fisk och skaldjur fran dagen. Traditionell stil.',
 'Juni-Augusti: 12:00-20:00 dagligt, Maj och September: 12:00-19:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555939594-58d7cb561341?w=800'],
 'https://images.unsplash.com/photo-1555939594-58d7cb561341?w=800',
 ARRAY['houtskaar','grill','fiskmat','rustikalt'],
 'Enkel men god grillmat fran den lokala fangsten.',
 'restaurant', 'houtskaar-fishermans-grill', 'skargaardshavet',
 ARRAY['restaurant','grill','seafood','casual'],
 ARRAY['boaters','families','local-flavors'],
 ARRAY['restaurant','parking','casual'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Turku Marina Fuel', 'Turku', 60.4368, 22.2718,
 'Bensinstationen i Turkus marina. Diesel, bensin och marinoljor. 24h serveraing.',
 'Ganzajrig: 07:00-21:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800'],
 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800',
 ARRAY['turku','fuel','marina','bensin','diesel'],
 'Palivailu og marinoljor i Turkus marina.',
 'fuel_station', 'turku-marina-fuel', 'skargaardshavet',
 ARRAY['fuel_station','marina','supplies'],
 ARRAY['boaters','vessels'],
 ARRAY['fuel_pump','diesel','gasoline','oil'],
 'year_round', 'high'),

(gen_random_uuid(), 'Nagu Harbor Fuel', 'Nagu', 60.2064, 21.5689,
 'Bensinstationen pa Nagu hamn. Diesel, bensin och marinservice.',
 'Juni-Augusti: 08:00-20:00, Maj och September: 09:00-18:00, Oktober-Maj: 10:00-17:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800'],
 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800',
 ARRAY['nagu','fuel','hamn','bensin','diesel','marinservice'],
 'Palvelu pa Nagu hamn for alla seglare.',
 'fuel_station', 'nagu-harbor-fuel', 'skargaardshavet',
 ARRAY['fuel_station','harbor','supplies'],
 ARRAY['boaters','vessels'],
 ARRAY['fuel_pump','diesel','gasoline','maintenance'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Pargas Fuel Station', 'Pargas', 60.2374, 21.7264,
 'Bensinstation och marinservice i Pargas. Fullt utslag av marinoljor och reservdelar.',
 'Juni-Augusti: 07:00-20:00, Maj och September: 08:00-19:00, Oktober-April: 09:00-17:00.', NULL,
 ARRAY['https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800'],
 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800',
 ARRAY['pargas','fuel','bensin','diesel','reservdelar','marinoljor'],
 'Fullstandig marinservice och palivailu pa Pargas.',
 'fuel_station', 'pargas-fuel-station', 'skargaardshavet',
 ARRAY['fuel_station','marina','service','supplies'],
 ARRAY['boaters','vessels','mechanics'],
 ARRAY['fuel_pump','diesel','gasoline','parts','maintenance'],
 'summer_only', 'high');
