-- seed-sodermanland.sql
-- Sodermanlands skargard seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'sodermanland';
DELETE FROM restaurants WHERE name IN (
  'Trosa Gasthamn', 'Oxelosund Gasthamn', 'Nykoping Gasthamn',
  'Nynashamn Gasthamn', 'Uto Gasthamn', 'Stendorren Gasthamn', 'Landsort Gasthamn',
  'Uto Naturhamn', 'Stendorren Naturhamn', 'Landsort Naturhamn', 'Haradskar Naturhamn',
  'Trosa Hamkrog', 'Uto Vardshus', 'Nykoping Hamn Bar', 'Nynashamn Restaurang',
  'Trosa Bunkring', 'Nykoping Bunkring', 'Nynashamn Bunkring', 'Uto Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Trosa Gasthamn', 'Trosa', 58.8972, 17.5528,
 'Charmig gasthamn i Trosa, kallad Sveriges lyckligaste stad. Pittoresk traahusmiljo, fina restauranger och levande sommaratmosfar vid an.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['trosa','gasthamn','pittoresk','traahus'],
 'Sveriges lyckligaste stad med traahusmiljo och mysig hamnkansla.',
 'marina', 'trosa-gasthamn', 'sodermanland',
 ARRAY['marina','harbor_stop','pittoresk'],
 ARRAY['par','familjer','turister'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe','wifi'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Oxelosund Gasthamn', 'Oxelosund', 58.6667, 17.1000,
 'Gasthamn i Oxelosund vid Braviken. Industristad med omgivande skargardslandskap och bra service for seglare.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['oxelosund','gasthamn','braviken','service'],
 'Hamn med bra service vid Bravikens mynning.',
 'marina', 'oxelosund-gasthamn', 'sodermanland',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['transitseglare','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nykoping Gasthamn', 'Nykoping', 58.7522, 17.0075,
 'Gasthamn i Nykoping, en av Sodermanlands stoersta staeder. Historisk stad med Nykopingshus och aktiv sommarhamn.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['nykoping','gasthamn','historisk','nykopingshus'],
 'Historisk stad med medeltida slott och levande hamn.',
 'marina', 'nykoping-gasthamn', 'sodermanland',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['familjer','historieintresserade','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket'],
 'year_round', 'high'),

(gen_random_uuid(), 'Nynashamn Gasthamn', 'Nynashamn', 58.9042, 17.9483,
 'Stor gasthamn i Nynashamn, porten till Stockholms sodra skargard. Farja till Gotland gar harifran. Bra service och stor kapacitet.',
 'Helaret: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['nynashamn','gasthamn','gotlandsfarja','porten'],
 'Porten till Gotland och sodra skargarden med bra fullservice.',
 'marina', 'nynashamn-gasthamn', 'sodermanland',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['alla_seglare','gotlandsseglar','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi','ferry'],
 'year_round', 'high'),

(gen_random_uuid(), 'Uto Gasthamn', 'Uto', 58.9667, 18.3167,
 'Gasthamn pa Uto i yttre Stockholms skargard. Bilfri miljoby med naturreservat, vandringsleder och genuint skargardsarv.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['uto','gasthamn','bilfri','naturreservat'],
 'Bilfri o med naturreservat och genuint skargardsarv i yttre skargarden.',
 'marina', 'uto-gasthamn', 'sodermanland',
 ARRAY['marina','harbor_stop','bilfri'],
 ARRAY['naturintresserade','familjer','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Stendorren Gasthamn', 'Stendorren', 58.7833, 17.5333,
 'Gasthamn vid Stendorrens naturreservat. Skyddad hamn med omgivande storslagen kustmiljo och rikt djurliv.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['stendorren','gasthamn','naturreservat','kustmiljo'],
 'Naturreservatets hamn med storslagna klippor och skyddade vikar.',
 'marina', 'stendorren-gasthamn', 'sodermanland',
 ARRAY['marina','harbor_stop','natur'],
 ARRAY['naturintresserade','familjer','lugnsokande'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Landsort Gasthamn', 'Landsort', 58.7417, 17.8597,
 'Gasthamn pa Landsort, Sveriges sydligaste bebodda fyr-o. Yttersta utposten i Stockholms skargard med Ostersjons oppen horisont.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['landsort','gasthamn','fyro','ytterst'],
 'Yttersta bebodda on med fyrtorn och dramatisk Ostersjoutsikt.',
 'marina', 'landsort-gasthamn', 'sodermanland',
 ARRAY['marina','harbor_stop','ytterhamn'],
 ARRAY['erfarna_seglare','aventyrare','naturintresserade'],
 ARRAY['guest_dock','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Uto Naturhamn', 'Uto', 58.9500, 18.3400,
 'Naturhamn pa sodra Uto med skyddade ankringsvikar i naturreservatet.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['uto','naturhamn','ankring','naturreservat'],
 'Skyddad ankring i naturreservat pa yttre Uto.',
 'anchorage', 'uto-naturhamn', 'sodermanland',
 ARRAY['anchorage','nature','naturreservat'],
 ARRAY['naturintresserade','familjer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Stendorren Naturhamn', 'Stendorren', 58.7700, 17.5500,
 'Naturhamn i Stendorrens naturreservat. Vacker kustmiljo med klippor och ronn.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['stendorren','naturhamn','ankring','klippor'],
 'Storslagna klippor och skyddade vikar i naturreservat.',
 'anchorage', 'stendorren-naturhamn', 'sodermanland',
 ARRAY['anchorage','nature','klippa'],
 ARRAY['naturintresserade','familjer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Landsort Naturhamn', 'Landsort', 58.7350, 17.8650,
 'Naturankring runt Landsort med dramatisk ytterskargardsmiljo.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['landsort','naturhamn','ankring','dramatisk'],
 'Dramatisk ytterskargard vid Sveriges sydligaste fyrtorn.',
 'anchorage', 'landsort-naturhamn', 'sodermanland',
 ARRAY['anchorage','nature','ytterhamn'],
 ARRAY['erfarna_seglare','aventyrare'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Haradskar Naturhamn', 'Haradskar', 58.8500, 17.9000,
 'Naturhamn pa Haradskar med skyddade vikar och tyst skargardskaraktar.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['haradskar','naturhamn','ankring','stilla'],
 'Lugn naturankring med typisk Sodermanlands-skargard.',
 'anchorage', 'haradskar-naturhamn', 'sodermanland',
 ARRAY['anchorage','nature','lugn'],
 ARRAY['lugnsokande','familjer'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Trosa Hamkrog', 'Trosa', 58.8974, 17.5531,
 'Klassisk hamkrog i Trosa med sommarmat och traahusutsikt. God fisk och husmanskost i trevlig miljo.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['trosa','hamkrog','sommarmat','traahusmiljo'],
 'God mat i pittoreska Trosas hamnmiljo.',
 'restaurant', 'trosa-hamkrog', 'sodermanland',
 ARRAY['restaurang','middag'],
 ARRAY['par','familjer','turister'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Uto Vardshus', 'Uto', 58.9669, 18.3170,
 'Traditionsrikt vardshus pa Uto med god mat och unikt lage pa bilfri o. Populart tillhall for seglare och dagbesokare.',
 'Maj-September: 11:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['uto','vardshus','traditionsrik','bilfri'],
 'Traditionsrikt vardshus pa bilfri naturreservats-o.',
 'restaurant', 'uto-vardshus', 'sodermanland',
 ARRAY['restaurang','traditionsrik'],
 ARRAY['seglare','naturintresserade','par'],
 ARRAY['restaurang','bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nykoping Hamn Bar', 'Nykoping', 58.7524, 17.0078,
 'Bar och restaurang vid Nykopings gasthamn. Levande sommaratmosfar med utsikt over an och hamnen.',
 'April-Oktober: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['nykoping','hamnbar','sommar','an'],
 'Sommarbar vid an i historiska Nykoping.',
 'restaurant', 'nykoping-hamn-bar', 'sodermanland',
 ARRAY['restaurang','bar'],
 ARRAY['par','lokala','turister'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nynashamn Restaurang', 'Nynashamn', 58.9044, 17.9486,
 'Restaurang i Nynashamns hamn med utsikt mot skargarden. Bra mat for seglare pa vag ut eller hemkomna.',
 'April-Oktober: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['nynashamn','restaurang','hamnutsikt'],
 'Hamnutsikt och god mat i Nynashamns aktiva hamn.',
 'restaurant', 'nynashamn-restaurang', 'sodermanland',
 ARRAY['restaurang'],
 ARRAY['seglare','familjer','gotlandsresenarer'],
 ARRAY['restaurang','uteservering'],
 'year_round', 'medium'),

(gen_random_uuid(), 'Trosa Bunkring', 'Trosa', 58.8969, 17.5524,
 'Marinbunkring i Trosa. Diesel och bensin for seglare i Sodermanlands vackraste hamnstad.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['trosa','bransle','diesel'],
 NULL,
 'fuel_station', 'trosa-bunkring', 'sodermanland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nykoping Bunkring', 'Nykoping', 58.7519, 17.0071,
 'Branslestation i Nykoping for seglare pa vag langs Sodermanlands kust.',
 'April-Oktober: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['nykoping','bransle','diesel'],
 NULL,
 'fuel_station', 'nykoping-bunkring', 'sodermanland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nynashamn Bunkring', 'Nynashamn', 58.9039, 17.9479,
 'Marinbunkring i Nynashamn. Aret-runt-station for seglare och farjeresenarer.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['nynashamn','bransle','helaret'],
 NULL,
 'fuel_station', 'nynashamn-bunkring', 'sodermanland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Uto Bunkring', 'Uto', 58.9663, 18.3163,
 'Branslestopp pa Uto for seglare i yttre skargarden.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['uto','bransle','ytterhamn'],
 NULL,
 'fuel_station', 'uto-bunkring', 'sodermanland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
