-- seed-roslagen.sql
-- Roslagen seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'roslagen';
DELETE FROM restaurants WHERE name IN (
  'Norrtalje Gasthamn', 'Grisslehamn Gasthamn', 'Arholma Gasthamn',
  'Oregrund Gasthamn', 'Singo Gasthamn', 'Blido Gasthamn', 'Rafsnäs Gasthamn',
  'Arholma Naturhamn', 'Blidosund Naturhamn', 'Idskaret Naturhamn', 'Kallskaret Naturhamn',
  'Norrtalje Hamkrog', 'Arholma Vardshus', 'Grisslehamn Restaurang', 'Oregrund Krogen',
  'Norrtalje Bunkring', 'Oregrund Bunkring', 'Grisslehamn Bunkring', 'Arholma Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Norrtalje Gasthamn', 'Norrtalje', 59.7578, 18.7042,
 'Stor och valutrustad gasthamn i Norrtalje stad. Centralhamn for hela Roslagen med bra service, affarer och restauranger inom gangavstand.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['norrtalje','gasthamn','stad','service'],
 'Roslagens centralhamn med fullservice och bra stadutsikt.',
 'marina', 'norrtalje-gasthamn', 'roslagen',
 ARRAY['marina','harbor_stop','town'],
 ARRAY['boaters','families','transitseglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Grisslehamn Gasthamn', 'Grisslehamn', 60.0939, 18.8231,
 'Historisk hamn i norra Roslagen. Angbatsbrygga och forfattarhistoria — August Strindberg bodde har. Bra utgangspunkt for utfarden till Finland.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['grisslehamn','gasthamn','historisk','strindberg'],
 'Historisk hamnby med litterart arv och bra lage for Finlandsseglatser.',
 'marina', 'grisslehamn-gasthamn', 'roslagen',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['boaters','historieintresserade','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Arholma Gasthamn', 'Arholma', 59.9233, 19.1667,
 'Landande gasthamn pa Arholma, en av Roslagens yttersta oar. Vild skargard och enastaaende utsikt. Populart mal for seglare.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['arholma','gasthamn','ytterskargard','vild'],
 'Yttersta Roslagen med oppen horisont mot Finland och Aland.',
 'marina', 'arholma-gasthamn', 'roslagen',
 ARRAY['marina','harbor_stop','ytterhamn'],
 ARRAY['erfarna_seglare','naturintresserade','aventyrare'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Oregrund Gasthamn', 'Oregrund', 60.3333, 18.4500,
 'Trevlig gasthamn i Oregrund, en gammal handelstad med bevarad traahusmiljo. Norra Roslagens porten mot havet.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['oregrund','gasthamn','historisk','traahusmiljo'],
 'Gammal handelstad med vacker traahusmiljo och aktiv hamn.',
 'marina', 'oregrund-gasthamn', 'roslagen',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['familjer','historieintresserade','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Singo Gasthamn', 'Singo', 59.9167, 18.7333,
 'Lugn gasthamn pa Singo med naturskon miljo. Bra lage i Roslagens innerskargard for dagsturer och ankring.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['singo','gasthamn','innerskargard','lugn'],
 'Naturskon innerskargard med lugna liggplatser.',
 'marina', 'singo-gasthamn', 'roslagen',
 ARRAY['marina','harbor_stop','natur'],
 ARRAY['familjer','lugnsokande','naturintresserade'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Blido Gasthamn', 'Blido', 59.6167, 18.8833,
 'Gasthamn pa Blido, en stor bebodd o i sydliga Roslagen. Nara nog till Stockholm for dagsturer men tillrackligt avlags for att kanna skargardsro.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1551524358-f34c0214781c?w=800'],
 'https://images.unsplash.com/photo-1551524358-f34c0214781c?w=800',
 ARRAY['blido','gasthamn','skargard','tillganglig'],
 'Befolkad o med bra service och narheten till Stockholms skargard.',
 'marina', 'blido-gasthamn', 'roslagen',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['familjer','nyboljare','stockholmsseglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Rafsnäs Gasthamn', 'Rafsnas', 59.6667, 18.8333,
 'Liten gasthamn vid Rafsnas med god service och trivsam atmosfar. Populart mal pa vag norrut langs Roslagen.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['rafsnas','gasthamn','transithamn'],
 'Bekam gasthamn pa vag langs Roslagens kust.',
 'marina', 'rafsnas-gasthamn', 'roslagen',
 ARRAY['marina','harbor_stop'],
 ARRAY['transitseglare','familjer'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Arholma Naturhamn', 'Arholma', 59.9100, 19.1800,
 'Skyddad naturhamn pa norra Arholma med vacker vildmarkskaraktar. Perfekt ankring for de som soker ostordhet.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['arholma','naturhamn','ankring','vildmark'],
 'Oppen ytterskargard med vildmarkskaraktar och stjarnhimmel.',
 'anchorage', 'arholma-naturhamn', 'roslagen',
 ARRAY['anchorage','nature','remote'],
 ARRAY['erfarna_seglare','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Blidosund Naturhamn', 'Blido', 59.6250, 18.9000,
 'Naturskon ankringsplats i Blidosund med skyddade vikar och fin vegetation. Klassiskt Roslagens-landskap.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['blidosund','naturhamn','ankring','klassisk'],
 'Klassisk Roslagen-skargard med lummig natur och lugna vikar.',
 'anchorage', 'blidosund-naturhamn', 'roslagen',
 ARRAY['anchorage','nature','classic'],
 ARRAY['familjer','naturintresserade','par'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Idskaret Naturhamn', 'Idskar', 59.8500, 18.9500,
 'Liten och skyddad naturhamn vid Idskar. Bra simning och fiske fran klipporna.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['idskar','naturhamn','ankring','simning'],
 'Skyddad ankring med klipphall och bra simstalle.',
 'anchorage', 'idskaret-naturhamn', 'roslagen',
 ARRAY['anchorage','nature','simning'],
 ARRAY['familjer','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kallskaret Naturhamn', 'Kallskar', 59.9800, 19.0500,
 'Avlagsna naturhamn med typisk ytter-Roslagen-karaktar. Oppen utsikt och rik fagelliv.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['kallskar','naturhamn','ankring','faglar'],
 'Avlagsen ankring med vacker ytterskargardsmiljo och rik fagelliv.',
 'anchorage', 'kallskaret-naturhamn', 'roslagen',
 ARRAY['anchorage','nature','birdwatching'],
 ARRAY['naturintresserade','fagelskadare','aventyrare'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Norrtalje Hamkrog', 'Norrtalje', 59.7580, 18.7048,
 'Populart krogstopp i Norrtalje hamn. Serverar klassisk husmanskost och fisk med hamnutsikt. Livlig sommaratmosfar.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['norrtalje','restaurang','husmanskost','hamnutsikt'],
 'God mat och hamnutsikt i Roslagens centralhamn.',
 'restaurant', 'norrtalje-hamkrog', 'roslagen',
 ARRAY['restaurang','middag'],
 ARRAY['familjer','par','transitseglare'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Arholma Vardshus', 'Arholma', 59.9236, 19.1670,
 'Klassiskt vardshus pa Arholma med enkel och god mat. Perfekt malsattning efter langseglatsen ut till yttersta Roslagen.',
 'Juni-Augusti: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['arholma','vardshus','klassisk','ytterhamn'],
 'Enkel och god mat pa yttersta holmen efter lang seglats.',
 'restaurant', 'arholma-vardshus', 'roslagen',
 ARRAY['restaurang','klassisk'],
 ARRAY['erfarna_seglare','aventyrare'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grisslehamn Restaurang', 'Grisslehamn', 60.0941, 18.8234,
 'Restaurang i Grisslehamn med lokalmeny och havsutsikt. Fisk fran trakten och god husmanskost i historisk miljo.',
 'Juni-Augusti: 11:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['grisslehamn','restaurang','lokalmeny','historisk'],
 'Lokalmeny och historisk miljo i den gamla angbatsstaden.',
 'restaurant', 'grisslehamn-restaurang', 'roslagen',
 ARRAY['restaurang','lokalmad'],
 ARRAY['par','historieintresserade','familjer'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Oregrund Krogen', 'Oregrund', 60.3335, 18.4503,
 'Traditionsrik krog i Oregrund med hemlagad mat och sommarsmaak. Utsikt over den vackra hamnbyn.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['oregrund','restaurang','traditionsrik','hemlagad'],
 'Hemlagad mat i en av Roslagens vackraste smastaeder.',
 'restaurant', 'oregrund-krogen', 'roslagen',
 ARRAY['restaurang','traditionsrik'],
 ARRAY['familjer','par','historieintresserade'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Norrtalje Bunkring', 'Norrtalje', 59.7575, 18.7039,
 'Marinbunkring i Norrtalje gasthamn. Diesel och bensin tillgangligt for alla battyper.',
 'April-Oktober: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['norrtalje','bransle','diesel','bensin'],
 NULL,
 'fuel_station', 'norrtalje-bunkring', 'roslagen',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Oregrund Bunkring', 'Oregrund', 60.3330, 18.4497,
 'Branslestopp i Oregrund for seglare pa vag norrut eller soderut langs Roslagens kust.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['oregrund','bransle','diesel'],
 NULL,
 'fuel_station', 'oregrund-bunkring', 'roslagen',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grisslehamn Bunkring', 'Grisslehamn', 60.0937, 18.8228,
 'Branslestation i Grisslehamn. Viktigt stopp pa vagen till Finland eller Aland.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['grisslehamn','bransle','diesel','finland'],
 NULL,
 'fuel_station', 'grisslehamn-bunkring', 'roslagen',
 ARRAY['bransle'],
 ARRAY['alla_seglare','finlandsseglar'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Arholma Bunkring', 'Arholma', 59.9231, 19.1663,
 'Ytterhamn-bunkring pa Arholma. Sista chansen att tanka pa vagen ut mot Finland.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['arholma','bransle','diesel','ytterhamn'],
 NULL,
 'fuel_station', 'arholma-bunkring', 'roslagen',
 ARRAY['bransle'],
 ARRAY['alla_seglare','ytterhavsseglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
