-- ============================================================
-- SVALLA — Seed Places v2
-- ~110 nya platser + bränslestationer
-- Kör EFTER migration-places-v2.sql
-- ============================================================

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

-- ════════════════════════════════════════════════
-- INRE SKÄRGÅRD / NÄRA STOCKHOLM
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Vita Grindarna', 'Djurö', 59.1952, 18.6963,
 'Populär krog och gästhamn på Djurö nära Stavsnäs. Enkelt och bra med direkt bryggläge och sommarstämning.',
 'Juni–Augusti: dagligen 11–21.', 'Enkel mat, räkor, smörgåsar, öl och vin.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['lunch','hamn','sommar','enkel'],
 'En klassisk sommarstoppunkt för den som passerar Djurö – bryggläge, enkel mat och avslappnad stämning.',
 'restaurant', 'vita-grindarna-djuro', 'middle',
 ARRAY['restaurant','harbor_stop','lunch_stop'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Röda Villan', 'Nacka', 59.3035, 18.2285,
 'Mysig krog i rött trähus vid vattnet i Nacka. Lokal favorit med god mat och skärgårdskänsla utan att åka långt.',
 'Maj–September: tis–sön 12–21.', 'Säsongsmat, fisk, kött, vegetariskt.',
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['nacka','lokal','mysigt','nära stan'],
 'Röda Villan är lokalen som Nacka-borna håller för sig själva – charmigt läge, bra mat, inga turister.',
 'restaurant', 'roda-villan', 'inner',
 ARRAY['restaurant','lunch_stop','hidden_gem'],
 ARRAY['couples','friends','day_trip'],
 ARRAY['restaurant','bar'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Fjäderholmarnas Bryggeri Taproom', 'Fjäderholmarna', 59.3218, 18.1625,
 'Litet bryggeri på Fjäderholmarna med hantverk-öl direkt från tankarna. Perfekt för en kvällsöl med utsikt.',
 'Maj–September: dagligen 12–21.', 'Hantverksöl, enkla tilltugg.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['öl','bryggeri','fjäderholmarna','kväll'],
 'Hantverksöl med Stockholms siluett i bakgrunden – en enkel men svårslagen kvällsstund.',
 'bar', 'fjaderholmarna-bryggeri', 'inner',
 ARRAY['bar','hidden_gem','sunset_stop'],
 ARRAY['friends','boaters','couples'],
 ARRAY['bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'The Old Smokehouse', 'Fjäderholmarna', 59.3215, 18.1618,
 'Enklare rökerialternativ på Fjäderholmarna med rökt fisk och skaldjur direkt vid bryggan.',
 'April–Oktober: dagligen 11–20.', 'Rökt lax, räkor, sillinläggningar, mackor.',
 ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800'],
 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
 ARRAY['rökt fisk','skaldjur','enkel','fjäderholmarna'],
 'Ta en smörgås med rökt lax och ät den på bryggan – det är skärgårdsmat i sin enklaste och bästa form.',
 'restaurant', 'old-smokehouse', 'inner',
 ARRAY['restaurant','lunch_stop','harbor_stop'],
 ARRAY['family','day_trip','boaters'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Bockholmen Hav & Restaurang', 'Bockholmen', 59.3598, 18.1128,
 'Fridfullt läge på lilla Bockholmen nära Lidingö. Fin terrass, vällagad mat och nära nog för kvällsturen.',
 'Maj–September: ons–sön 12–21.', 'Skärgårdsmat, fisk, skaldjur, vegetariskt.',
 ARRAY['https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800'],
 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
 ARRAY['bockholmen','utsikt','terrass','nära stan'],
 'En liten ö, en fin terrass och havet – Bockholmen är innerstadens bäst dolda skärgårdsrestaurang.',
 'restaurant', 'bockholmen-restaurang', 'inner',
 ARRAY['restaurant','hidden_gem','sunset_stop'],
 ARRAY['couples','friends','day_trip'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Holmen Kök & Bar', 'Nacka Strand', 59.3158, 18.1572,
 'Modern krog vid vattnet i Nacka Strand. Nära stan men med skärgårdskänsla, öppen även på vintern.',
 'Året runt: mån–fre 11–22, lör–sön 12–22.', 'Á la carte, lunch, bar, säsongsrätter.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['nacka strand','helår','modern','bar'],
 'Holmen är Nacka Strands samlingsplats – moderna rätter, bra bar och vattenutsikt hela året.',
 'restaurant', 'holmen-kok-bar', 'inner',
 ARRAY['restaurant','bar','lunch_stop'],
 ARRAY['friends','couples','family'],
 ARRAY['restaurant','bar'],
 'year_round', 'high'),

(gen_random_uuid(), 'Artipelag', 'Gustavsberg', 59.3162, 18.3613,
 'Kulturhus och restaurang på Värmdö med fantastisk utsikt över Baggensfjärden. Unikt kombination av konst och mat.',
 'Tisdag–söndag 11–17 (restaurang). Utökade tider vid utställningar.',
 'Smårätter, sallader, lunch, fika, hembakat.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['konst','kultur','utsikt','värmdö','lunch'],
 'Artipelag kombinerar konst och vatten på ett sätt som är svårt att hitta någon annanstans – lunchen är ett bonus.',
 'restaurant', 'artipelag', 'inner',
 ARRAY['restaurant','cafe','lunch_stop','hidden_gem'],
 ARRAY['couples','family','day_trip'],
 ARRAY['restaurant','cafe','toilet'],
 'year_round', 'high'),

(gen_random_uuid(), 'Strömma Krog & Kanalbar', 'Duvnäs', 59.3392, 18.3104,
 'Kanalbar vid Strömma kanal – klassisk passage med sommarstämning. Bra kombinationsstopp för den som passerar.',
 'Juni–Augusti: dagligen 12–21.', 'Enkel mat, smörgåsar, räkor, öl och vin.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['kanal','strömma','passage','sommar'],
 'Stopp vid Strömma kanal med en öl och utsikt mot båttrafiken – ett enkelt nöje som aldrig tröttar.',
 'restaurant', 'stromma-kanalbar', 'inner',
 ARRAY['restaurant','bar','harbor_stop','lunch_stop'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['restaurant','bar','guest_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Bistro Lillströmma', 'Ljusterö', 59.5168, 18.4992,
 'Liten bistro vid Lillströmma färjeläge på Ljusterö. Bra stopp inför eller efter färjan till fastlandet.',
 'Juni–Augusti: dagligen 9–18.', 'Frukost, lunch, fika, smörgåsar.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['ljusterö','färja','frukost','fika'],
 'En enkel bistro med det perfekta läget – vid färjeläget på Ljusterö, precis rätt för morgonkaffe eller lunch.',
 'cafe', 'bistro-lillstromma', 'north',
 ARRAY['cafe','lunch_stop','easy_from_stockholm'],
 ARRAY['family','day_trip','boaters'],
 ARRAY['cafe','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Fredriksborg Hotell', 'Vaxholm', 59.4028, 18.3518,
 'Litet boutiquehotell i Vaxholm med restaurang och havsutsikt. Bra alternativ till Hamnkrogen för lite finare middag.',
 'Maj–September: dagligen 12–21.', 'Á la carte, skärgårdsmat, säsongsrätter, frukost.',
 ARRAY['https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800'],
 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
 ARRAY['vaxholm','hotell','finare','utsikt'],
 'Fredriksborg erbjuder lite mer ro än hamnen – en vällagad middag i lugna omgivningar med havsutsikt.',
 'restaurant', 'fredriksborg-hotell', 'inner',
 ARRAY['restaurant','lunch_stop'],
 ARRAY['couples','family'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Magasinet', 'Gustavsberg', 59.3248, 18.3688,
 'Populär restaurang i gamla magasinslokaler vid Gustavsbergs hamn. Bra mat och avslappnad industrikänsla.',
 'Tisdag–lördag 17–22, lördag–söndag lunch 12–15.', 'Á la carte, skärgårdsinfluerad mat, bar.',
 ARRAY['https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800'],
 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800',
 ARRAY['gustavsberg','hamn','industrikänsla','kväll'],
 'Gamla magasinslokaler, god mat och Gustavsbergs pittoreska hamn – ett genuint alternativ till turistkrogarna.',
 'restaurant', 'magasinet-gustavsberg', 'inner',
 ARRAY['restaurant','dinner_stop','hidden_gem'],
 ARRAY['couples','friends'],
 ARRAY['restaurant','bar'],
 'year_round', 'medium'),

-- ════════════════════════════════════════════════
-- VAXHOLM / RINDÖ / TENÖ / GETFOTEN
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Bryggan på Tenö', 'Tenö', 59.4135, 18.3947,
 'Liten krog på Tenö nära Vaxholm med direkt bryggläge. Enkel men trivsam – perfekt lunchstopp.',
 'Juni–Augusti: dagligen 11–19.', 'Enkel mat, räkor, smörgåsar, öl.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['tenö','brygga','lunch','enkel'],
 'En stilla brygga, enkla räkor och inga krav – Tenö är Vaxholmsområdets lugna alternativ.',
 'restaurant', 'bryggan-teno', 'inner',
 ARRAY['restaurant','harbor_stop','lunch_stop'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Mathantverkstan i Skärgården', 'Vaxholm', 59.4015, 18.3548,
 'Delikatessbutik och café i Vaxholm med lokalt producerade varor, rökt fisk och hembakat bröd.',
 'Maj–September: dagligen 10–18.', 'Delikatess, rökt fisk, hembakat, lokala produkter, fika.',
 ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800'],
 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
 ARRAY['delikatess','lokalt','rökt fisk','vaxholm','proviant'],
 'Fyll på med lokalt producerat från Mathantverkstan – rökt fisk, hembakat och skärgårdsnärproducerat.',
 'cafe', 'mathantverkstan-skargarden', 'inner',
 ARRAY['cafe','provisions','hidden_gem'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['provisions','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Winbergs Kök & Bar', 'Vaxholm', 59.4022, 18.3543,
 'Litet kök och bar i Vaxholm med husmanskost och avslappnad atmosfär. God mat utan krångel.',
 'April–Oktober: tis–sön 12–21.', 'Husmanskost, fisk, smårätter, bar.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['vaxholm','husmanskost','bar','avslappnat'],
 'Winbergs är Vaxholms vardagsalternativ – ingen show, bara bra mat och en avslappnad öl.',
 'restaurant', 'winbergs-kok-bar', 'inner',
 ARRAY['restaurant','bar','lunch_stop'],
 ARRAY['friends','family','boaters'],
 ARRAY['restaurant','bar'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Getfoten Sjökrog', 'Getfoten', 59.3843, 18.4937,
 'Avlägset sjökrog vid Getfoten på Värmdösidan. Lång tradition, fin utsikt och typisk skärgårdsstämning.',
 'Juni–Augusti: dagligen 12–21.', 'Skärgårdsmat, fisk, räkor, enkla rätter.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['getfoten','sjökrog','avlägset','utsikt'],
 'Getfoten är svårare att ta sig till men det är halva poängen – ett genuint sjökrog-stopp långt från turiststråket.',
 'restaurant', 'getfoten-sjokrog', 'middle',
 ARRAY['restaurant','harbor_stop','hidden_gem'],
 ARRAY['boaters','couples','day_trip'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Vaxholms Hembygdsgårds Café', 'Vaxholm', 59.4028, 18.3562,
 'Litet hembygdscafé i Vaxholm med hembakat och en lugnare atmosfär. Perfekt fika-stopp.',
 'Juni–Augusti: ons–sön 11–16.', 'Fika, hembakat, kaffe, enkla smörgåsar.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['vaxholm','hembygd','fika','hembakat'],
 'Lugnet mitt i Vaxholms turistsommar – hemkänsla, hembakat och inga köer.',
 'cafe', 'vaxholms-hembygdsgards-cafe', 'inner',
 ARRAY['cafe','coffee','family_stop'],
 ARRAY['family','day_trip'],
 ARRAY['cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Waxholms Campings servering', 'Vaxholm', 59.4041, 18.3488,
 'Enkel campingservering vid Vaxholms camping. Billigt och grundläggande – bra för familjer med begränsad budget.',
 'Juni–Augusti: dagligen 8–20.', 'Enkel mat, grill, glass, frukost.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['vaxholm','camping','familj','enkelt'],
 'Ingen gastronomisk upplevelse, men ärlig mat vid ett bra läge – perfekt för barnfamiljen som campar.',
 'restaurant', 'waxholms-camping-servering', 'inner',
 ARRAY['restaurant','family_stop'],
 ARRAY['family'],
 ARRAY['restaurant','toilet'],
 'summer_only', 'medium'),

-- ════════════════════════════════════════════════
-- DJURÖ / STAVSNÄS
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Motorverkstan Bistro & Bar', 'Stavsnäs', 59.2013, 18.7151,
 'Ovanlig kombination – bryggeri, bistro och bar i gamla verkstadslokaler vid Stavsnäs. Lokal kult.',
 'Maj–September: tors–sön 12–21.', 'Bistrorätter, smårätter, lokalt öl, cocktails.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['stavsnäs','bar','industrikänsla','öl'],
 'Bästa stället att börja eller sluta dagen i Stavsnäs – ovanligt, lokalt och bra mat till ölet.',
 'bar', 'motorverkstan-bistro-bar', 'middle',
 ARRAY['bar','restaurant','hidden_gem'],
 ARRAY['friends','boaters'],
 ARRAY['bar','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Munkens Bageri i Djurhamn', 'Djurhamn', 59.1824, 18.6603,
 'Litet hantverksbageri i pittoreska Djurhamn. Nygräddat bröd och bullar – populärt bland seglare.',
 'Juni–Augusti: dagligen 7–14.', 'Hantverksbröd, bullar, frukostbakelser, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['bageri','hantverksbröd','djurhamn','morgon'],
 'Vakna tidigt, ro in till Djurhamn och hämta varmt bröd – en morgon som är svår att slå.',
 'cafe', 'munkens-bageri-djurhamn', 'middle',
 ARRAY['cafe','bakery','coffee','hidden_gem'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['bakery','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Stavsnäs Hembageri Sommarhamn', 'Stavsnäs', 59.2015, 18.7145,
 'Hembageri vid Stavsnäs hamn med nybakat bröd och bakverk. Bra morgonstopp.',
 'Juni–Augusti: dagligen 8–15.', 'Hembakat bröd, bullar, kaffe, frukost.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['stavsnäs','bageri','morgon','hembakat'],
 'Starta dagen rätt – färskt bröd och kaffe vid bryggan i Stavsnäs innan avfärd.',
 'cafe', 'stavsnäs-hembageri', 'middle',
 ARRAY['cafe','bakery','coffee'],
 ARRAY['boaters','family'],
 ARRAY['bakery','cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Stavsnäs Båtvarv & Sjömack', 'Stavsnäs', 59.2005, 18.7162,
 'Komplett marin service i Stavsnäs med drivmedel, varv och grundläggande förnödenheter.',
 'Maj–September: dagligen 8–18.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','varv','stavsnäs','service'],
 'Full marin service i Stavsnäs – tanka, serva och handla innan avfärd ut i skärgården.',
 'fuel', 'stavsnäs-batvart-sjomack', 'middle',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline','toilet'],
 'summer_only', 'high'),

-- ════════════════════════════════════════════════
-- LJUSTERÖ
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Linanäsbryggan', 'Ljusterö', 59.5271, 18.5032,
 'Populär sommarbrygga på Ljusterö med restaurang och gästhamn. Bra utgångspunkt för norra skärgården.',
 'Juni–Augusti: dagligen 11–20.', 'Räkor, skaldjur, enkel mat, glass.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['ljusterö','brygga','gästhamn','norr'],
 'Linanäsbryggan är Ljusterös samlingsplats på sommaren – hamnliv, mat och bra stämning.',
 'restaurant', 'linanaesbryggan', 'north',
 ARRAY['restaurant','harbor_stop','guest_harbor'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ljusteröfärjans krog & grillkiosk', 'Ljusterö', 59.5043, 18.5273,
 'Enkel grillkiosk vid Ljusteröfärjans färjeläge. Billig och praktisk mat för den som väntar på båten.',
 'Juni–Augusti: dagligen 10–18.', 'Grill, korv, smörgåsar, glass, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['ljusterö','grillkiosk','enkel','färja'],
 'Ingen fancy upplevelse – bara en grillad korv och utsikt mot skärgården medan du väntar på färjan.',
 'restaurant', 'ljustero-farjans-krog', 'north',
 ARRAY['restaurant','family_stop'],
 ARRAY['family','day_trip'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Pizzeria Ljusterö', 'Ljusterö', 59.5128, 18.5192,
 'Liten pizzeria på Ljusterö – ett av få ställen med varm mat hela sommaren.',
 'Maj–September: dagligen 12–21.', 'Pizza, pasta, enkel mat.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['ljusterö','pizza','enkelt'],
 'Ibland är en bra pizza det bästa alternativet – Ljusterös pizzeria levererar det grundläggande på ett bra sätt.',
 'restaurant', 'pizzeria-ljustero', 'north',
 ARRAY['restaurant','family_stop'],
 ARRAY['family'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Åsättra sommarkiosk', 'Ljusterö', 59.5228, 18.5025,
 'Liten sommarkiosk i Åsättra på Ljusterö. Grundläggande förnödenheter, glass och enkel mat.',
 'Juni–Augusti: dagligen 9–17.', 'Glass, läsk, smörgåsar, enkla förnödenheter.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['ljusterö','kiosk','glass','sommar'],
 'En liten sommarkiosk som fyller en stor funktion – glass, kaffe och grundvaror när du är ute på Ljusterö.',
 'cafe', 'asattra-sommarkiosk', 'north',
 ARRAY['cafe','provisions','family_stop'],
 ARRAY['family','day_trip'],
 ARRAY['cafe','provisions'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Klintan', 'Ljusterö', 59.5172, 18.5498,
 'Klintan är Ljusterös centrala hamn och mötesplats med krog, butik och bränsle. Komplett stopp.',
 'Juni–Augusti: dagligen 8–21.', 'Skärgårdsmat, räkor, enkel mat, bar.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['klintan','ljusterö','hamn','komplett'],
 'Klintan är Ljusterös nav – hamn, mat, bränsle och stämning på ett och samma ställe.',
 'restaurant', 'klintan', 'north',
 ARRAY['restaurant','harbor_stop','guest_harbor','fuel'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['guest_dock','fuel','restaurant','provisions','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Klintan sjöstation', 'Ljusterö', 59.5175, 18.5502,
 'Marin bränslestation vid Klintans hamn på Ljusterö. Diesel och bensin direkt från bryggan.',
 'Juni–Augusti: dagligen 8–18.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','klintan','ljusterö','sjömack'],
 'Tanka i Klintan och fortsätt norrut – centralt och enkelt med bra service.',
 'fuel', 'klintan-sjöstation', 'north',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'high'),

-- ════════════════════════════════════════════════
-- GRINDA / INGMARSÖ / FINNHAMN
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Framfickan', 'Grinda', 59.4092, 18.5618,
 'Enklare alternativet på Grinda jämfört med Wärdshuset. Bra för snabb lunch eller fika utan att boka.',
 'Juni–Augusti: dagligen 10–18.', 'Fika, smörgåsar, enkel lunch, glass.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['grinda','fika','enkel','lunch','alternativ'],
 'Ingen bokning, ingen stress – Framfickan är rätt val på Grinda när Wärdshuset är fullbokat.',
 'cafe', 'framfickan-grinda', 'middle',
 ARRAY['cafe','lunch_stop','coffee','family_stop'],
 ARRAY['family','boaters','day_trip'],
 ARRAY['cafe','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grinda Lanthandel & Café', 'Grinda', 59.4091, 18.5616,
 'Liten lanthandel och café på Grinda med grundvaror och fika. Bra proviantpunkt.',
 'Juni–Augusti: dagligen 9–18.', 'Fika, smörgåsar, lanthandelsvaror, glass.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['grinda','lanthandel','proviant','fika'],
 'Hämta upp förnödenheter och en kaffekopp – Grinda Lanthandel sköter det grundläggande väl.',
 'cafe', 'grinda-lanthandel-cafe', 'middle',
 ARRAY['cafe','provisions','coffee','family_stop'],
 ARRAY['boaters','family'],
 ARRAY['cafe','provisions'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ingmarsö Krog', 'Ingmarsö', 59.4712, 18.7358,
 'Liten krog på avlägsna Ingmarsö. Autentisk stämning, enkel mat och få besökare.',
 'Juni–Augusti: begränsade dagar, kolla i förväg.', 'Husmanskost, fisk, räkor, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['ingmarsö','autentisk','avlägset','enkel'],
 'Ingmarsö är utan turister och Ingmarsö Krog speglar det – äkta, enkelt och värt resan.',
 'restaurant', 'ingmarso-krog', 'middle',
 ARRAY['restaurant','hidden_gem','harbor_stop'],
 ARRAY['boaters','couples'],
 ARRAY['restaurant','guest_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Bagarbordet', 'Finnhamn', 59.4922, 18.7848,
 'Litet bageri och café på Finnhamn. Nybakat bröd till seglare och campare på ön.',
 'Midsommar–Mitten av Augusti: dagligen 8–13.', 'Hantverksbröd, bullar, kaffe, frukost.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['finnhamn','bageri','morgon','hantverksbröd'],
 'Vakna upp på Finnhamn och hämta nygräddat bröd – en av skärgårdens bästa morgonar.',
 'cafe', 'bagarbordet-finnhamn', 'middle',
 ARRAY['cafe','bakery','coffee'],
 ARRAY['boaters','family'],
 ARRAY['bakery','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ragnars kiosk', 'Finnhamn', 59.4930, 18.7862,
 'Liten kiosk på Finnhamn med glass, läsk och grundförnödenheter.',
 'Midsommar–Mitten av Augusti: dagligen 10–18.', 'Glass, läsk, chips, enkla förnödenheter.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['finnhamn','kiosk','glass'],
 'En kiosk är en kiosk – men Ragnars är porten till Finnhamns sommarvärld.',
 'cafe', 'ragnars-kiosk-finnhamn', 'middle',
 ARRAY['cafe','provisions','family_stop'],
 ARRAY['family','boaters'],
 ARRAY['provisions'],
 'summer_only', 'medium'),

-- ════════════════════════════════════════════════
-- GÄLLNÖ / SVARTSÖ / RUNMARÖ / SIARÖFORTET
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Gällnö Bar', 'Gällnö', 59.4298, 18.6802,
 'Enkel bar och servering på lilla Gällnö. Sommarstopp med hamnstämning och avslappnad atmosfär.',
 'Juni–Augusti: dagligen 11–20.', 'Öl, vin, enkla tilltugg.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['gällnö','bar','sommar','enkel'],
 'En liten bar på en liten ö – Gällnö handlar om att sluta leta och bara vara.',
 'bar', 'gallno-bar', 'middle',
 ARRAY['bar','harbor_stop','hidden_gem'],
 ARRAY['boaters','couples','friends'],
 ARRAY['bar','guest_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Gällnö Handelsbod café', 'Gällnö', 59.4295, 18.6798,
 'Lantlig handelsbod och café på Gällnö. Grundvaror och fika i äkta skärgårdsmiljö.',
 'Juni–Augusti: dagligen 9–17.', 'Fika, kaffe, smörgåsar, lanthandelsvaror.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['gällnö','handelsbod','fika','lantlig'],
 'Gällnös handelsbod är som en tidsresa – lantlig, lugn och äkta som skärgården borde vara.',
 'cafe', 'gallno-handelsbod-cafe', 'middle',
 ARRAY['cafe','provisions','coffee','hidden_gem'],
 ARRAY['boaters','family'],
 ARRAY['cafe','provisions'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Svartsö Krog', 'Svartsö', 59.4645, 18.7265,
 'Genuint liten krog på bilfria Svartsö. Husmanskost och äkta ö-känsla utan turister.',
 'Juni–Augusti: dagligen 12–20.', 'Husmanskost, fisk, enkla rätter, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['svartsö','bilfri','autentisk','husmanskost'],
 'Svartsö Krog är skärgårdslivet på riktigt – bilfritt, lugnt och med mat som smakar hemlagat.',
 'restaurant', 'svartso-krog', 'middle',
 ARRAY['restaurant','hidden_gem','harbor_stop'],
 ARRAY['boaters','couples','day_trip'],
 ARRAY['restaurant','guest_dock'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Svängen Runmarö', 'Runmarö', 59.3452, 18.7502,
 'Krog och bar på Runmarö med sommarstämning och aktiva helger. En av södra skärgårdens levande träffpunkter.',
 'Juni–Augusti: dagligen 12–21.', 'Skärgårdsmat, bar, enkel mat, räkor.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['runmarö','bar','helger','social'],
 'Svängen på Runmarö har puls när resten av skärgården sover – social, levande och rolig sommarplats.',
 'restaurant', 'svangen-runmaro', 'middle',
 ARRAY['restaurant','bar','hidden_gem'],
 ARRAY['friends','boaters','couples'],
 ARRAY['restaurant','bar','guest_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Låttas bageri', 'Runmarö', 59.3448, 18.7498,
 'Litet hantverksbageri på Runmarö med nybakat bröd och bullar. Välkänt bland stamgäster.',
 'Juni–Augusti: dagligen 8–13.', 'Hantverksbröd, bullar, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['runmarö','bageri','hantverksbröd','morgon'],
 'Låttas nybakade bröd är ett bra skäl att stanna på Runmarö lite längre än planerat.',
 'cafe', 'lattas-bageri', 'middle',
 ARRAY['cafe','bakery','coffee','hidden_gem'],
 ARRAY['boaters','family'],
 ARRAY['bakery','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Siaröfortet krog', 'Siarö', 59.5102, 18.6098,
 'Historisk krog i det gamla kustfortets lokaler på Siarö. Unik miljö, god mat och historia i väggarna.',
 'Midsommar–Mitten av Augusti: dagligen 12–20.', 'Skärgårdsmat, fisk, skaldjur, bar.',
 ARRAY['https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800'],
 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800',
 ARRAY['siaröfortet','historia','unik','kustfort'],
 'Att äta middag i ett gammalt kustfort är en upplevelse i sig – Siaröfortet krog levererar mat och historia i ett.',
 'restaurant', 'siarofortet-krog', 'north',
 ARRAY['restaurant','hidden_gem','harbor_stop'],
 ARRAY['boaters','couples','friends'],
 ARRAY['restaurant','guest_dock','toilet'],
 'summer_only', 'high'),

-- ════════════════════════════════════════════════
-- SANDHAMN
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Bistro Sands', 'Sandhamn', 59.2882, 18.9115,
 'Avslappnad bistro i Sandhamns by. Enkelt och prisvärt alternativ till Värdshuset och Seglarhotellet.',
 'Juni–Augusti: dagligen 11–21.', 'Enklare rätter, smörgåsar, räkor, bar.',
 ARRAY['https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800'],
 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800',
 ARRAY['sandhamn','bistro','enkel','prisvärt'],
 'Bistro Sands är Sandhamns vardagsalternativ – bra mat utan Seglarhotellets prislapp.',
 'restaurant', 'bistro-sands', 'outer',
 ARRAY['restaurant','lunch_stop'],
 ARRAY['friends','boaters','family'],
 ARRAY['restaurant','bar'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Dykarbaren', 'Sandhamn', 59.2888, 18.9103,
 'Känd bar i Sandhamn med lång historia och levande stämning under högsommaren.',
 'Juni–Augusti: dagligen 14–01.', 'Bar, cocktails, öl, enkla tilltugg.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['sandhamn','bar','kväll','nattliv','historia'],
 'Dykarbaren är Sandhamns puls på kvällen – högt i tak, bra stämning och en del av seglarlivet.',
 'bar', 'dykarbaren', 'outer',
 ARRAY['bar','sunset_stop'],
 ARRAY['friends','boaters','couples'],
 ARRAY['bar'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Sandhamns Bageriet', 'Sandhamn', 59.2884, 18.9118,
 'Klassiskt bageri i Sandhamn med nybakt bröd och bakverk. Köerna är långa men värda det.',
 'Juni–Augusti: dagligen 7–15.', 'Hantverksbröd, bullar, croissanter, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['sandhamn','bageri','bröd','morgon','klassiker'],
 'Vakna tidigt, stå i kön och ta hem varmt bröd till båten – Sandhamns Bageriet är en sommarritt.',
 'cafe', 'sandhamns-bageriet', 'outer',
 ARRAY['cafe','bakery','coffee'],
 ARRAY['boaters','family','day_trip'],
 ARRAY['bakery','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Café Ankaret', 'Sandhamn', 59.2875, 18.9108,
 'Litet café i Sandhamns by med kaffe, glass och lugn stämning. Alternativ till de större ställena.',
 'Juni–Augusti: dagligen 10–17.', 'Kaffe, te, glass, enkel fika.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['sandhamn','café','fika','lugnt'],
 'Café Ankaret är rätt när du vill ha Sandhamn utan Sandhamns stress – en kopp kaffe och lugn.',
 'cafe', 'cafe-ankaret', 'outer',
 ARRAY['cafe','coffee','family_stop'],
 ARRAY['family','couples'],
 ARRAY['cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Café Strindbergsgården', 'Sandhamn', 59.2891, 18.9121,
 'Café i anslutning till Strindbergsgården på Sandhamn. Kulturellt och trivsamt kafé med historisk koppling.',
 'Juni–Augusti: dagligen 10–16.', 'Kaffe, te, hembakat, enkel lunch.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['sandhamn','strindberg','kultur','fika'],
 'Ta fika där August Strindberg en gång vistades – Sandhamns kulturella och mysiga caféstopp.',
 'cafe', 'cafe-strindbergsgarden', 'outer',
 ARRAY['cafe','coffee','hidden_gem'],
 ARRAY['couples','family','day_trip'],
 ARRAY['cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'PUB Alma', 'Sandhamn', 59.2883, 18.9112,
 'Pubkänsla i Sandhamn med sport, öl och avslappnad kväll. Bra alternativ till de mer formella ställena.',
 'Juni–Augusti: dagligen 15–23.', 'Öl, bar, enkla tilltugg.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['sandhamn','pub','kväll','avslappnat'],
 'PUB Alma är Sandhamns enkla kvällsalternativ – inga pretentioner, bara öl och bra sällskap.',
 'bar', 'pub-alma-sandhamn', 'outer',
 ARRAY['bar'],
 ARRAY['friends','boaters'],
 ARRAY['bar'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Sandhamns Glassigaste Ställe', 'Sandhamn', 59.2878, 18.9110,
 'Glasskiosk i Sandhamn med ett stort utbud och ständig kö. Klassiker för barnfamiljer.',
 'Juni–Augusti: dagligen 10–20.', 'Glass, sorbet, läsk.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['sandhamn','glass','familj','kiosk'],
 'Barnen hittar hit av instinkt – Sandhamns bästa glass och ett klassiskt sommarstopp.',
 'cafe', 'sandhamns-glassigaste-stalle', 'outer',
 ARRAY['cafe','family_stop'],
 ARRAY['family','day_trip'],
 ARRAY['cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Sandhamns sjöstation', 'Sandhamn', 59.2893, 18.9098,
 'Shell-sjömack i Sandhamn med diesel, bensin och grundläggande service.',
 'Juni–Augusti: dagligen 8–18.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','sandhamn','sjömack','service'],
 'Tanka i Sandhamn innan hemfärden – Shell-sjömacken är välplacerad vid gästhamnen.',
 'fuel', 'sandhamns-sjöstation', 'outer',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'high'),

-- ════════════════════════════════════════════════
-- MÖJA
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Möja Hamnbar', 'Möja', 59.4381, 18.8292,
 'Hamnbar vid Möjas huvudhamn. Enkel bar med sommarstämning och direkt utsikt över hamnlivet.',
 'Juni–Augusti: dagligen 12–22.', 'Öl, vin, cocktails, enkla tilltugg.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['möja','hamnbar','kväll','utsikt'],
 'En öl med utsikt över Möjas hamn på kvällen – enkelt, äkta och svårt att lämna.',
 'bar', 'moja-hamnbar', 'middle',
 ARRAY['bar','harbor_stop','sunset_stop'],
 ARRAY['boaters','friends','couples'],
 ARRAY['bar','guest_dock'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Les Poissonniers de Möja', 'Möja', 59.4372, 18.8285,
 'Franskinspirerad fiskrestaurang på bilfria Möja. Oväntat fin mat långt ute i skärgården.',
 'Juni–Augusti: dagligen 12–21.', 'Fisk, skaldjur, franskinspirerade rätter, gott vin.',
 ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800'],
 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
 ARRAY['möja','fisk','franskt','bilfri','unik'],
 'Franskinspirerad fisk på en bilfri skärgårdsö – Les Poissonniers är en av skärgårdens bäst dolda restauranger.',
 'restaurant', 'les-poissonniers-moja', 'middle',
 ARRAY['restaurant','hidden_gem','dinner_stop'],
 ARRAY['couples','boaters','friends'],
 ARRAY['restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Jeppes', 'Möja', 59.4365, 18.8278,
 'Liten enkel servering på Möja. Husmanskost och smörgåsar för den som inte hittade bord på Värdshuset.',
 'Juni–Augusti: dagligen 11–18.', 'Enkel mat, smörgåsar, räkor, glass.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['möja','enkelt','lunch','alternativ'],
 'Jeppes är Möjas no-nonsense-alternativ – enkel mat, inga bokningskrav och ärlig stämning.',
 'restaurant', 'jeppes-moja', 'middle',
 ARRAY['restaurant','lunch_stop','family_stop'],
 ARRAY['family','boaters'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Hamncafét Möja', 'Möja', 59.4382, 18.8295,
 'Enkelt hantverkskafé vid Möjas hamn. Kaffe, smörgåsar och en bit i solen vid bryggan.',
 'Juni–Augusti: dagligen 8–15.', 'Kaffe, te, smörgåsar, fika, hembakat.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['möja','café','frukost','hamn'],
 'Morgonkaffe vid Möjas hamn med hembakat bröd – det är den perfekta starten på en bilfri ö-dag.',
 'cafe', 'hamncafet-moja', 'middle',
 ARRAY['cafe','coffee','family_stop'],
 ARRAY['boaters','family'],
 ARRAY['cafe'],
 'summer_only', 'medium'),

-- ════════════════════════════════════════════════
-- UTÖ / ÅLÖ / RÅNÖ
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Seglarbaren Utö', 'Utö', 58.9550, 18.3148,
 'Avslappnad bar vid Utös gästhamn. Populär kvällssamlingsplats för seglare och båtfolk.',
 'Juni–Augusti: dagligen 14–23.', 'Öl, vin, cocktails, enkla tilltugg.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['utö','seglare','bar','kväll'],
 'Seglarbaren är Utös sociala hjärta på kvällen – köp en öl, hitta en kajplats och prata båt.',
 'bar', 'seglarbaren-uto', 'south',
 ARRAY['bar','harbor_stop','sunset_stop'],
 ARRAY['boaters','friends','couples'],
 ARRAY['bar','guest_dock'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Hamnboden Utö', 'Utö', 58.9545, 18.3142,
 'Liten bod vid hamnen på Utö med fisk, skaldjur och färskvaror. Perfekt för proviantering.',
 'Juni–Augusti: dagligen 9–18.', 'Färsk fisk, räkor, skaldjur, smörgåsar, glass.',
 ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800'],
 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
 ARRAY['utö','proviant','fisk','hamn'],
 'Friskaste fisken på Utö hittar du i Hamnboden – ta med räkor till bryggan och ät i solskenet.',
 'restaurant', 'hamnboden-uto', 'south',
 ARRAY['restaurant','provisions','harbor_stop'],
 ARRAY['boaters','family'],
 ARRAY['provisions','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Bakfickan Utö', 'Utö', 58.9538, 18.3155,
 'Informell matservering på Utö med enklare rätter. Bra när Värdshuset är fullbokat.',
 'Juni–Augusti: dagligen 11–19.', 'Enkel mat, smörgåsar, räkor, fika.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['utö','enkelt','alternativ','lunch'],
 'Bakfickan är Utös informella alternativ – enkel mat utan väntan eller bokning.',
 'restaurant', 'bakfickan-uto', 'south',
 ARRAY['restaurant','lunch_stop','family_stop'],
 ARRAY['family','boaters'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Bryggans lilla kök', 'Utö', 58.9548, 18.3138,
 'Liten kök direkt vid bryggan på Utö. Snabb och god mat för hungriga seglare.',
 'Juni–Augusti: dagligen 11–18.', 'Smörgåsar, räkor, grill, fisk.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['utö','brygga','snabb mat','lunch'],
 'Bryggans lilla kök levererar rätt mat på rätt plats – direkt vid kajen, snabbt och bra.',
 'restaurant', 'bryggans-lilla-kok-uto', 'south',
 ARRAY['restaurant','harbor_stop','lunch_stop'],
 ARRAY['boaters','family'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Lilla Haket & Ninas Bod', 'Utö', 58.9542, 18.3145,
 'Kombinerad kiosk och matservering på Utö. Klassisk skärgårdskiosk med lokalt känd stämning.',
 'Juni–Augusti: dagligen 10–18.', 'Glass, smörgåsar, korv, enkla förnödenheter.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['utö','kiosk','enkelt','familj'],
 'Lilla Haket är ett besök i skärgårdsnostalgin – glass och enkla saker gjorda med omtanke.',
 'cafe', 'lilla-haket-ninas-bod', 'south',
 ARRAY['cafe','provisions','family_stop'],
 ARRAY['family','boaters'],
 ARRAY['cafe','provisions'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Utö Bykrog', 'Utö', 58.9515, 18.3172,
 'Enkel bykrog inne på Utö, skild från hamnen. Mer lokalt och lugnt än hamnrestaurangerna.',
 'Juni–Augusti: ons–sön 12–20.', 'Husmanskost, fisk, vegetariskt, fika.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['utö','bykrog','lugnt','lokalt'],
 'Utö Bykrog är för den som vill uppleva Utö bortom hamnen – lugn, lokal och äkta.',
 'restaurant', 'uto-bykrog', 'south',
 ARRAY['restaurant','hidden_gem','lunch_stop'],
 ARRAY['couples','boaters'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Bakgården Utö', 'Utö', 58.9522, 18.3160,
 'Charmig bakgård med servering och trädgårdsmöbler på Utö. Mer hem-känsla än hamnkrog.',
 'Juni–Augusti: tors–sön 12–19.', 'Hembakat, smörgåsar, fika, enkel lunch.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['utö','bakgård','lugnt','hemkänsla','fika'],
 'Bakgården på Utö är skärgårdslivet utan prestation – trädgård, hembakat och total ro.',
 'cafe', 'bakgarden-uto', 'south',
 ARRAY['cafe','hidden_gem','coffee'],
 ARRAY['couples','family'],
 ARRAY['cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Rånö Brygga', 'Rånö', 58.9972, 18.2212,
 'Enkel brygga och servering på Rånö i södra skärgården. Avlägset och fridfullt.',
 'Juni–Augusti: begränsade tider, kolla i förväg.', 'Enkel mat, räkor, öl.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['rånö','avlägset','brygga','lugnt'],
 'Rånö Brygga är slutstationen i söder – avlägset, stilla och med den äktaste skärgårdskänslan.',
 'restaurant', 'rano-brygga', 'south',
 ARRAY['restaurant','harbor_stop','hidden_gem'],
 ARRAY['boaters','couples'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'medium'),

-- ════════════════════════════════════════════════
-- ORNÖ / MUSKÖ / NÅTTARÖ / GÅLÖ / TORÖ / ÅRSTA
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Kyrkviken Bar & Bistro', 'Ornö', 58.9892, 18.3518,
 'Bar och bistro vid Kyrkvikens hamn på Ornö. Populär träffpunkt med sommarstämning.',
 'Juni–Augusti: dagligen 12–21.', 'Bistrorätter, bar, räkor, skaldjur.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['ornö','kyrkviken','bar','bistro'],
 'Kyrkviken är Ornös pulserande nav på sommaren – bra mat, bra bar och ett av sydskärgårdens bästa lägen.',
 'restaurant', 'kyrkviken-bar-bistro', 'south',
 ARRAY['restaurant','bar','harbor_stop'],
 ARRAY['boaters','friends','couples'],
 ARRAY['restaurant','bar','guest_dock'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gittans-KBB Ornö', 'Ornö', 58.9912, 18.3538,
 'Enkel servering på Ornö med husmanskost. En av öns mest kända matplatser bland återkommande besökare.',
 'Juni–Augusti: dagligen 11–19.', 'Husmanskost, smörgåsar, räkor, glass.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['ornö','husmanskost','enkel','lokalt'],
 'Gittans serverar det enkla med stolthet – Ornö-klassikern som stamgästerna inte berättar om.',
 'restaurant', 'gittans-kbb-orno', 'south',
 ARRAY['restaurant','hidden_gem','lunch_stop'],
 ARRAY['boaters','family'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Ornö Brödbod o Deli', 'Ornö', 58.9903, 18.3525,
 'Liten delikatessbrödbod på Ornö med hantverksbröd och lokala produkter.',
 'Juni–Augusti: dagligen 9–14.', 'Hantverksbröd, delikatess, smör och ost.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['ornö','bröd','deli','hantverksbröd'],
 'Ornös bästa morgonproviantering – hantverksbröd och lokala delikatesser att ta med ut på vattnet.',
 'cafe', 'orno-brodbod-deli', 'south',
 ARRAY['cafe','bakery','provisions','hidden_gem'],
 ARRAY['boaters','family'],
 ARRAY['bakery','provisions'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Muskö Sjökrog', 'Muskö', 59.0248, 17.9882,
 'Krog vid Muskös inre hamn med lång tradition. Lokalt känd och bra för en lunch längs sydvästra sträckan.',
 'Juni–Augusti: dagligen 11–20.', 'Skärgårdsmat, fisk, räkor, enkel mat.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['muskö','sjökrog','lunch','lokalt'],
 'Muskö Sjökrog sitter perfekt för den som kör längs sydvästra skärgården – bra mat i ett glömt läge.',
 'restaurant', 'musko-sjokrog', 'south',
 ARRAY['restaurant','harbor_stop','lunch_stop','fuel'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','restaurant','fuel'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Gålö Havsbad restaurang', 'Gålö', 59.0112, 17.9818,
 'Restaurang vid Gålös havsbad med badstrand och sommarstämning. Bra för familjer med bil.',
 'Juni–Augusti: dagligen 11–20.', 'Enkel mat, grill, smörgåsar, glass.',
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['gålö','bad','familj','sommar'],
 'Gålö Havsbad kombinerar strand och mat på ett enkelt sätt – perfekt familjedag utan båt.',
 'restaurant', 'galo-havsbad-restaurang', 'south',
 ARRAY['restaurant','family_stop'],
 ARRAY['family','day_trip'],
 ARRAY['restaurant','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Restaurang Sjöboden Torö', 'Torö', 58.8152, 17.8452,
 'Enkel sjöbod-restaurang på Torö vid Ankarudden. Avlägset läge med äkta skärgårdskänsla.',
 'Juni–Augusti: dagligen 11–19.', 'Enkel mat, fisk, räkor, smörgåsar.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['torö','ankarudden','avlägset','sjöbod'],
 'Sjöboden på Torö är en naturlig ankarplats – avlägset, fridfullt och med enkel mat som fungerar.',
 'restaurant', 'sjoboden-toro-ankarudden', 'south',
 ARRAY['restaurant','harbor_stop','hidden_gem'],
 ARRAY['boaters','couples'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Restaurang Horsfjärden', 'Muskö', 58.8202, 17.8498,
 'Restaurang vid Horsfjärdens inre vatten. Skyddat läge och bra mat längs den sydliga sträckan.',
 'Juni–Augusti: tis–sön 12–21.', 'Skärgårdsmat, fisk, skaldjur, á la carte.',
 ARRAY['https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800'],
 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
 ARRAY['horsfjärden','muskö','skyddat','lunch'],
 'Horsfjärden är ett av sydskärgårdens skyddade hav – restaurangen erbjuder bra mat i lugnt vatten.',
 'restaurant', 'restaurang-horsfjarden', 'south',
 ARRAY['restaurant','harbor_stop','dinner_stop'],
 ARRAY['boaters','couples'],
 ARRAY['restaurant','guest_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Årsta Havsbads Grillen', 'Årsta Havsbad', 58.9842, 17.9512,
 'Grillkiosk vid Årsta Havsbad. Enkelt och praktiskt för badsällskap och dagturister.',
 'Juni–Augusti: dagligen 10–18.', 'Grill, korv, hamburgare, glass.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['årsta havsbad','grill','bad','familj'],
 'Smidigt badbuffert för Årstas badgäster – inga pretentioner, men god korv och bra läge.',
 'restaurant', 'arsta-havsbads-grillen', 'south',
 ARRAY['restaurant','family_stop'],
 ARRAY['family','day_trip'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

-- ════════════════════════════════════════════════
-- NÄMDÖ / IDÖBORG / RÖGRUND / LANDSORT
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Strandbaren på Idöborg', 'Idöborg', 59.0228, 18.6232,
 'Strandbar på Idöborg med utsikt och sommardrinkar. Svårtillgängligt men värt resan.',
 'Juni–Augusti: dagligen 12–22.', 'Bar, cocktails, öl, enkel mat.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['idöborg','strandbar','avlägset','utsikt'],
 'Idöborg är en av de platser du berättar om efteråt – strandbar med utsikt och känsla av äventyr.',
 'bar', 'strandbaren-idoborg', 'middle',
 ARRAY['bar','hidden_gem','sunset_stop'],
 ARRAY['boaters','couples','friends'],
 ARRAY['bar','guest_dock'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Rögrunds Sjökrog', 'Rögrund', 58.8552, 17.9702,
 'Sjökrog på lilla Rögrund i södra ytterskärgården. Extremt avlägset och unikt.',
 'Juli–Mitten av Augusti: begränsade dagar.', 'Enkel mat, räkor, skaldjur.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['rögrund','avlägset','ytter','unik'],
 'Rögrund är få förunt att hitta – den som tar sig dit minns det länge.',
 'restaurant', 'rogrunds-sjokrog', 'south',
 ARRAY['restaurant','hidden_gem','harbor_stop'],
 ARRAY['boaters'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Saltboden Kök & Proviant', 'Landsort', 58.7402, 17.8652,
 'Kök och proviantbutik vid Landsort – sydligaste punkten i Stockholms skärgård. Unik destination.',
 'Juni–Augusti: dagligen 10–18.', 'Mat, proviant, kaffe, enkel mat.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['landsort','ytterst','proviant','unik'],
 'Saltboden markerar slutet på skärgården – här tankar du upp och vänder tillbaka eller fortsätter ut.',
 'restaurant', 'saltboden-kok-proviant', 'south',
 ARRAY['restaurant','provisions','harbor_stop','hidden_gem'],
 ARRAY['boaters'],
 ARRAY['provisions','restaurant'],
 'summer_only', 'high'),

-- ════════════════════════════════════════════════
-- NORRA SKÄRGÅRDEN
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Furusund Värdshus', 'Furusund', 59.6672, 18.9175,
 'Klassiskt värdshus i Furusunds sund med lång historia och utsikt mot passagetrafiken. Norra skärgårdens ikon.',
 'Maj–September: dagligen 12–21.', 'Husmanskost, fisk, skaldjur, säsongsrätter.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['furusund','värdshus','klassiker','norr','historia'],
 'Furusund Värdshus blickar ut mot ett av norra skärgårdens mest trafikerade sund – historia och mat i perfekt kombination.',
 'restaurant', 'furusund-vardshus', 'north',
 ARRAY['restaurant','harbor_stop','dinner_stop'],
 ARRAY['boaters','couples','family'],
 ARRAY['guest_dock','restaurant','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fejans Sjökrog', 'Fejan', 59.6648, 18.9622,
 'Sjökrog på ögruppen Fejan längst norrut. Avlägset men med utsikt och sommarstämning.',
 'Juni–Augusti: dagligen 12–20.', 'Skärgårdsmat, fisk, räkor, öl.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['fejan','norr','avlägset','sjökrog'],
 'Fejan är skärgårdsresans slutdestination i norr – sjökrogen är en välförtjänt belöning.',
 'restaurant', 'fejans-sjokrog', 'north',
 ARRAY['restaurant','harbor_stop','hidden_gem'],
 ARRAY['boaters','couples'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fejan Outdoor våffelcafé', 'Fejan', 59.6645, 18.9618,
 'Litet utomhuscafé på Fejan med våfflor och enkel fika. Perfekt stopp i nordskärgårdens yttersta hörn.',
 'Juni–Augusti: dagligen 10–16.', 'Våfflor, fika, kaffe, glass.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['fejan','café','våfflor','norr'],
 'Hemgjorda våfflor långt ute i norra skärgården – en liten glädje som är stor när du kommit dit.',
 'cafe', 'fejan-outdoor-vaffelcafe', 'north',
 ARRAY['cafe','coffee','family_stop','hidden_gem'],
 ARRAY['family','boaters'],
 ARRAY['cafe'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Restaurang Varvet på Högmarsö', 'Högmarsö', 59.5972, 18.6802,
 'Restaurang i gamla varvslokaler på Högmarsö. Industriell charm och vällagad mat i norra skärgården.',
 'Juni–Augusti: dagligen 12–21.', 'Skärgårdsmat, fisk, kött, vegetariskt.',
 ARRAY['https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800'],
 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800',
 ARRAY['högmarsö','varvet','industrikänsla','norr'],
 'Varvet på Högmarsö blandar industrikänsla och skärgårdsmat på ett sätt som är svårt att hitta annorstans.',
 'restaurant', 'varvet-hogmarso', 'north',
 ARRAY['restaurant','hidden_gem','dinner_stop'],
 ARRAY['couples','boaters','friends'],
 ARRAY['restaurant','guest_dock'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Blidö Brygga & Bistro', 'Blidö', 59.6172, 18.8498,
 'Bistro och brygga på Blidö med enkel mat och hamnstämning. Bra stopp i norra innerskärgården.',
 'Juni–Augusti: dagligen 11–20.', 'Bistrorätter, smörgåsar, räkor, enkel mat.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['blidö','brygga','bistro','norr'],
 'Blidö Brygga är ett pålitligt stopp i norr – bra mat, bra läge och inga överraskningar.',
 'restaurant', 'blido-brygga-bistro', 'north',
 ARRAY['restaurant','harbor_stop','lunch_stop'],
 ARRAY['boaters','family'],
 ARRAY['guest_dock','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Arholma Dansbana & krog', 'Arholma', 59.8482, 19.1302,
 'Legendarisk dansbana och krog på Arholma – nordligaste skärgårdens sociala mittpunkt.',
 'Midsommar–Mitten av Augusti: mån–sön kväll.', 'Bar, dans, enkel mat, öl.',
 ARRAY['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800'],
 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800',
 ARRAY['arholma','dansbana','kväll','legendar','norr'],
 'Arholma Dansbana är en institution – dans under bar himmel längst norrut. Gammaldags och fantastiskt.',
 'bar', 'arholma-dansbana-krog', 'north',
 ARRAY['bar','hidden_gem','sunset_stop'],
 ARRAY['friends','boaters','couples'],
 ARRAY['bar','guest_dock'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Lidö Värdshus', 'Lidö', 59.6272, 18.7692,
 'Charmigt värdshus på naturreservatsön Lidö. Fredad natur, bra mat och äkta skärgårdsidyll.',
 'Juni–Mitten av Augusti: dagligen 12–20.', 'Husmanskost, fisk, hembakat, kaffe.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['lidö','naturreservat','värdshus','norr','fredad'],
 'Lidö är naturreservatets hjärta i norr – värdshuset serverar mat med samma enkelhet och kvalitet som ön förtjänar.',
 'restaurant', 'lido-vardshus', 'north',
 ARRAY['restaurant','harbor_stop','hidden_gem'],
 ARRAY['boaters','couples','family'],
 ARRAY['restaurant','guest_dock'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ökrogen på Tjockö', 'Tjockö', 59.3752, 18.3948,
 'Liten krog på Tjockö nära Vaxholm. Lugnt läge, enkel mat och ett bra stopp för den som kör norrifrån.',
 'Juni–Augusti: dagligen 11–19.', 'Enkel mat, räkor, smörgåsar, öl.',
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['tjockö','vaxholm','enkel','lugnt'],
 'Tjockö är det lugna alternativet när Vaxholm är för folkfyllt – Ökrogen sköter maten enkelt och bra.',
 'restaurant', 'okrogen-tjocko', 'inner',
 ARRAY['restaurant','harbor_stop','lunch_stop'],
 ARRAY['boaters','family'],
 ARRAY['restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Café Truten på Rödlöga', 'Rödlöga', 59.7192, 18.9332,
 'Litet café på avlägsna Rödlöga i norra ytterskärgården. En av skärgårdens äktaste fynd.',
 'Juni–Mitten av Augusti: dagligen 9–15.', 'Kaffe, hembakat, fika, enkel frukost.',
 ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 ARRAY['rödlöga','café','avlägset','äkta','ytter'],
 'Café Truten på Rödlöga är belöningen för den som vågar ta sig längst norrut – äkta, enkelt och minnesvärt.',
 'cafe', 'cafe-truten-rodloga', 'north',
 ARRAY['cafe','hidden_gem','coffee'],
 ARRAY['boaters','couples'],
 ARRAY['cafe'],
 'summer_only', 'high'),

-- ════════════════════════════════════════════════
-- BRÄNSLE / SERVICE / SJÖMACKAR
-- ════════════════════════════════════════════════

(gen_random_uuid(), 'Bullandö Marina', 'Bullandö', 59.2862, 18.5852,
 'Komplett marina på Bullandö med bränsle, varv, handel och matservering. Bäst utrustat i mellersta skärgården.',
 'Maj–September: dagligen 8–18.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bullandö','marina','bränsle','komplett','service'],
 'Bullandö Marina är skärgårdens mest kompletta servicehamn – tanka, handla och serva allt på ett ställe.',
 'fuel', 'bullanda-marina', 'middle',
 ARRAY['fuel','guest_harbor','service_point','provisions'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline','guest_dock','provisions','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Utö Gästhamn sjömack', 'Utö', 58.9558, 18.3142,
 'Marin bränslestation vid Utös gästhamn med diesel och bensin.',
 'Juni–Augusti: dagligen 8–18.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','utö','sjömack'],
 'Tanka i Utö och välj riktning – söderut mot Landsort eller tillbaka mot Stockholm.',
 'fuel', 'uto-gasthamn-sjomack', 'south',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grinda Sjömack', 'Grinda', 59.4100, 18.5622,
 'Enkel marin bränslepunkt vid Grindas gästhamn.',
 'Juni–Augusti: dagligen 8–17.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','grinda','sjömack'],
 'Tanka vid Grinda innan eller efter middagen på Wärdshuset – smidig kombination.',
 'fuel', 'grinda-sjomack', 'middle',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Högmarsö sjömack', 'Högmarsö', 59.5975, 18.6815,
 'Marin bränslestation på Högmarsö. Viktig tankpunkt för den som kör norrut.',
 'Juni–Augusti: dagligen 8–17.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','högmarsö','norr','sjömack'],
 'Tanka på Högmarsö – sista ordentliga macken innan du styr norrut mot Arholma och Rödlöga.',
 'fuel', 'hogmarso-sjomack', 'north',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Arholma sjömack', 'Arholma', 59.8485, 19.1312,
 'Nordligast belägna sjömacken i Stockholms skärgård. Sista bränslepunkten mot Åland och Finland.',
 'Juni–Mitten av Augusti: dagligen 8–17.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','arholma','ytterst','norr'],
 'Arholma sjömack är sista tankmöjligheten i norr – tanka fullt om du planerar Ålands-overgången.',
 'fuel', 'arholma-sjomack', 'north',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Nämdö Macken', 'Nämdö', 59.1332, 18.6722,
 'Liten marin bränslepunkt vid Nämdös hamn. Viktig för den som kör i mellersta södra skärgården.',
 'Juni–Augusti: dagligen 8–16.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','nämdö','service'],
 'Tanka vid Nämdö Macken – ett av få bränslealternativ i den annars glesa södra mellanskärgården.',
 'fuel', 'namdo-macken', 'middle',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Circle K Klintsundet', 'Klintsundet', 59.5182, 18.5522,
 'Circle K sjömack i Klintsundet på Ljusterö. Välkänd tankpunkt för norrut-trafiken.',
 'Maj–September: dagligen 7–19.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','klintsundet','circle k','norr'],
 'Circle K Klintsundet är en av norra skärgårdens pålitligaste tankpunkter – tanka och fortsätt.',
 'fuel', 'circle-k-klintsundet', 'north',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Sjömack Muskö', 'Muskö', 59.0240, 17.9892,
 'Marin bränslestation vid Muskö. Bra läge för båtar i sydvästra skärgården.',
 'Juni–Augusti: dagligen 8–17.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['bränsle','muskö','sydväst','sjömack'],
 'Muskö-macken sitter rätt för den som kör mot Landsort eller in mot Nynäshamn.',
 'fuel', 'sjomack-musko', 'south',
 ARRAY['fuel','service_point'],
 ARRAY['boaters'],
 ARRAY['fuel','diesel','gasoline'],
 'summer_only', 'medium')

ON CONFLICT (name) DO NOTHING;
