-- seed-stockholm-norra.sql
-- Norra Stockholms skargard seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'stockholm_norra';
DELETE FROM restaurants WHERE name IN (
  'Vaxholm Gasthamn', 'Grinda Gasthamn', 'Sandhamn Gasthamn',
  'Finnhamn Gasthamn', 'Moja Gasthamn', 'Furusund Gasthamn', 'Ljustero Gasthamn',
  'Svartso Naturhamn', 'Angso Naturhamn', 'Boo Naturhamn', 'Husaro Naturhamn',
  'Sandhamn Seglarsallskapet', 'Vaxholm Hamn Bar', 'Finnhamn Vardshus', 'Grinda Wardshus',
  'Vaxholm Bunkring', 'Sandhamn Bunkring', 'Furusund Bunkring', 'Moja Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Vaxholm Gasthamn', 'Vaxholm', 59.4019, 18.3528,
 'Gasthamn i Vaxholm, porten till Stockholms skargard. Historisk fästningsstad med levande sommartorget, bra service och nara till innerskargarden.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['vaxholm','gasthamn','porten','fastning'],
 'Porten till Stockholms skargard med historisk fastning och levande stadsliv.',
 'marina', 'vaxholm-gasthamn', 'stockholm_norra',
 ARRAY['marina','harbor_stop','kulturstad'],
 ARRAY['alla_seglare','familjer','stockholmare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Grinda Gasthamn', 'Grinda', 59.3833, 18.6667,
 'Gasthamn pa Grinda i mellerskargarden. Bilfri naturreservats-o med vandringsleder, badplatser och Vardshuset som serverar klassisk skargardskost.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['grinda','gasthamn','bilfri','naturreservat'],
 'Bilfri mellerskargardsö med vandring, bad och klassisk skargardskost.',
 'marina', 'grinda-gasthamn', 'stockholm_norra',
 ARRAY['marina','harbor_stop','bilfri'],
 ARRAY['familjer','naturintresserade','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Sandhamn Gasthamn', 'Sandhamn', 59.2833, 18.9167,
 'Gasthamn pa Sandhamn, det klassiska seglarparadiset i Stockholms ytterskargard. SSKF har sin bas har. Levande sommarliv, fina restauranger och dramatisk Ostersjoutsikt.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['sandhamn','gasthamn','seglarmecka','sskf'],
 'Stockholms klassiska seglarmecka med SSKF-bas och levande sommarhavsambians.',
 'marina', 'sandhamn-gasthamn', 'stockholm_norra',
 ARRAY['marina','harbor_stop','seglarmecka'],
 ARRAY['erfarna_seglare','par','festlystet'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','bar','wifi','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Finnhamn Gasthamn', 'Finnhamn', 59.4667, 18.7333,
 'Gasthamn pa Finnhamn i norra mellerskargarden. Naturreservat med vandringsleder och vardshus. Populart familjestopp med fin natur.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['finnhamn','gasthamn','naturreservat','familj'],
 'Naturreservat med vardshus och vandringsleder i mellerskargarden.',
 'marina', 'finnhamn-gasthamn', 'stockholm_norra',
 ARRAY['marina','harbor_stop','naturreservat'],
 ARRAY['familjer','naturintresserade','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Moja Gasthamn', 'Moja', 59.4167, 18.7833,
 'Gasthamn pa Moja i Stockholms norra mellerskargard. Stor bebodd o med skolor och butiker. Autentisk skargardskaraktar.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['moja','gasthamn','bebodd','autentisk'],
 'Stor bebodd skargardsö med autentiskt skargardssamhalle.',
 'marina', 'moja-gasthamn', 'stockholm_norra',
 ARRAY['marina','harbor_stop','autentisk'],
 ARRAY['naturintresserade','familjer','lugnsokande'],
 ARRAY['guest_dock','electricity','water','shower','toilet','cafe','supermarket'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Furusund Gasthamn', 'Furusund', 59.6667, 18.9167,
 'Gasthamn i Furusund i norra Stockholms skargard. Klassisk sommarort pa gransen mot Roslagen med levande hamnmiljo.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['furusund','gasthamn','klassisk','sommarmiljo'],
 'Klassisk norrskargards-sommarort vid gransen mot Roslagen.',
 'marina', 'furusund-gasthamn', 'stockholm_norra',
 ARRAY['marina','harbor_stop','klassisk'],
 ARRAY['familjer','par','stockholmare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Ljustero Gasthamn', 'Ljustero', 59.5000, 18.6833,
 'Gasthamn pa Ljustero i norra mellerskargarden. Stor bro-forebunden o med bra service och tillgang till fin natur och cykling.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['ljustero','gasthamn','broforebunden','cykling'],
 'Stor skargardsö med bra service och fin natur att cykla i.',
 'marina', 'ljustero-gasthamn', 'stockholm_norra',
 ARRAY['marina','harbor_stop','cykling'],
 ARRAY['familjer','cykelturister','naturintresserade'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Svartso Naturhamn', 'Svartso', 59.3667, 18.7167,
 'Naturankring pa Svartso i mellerskargarden. Lugn bilfri o med vandringsleder och ostord natur.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['svartso','naturhamn','bilfri','ankring'],
 'Bilfri mellerskargardsö med ostord natur och vandringsleder.',
 'anchorage', 'svartso-naturhamn', 'stockholm_norra',
 ARRAY['anchorage','nature','bilfri'],
 ARRAY['lugnsokande','naturintresserade','par'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Angso Naturhamn', 'Angso', 59.5500, 18.7000,
 'Naturankring vid Angso nationalpark, den biologiska mangfaldens klenod. Blomsterrika lunder och unikt natur-arv.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['angso','naturhamn','nationalpark','blomsterlund'],
 'Nationalpark med blomsterrika lunder och unik biologisk mangfald.',
 'anchorage', 'angso-naturhamn', 'stockholm_norra',
 ARRAY['anchorage','nature','nationalpark'],
 ARRAY['naturintresserade','botaniker','familjer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Boo Naturhamn', 'Boo', 59.3333, 18.5333,
 'Naturankring pa Boo i innerskargarden. Skyddad vik med typisk stockholmsk skargardskaraktar.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['boo','naturhamn','ankring','innerskargard'],
 'Skyddad naturankring i stockholmsk innerskargard.',
 'anchorage', 'boo-naturhamn', 'stockholm_norra',
 ARRAY['anchorage','nature'],
 ARRAY['familjer','stockholmare'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Husaro Naturhamn', 'Husaro', 59.5833, 18.8167,
 'Naturankring pa Husaro med skyddade vikar och vacker norrskargardsnatur.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['husaro','naturhamn','ankring','norrskargard'],
 'Vacker norrskargardsnatur med skyddade ankringsvikar.',
 'anchorage', 'husaro-naturhamn', 'stockholm_norra',
 ARRAY['anchorage','nature'],
 ARRAY['naturintresserade','lugnsokande'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Sandhamn Seglarsallskapet', 'Sandhamn', 59.2835, 18.9170,
 'SSKF:s restaurang pa Sandhamn. Seglarkrogen framfor alla andra med klassisk mat och oovertraffad seglararatmosfar.',
 'Juni-Augusti: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['sandhamn','sskf','seglarkrog','klassisk'],
 'Seglarkrogen framfor alla andra med SSKF-atmosfar och god mat.',
 'restaurant', 'sandhamn-seglarsallskapet', 'stockholm_norra',
 ARRAY['restaurang','seglartradition'],
 ARRAY['seglare','erfarna_seglare','par'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Vaxholm Hamn Bar', 'Vaxholm', 59.4021, 18.3531,
 'Bar och restaurang i Vaxholms gasthamn med utsikt mot fastningen. Populart sommarstopp for bade stockholmare och turister.',
 'April-Oktober: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['vaxholm','hamnbar','fastningsutsikt','populart'],
 'Populart sommarstopp med fastningsutsikt i porten till skargarden.',
 'restaurant', 'vaxholm-hamn-bar', 'stockholm_norra',
 ARRAY['restaurang','bar'],
 ARRAY['par','stockholmare','turister'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Finnhamn Vardshus', 'Finnhamn', 59.4669, 18.7336,
 'Traditionsrikt vardshus pa Finnhamn med klassisk skargardskost. Mat lagad av lokalt inspirerade rad i naturreservatsmiljo.',
 'Maj-September: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['finnhamn','vardshus','skargardskost','naturreservat'],
 'Klassisk skargardskost i naturreservatsmiljo pa Finnhamn.',
 'restaurant', 'finnhamn-vardshus', 'stockholm_norra',
 ARRAY['restaurang','traditionsrik'],
 ARRAY['familjer','par','naturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grinda Wardshus', 'Grinda', 59.3835, 18.6670,
 'Klassiskt vardshus pa Grinda med god mat och utsikt over skargarden. Traditionsrik miljo pa bilfri naturreservats-o.',
 'Maj-September: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['grinda','wardshus','klassisk','bilfri'],
 'Klassiskt skargardsvardshus pa bilfri naturreservatsö.',
 'restaurant', 'grinda-wardshus', 'stockholm_norra',
 ARRAY['restaurang','traditionsrik'],
 ARRAY['familjer','par','seglare'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Vaxholm Bunkring', 'Vaxholm', 59.4015, 18.3522,
 'Marinbunkring i Vaxholm. Aret-runt-service vid porten till Stockholms skargard.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['vaxholm','bransle','helaret'],
 NULL,
 'fuel_station', 'vaxholm-bunkring', 'stockholm_norra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Sandhamn Bunkring', 'Sandhamn', 59.2830, 18.9163,
 'Branslestation pa Sandhamn. Viktigt tankstopp i ytterskargarden for seglare pa vag till och fran Ostersjon.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['sandhamn','bransle','ytterskargard'],
 NULL,
 'fuel_station', 'sandhamn-bunkring', 'stockholm_norra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Furusund Bunkring', 'Furusund', 59.6663, 18.9161,
 'Branslestation i Furusund for seglare i norra Stockholms skargard och pa vag mot Roslagen.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['furusund','bransle','norrskargard'],
 NULL,
 'fuel_station', 'furusund-bunkring', 'stockholm_norra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Moja Bunkring', 'Moja', 59.4163, 18.7826,
 'Branslestopp pa Moja for seglare i mellerskargarden.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['moja','bransle'],
 NULL,
 'fuel_station', 'moja-bunkring', 'stockholm_norra',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
