-- seed-oland.sql
-- Oland och Kalmarsund seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'oland';
DELETE FROM restaurants WHERE name IN (
  'Borgholm Gasthamn', 'Byxelkrok Gasthamn', 'Fajrestaden Gasthamn',
  'Morbylanga Gasthamn', 'Kalmar Gasthamn', 'Kapelludden Gasthamn', 'Grankullavik Gasthamn',
  'Byxelkrok Naturhamn', 'Skarpa Alby Naturhamn', 'Ottenby Naturhamn', 'Stensholmen Naturhamn',
  'Borgholm Hamkrog', 'Kapelludden Restaurang', 'Kalmar Hamn Bar', 'Olands Skafferi',
  'Borgholm Bunkring', 'Kalmar Bunkring', 'Byxelkrok Bunkring', 'Morbylanga Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Borgholm Gasthamn', 'Oland', 56.8778, 16.6536,
 'Centralt belagen gasthamn i Borgholm, Olands huvudstad. Slottsruinen tronar over hamnen. Bra service med restauranger, cafeeer och affarer inom gangavstand.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['borgholm','gasthamn','oland','slott'],
 'Olands centralhamn med slottsruinen och sommarens livliga stadsmiljo.',
 'marina', 'borgholm-gasthamn', 'oland',
 ARRAY['marina','harbor_stop','stad'],
 ARRAY['familjer','turister','historieintresserade'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Byxelkrok Gasthamn', 'Oland', 57.3167, 17.0000,
 'Norra Olands gasthamn i Byxelkrok. Lugnt lage med bra service och narheten till Trollskogen naturreservat. Populart mal for sommarseglar.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['byxelkrok','gasthamn','norra_oland','trollskogen'],
 'Norra Olands porten med narheten till det mystiska Trollskogen.',
 'marina', 'byxelkrok-gasthamn', 'oland',
 ARRAY['marina','harbor_stop','natur'],
 ARRAY['naturintresserade','familjer','seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Fajrestaden Gasthamn', 'Oland', 56.6333, 16.4667,
 'Gasthamn i Fajrestaden vid brofastet till fastlandet. Nara Olands bro och praktisk for de som korsade med bat.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['fajrestaden','gasthamn','olandsbron','praktisk'],
 'Strategisk hamn vid Olands bro med bra service och lage.',
 'marina', 'fajrestaden-gasthamn', 'oland',
 ARRAY['marina','harbor_stop','strategisk'],
 ARRAY['transitseglare','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Morbylanga Gasthamn', 'Oland', 56.5333, 16.3833,
 'Gasthamn i Morbylanga pa vastra Oland. Typisk kalmarsunds-karaktar med flat olandsk natur och alvarlandskap i narheten.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['morbylanga','gasthamn','alvar','oland'],
 'Hamn pa det UNESCO-listade Olands alvar med unik landsbygdsnatur.',
 'marina', 'morbylanga-gasthamn', 'oland',
 ARRAY['marina','harbor_stop','unesco'],
 ARRAY['naturintresserade','kulturintresserade','par'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kalmar Gasthamn', 'Kalmar', 56.6636, 16.3569,
 'Gasthamn i Kalmar vid Kalmarsund. Medeltidsstaden Kalmar med Kalmar Slott erbjuder rik historia. Bra service och levande stadsliv.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['kalmar','gasthamn','slott','medeltid'],
 'Medeltidsstad med Kalmar Slott och levande hamn vid Kalmarsund.',
 'marina', 'kalmar-gasthamn', 'oland',
 ARRAY['marina','harbor_stop','historisk'],
 ARRAY['familjer','historieintresserade','par'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','wifi','museum'],
 'year_round', 'high'),

(gen_random_uuid(), 'Kapelludden Gasthamn', 'Oland', 57.0000, 17.0833,
 'Gasthamn pa Kapelludden pa norra Olands ostkust. Oppen utsikt mot Ostersjons horisont och bra lage for ostergotlandsseglatsen.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['kapelludden','gasthamn','ostkusten','oppen_utsikt'],
 'Havshamn med oppen Ostersjoutsikt pa Olands ostlig kust.',
 'marina', 'kapelludden-gasthamn', 'oland',
 ARRAY['marina','harbor_stop','ostkust'],
 ARRAY['erfarna_seglare','naturintresserade'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Grankullavik Gasthamn', 'Oland', 57.3500, 16.9833,
 'Nordligaste gasthamnen pa Oland vid Grankullavik. Naturskont lage med narheten till Neptuni Akrar naturreservat.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['grankullavik','gasthamn','nordoland','neptuni_akrar'],
 'Nordligaste Oland med unik natur och Neptuni Akrar naturreservat.',
 'marina', 'grankullavik-gasthamn', 'oland',
 ARRAY['marina','harbor_stop','natur'],
 ARRAY['naturintresserade','lugnsokande'],
 ARRAY['guest_dock','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Byxelkrok Naturhamn', 'Oland', 57.3050, 17.0100,
 'Naturhamn runt Byxelkrok med skyddad ankring. Nara Trollskogen och bra for naturupplevelser.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['byxelkrok','naturhamn','ankring','trollskogen'],
 'Naturhamn nara det magiska Trollskogen pa norra Oland.',
 'anchorage', 'byxelkrok-naturhamn', 'oland',
 ARRAY['anchorage','nature','skog'],
 ARRAY['naturintresserade','familjer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Skarpa Alby Naturhamn', 'Oland', 56.7500, 16.7000,
 'Naturhamn vid Skarpa Alby pa vastra Oland. Typisk Kalmarsund-miljo med flatt landskap och oppen utsikt.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['skarpa_alby','naturhamn','ankring','kalmarsund'],
 'Klassisk Kalmarsunds-ankring med oppen horisont mot fastlandet.',
 'anchorage', 'skarpa-alby-naturhamn', 'oland',
 ARRAY['anchorage','nature','kalmarsund'],
 ARRAY['familjer','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Ottenby Naturhamn', 'Oland', 56.1833, 16.4000,
 'Naturhamn vid Olands sydspets Ottenby. Europas basta fagelstation nara, med massor av fagelskadningsmojligheter.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['ottenby','naturhamn','faglar','sydspets'],
 'Sydspetsen av Oland med Europas basta fagelskadning och rik natur.',
 'anchorage', 'ottenby-naturhamn', 'oland',
 ARRAY['anchorage','nature','birdwatching'],
 ARRAY['fagelskadare','naturintresserade','aventyrare'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Stensholmen Naturhamn', 'Oland', 57.1000, 17.0500,
 'Liten naturhamn pa ostkusten av Oland. Oppen miljoe mot Ostersjons vidder med bra fiskevatten runt om.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['stensholmen','naturhamn','ankring','fiske'],
 'Liten ankringshamn pa ostkusten med bra fiskemojligheter.',
 'anchorage', 'stensholmen-naturhamn', 'oland',
 ARRAY['anchorage','nature','fiske'],
 ARRAY['fiskare','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Borgholm Hamkrog', 'Oland', 56.8780, 16.6540,
 'Klassisk hamkrog i Borgholm med sommarmeny och utsikt mot Kalmarsund. Fisk, skaldjur och olandska smaker.',
 'Maj-September: 11:00-22:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['borgholm','hamkrog','oland','sommarmeny'],
 'Sommarkrog med olandsk mat och utsikt mot Kalmarsund.',
 'restaurant', 'borgholm-hamkrog', 'oland',
 ARRAY['restaurang','olandsmad','middag'],
 ARRAY['turister','familjer','par'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kapelludden Restaurang', 'Oland', 57.0002, 17.0836,
 'Restaurang vid Kapelludden med Ostersjoutsikt. Fiskmat och enkel god sommarmat i vackert lage.',
 'Juni-Augusti: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['kapelludden','restaurang','ostersjoutsikt','fisk'],
 'God mat med oppen Ostersjoutsikt.',
 'restaurant', 'kapelludden-restaurang', 'oland',
 ARRAY['restaurang','fisk'],
 ARRAY['seglare','naturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Kalmar Hamn Bar', 'Kalmar', 56.6638, 16.3572,
 'Hamn-bar och restaurang i Kalmar med utsikt over Kalmarsund. Levande sommarambians och bra mat nara Kalmar Slott.',
 'April-Oktober: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['kalmar','hamnbar','slott','kalmarsund'],
 'Stadsmiljo vid Kalmarsund med utsikt mot Oland och Kalmar Slott.',
 'restaurant', 'kalmar-hamn-bar', 'oland',
 ARRAY['restaurang','bar','historisk'],
 ARRAY['turister','par','stadsbor'],
 ARRAY['restaurang','bar','uteservering'],
 'year_round', 'high'),

(gen_random_uuid(), 'Olands Skafferi', 'Oland', 56.8500, 16.6000,
 'Restaurang och gard pa Oland med lokala ravaror — lamm, kryddar, grodor, lokalt frukost. Olandsk gastronomisk upplevelse.',
 'Maj-September: 10:00-20:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['oland','gard','lokal','gastronomisk'],
 'Autentisk olandsk gastronomi med lokala ravaror fran on.',
 'restaurant', 'olands-skafferi', 'oland',
 ARRAY['restaurang','lokal','gastronomisk'],
 ARRAY['mat_intresserade','par','kulturintresserade'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Borgholm Bunkring', 'Oland', 56.8775, 16.6532,
 'Marinbunkring i Borgholm. Diesel och bensin for seglare vid Olands centralhamn.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['borgholm','bransle','diesel'],
 NULL,
 'fuel_station', 'borgholm-bunkring', 'oland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Kalmar Bunkring', 'Kalmar', 56.6633, 16.3565,
 'Branslestation i Kalmar gasthamn. Tillganglig aret runt for seglare pa Kalmarsund.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['kalmar','bransle','helaret'],
 NULL,
 'fuel_station', 'kalmar-bunkring', 'oland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Byxelkrok Bunkring', 'Oland', 57.3164, 16.9997,
 'Branslestopp i Byxelkrok for seglare pa norra Oland. Viktigt pa vagen mot Gotland eller Ostergotland.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['byxelkrok','bransle','gotland_led'],
 NULL,
 'fuel_station', 'byxelkrok-bunkring', 'oland',
 ARRAY['bransle'],
 ARRAY['alla_seglare','gotlandsseglar'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Morbylanga Bunkring', 'Oland', 56.5330, 16.3830,
 'Branslestopp i Morbylanga pa sodra Oland.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['morbylanga','bransle','sodra_oland'],
 NULL,
 'fuel_station', 'morbylanga-bunkring', 'oland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
