-- seed-gotland.sql
-- Gotland seed data for Svalla sailing app
-- 19 places: 7 gasthamnar, 4 naturhamnar, 4 restauranger, 4 bensinstationer

DELETE FROM restaurants WHERE archipelago_region = 'gotland';
DELETE FROM restaurants WHERE name IN (
  'Visby Gasthamn', 'Slite Gasthamn', 'Klintehamn Gasthamn',
  'Burgsvik Gasthamn', 'Faaroesund Gasthamn', 'Katthammarsvik Gasthamn', 'Ljugarn Gasthamn',
  'Lickershamn Naturhamn', 'Gotska Sando Naturhamn', 'Faro Naturhamn', 'Holmhallarna Naturhamn',
  'Visby Hamn Bar', 'Klintehamn Fiskekrog', 'Burgsvik Vardshus', 'Slite Restaurang',
  'Visby Bunkring', 'Klintehamn Bunkring', 'Slite Bunkring', 'Burgsvik Bunkring'
);

INSERT INTO restaurants (
  id, name, island, latitude, longitude,
  description, opening_hours, menu, images, image_url,
  tags, core_experience,
  type, slug, archipelago_region, categories, best_for,
  facilities, seasonality, source_confidence
) VALUES

(gen_random_uuid(), 'Visby Gasthamn', 'Gotland', 57.6348, 18.2948,
 'Stor gasthamn i Visby, Gotlands huvudstad och UNESCO-varldsarv. Medeltida ringmur, beromda rosor och levande sommarliv gor Visby till ett av Ostersjons mest ikoniska resmal.',
 'April-Oktober: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 ARRAY['visby','gasthamn','unesco','medeltid'],
 'UNESCO-stad med medeltida ringmur, rosor och Ostersjons folkligaste sommarfest.',
 'marina', 'visby-gasthamn', 'gotland',
 ARRAY['marina','harbor_stop','unesco','kulturstad'],
 ARRAY['alla_seglare','kulturintresserade','turister','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','supermarket','wifi'],
 'year_round', 'high'),

(gen_random_uuid(), 'Slite Gasthamn', 'Gotland', 57.7083, 18.7972,
 'Gasthamn i Slite pa Gotlands ostkust. Industrihamn med aktiv cementfabrik men bra service for seglare som utforskar ostkustens natur.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800'],
 'https://images.unsplash.com/photo-1548199569-3e1c6aa8f469?w=800',
 ARRAY['slite','gasthamn','ostkust','service'],
 'Praktisk hamn pa Gotlands ostkust med bra service.',
 'marina', 'slite-gasthamn', 'gotland',
 ARRAY['marina','harbor_stop','service'],
 ARRAY['transitseglare','familjer'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Klintehamn Gasthamn', 'Gotland', 57.3833, 18.2000,
 'Gasthamn i Klintehamn pa sydvaestra Gotland. Naturlig utgangspunkt for att utforska Gotlands vackraste kuststrackor och Karsons naturreservat.',
 'Maj-September: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 ARRAY['klintehamn','gasthamn','sydvast','naturreservat'],
 'Utgangspunkt for sydvastra Gotlands klippkust och naturreservat.',
 'marina', 'klintehamn-gasthamn', 'gotland',
 ARRAY['marina','harbor_stop','naturreservat'],
 ARRAY['naturintresserade','familjer','seglare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','restaurant','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Burgsvik Gasthamn', 'Gotland', 57.0333, 18.2667,
 'Gasthamn i Burgsvik pa sodra Gotland. Populart sommarmaal med bra bad, fiskemojligheter och nara till Hoburgen, Gotlands sydligaste punkt.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800'],
 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800',
 ARRAY['burgsvik','gasthamn','sydgotland','hoburgen'],
 'Sydgotlands hamn nara Hoburgen med bra bad och fiske.',
 'marina', 'burgsvik-gasthamn', 'gotland',
 ARRAY['marina','harbor_stop','sydgotland'],
 ARRAY['familjer','naturintresserade','fiskare'],
 ARRAY['guest_dock','electricity','water','shower','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Faaroesund Gasthamn', 'Faaroe', 57.9167, 19.0833,
 'Gasthamn i Faaroesund pa norra Gotland. Faerjan till Faaroe-on gar harifran. Dramatisk natur med raukar och steniga strender.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800'],
 'https://images.unsplash.com/photo-1465188162913-8fb5709d6d57?w=800',
 ARRAY['faaroe','gasthamn','raukar','nordgotland'],
 'Porten till Faaroe-on med dramatiska raukar och vild natur.',
 'marina', 'faaroesund-gasthamn', 'gotland',
 ARRAY['marina','harbor_stop','raukar'],
 ARRAY['naturintresserade','fotografer','aventyrare'],
 ARRAY['guest_dock','electricity','water','toilet','cafe'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Katthammarsvik Gasthamn', 'Gotland', 57.4500, 18.8167,
 'Charmig liten gasthamn i Katthammarsvik pa ostkusten. Lugnt och avskilt lage med fin natur och klar Ostersjö.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800'],
 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc8?w=800',
 ARRAY['katthammarsvik','gasthamn','lugnt','ostkust'],
 'Lugn och avskild ostkust med klart vatten och fin natur.',
 'marina', 'katthammarsvik-gasthamn', 'gotland',
 ARRAY['marina','harbor_stop','lugn'],
 ARRAY['lugnsokande','par','naturintresserade'],
 ARRAY['guest_dock','electricity','water','toilet'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Ljugarn Gasthamn', 'Gotland', 57.3333, 18.7167,
 'Gasthamn i Ljugarn pa sydostra Gotland. Omgiven av rauk-omradet vid Folhammar och vita sandstrander. Populart badparadis.',
 'Juni-Augusti: dygnet runt.', NULL,
 ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
 ARRAY['ljugarn','gasthamn','raukar','sandstrand'],
 'Badparadis med raukar och sandstrander pa sydostra Gotland.',
 'marina', 'ljugarn-gasthamn', 'gotland',
 ARRAY['marina','harbor_stop','bad','raukar'],
 ARRAY['badglada','familjer','par'],
 ARRAY['guest_dock','electricity','water','toilet','badstrand'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Lickershamn Naturhamn', 'Gotland', 57.7833, 18.1333,
 'Naturankring vid Lickershamn med raukar langs kusten. Dramatiskt kalkstenslandskap och skyddad vik.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800'],
 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
 ARRAY['lickershamn','naturhamn','raukar','kalksten'],
 'Naturankring med dramatiska raukar och kalkstenslandskap.',
 'anchorage', 'lickershamn-naturhamn', 'gotland',
 ARRAY['anchorage','nature','raukar'],
 ARRAY['naturintresserade','fotografer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Gotska Sando Naturhamn', 'Gotska Sando', 58.4000, 19.2000,
 'Naturankring vid Gotska Sando nationalpark. Obefolkad sandö med sallsynta vaxter, faglar och dramatisk ytterskargardsmiljo.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800'],
 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
 ARRAY['gotska_sando','naturhamn','nationalpark','obefolkad'],
 'Nationalpark pa avlagan sandö med unik flora och fauna.',
 'anchorage', 'gotska-sando-naturhamn', 'gotland',
 ARRAY['anchorage','nature','nationalpark','remote'],
 ARRAY['aventyrare','naturintresserade','fagelskadare'],
 ARRAY['ankring'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Faro Naturhamn', 'Faaroe', 57.9500, 19.1500,
 'Naturankring pa Faaroe, on som Ingmar Bergman kallade sitt hem. Dramatisk klippkust, raukar och vild natur.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800'],
 'https://images.unsplash.com/photo-1439853949212-36589f9f7756?w=800',
 ARRAY['faaroe','naturhamn','bergman','raukar'],
 'Bergmans hemö med dramatisk raukmiljo och vild gotlandsnatur.',
 'anchorage', 'faro-naturhamn', 'gotland',
 ARRAY['anchorage','nature','kulturarv'],
 ARRAY['kulturintresserade','naturintresserade','fotografer'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Holmhallarna Naturhamn', 'Gotland', 57.2000, 18.1500,
 'Naturankring vid Holmhallarna pa sydvastra Gotland. Vacker kalkstenskust med kristallklart vatten och god bad.',
 'Alltid tillganglig.', NULL,
 ARRAY['https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800'],
 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800',
 ARRAY['holmhallarna','naturhamn','kalksten','bad'],
 'Kalkstenskust med kristallklart vatten och bra bad.',
 'anchorage', 'holmhallarna-naturhamn', 'gotland',
 ARRAY['anchorage','nature','bad'],
 ARRAY['badglada','familjer','naturintresserade'],
 ARRAY['ankring'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Visby Hamn Bar', 'Gotland', 57.6350, 18.2951,
 'Bar och restaurang i Visbys gasthamn med utsikt mot ringmuren. Levande sommaratmosfar och Gotlandslammets basta tillhall.',
 'Maj-September: 11:00-23:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
 ARRAY['visby','hamnbar','ringmuren','gotlandslamm'],
 'Sommarbar med utsikt mot medeltida ringmuren och Ostersjon.',
 'restaurant', 'visby-hamn-bar', 'gotland',
 ARRAY['restaurang','bar','utsikt'],
 ARRAY['turister','par','kulturintresserade'],
 ARRAY['restaurang','bar','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Klintehamn Fiskekrog', 'Gotland', 57.3835, 18.2003,
 'Fiskekrog i Klintehamn med lokalt gotlandsfisk och skaldjur. Enkel och god mat i avslappnad miljo.',
 'Juni-Augusti: 11:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
 ARRAY['klintehamn','fiskekrog','gotlandsfisk','avslappnad'],
 'Lokal gotlandsfisk och skaldjur i avslappnad hamnmiljo.',
 'restaurant', 'klintehamn-fiskekrog', 'gotland',
 ARRAY['restaurang','fisk','lokalmad'],
 ARRAY['mat_intresserade','seglare','familjer'],
 ARRAY['restaurang','uteservering'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Burgsvik Vardshus', 'Gotland', 57.0335, 18.2670,
 'Traditionsrikt vardshus i Burgsvik med gotlandsk mat och sommaratmosfar. Gotlandslamm, saffranspannkaka och lokala smaker.',
 'Juni-Augusti: 12:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'],
 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
 ARRAY['burgsvik','vardshus','gotlandslamm','saffranspannkaka'],
 'Gotlandsk traditionsmat med lamm och saffranspannkaka.',
 'restaurant', 'burgsvik-vardshus', 'gotland',
 ARRAY['restaurang','traditionsrik','gotlandsmad'],
 ARRAY['mat_intresserade','par','kulturintresserade'],
 ARRAY['restaurang'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Slite Restaurang', 'Gotland', 57.7085, 18.7975,
 'Restaurang i Slite med gotlandsk mat och hamnutsikt. Bra stopp for seglare pa vag runt Gotlands ostkust.',
 'Juni-Augusti: 11:00-21:00 dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
 ARRAY['slite','restaurang','ostkust','gotlandsmad'],
 'Gotlandsk mat med hamnutsikt pa ostkusten.',
 'restaurant', 'slite-restaurang', 'gotland',
 ARRAY['restaurang'],
 ARRAY['seglare','transitseglare'],
 ARRAY['restaurang'],
 'summer_only', 'medium'),

(gen_random_uuid(), 'Visby Bunkring', 'Gotland', 57.6345, 18.2944,
 'Marinbunkring i Visby. Aret-runt-service for seglare i Ostersjon.',
 'Helaret: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['visby','bransle','helaret'],
 NULL,
 'fuel_station', 'visby-bunkring', 'gotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel','bensin'],
 'year_round', 'high'),

(gen_random_uuid(), 'Klintehamn Bunkring', 'Gotland', 57.3830, 18.1996,
 'Branslestation i Klintehamn for seglare pa sydvastra Gotland.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['klintehamn','bransle'],
 NULL,
 'fuel_station', 'klintehamn-bunkring', 'gotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Slite Bunkring', 'Gotland', 57.7080, 18.7968,
 'Branslestation i Slite for seglare pa Gotlands ostkust.',
 'Maj-September: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['slite','bransle','ostkust'],
 NULL,
 'fuel_station', 'slite-bunkring', 'gotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'high'),

(gen_random_uuid(), 'Burgsvik Bunkring', 'Gotland', 57.0329, 18.2661,
 'Branslestopp i Burgsvik for seglare i sydgotland.',
 'Juni-Augusti: dagligen.', NULL,
 ARRAY['https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800'],
 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800',
 ARRAY['burgsvik','bransle','sydgotland'],
 NULL,
 'fuel_station', 'burgsvik-bunkring', 'gotland',
 ARRAY['bransle'],
 ARRAY['alla_seglare'],
 ARRAY['bransle','diesel'],
 'summer_only', 'medium');
