/**
 * hike-data.ts — Svalla vandringsdatabas
 * Täcker 12 kust- och skärgårdsregioner med topp 10 vandringar per region.
 * Alla avstånd och tider är uppskattade — kontrollera alltid lokala källors aktuella info.
 */

export type HikeRegion =
  | 'stockholms-skargard'
  | 'bohuslan'
  | 'goteborg-skargard'
  | 'gotland'
  | 'hoga-kusten'
  | 'blekinge'
  | 'oland'
  | 'skane'
  | 'sormland'
  | 'ostgota'
  | 'smalandskusten'
  | 'halland'

export type HikeDifficulty = 'lätt' | 'medel' | 'krävande'

export type Hike = {
  slug: string
  name: string
  region: HikeRegion
  distanceKm: number         // 0 = variabel/okänd
  durationMin: number        // timmar, lägre gräns
  durationMax: number        // timmar, övre gräns
  difficulty: HikeDifficulty
  transport: string          // hur man tar sig dit utan bil
  carRequired: boolean
  ferryRequired: boolean
  hasBathing: boolean
  hasRestaurant: boolean
  hasCafe: boolean
  suitableForChildren: boolean
  suitableForDogs: boolean
  bestSeason: string
  tagline: string            // max 1 mening
  islandSlug?: string        // koppling till /o/[slug] om den finns
  featured?: boolean         // visas i "Börja här"-sektionen
  topSweden?: number         // 1-10 om den är med i Topp 10 Sverige-listan
}

export const HIKES: Hike[] = [
  // ─── STOCKHOLMS SKÄRGÅRD ──────────────────────────────────────────────────
  {
    slug: 'uto',
    name: 'Utö',
    region: 'stockholms-skargard',
    distanceKm: 8,
    durationMin: 3,
    durationMax: 4.5,
    difficulty: 'medel',
    transport: 'Pendeltåg linje 43 → Nynäshamn → pendelbåt Utö',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Skärgårdens längsta och mest varierade led — gruvor, kvarn, naturreservat och havsklippor på samma ö.',
    islandSlug: 'uto',
    featured: true,
    topSweden: 2,
  },
  {
    slug: 'finnhamn',
    name: 'Finnhamn',
    region: 'stockholms-skargard',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Waxholmsbolaget linje 3 från Strömkajen',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Den perfekta nybörjarön — STF-vandrarhem, klippbad och välmarkerade stigar utan bilar.',
    islandSlug: 'finnhamn',
    featured: true,
    topSweden: 6,
  },
  {
    slug: 'grinda',
    name: 'Grinda',
    region: 'stockholms-skargard',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Waxholmsbolaget från Strömkajen (~1h40)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Sandstrand, STF-gästgård och en av skärgårdens kortaste och vackraste leder.',
    islandSlug: 'grinda',
    featured: true,
  },
  {
    slug: 'sandhamn',
    name: 'Sandhamn',
    region: 'stockholms-skargard',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Waxholmsbolaget linje 5 från Strömkajen (~2h30)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Runda Sandhamn på ~5 km och avsluta med middag på Värdshuset — en dag som sitter kvar.',
    islandSlug: 'sandhamn',
  },
  {
    slug: 'nattaro',
    name: 'Nåttarö',
    region: 'stockholms-skargard',
    distanceKm: 8,
    durationMin: 3,
    durationMax: 4,
    difficulty: 'medel',
    transport: 'Pendelbåt från Nynäshamn (kontrollera aktuell tidtabell)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Orörd naturreservatsstämning — gammal barrskog, klippor och nästan inga andra besökare.',
    islandSlug: 'nattaro',
    featured: true,
  },
  {
    slug: 'moja',
    name: 'Möja',
    region: 'stockholms-skargard',
    distanceKm: 7,
    durationMin: 2.5,
    durationMax: 3.5,
    difficulty: 'medel',
    transport: 'Waxholmsbolaget från Strömkajen (~2h30)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'En av få öar med folk som faktiskt bor här — fiskebryggor, bakgårdar och vandringsstigar med havsutsikt.',
    islandSlug: 'moja',
  },
  {
    slug: 'arholma',
    name: 'Arholma',
    region: 'stockholms-skargard',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Waxholmsbolaget eller buss + färja via Norrtälje (~3–4h från Stockholm)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Norra skärgårdens yttersta pärla — fyr, öppet hav och en ö som kräver en hel dag.',
    islandSlug: 'arholma',
  },
  {
    slug: 'ingmarso',
    name: 'Ingmarsö',
    region: 'stockholms-skargard',
    distanceKm: 6,
    durationMin: 2.5,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Waxholmsbolaget från Strömkajen (~2h)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Mellersta skärgårdens lugna naturreservat — utan turistbroschyrer men med riktigt vacker natur.',
    islandSlug: 'ingmarso',
  },
  {
    slug: 'gallno',
    name: 'Gällnö',
    region: 'stockholms-skargard',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Waxholmsbolaget från Strömkajen (~2h)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Naturreservat med skiftande landskap — barrskog inåt ön, havsklippor mot yttersidan.',
    islandSlug: 'gallno',
  },
  {
    slug: 'landsort',
    name: 'Landsort / Öja',
    region: 'stockholms-skargard',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Pendelbåt från Nynäshamn (kontrollera aktuell tidtabell)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Östersjöns sydligaste punkt i Stockholms skärgård — historisk fyr och öppet hav i alla riktningar.',
    islandSlug: 'landsort',
  },

  // ─── BOHUSLÄN ────────────────────────────────────────────────────────────
  {
    slug: 'nordkoster',
    name: 'Nordkoster',
    region: 'bohuslan',
    distanceKm: 8,
    durationMin: 3,
    durationMax: 5,
    difficulty: 'medel',
    transport: 'Tåg Göteborg → Strömstad, sedan båt till Koster (~3–4h totalt)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Sveriges första marina nationalpark — dramatiska klippor och Västerhavet i alla riktningar.',
    topSweden: 4,
  },
  {
    slug: 'sydkoster',
    name: 'Sydkoster',
    region: 'bohuslan',
    distanceKm: 6,
    durationMin: 2,
    durationMax: 3.5,
    difficulty: 'lätt',
    transport: 'Tåg Göteborg → Strömstad, sedan båt till Koster',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bilfri ö i Kosterhavet nationalpark med välmarkerade leder och kvällsdoppsplatser.',
  },
  {
    slug: 'fjallbacka',
    name: 'Fjällbacka / Grötö',
    region: 'bohuslan',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Buss 875 från Göteborg (~2h30), eller bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bohusläns klippor och det dramatiska havsljuset — kulturhistoria, bad och utsikt.',
  },
  {
    slug: 'marstrand',
    name: 'Marstrand',
    region: 'bohuslan',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Buss 302/312 från Göteborg C → Koön, sedan Marstrandsfärjan (ingår i biljetten)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Runda Carlstens fästningsö — historisk, bilfri och med Bohusläns bästa mat.',
  },
  {
    slug: 'vrango-bohuslan',
    name: 'Vrångö (Göteborg)',
    region: 'bohuslan',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Spårvagn linje 11 → Saltholmen, sedan båt linje 281/282',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bilfri naturreservats-ö i södra Göteborgs skärgård — råa klippor och Västerhavet.',
  },
  {
    slug: 'kladedsholmen',
    name: 'Klädesholmen (Tjörn)',
    region: 'bohuslan',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Buss 870/871 från Göteborg → Tjörn (~1h30), sedan lokalbuss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: '"Sillön" — välbevarat fiskebysamhälle med kustpromenad och frisk bohuslänsatmosfär.',
  },
  {
    slug: 'mollösund',
    name: 'Mollösund (Orust)',
    region: 'bohuslan',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Bil rekommenderas, eller lokal buss från Stenungsund',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Välbevarad gammal fiskehamn längs Bohusläns inre kustled med charm i varje detalj.',
  },
  {
    slug: 'hamburgsund',
    name: 'Hamburgsund',
    region: 'bohuslan',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Buss 875 från Göteborg (~3h), eller bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Havsklippor och Norges kust på horisonten — norrut längs Bohuslän med vinden i ryggen.',
  },
  {
    slug: 'grebbestad',
    name: 'Grebbestad',
    region: 'bohuslan',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Buss 878 från Göteborg (~3h), eller bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Ostronlandets kustleder — klippor, havsvy och mat som motiverar varje steg.',
  },
  {
    slug: 'smogen',
    name: 'Smögen',
    region: 'bohuslan',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Buss 870/871 från Göteborg (~2h), eller bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Bohusläns mest kända brygga omgiven av klippor med utsikt som rättfärdigar trängsel.',
  },

  // ─── GÖTEBORGS SKÄRGÅRD ──────────────────────────────────────────────────
  {
    slug: 'vrango-goteborg',
    name: 'Vrångö',
    region: 'goteborg-skargard',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Spårvagn linje 11 → Saltholmen, båt linje 281/282',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bilfri naturreservats-ö längst söderut i Göteborgs skärgård — råast och vackrast.',
  },
  {
    slug: 'styrso',
    name: 'Styrsö',
    region: 'goteborg-skargard',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Spårvagn linje 11 → Saltholmen, båt linje 282',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bilfri ö med välkänt värdshus och badklippor som gör sig bäst i kvällsljuset.',
  },
  {
    slug: 'donso',
    name: 'Donsö',
    region: 'goteborg-skargard',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Spårvagn linje 11 → Saltholmen, båt linje 281',
    carRequired: false,
    ferryRequired: true,
    hasBathing: false,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bohusläns fiskehamn par excellence — rökeri, bystigmar och äkta skärgårdsatmosfär.',
  },
  {
    slug: 'asperö',
    name: 'Asperö',
    region: 'goteborg-skargard',
    distanceKm: 2,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Spårvagn linje 11 → Saltholmen, båt linje 282',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Den lugna grannen i södra skärgården — bilfri, enkel och med egna välvalda badklippor.',
  },
  {
    slug: 'brando',
    name: 'Brändö',
    region: 'goteborg-skargard',
    distanceKm: 2,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Spårvagn linje 11 → Saltholmen, båt linje 282',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bilfri strandpromenad med enkel natur och Göteborgsvy.',
  },
  {
    slug: 'hono',
    name: 'Hönö / Klåva',
    region: 'goteborg-skargard',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Buss 301 från Göteborg → Öckerö (~1h)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Norra södra skärgårdsö med varierad kustlinje och bra service.',
  },
  {
    slug: 'tjorn-pilane',
    name: 'Tjörn / Pilane',
    region: 'goteborg-skargard',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'medel',
    transport: 'Buss 870/871 från Göteborg C (~1h30)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Skulpturpark möter kustled — Bohusläns konstiga och vackra kombination.',
  },
  {
    slug: 'orust-mollösund-goteborg',
    name: 'Orust / Mollösund',
    region: 'goteborg-skargard',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Buss eller bil från Göteborg',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Välbevarad fiskebyatmosfär längs Bohusläns inre kustled.',
  },
  {
    slug: 'marstrand-goteborg',
    name: 'Marstrand',
    region: 'goteborg-skargard',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Buss 302/312 från Göteborg C, sedan Marstrandsfärjan',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Carlstens fästning, KSSS-stämning och bilfri ö — Bohusläns klassiskaste dagsmål.',
  },
  {
    slug: 'kungsbackafjord',
    name: 'Kungsbackafjord',
    region: 'goteborg-skargard',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Pendeltåg Göteborg → Kungsbacka (~30 min)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Fjordnatur vid Göteborgs-Hallandsgränsen — lugnt, grönt och nästintill turistfritt.',
  },

  // ─── GOTLAND ─────────────────────────────────────────────────────────────
  {
    slug: 'digerhuvud-faro',
    name: 'Digerhuvud, Fårö',
    region: 'gotland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Destination Gotland Nynäshamn → Visby, sedan bil till Fårö (bil rekommenderas)',
    carRequired: true,
    ferryRequired: true,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'De mest dramatiska raukarna i Sverige — surrealistiska klippformationer mot öppet hav.',
    topSweden: 3,
  },
  {
    slug: 'lickershamn',
    name: 'Lickershamn / Jungfrun',
    region: 'gotland',
    distanceKm: 2,
    durationMin: 0.5,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan buss eller bil (~45 min)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Gotlands mest fotograferade raukar — "Jungfrun" reser sig ensam ur havet.',
  },
  {
    slug: 'lummelunda',
    name: 'Lummelundagrottorna',
    region: 'gotland',
    distanceKm: 2,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan buss 21 (~30 min)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: false,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: false,
    bestSeason: 'Maj–september',
    tagline: 'Grottor, skog och Gotlands bästa barnupplevelse — en halvdag som levererar.',
  },
  {
    slug: 'holmhallar-gotland',
    name: 'Holmhallar, södra Gotland',
    region: 'gotland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan bil eller cykel söderut (~1h)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Sydspetsens råa kust med gammalt fyr och känslan av att befinna sig i världens ände.',
  },
  {
    slug: 'sudersand-faro',
    name: 'Sudersand, Fårö',
    region: 'gotland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan bil till Fårö',
    carRequired: true,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Fårös bästa strand — dynlandskap, badvatten och sommarcafé i bakgrunden.',
  },
  {
    slug: 'langhammars-faro',
    name: 'Langhammars, Fårö',
    region: 'gotland',
    distanceKm: 2,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan bil till Fårö',
    carRequired: true,
    ferryRequired: true,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Fårös vildaste rauklandskap — tyst, dramatiskt och nästan alltid tomt.',
  },
  {
    slug: 'hellvi-gotland',
    name: 'Hellvi, norra Gotland',
    region: 'gotland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan buss 22 (~1h)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Norra Gotlands stilla kustsida — lugnt, välmarkerat och med bra bad.',
  },
  {
    slug: 'petesviken-gotland',
    name: 'Petesviken, östkusten',
    region: 'gotland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan bil (~45 min)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Tyst östgotlandsk kust med fågelrika strandängar och havsutsikt mot fastlandet.',
  },
  {
    slug: 'gnisvard-gotland',
    name: 'Gnisvärd',
    region: 'gotland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Destination Gotland → Visby, sedan buss 21 (~30 min) eller cykel',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Kittade sten och raukar längs Gotlands västkust — lättillgängligt och välkänt.',
  },
  {
    slug: 'frojel-gotland',
    name: 'Fröjel / Klintebys kust',
    region: 'gotland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Destination Gotland → Visby, sedan buss (~1h) eller bil',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Medeltida kyrka, kustsikt och en av Gotlands finare halvdagsleder.',
  },

  // ─── HÖGA KUSTEN ─────────────────────────────────────────────────────────
  {
    slug: 'skuleskogen',
    name: 'Skuleskogen',
    region: 'hoga-kusten',
    distanceKm: 30,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'SJ/Norrtåg → Härnösand eller Kramfors, sedan lokal buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'UNESCO-reservat med dramatiska bergssidor och urskogsstämning — Höga kustens hjärta.',
    topSweden: 1,
  },
  {
    slug: 'rotsidan',
    name: 'Rotsidan',
    region: 'hoga-kusten',
    distanceKm: 8,
    durationMin: 3,
    durationMax: 4,
    difficulty: 'medel',
    transport: 'SJ/Norrtåg → Härnösand, sedan lokal buss eller bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Strandnära urskog längs Höga kustenleden — lager på lager av dramatik.',
  },
  {
    slug: 'trysunda',
    name: 'Trysunda',
    region: 'hoga-kusten',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'SJ/Norrtåg → Kramfors, sedan sommarbåt (kontrollera aktuell tidtabell)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    // KÄLLA: Länsstyrelsen Västernorrland — Ångermanlandskustens bäst bevarade fiskeläge, grundat på 1500-talet, kapell från 1600-talet.
    tagline: 'Ångermanlandskustens bäst bevarade fiskeläge på liten ö — nås med sommarbåt och stannar kvar i minnet.',
    topSweden: 8,
  },
  {
    slug: 'ulvon',
    name: 'Ulvön',
    region: 'hoga-kusten',
    distanceKm: 6,
    durationMin: 2.5,
    durationMax: 3.5,
    difficulty: 'medel',
    transport: 'SJ/Norrtåg → Härnösand/Kramfors, sedan sommarbåt',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Surströmmingstraditionen och havsvy — Ulvöns leder vandrar runt berättelsen.',
  },
  {
    slug: 'nordingra',
    name: 'Nordingrå (fastland)',
    region: 'hoga-kusten',
    distanceKm: 8,
    durationMin: 3,
    durationMax: 4,
    difficulty: 'medel',
    transport: 'SJ/Norrtåg → Härnösand, sedan lokal buss Din Tur',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Panoramautsikt över Höga kusten och öarna — dramatik utan båt.',
  },
  {
    slug: 'harnosand-skargard',
    name: 'Härnösands skärgård',
    region: 'hoga-kusten',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'SJ/Norrtåg direkt till Härnösand (~4h30 från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Lättillgänglig skärgård rakt utanför Härnösand — familjeutflykt utan krångel.',
  },
  {
    slug: 'kvissleberget',
    name: 'Kvissleberget',
    region: 'hoga-kusten',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'krävande',
    transport: 'SJ/Norrtåg → Kramfors, sedan lokal buss eller bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Brant höjdvandring med makalös panoramautsikt — Höga kusten uppifrån.',
  },
  {
    slug: 'bonhamn',
    name: 'Bönhamn',
    region: 'hoga-kusten',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'SJ/Norrtåg → Härnösand/Kramfors, sedan bil eller lokal buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Historisk fiskehamn med sommarkafé och enkel vandring längs vattnet.',
  },
  {
    slug: 'hogakustenleden',
    name: 'Höga kustenleden (etapp)',
    region: 'hoga-kusten',
    distanceKm: 20,
    durationMin: 7,
    durationMax: 10,
    difficulty: 'krävande',
    transport: 'SJ/Norrtåg till start- och slutpunkt beroende på etapp',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: '130 km längs UNESCO-kustens ryggrad — välj valfri etapp för en oförglömlig vandring.',
  },
  {
    slug: 'storon-hogakusten',
    name: 'Storön',
    region: 'hoga-kusten',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'SJ/Norrtåg → Härnösand/Kramfors, sedan sommarbåt',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Tystnad och orördhet på ö som nås med sommarbåt — Höga kustens dolda kort.',
  },

  // ─── BLEKINGE ────────────────────────────────────────────────────────────
  {
    slug: 'hano',
    name: 'Hanö',
    region: 'blekinge',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'SJ → Karlskrona/Sölvesborg, sedan bil/buss till Nogersund, sommarbåt till Hanö',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Blekinges utpost med unik engelsk kyrkogård, fågelrika strandängar och råt Östersjö-hav.',
    topSweden: 10,
  },
  {
    slug: 'aspo-blekinge',
    name: 'Aspö',
    region: 'blekinge',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'SJ → Karlskrona, Blekingetrafiken pendelbåt',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Skärgårdsö nära Karlskrona med gästbrygga och välbevarad byatmosfär.',
  },
  {
    slug: 'tjurko-blekinge',
    name: 'Tjurkö',
    region: 'blekinge',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'SJ → Karlskrona, Blekingetrafiken pendelbåt',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Lättillgänglig ö utanför Karlskrona med vacker klippkust.',
  },
  {
    slug: 'hasslo-blekinge',
    name: 'Hasslö',
    region: 'blekinge',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'SJ → Karlskrona, Blekingetrafiken pendelbåt',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Bilfri ö med natur och byatmosfär — Blekinges lättillgängligaste dagsutflykt.',
  },
  {
    slug: 'sturko-blekinge',
    name: 'Sturkö',
    region: 'blekinge',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'SJ → Karlskrona, Blekingetrafiken pendelbåt',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Blekinges mest varierade skärgårdsö — leder längs en omväxlande kustlinje.',
  },
  {
    slug: 'ronneby-skargard',
    name: 'Ronneby skärgård',
    region: 'blekinge',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'SJ → Ronneby, sedan bil eller lokal buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Geologiskt unik serpentinsten — rödbrun dramaturgi längs Blekinges kust.',
  },
  {
    slug: 'karlskrona-stadsvandring',
    name: 'Karlskrona — marinstad',
    region: 'blekinge',
    distanceKm: 3,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'SJ/Öresundståg direkt till Karlskrona C (~4h30 från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Helår',
    tagline: 'UNESCO-världsarv och örlogsstad — en kulturvandring som också är riktig natur.',
  },
  {
    slug: 'solvesborg-kust',
    name: 'Sölvesborg kust',
    region: 'blekinge',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'SJ → Sölvesborg (~3h30 från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Enkel kustpromenad med god service — cykelleden EuroVelo 10 (Östersjöleden) passerar längs kusten.',
  },
  {
    slug: 'tromto-blekinge',
    name: 'Tromtö',
    region: 'blekinge',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'SJ → Karlskrona, sedan bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Lugnt läge i Blekinge skärgård med hamnmiljö och naturreservat.',
  },
  {
    slug: 'nogersund',
    name: 'Nogersund',
    region: 'blekinge',
    distanceKm: 2,
    durationMin: 0.5,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'SJ → Sölvesborg, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Avresehamnen till Hanö — charmig fiskehamn med promenad längs vattnet.',
  },

  // ─── ÖLAND ───────────────────────────────────────────────────────────────
  {
    slug: 'trollskogen-oland',
    name: 'Trollskogen, Öland',
    region: 'oland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss KLT 101/106 över Ölandsbron, buss norrut',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Gammal urskog med vridna träd vid havsstranden — Ölands mest sagolika naturupplevelse.',
    topSweden: 7,
  },
  {
    slug: 'ottenby-oland',
    name: 'Ottenby naturreservat',
    region: 'oland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss KLT söderut',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: false,
    bestSeason: 'Maj–oktober',
    tagline: 'Södra Öland och Europas bästa fågelskådning — fyren Långa Jan i siluett mot havet.',
  },
  {
    slug: 'stora-alvaret',
    name: 'Stora alvaret',
    region: 'oland',
    distanceKm: 0,
    durationMin: 2,
    durationMax: 5,
    difficulty: 'medel',
    transport: 'Tåg → Kalmar, sedan buss KLT',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'UNESCO-klassat öppet landskap utan motstycke — vindpinat, oändligt och unikt i världen.',
  },
  {
    slug: 'horns-naturreservat',
    name: 'Horns naturreservat',
    region: 'oland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'medel',
    transport: 'Tåg → Kalmar, sedan buss norrut till Böda',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Ölands nordspets med hällmarker, havsvy och en känsla av öns yttersta gräns.',
  },
  {
    slug: 'bodahamn-oland',
    name: 'Bödahamn',
    region: 'oland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss KLT norrut',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Sandstrand och skog vid Ölands nordkust — lättillgängligt och barnvänligt.',
  },
  {
    slug: 'kapelludden-oland',
    name: 'Kapelludden',
    region: 'oland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss KLT',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Kalkstenskust och ett av Ölands äldsta fyrar — kort men med stark karaktär.',
  },
  {
    slug: 'borgholm-oland',
    name: 'Borgholms slottsruin',
    region: 'oland',
    distanceKm: 2,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss KLT 101 till Borgholm',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Ruinens panoramautsikt och Ölands handelsstad i en och samma promenad.',
  },
  {
    slug: 'ralla-gardslosa',
    name: 'Rälla–Gärdslösa',
    region: 'oland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Tåg → Kalmar, sedan buss KLT',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Medeltida kyrkor längs alvarkanten — historia, tomhet och Öland när det är bäst.',
  },
  {
    slug: 'olandsleden',
    // KÄLLA: STF Signaturled Öland — Mörbylångaleden, 84 km i fem etapper (12–18 km/dag), Färjestaden–Ottenby. 'Ölandsleden' är cykelleden.
    name: 'Mörbylångaleden (etapp)',
    region: 'oland',
    distanceKm: 15,
    durationMin: 5,
    durationMax: 8,
    difficulty: 'krävande',
    transport: 'Tåg → Kalmar, sedan buss KLT till etapps startpunkt',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Södra Ölands världsarv i fem etapper — 84 km från Färjestaden till Ottenby, vandra en dagsetapp eller hela leden.',
  },
  {
    slug: 'kopingsvik-oland',
    name: 'Köpingsvik',
    region: 'oland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss KLT',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Lugn kustpromenad med havsutsikt på Ölands västra sida.',
  },

  // ─── SKÅNE ───────────────────────────────────────────────────────────────
  {
    slug: 'kullaberg',
    name: 'Kullaberg',
    region: 'skane',
    distanceKm: 8,
    durationMin: 3,
    durationMax: 5,
    difficulty: 'medel',
    transport: 'Tåg → Helsingborg/Höganäs, sedan buss (~1h30)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Dramatiska klippavsatser och sällsynt flora — Skånes mest spektakulära naturreservat.',
    topSweden: 5,
  },
  {
    slug: 'soderaasen',
    name: 'Söderåsen',
    region: 'skane',
    distanceKm: 7,
    durationMin: 2.5,
    durationMax: 4,
    difficulty: 'medel',
    transport: 'Tåg → Eslöv, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Helår',
    tagline: 'Dramatiska raviner och lövskogar — nationalpark med hela Skåne under sig.',
  },
  {
    slug: 'hovs-hallar',
    name: 'Hovs hallar',
    region: 'skane',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'medel',
    transport: 'Bil rekommenderas, eller buss från Ängelholm',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Skånes vildaste klippor — dramatisk panoramautsikt och havsljus som inte finns bättre.',
  },
  {
    slug: 'stenshuvud',
    name: 'Stenshuvud nationalpark',
    region: 'skane',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Simrishamn, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Sydlig natur med sand, skog och hav — nationalpark med ovanliga växter och djur.',
  },
  {
    slug: 'ales-stenar',
    name: 'Ales stenar',
    region: 'skane',
    distanceKm: 2,
    durationMin: 0.5,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Tåg → Ystad, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Helår',
    tagline: 'Fornminne + havsutsikt — ett av Sveriges bäst placerade kulturarv.',
  },
  {
    slug: 'nimis-ladonia',
    name: 'Nimis / Ladonia',
    region: 'skane',
    distanceKm: 2,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Bil från Helsingborg (~45 min), eller buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'En konststallation som blivit sin egen nation — märklig, vacker och unik.',
  },
  {
    slug: 'falsterbo',
    name: 'Falsterbo',
    region: 'skane',
    distanceKm: 6,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Malmö, sedan buss (~1h)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Sept–oktober (fåglar), juni–aug (bad)',
    tagline: 'Europas bästa fågelskådning september–oktober och Skånes längsta sanddyner.',
  },
  {
    slug: 'molle-fyr',
    name: 'Mölle fyr',
    region: 'skane',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Helsingborg, sedan buss (~1h)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Klassisk utflyktsplats på Kullahalvön med bra utsikt och gott om restauranger.',
  },
  {
    slug: 'osterlen-kust',
    name: 'Österlen kust',
    region: 'skane',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Simrishamn/Ystad',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Havsutsikt, mysiga byar och Skånes bästa mat längs Österlenleden.',
  },
  {
    slug: 'torekov',
    name: 'Torekov',
    region: 'skane',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Tåg → Ängelholm, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Pittoresk kuststad med smal promenad ut mot Hallands Väderö.',
  },

  // ─── SÖRMLAND ────────────────────────────────────────────────────────────
  {
    slug: 'stendorren',
    name: 'Stendörren naturreservat',
    region: 'sormland',
    distanceKm: 6,
    durationMin: 2,
    durationMax: 3.5,
    difficulty: 'medel',
    transport: 'Tåg → Nyköping, sedan lokal buss (kontrollera tidtabell)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Sörmlands bästa kustnatur — dramatisk klippkust med hängbro och havsvy.',
  },
  {
    slug: 'trosa-skargard',
    name: 'Trosa skärgård',
    region: 'sormland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Vagnhärad, sedan buss till Trosa (~1h20 totalt)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Sörmlands lilla kuststad med charmig hamn och dagsutflykter till skärgården.',
  },
  {
    slug: 'morko-sormland',
    name: 'Mörkö',
    region: 'sormland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'medel',
    transport: 'Tåg → Södertälje, sedan buss via bro till ön',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Sörmlandskust via bro — blandskog, klippor och nästan ingen turism.',
  },
  {
    slug: 'asko-sormland',
    name: 'Askö',
    region: 'sormland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'medel',
    transport: 'Tåg → Nyköping, sedan båt (kontrollera aktuell tidtabell)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Naturvårdsverkets forskningsö öppen för besökare — stilla, vacker och nästan folktomt.',
  },
  {
    slug: 'bergholmen-trosa',
    name: 'Bergholmen / Trosaön',
    region: 'sormland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Vagnhärad, sedan buss till Trosa',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Lättillgänglig kustpromenad strax utanför Trosa centrum.',
  },
  {
    slug: 'sormlandsleden-kust',
    name: 'Sörmlandsleden (kustdel)',
    region: 'sormland',
    distanceKm: 20,
    durationMin: 7,
    durationMax: 10,
    difficulty: 'krävande',
    transport: 'Tåg till start- och slutpunkt',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Sörmlandsleden längs kusten — välkarterade etapper med natur och tystnad.',
  },
  {
    slug: 'halluden-sormland',
    name: 'Hålludden naturreservat',
    region: 'sormland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Norrköping, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Sörmlandskusthedens öppna marker med havsvy — lite känt men genuint fint.',
  },
  {
    slug: 'braviken-sormland',
    name: 'Breviks klint',
    region: 'sormland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'medel',
    transport: 'Tåg → Norrköping, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Kolmårdens kustbrant med havsvy — litet känd utsiktsklättring vid Bråviken.',
  },
  {
    slug: 'nynashamn-skargard',
    name: 'Nynäshamn skärgård',
    region: 'sormland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Pendeltåg linje 43 direkt från Stockholm City (ca 65 min)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Stadsvandrings-skärgård nästintill Stockholm — nås med pendeltåg.',
  },
  {
    slug: 'oxelosund-kust',
    name: 'Oxelösund kust',
    region: 'sormland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Oxelösund (~1h30 från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Sörmlands industristad med förvånansvärd kustpromenad och naturreservat.',
  },

  // ─── ÖSTGÖTA ─────────────────────────────────────────────────────────────
  {
    slug: 'harstena',
    name: 'Harstena',
    region: 'ostgota',
    distanceKm: 3,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Valdemarsvik, sedan sommarbåt (kontrollera aktuell tidtabell)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Välbevarad gammal fiskebyatmosfär på ö i S:t Anna skärgård — historia och hav.',
  },
  {
    slug: 'gryt-fyrudden',
    name: 'Gryt / Fyrudden',
    region: 'ostgota',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Tåg → Valdemarsvik, sedan buss (kontrollera aktuell tidtabell)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Kuststigar i S:t Anna skärgård — ett av Sverige vackraste och mest underbesökta archipelago.',
  },
  {
    slug: 'arko',
    name: 'Arkö',
    region: 'ostgota',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'medel',
    transport: 'Tåg → Norrköping, sedan båt (kontrollera aktuell tidtabell)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Historisk fästningsö med natur och gästhamn i Östergötlands skärgård.',
  },
  {
    slug: 'sant-anna-kust',
    name: 'S:t Anna kuststig',
    region: 'ostgota',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Tåg → Valdemarsvik, sedan buss eller bil',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Nationalparksmiljö längs fastlandssidan av S:t Anna — 6 000 öar och kobbar inom syn.',
  },
  {
    slug: 'valdemarsviken',
    name: 'Valdemarsviken',
    region: 'ostgota',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Valdemarsvik direkt (~2h från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Vacker inre fjärd med kustled och Östergötlands lugnaste vandring.',
  },
  {
    slug: 'braviken-ostgota',
    name: 'Bråvikens kust',
    region: 'ostgota',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Norrköping (~1h30 från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Kustpromenad längs Norrköpingsregionens fjärdinlopp.',
  },
  {
    slug: 'vindo-ostgota',
    name: 'Vindö (Östergötland)',
    region: 'ostgota',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Norrköping, sedan båt',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Liten bilfri ö i Östgötaskärgården — tyst och med äkta skärgårdsstämning.',
  },
  {
    slug: 'kvadofjarden',
    name: 'Kvädöfjärden',
    region: 'ostgota',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Bil rekommenderas, eller tåg → Valdemarsvik + buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Stilla fjärdnatur på gränsen Östergötland–Småland — bortglömd och vacker.',
  },
  {
    slug: 'vikbolandet',
    name: 'Vikbolandet kustled',
    region: 'ostgota',
    distanceKm: 6,
    durationMin: 2.5,
    durationMax: 3.5,
    difficulty: 'medel',
    transport: 'Tåg → Norrköping, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: false,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Välmarkerad kustled på Vikbolandet — känd bland lokalbefolkningen, okänd för övriga.',
  },
  {
    slug: 'stegeborgsfjardin',
    name: 'Stegeborgsfjärden',
    region: 'ostgota',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Norrköping/Linköping, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Borgruin med fjärdutsikt — kulturhistoria och natur i en och samma vandring.',
  },

  // ─── SMÅLANDSKUSTEN ──────────────────────────────────────────────────────
  {
    slug: 'vastervik-hasselo',
    name: 'Västervik / Hasselö',
    region: 'smalandskusten',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Tåg → Västervik (~3h30 från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Västerviks undervattrade skärgårdslandskap börjar direkt utanför staden.',
  },
  {
    slug: 'kalmarsund-kustled',
    name: 'Kalmarsund kustled',
    region: 'smalandskusten',
    distanceKm: 7,
    durationMin: 2.5,
    durationMax: 4,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar (~3h från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Utsikt mot Öland hela vägen — Kalmarsund ger havsvy med varje steg.',
  },
  {
    slug: 'oskarshamn-farbo',
    name: 'Oskarshamn / Fårbo',
    region: 'smalandskusten',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'medel',
    transport: 'Tåg → Oskarshamn (~2h30 från Stockholm)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Småländsk ö-landskap runt Oskarshamn — lugnt och genuint.',
  },
  {
    slug: 'simpevarp',
    name: 'Simpevarp',
    region: 'smalandskusten',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Oskarshamn, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Kalmarsunds varmaste badvatten tack vare kärnkraftverkets kylvatten — ovanlig naturtillgång.',
  },
  {
    slug: 'viros-vastervik',
    name: 'Virös, Västervik',
    region: 'smalandskusten',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Västervik, sedan båt (kontrollera tidtabell)',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Liten sommarhamnsö i Västerviks skärgård med stilla natur.',
  },
  {
    slug: 'figeholm',
    name: 'Figeholm',
    region: 'smalandskusten',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Oskarshamn, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Stilla Östgöta-Småland-kust med tyst fjärdnatur och kaféhamn.',
  },
  {
    slug: 'bergkvara',
    name: 'Bergkvara kust',
    region: 'smalandskusten',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss söderut',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Sydsmåländsk kustort med sandstrand och utsikt mot Blekinge.',
  },
  {
    slug: 'stegeborgsfjardin-smaland',
    name: 'Stegeborg (norra sidan)',
    region: 'smalandskusten',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Linköping/Norrköping, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Fjärdutsikt och borgruin i gränslandets natur.',
  },
  {
    slug: 'kvadefjarden-smaland',
    name: 'Kvädöfjärden',
    region: 'smalandskusten',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Bil eller tåg → Valdemarsvik + buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Stilla fjärd vid gränsen Östergötland–Småland — bortglömd och vacker.',
  },
  {
    slug: 'krisdianda-kust',
    name: 'Pataholm kust',
    region: 'smalandskusten',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Kalmar, sedan buss norrut',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Liten kustort med sund och havsvy — Kalmarsunds norra sida.',
  },

  // ─── HALLAND ─────────────────────────────────────────────────────────────
  {
    slug: 'haverdal',
    name: 'Haverdal naturreservat',
    region: 'halland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Halmstad, sedan buss 20 (~30 min)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Hallands bästa dynlandskap — sandstränder, tallskog och havsluft hela vägen.',
  },
  {
    slug: 'tjolöholm',
    name: 'Tjolöholm slottspark',
    region: 'halland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Kungsbacka, sedan buss (~1h totalt)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Engelsk-gotisk slottspark med kustpromenad och havsutsikt söder om Göteborg.',
  },
  {
    slug: 'hallands-vadero',
    name: 'Hallands Väderö',
    region: 'halland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Tåg → Ängelholm, sedan buss + sommarbåt från Torekov',
    carRequired: false,
    ferryRequired: true,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: false,
    bestSeason: 'Juni–september',
    tagline: 'Naturreservat ute i Skagerrak — dramatisk ö med rika havskedjor.',
  },
  {
    slug: 'varberg-fastning',
    name: 'Varberg fästning',
    region: 'halland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Varberg direkt (~1h20 från Göteborg, ~2h30 från Malmö)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Helår',
    tagline: 'Medeltida fästning + Hallands vackraste havsfront — kulturvandring vid vattnet.',
  },
  {
    slug: 'tylosand-halmstad',
    name: 'Tylösand / Halmstad',
    region: 'halland',
    distanceKm: 5,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Halmstad, sedan buss 300 (~30 min)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Juni–september',
    tagline: 'Hallands mest kända sandstrand med dynlandskap och kustpromenad.',
  },
  {
    slug: 'falkenberg-kust',
    name: 'Falkenberg kust',
    region: 'halland',
    distanceKm: 4,
    durationMin: 1.5,
    durationMax: 2.5,
    difficulty: 'lätt',
    transport: 'Tåg → Falkenberg (~1h40 från Göteborg)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Hallands äldsta stad med kustpromenad och sandstrand — lägre profil än Tylösand.',
  },
  {
    slug: 'skottorp',
    name: 'Skottorp kust',
    region: 'halland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 1.5,
    difficulty: 'lätt',
    transport: 'Tåg → Laholm, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Lugn Hallandskust utan turisttryck — naturstrand och öppen kustlinje.',
  },
  {
    slug: 'laholm-kust',
    name: 'Laholm kust',
    region: 'halland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'lätt',
    transport: 'Tåg → Laholm (~1h50 från Göteborg)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–september',
    tagline: 'Öppen Hallandskusten med lång sandstrand och lättgångna kustleder.',
  },
  {
    slug: 'kungsbackafjord-halland',
    name: 'Kungsbackafjord (söder)',
    region: 'halland',
    distanceKm: 5,
    durationMin: 2,
    durationMax: 3,
    difficulty: 'medel',
    transport: 'Pendeltåg Göteborg → Kungsbacka (~30 min)',
    carRequired: false,
    ferryRequired: false,
    hasBathing: true,
    hasRestaurant: false,
    hasCafe: false,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Fjordnatur precis söder om Göteborg — lättillgänglig och förvånansvärt naturskön.',
  },
  {
    slug: 'steninge-slott',
    name: 'Steninge slott kust',
    region: 'halland',
    distanceKm: 3,
    durationMin: 1,
    durationMax: 2,
    difficulty: 'lätt',
    transport: 'Tåg → Halmstad, sedan buss',
    carRequired: false,
    ferryRequired: false,
    hasBathing: false,
    hasRestaurant: true,
    hasCafe: true,
    suitableForChildren: true,
    suitableForDogs: true,
    bestSeason: 'Maj–oktober',
    tagline: 'Slottspark med kustvy — en annorlunda kombination av kulturhistoria och havet.',
  },
]

export type RegionMeta = {
  id: HikeRegion
  name: string
  shortDesc: string
  relatedUrl?: string
}

export const REGIONS: RegionMeta[] = [
  {
    id: 'stockholms-skargard',
    name: 'Stockholms skärgård',
    shortDesc: '30 000 öar, kobbar och skär — och ett dussin av dem med välmarkerade vandringsleder som nås med Waxholmsbolaget utan bil.',
    relatedUrl: '/stockholms-skargard',
  },
  {
    id: 'bohuslan',
    name: 'Bohuslän',
    shortDesc: 'Klipphallar, smala sund och Kosterhavet nationalpark — Bohusläns leder varierar från bilfria öar till atlantexponerade klippkanter.',
    relatedUrl: '/bohuslan',
  },
  {
    id: 'goteborg-skargard',
    name: 'Göteborgs skärgård',
    shortDesc: 'Bilfria öar en timme från Göteborg med spårvagn och pendelbåt — Vrångö, Styrsö, Donsö och Marstrand.',
    relatedUrl: '/goteborg-skargard',
  },
  {
    id: 'gotland',
    name: 'Gotland',
    shortDesc: 'Raukar, kalksten och ett unikt ljus — Gotlands kustnatur saknar motstycke i Sverige. Bäst maj-juni och september.',
    relatedUrl: '/gotland',
  },
  {
    id: 'hoga-kusten',
    name: 'Höga kusten',
    shortDesc: 'UNESCO-klassad dramatisk topografi — landet reser sig ur havet och det syns i varje steg längs Skuleskogen.',
    relatedUrl: '/hoga-kusten',
  },
  {
    id: 'blekinge',
    name: 'Blekinge skärgård',
    shortDesc: 'Frodig, grön och genuint underbesökt — Karlskronas UNESCO-världsarv och Hanös ödesliga naturhamn.',
    relatedUrl: '/blekinge-skargard',
  },
  {
    id: 'oland',
    name: 'Öland',
    shortDesc: 'UNESCO-klassat alvar, Trollskogens urgamla träd och Ottenby med Europas bästa fågelskådning.',
    relatedUrl: '/oland',
  },
  {
    id: 'skane',
    name: 'Skånes kust',
    shortDesc: 'Kullabergs dramatiska klippavsatser, Söderåsen och Österlen — Skåneleden är ett av Sveriges bästa sammanhängande vandlingsnät.',
  },
  {
    id: 'sormland',
    name: 'Sörmlands skärgård',
    shortDesc: 'Stendörren naturreservat och Trosa skärgård — välhållen hemlighet längs Östersjöns västra kust.',
  },
  {
    id: 'ostgota',
    name: 'Östgötaskärgården',
    shortDesc: 'S:t Anna skärgård med 6 000 öar och kobbar — ett av Sveriges vackraste archipelago, lite känt utanför regionen.',
  },
  {
    id: 'smalandskusten',
    name: 'Smålandskusten',
    shortDesc: 'Västervik har ett av Sveriges bäst outforskade skärgårdslandskap. Kalmarsund ger havsutsikt mot Öland med varje steg.',
  },
  {
    id: 'halland',
    name: 'Hallandskusten',
    shortDesc: 'Sandstränder, dynlandskap och Haverdal naturreservat — Halland är inte skärgård men har kustleder av hög klass.',
  },
]

export function hikesForRegion(region: HikeRegion): Hike[] {
  return HIKES.filter(h => h.region === region)
}

export function featuredHikes(): Hike[] {
  return HIKES.filter(h => h.featured)
}

export function topSwedenHikes(): Hike[] {
  return HIKES.filter(h => h.topSweden != null).sort((a, b) => (a.topSweden ?? 99) - (b.topSweden ?? 99))
}
