export type PostMeta = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  emoji: string
  tags: string[]
}

export const POSTS_META: PostMeta[] = [
  { slug: 'basta-restaurangerna-sandhamn', title: 'Restauranger på Sandhamn – lunch, middag, kafé och bar', excerpt: 'Var du äter på Sandhamn: Värdshusets pub som är öppen året runt, Seglarhotellet, Dykarbaren, Sands, bageriet, kaféerna och barerna – säsonger, bordsbokning och båten dit.', category: 'Mat & dryck', date: '2026-04-10', readTime: '6 min', emoji: '🍽', tags: ['Sandhamn', 'Restauranger', 'Lunch', 'Kafé'] },
  { slug: 'kajak-stockholms-skargard-nyborjare', title: 'Kajak i Stockholms skärgård – guide för nybörjare', excerpt: 'Paddla kajak i Stockholms skärgård: var du hyr kajak, vad allemansrätten säger om att gå i land och övernatta, fågel- och sälskyddsområden, tältplatser och utrustning för säker paddling.', category: 'Aktiviteter', date: '2026-03-28', readTime: '8 min', emoji: '🛶', tags: ['Kajak', 'Nybörjare', 'Paddling'] },
  { slug: 'dolda-parlor-moja', title: 'Möja – vandring, bad, museum och mat på ön', excerpt: 'Vad du gör på Möja i Stockholms mellersta skärgård: naturstigen genom Björndalen, bad enligt allemansrätten, Roland Svensson-museet, kyrkan från 1768, var du äter och hur du tar dig dit.', category: 'Öguide', date: '2026-03-15', readTime: '6 min', emoji: 'island', tags: ['Möja', 'Bilfri ö', 'Skärgård'] },
  { slug: 'bransle-ankring-skargard', title: 'Bränsle och ankringsplatser i ytterskärgården', excerpt: 'Planerar du en längre tur mot Landsort eller Sandhamn? Här är en komplett genomgång av bränslehamnar, naturhamnar och tjänstehamnar längs vägen.', category: 'Praktiskt', date: '2026-03-01', readTime: '7 min', emoji: 'fuel', tags: ['Bränsle', 'Ankring', 'Planering'] },
  { slug: 'sommar-skargard-tips', title: '10 saker du måste göra i skärgården i sommar', excerpt: 'Från gryningsfika vid en klippa till kvällsseglingen med solnedgång. Vår lista över årets bästa skärgårdsupplevelser.', category: 'Inspiration', date: '2026-02-14', readTime: '4 min', emoji: 'sun', tags: ['Sommar', 'Tips', 'Inspiration'] },
  { slug: 'fjaderholmarna-dagstur', title: 'Fjäderholmarna dagstur – båt, mat och vad du gör på ön', excerpt: 'Dagstur till Fjäderholmarna från Stockholm: vilka båtar som går och hur lång tid det tar, Rökeriet, krogen och bryggeriet, hantverkarna, bad från klipporna och öarnas historia.', category: 'Öguide', date: '2026-01-30', readTime: '5 min', emoji: '⛴', tags: ['Fjäderholmarna', 'Dagstur', 'Stockholm'] },
  { slug: 'vaxholm-guide', title: 'Vaxholm dagstur – kastellet, staden och båt från Strömkajen', excerpt: 'Dagstur till Vaxholm: båt från Strömkajen eller buss 670, Vaxholms kastell och museet, kyrkan, Rindö redutt och Oscar-Fredriksborg, Bogesundslandet och var du äter vid hamnen.', category: 'Öguide', date: '2026-04-05', readTime: '6 min', emoji: 'building', tags: ['Vaxholm', 'Fästning', 'Dag- eller weekendtur'] },
  { slug: 'uto-guide', title: 'Utö guide – gruvorna, cykel, bad och båt från Årsta brygga', excerpt: 'Allt om Utö i Stockholms södra skärgård: Waxholmsbåten från Årsta brygga, gruvorna och väderkvarnen från 1791, cykeluthyrning, bad vid Ålö Storsand och Rävstavik, Utö Värdshus, gästhamnen och reglerna i naturreservatet.', category: 'Öguide', date: '2026-03-22', readTime: '7 min', emoji: '🚲', tags: ['Utö', 'Cykling', 'Havsbastu'] },
  { slug: 'segling-nyborjare-guide', title: 'Börja segla – så lär du dig segla i skärgården', excerpt: 'Så börjar du segla: seglarskola för vuxna, Seglarintyg 1 och 2, vilka krav som gäller för att köra fritidsbåt, de viktigaste väjningsreglerna och hur du hyr en segelbåt i Stockholms skärgård.', category: 'Aktiviteter', date: '2026-03-18', readTime: '9 min', emoji: 'sailboat', tags: ['Segling', 'Nybörjare', 'Hyrbåt'] },
  { slug: 'basta-badplatserna', title: 'Badplatser i Stockholms skärgård – sandstränder och klippbad', excerpt: 'Sandstränder, klippbad och havsbad i Stockholms skärgård: Trouville på Sandhamn, Björnö och Ingarö, Vaxholmsöarna och bad du når med Roslagsbanan, Saltsjöbanan eller buss. Fakta från kommunerna och Havs- och vattenmyndigheten.', category: 'Aktiviteter', date: '2026-04-08', readTime: '6 min', emoji: '🏊', tags: ['Bad', 'Badplatser', 'Sommar'] },
  { slug: 'vandring-orno-uto', title: 'Vandring i skärgården – bästa lederna på Ornö och Utö', excerpt: 'Stockholms skärgård är inte bara vatten. Ornö och Utö har markerade leder genom urbergslandskap och gammal skog som är värda varje steg.', category: 'Aktiviteter', date: '2026-02-28', readTime: '7 min', emoji: '🥾', tags: ['Vandring', 'Ornö', 'Utö', 'Natur'] },
  { slug: 'cykling-moja-gallno', title: 'Hyra cykel på Möja och Gällnö – cykla i skärgården', excerpt: 'Var du hyr cykel på Möja och Gällnö, hur långa öarna är, var du badar och äter längs vägen och hur du tar dig dit med båt från Stockholm.', category: 'Aktiviteter', date: '2026-02-20', readTime: '5 min', emoji: '🚴', tags: ['Cykling', 'Möja', 'Gällnö', 'Bilfri ö'] },
  { slug: 'fiske-skargard-guide', title: 'Fiske i Stockholms skärgård – arter, platser och regler', excerpt: 'Abborre, gädda, gös, havsöring och sik i Stockholms skärgård: när och var de biter enligt Länsstyrelsens fiskeguide, var handredskapsfisket är fritt och vilka mått och fångstgränser som gäller.', category: 'Aktiviteter', date: '2026-02-10', readTime: '8 min', emoji: 'fish', tags: ['Fiske', 'Sportfiske', 'Skärgård'] },
  { slug: 'gasthamnar-guide', title: 'Gästhamnar i Stockholms skärgård – platser, service och bokning', excerpt: 'Gästhamnar i Stockholms skärgård från Grisslehamn till Nåttarö: antal gästplatser, djup, förtöjning, service och om platsen går att boka – hämtat från hamnarnas egna sidor.', category: 'Praktiskt', date: '2026-01-25', readTime: '8 min', emoji: 'anchor', tags: ['Gästhamn', 'Båt', 'Övernattning'] },
  { slug: 'vinter-skargard', title: 'Skärgård på vintern – upplev islugnet', excerpt: 'De flesta undviker skärgården på vintern. Det är ett misstag. Stillheten, isfiskarna och de tomma bryggorna är en helt annan och fantastisk upplevelse.', category: 'Inspiration', date: '2025-12-15', readTime: '5 min', emoji: 'snow', tags: ['Vinter', 'Lugn', 'Skärgård'] },
  { slug: 'barnfamilj-skargard', title: 'Skärgård med barnfamilj – 8 tips för en lyckad tur', excerpt: 'Att ta ut hela familjen i skärgården kräver lite planering. Här är de bästa öarna, säkraste badplatserna och restaurangerna som faktiskt fungerar med barn.', category: 'Familj', date: '2026-01-15', readTime: '6 min', emoji: '👨‍👩‍👧‍👦', tags: ['Barnfamilj', 'Barn', 'Planering'] },
  { slug: 'svenska-hoar-sandhamn', title: 'Svenska Högarna – den yttersta förposten', excerpt: 'Längst ut i ytterskärgården: klippor, hav och en av skärgårdens absolut finaste naturupplevelser utan restauranger eller handel.', category: 'Öguide', date: '2026-03-05', readTime: '5 min', emoji: 'rock', tags: ['Svenska Högarna', 'Ytterskärgård', 'Naturreservat'] },
  { slug: 'grilla-naturhamn', title: 'Grilla i naturhamnen – regler, tips och bästa platser', excerpt: 'Vad gäller egentligen vid eldning i skärgården? Vi reder ut allemansrätten, när eldningsförbud gäller och de bästa platserna att grilla när reglerna tillåter.', category: 'Praktiskt', date: '2026-02-05', readTime: '5 min', emoji: '🔥', tags: ['Grill', 'Eldning', 'Allemansrätten'] },
  { slug: 'norrtelje-norra-skargard', title: 'Norra skärgården – Norrtelje och Singö', excerpt: 'Norrtäljes skärgård är mer rå och orörd än Stockholms. Singö, Väddö och Räfsnäs är ett annat tempo – lugnt, genuint och fortfarande inte turistifierat.', category: 'Öguide', date: '2026-01-20', readTime: '6 min', emoji: 'water', tags: ['Norra skärgården', 'Norrtelje', 'Singö'] },
  { slug: 'packlista-bat', title: 'Packlista för båten – bra saker att ha ombord', excerpt: 'Bra saker att ha i båten: säkerhetsutrustning, navigation, verktyg, mat och kläder – en checklista för dagsturen och veckan i skärgården.', category: 'Praktiskt', date: '2026-04-01', readTime: '4 min', emoji: '🎒', tags: ['Packlista', 'Utrustning', 'Säkerhet'] },
  { slug: 'havsbastu-guide', title: 'Havsbastu i skärgården – de bästa platserna 2026', excerpt: 'Ingenting slår en rykande bastu vid havet med ett dopp efteråt. Vi har listat de bästa havsbastuplatserna i Stockholms skärgård.', category: 'Aktiviteter', date: '2026-03-10', readTime: '5 min', emoji: '🧖', tags: ['Bastu', 'Havsbastu', 'Avkoppling'] },
  { slug: 'segling-klassiska-leder', title: 'Klassiska seglarleder i Stockholms skärgård', excerpt: 'Stockholmsleder, Furusundsleder och Sandhamnsleden är ryggraden i skärgårdssegling. En guide till ledernas historia, svårighetsgrad och bästa hamnarna.', category: 'Segling', date: '2026-02-25', readTime: '9 min', emoji: 'map', tags: ['Segling', 'Leder', 'Rutter'] },

  { slug: 'midsommar-skargarden-2026', title: 'Midsommar i skärgården 2026 – 15 alternativ', excerpt: '8 destinationer på ostkusten och 7 på västkusten. Kollektivtrafik, tips och var du äter – komplett planeringsguide.', category: 'Guide', date: '2026-05-10', readTime: '14 min', emoji: '🌸', tags: ['Midsommar', 'Skärgård', 'Guide'] },
  { slug: 'packlista-skargarden', title: 'Komplett packlista för skärgården', excerpt: 'Kläder, mat & dryck, säkerhet, teknik, barn och segling. Allt samlat i en guide du kan bocka av innan du lämnar bryggan.', category: 'Guide', date: '2026-05-05', readTime: '8 min', emoji: '📋', tags: ['Packlista', 'Förberedelse', 'Guide'] },
  { slug: 'allemansratten-pa-sjon', title: 'Allemansrätten på sjön – vad som gäller på vattnet', excerpt: 'Var får du ankra, tälta och elda? Vad gäller om toalettavfall? Enkla svar på de vanligaste frågorna om allemansrätten till sjöss.', category: 'Guide', date: '2026-05-01', readTime: '7 min', emoji: '⚓', tags: ['Allemansrätten', 'Regler', 'Guide'] },
  { slug: 'waxholmsbolaget-guide', title: 'Waxholmsbolaget – komplett guide till båttrafiken', excerpt: 'Hur fungerar linjerna? Vilka hållplatser gäller? Är SL-kortet giltigt? Allt om Waxholmsbolaget samlat på ett ställe.', category: 'Guide', date: '2026-04-28', readTime: '9 min', emoji: '🚢', tags: ['Waxholmsbolaget', 'Transport', 'Guide'] },
  { slug: 'skargard-utan-bat', title: 'Skärgård utan båt – 10 öar du når utan eget fartyg', excerpt: 'Bilfärja, Waxholmsbolaget och SL – 10 konkreta förslag rangordnade efter tillgänglighet för dig utan båt.', category: 'Guide', date: '2026-04-25', readTime: '10 min', emoji: '🚌', tags: ['Transport', 'Kollektivt', 'Guide'] },

  // ── Strategiska SEO-artiklar (2026) ──────────────────────────────────────
  { slug: 'weekend-skargard-stockholm', title: 'Weekend i skärgården 2026 – 8 kompletta upplägg från Stockholm', excerpt: 'Hur planerar man en perfekt skärgårdshelg? Här är åtta konkreta upplägg — från dagsturen som känns som ett äventyr till weekendresan som laddar batterierna ordentligt.', category: 'Guide', date: '2026-07-28', readTime: '9 min', emoji: '⚓', tags: ['Weekend', 'Helgresa', 'Stockholm', 'Planering'] },
  { slug: 'sandhamn-guide-2026', title: 'Sandhamn guide – båt dit, Trouville, mat, boende och historia', excerpt: 'Allt om Sandhamn i Stockholms skärgård: båt från Strömkajen, Strandvägen och Stavsnäs med restider, Trouville och Sandhamnsstigen, restauranger och boende, Grönskärs fyr och öns historia som lotsplats.', category: 'Öguide', date: '2026-07-28', readTime: '8 min', emoji: 'sailboat', tags: ['Sandhamn', 'Guide', 'Restauranger', 'Segling'] },
  { slug: 'boende-skargard-2026', title: 'Boende i skärgården 2026 – stugor, gästhamnar och camping', excerpt: 'Ska du övernatta i skärgården? Här är en genomgång av alla alternativ — från lyxig värdshussvit till tält på klippan — med konkreta råd om vad som passar vem.', category: 'Praktiskt', date: '2026-07-28', readTime: '7 min', emoji: '🏕', tags: ['Boende', 'Stuga', 'Camping', 'Övernattning'] },
  { slug: 'skargard-med-hund', title: 'Skärgård med hund – regler, båten och öar att besöka', excerpt: 'Ta med hunden till Stockholms skärgård: när hunden ska vara kopplad enligt Naturvårdsverket, vad som gäller i naturreservat, hund på Waxholmsbåten, hundbad och öar att besöka.', category: 'Guide', date: '2026-07-28', readTime: '6 min', emoji: '🐕', tags: ['Hund', 'Hundvänlig', 'Regler', 'Allemansrätten'] },
  { slug: 'vandring-skargard-guide', title: 'Vandring i Stockholms skärgård 2026 – de 8 bästa lederna', excerpt: 'Stockholms skärgård är inte bara vatten. De bästa lederna tar dig genom urbergslandskap, längs klippkuster och över bilfria öar. Här är åtta vandringar du faktiskt kan genomföra.', category: 'Aktiviteter', date: '2026-07-28', readTime: '8 min', emoji: '🥾', tags: ['Vandring', 'Leder', 'Natur', 'Friluftsliv'] },
  { slug: 'naturhamnar-stockholm-skargard', title: 'Bästa naturhamnarna i Stockholms skärgård 2026 – seglares guide', excerpt: 'De bästa platserna att ankra för natten är sällan i en gästhamn. Här är de naturhamnar i Stockholms skärgård som seglare pratar om — med djup, vindskydd och vad du behöver veta.', category: 'Segling', date: '2026-07-28', readTime: '7 min', emoji: '⚓', tags: ['Naturhamn', 'Segling', 'Ankring', 'Båt'] },
  { slug: 'grinda-guide-2026', title: 'Grinda guide – båt dit, Wärdshuset, gästhamn och bad', excerpt: 'Allt om Grinda i Stockholms skärgård: Waxholmsbåten från Strömkajen, Grinda Wärdshus och Framfickan, gästhamnen med 28 bokningsbara platser, bad vid Källviken, natur- och kulturstigen och reglerna i naturreservatet.', category: 'Öguide', date: '2026-07-28', readTime: '6 min', emoji: '🌿', tags: ['Grinda', 'Värdshus', 'Gästhamn', 'Guide'] },
  { slug: 'basta-utflykter-skargard-2026', title: 'De 12 bästa utflykterna i Stockholms skärgård 2026', excerpt: 'Från 25-minutersdagsturen till Fjäderholmarna till weekendäventyret på Sandhamn — tolv utflykter i Stockholms skärgård rangordnade efter tid, svårighetsgrad och upplevelse.', category: 'Inspiration', date: '2026-07-28', readTime: '10 min', emoji: '🗺', tags: ['Utflykter', 'Tips', 'Stockholm', '2026', 'Inspiration'] },

  // ── Säsongsredaktionella artiklar (2026) ──────────────────────────────────
  { slug: 'host-i-skargarden-2026', title: 'Höst i skärgården – öar du når med båt i september och oktober', excerpt: 'Skärgården på hösten: öarna med båt året runt (Sandhamn, Grinda, Utö, Vaxholm), var du kan äta och bo efter högsäsongen, bastun och nationalparken på Bullerö och vad som stänger i augusti och september.', category: 'Inspiration', date: '2026-07-27', readTime: '6 min', emoji: '🍂', tags: ['Höst', 'September', 'Säsong', 'Tips'] },
  { slug: 'dagstur-skargard-fyra-timmar', title: 'Dagstur till skärgården på 4 timmar – 6 konkreta förslag från Stockholm', excerpt: 'Inget eget fartyg, inget tält, inga dagar ledigt. Bara en förmiddag och en retur med Waxholmsbåten. Här är sex rutter som faktiskt fungerar.', category: 'Guide', date: '2026-07-27', readTime: '7 min', emoji: '⏱', tags: ['Dagstur', 'Stockholm', 'Kollektivt', 'Planering'] },
  { slug: 'eftersasong-skargard-oktober', title: 'Öppet i skärgården efter säsong – mat, båtar, bränsle och boende', excerpt: 'Vad har öppet i Stockholms skärgård i oktober och vintern? Lista med källa: pubar och butiker som har öppet året runt, båtlinjer som går hela året, sjömackar med automat och vandrarhem som tar emot gäster efter sommaren.', category: 'Praktiskt', date: '2026-07-27', readTime: '5 min', emoji: '🌿', tags: ['Oktober', 'Höst', 'Eftersäsong', 'Öppettider'] },
  { slug: 'skargard-barnfamilj-sommar-2026', title: 'Skärgård med barnfamilj sommaren 2026 – de 7 bästa öarna', excerpt: 'Sandstrand, grunt vatten, direktbåt och restaurang som faktiskt fungerar med barn. Vi har rangordnat de bästa alternativen för barnfamiljer i Stockholms skärgård sommaren 2026.', category: 'Familj', date: '2026-07-27', readTime: '8 min', emoji: '👨‍👩‍👧', tags: ['Barnfamilj', 'Sommar', 'Barn', '2026'] },
]
