export type PostMeta = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  emoji: string
  tags: string[]
}

export const POSTS_META: PostMeta[] = [
  { slug: 'basta-restaurangerna-sandhamn', title: 'De 5 bästa restaurangerna på Sandhamn 2026', excerpt: 'Sandhamn är seglingscentrum och skärgårdsklassiker. Men vilka ställen är verkligen värda ett besök? Vi har testat allt från bryggserveringar till seglarhotellets kök.', category: 'Mat & dryck', date: '2026-04-10', readTime: '5 min', emoji: '🍽', tags: ['Sandhamn', 'Restauranger', 'Sommar'] },
  { slug: 'kajak-stockholms-skargard-nybörjare', title: 'Kajak i skärgården – guide för nybörjaren', excerpt: 'Aldrig paddlat men vill prova? Här är allt du behöver veta: utrustning, säkerhet, bra startsträckor och vad du inte får missa längs vägen.', category: 'Aktiviteter', date: '2026-03-28', readTime: '8 min', emoji: '🛶', tags: ['Kajak', 'Nybörjare', 'Paddling'] },
  { slug: 'dolda-parlor-moja', title: 'Möjas dolda pärlor – bilfri ö med äkta skärgårdsstämning', excerpt: 'Möja är en av skärgårdens bäst bevarade hemligheter. Bilfri, lugn och genuint vacker. Vi visar dig vad som gör ön unik – och var du ska äta.', category: 'Öguide', date: '2026-03-15', readTime: '6 min', emoji: '🏝', tags: ['Möja', 'Bilfri ö', 'Skärgård'] },
  { slug: 'bransle-ankring-skargard', title: 'Bränsle och ankringsplatser i ytterskärgården', excerpt: 'Planerar du en längre tur mot Landsort eller Sandhamn? Här är en komplett genomgång av bränslehamnar, naturhamnar och tjänstehamnar längs vägen.', category: 'Praktiskt', date: '2026-03-01', readTime: '7 min', emoji: '⛽', tags: ['Bränsle', 'Ankring', 'Planering'] },
  { slug: 'sommar-skargard-tips', title: '10 saker du måste göra i skärgården i sommar', excerpt: 'Från gryningsfika vid en klippa till kvällsseglingen med solnedgång. Vår lista över årets bästa skärgårdsupplevelser.', category: 'Inspiration', date: '2026-02-14', readTime: '4 min', emoji: '☀️', tags: ['Sommar', 'Tips', 'Inspiration'] },
  { slug: 'fjaderholmarna-dagstur', title: 'Fjäderholmarna – perfekt dagstur från Stockholm', excerpt: 'Bara 25 minuter från Strandvägen och du är i skärgården. Fjäderholmarna är den perfekta introduktionen – krogen, hantverksgallerierna och det blå vattnet.', category: 'Öguide', date: '2026-01-30', readTime: '5 min', emoji: '⛴', tags: ['Fjäderholmarna', 'Dagstur', 'Stockholm'] },
  { slug: 'vaxholm-guide', title: 'Vaxholm – skärgårdsstadens kompletta guide', excerpt: 'Vaxholm är porten till skärgården. En stad med fästning, historia, fantastiska restauranger och direktbåt från Strömkajen. Allt du behöver veta.', category: 'Öguide', date: '2026-04-05', readTime: '6 min', emoji: '🏰', tags: ['Vaxholm', 'Fästning', 'Dag- eller weekendtur'] },
  { slug: 'uto-guide', title: 'Utö – södra skärgårdens kronjuvel', excerpt: 'Utö har allt: cykelleder, gruvhistoria, havsbastu, topprestaurang och fantastiska naturhamnar. Så här planerar du din tur dit.', category: 'Öguide', date: '2026-03-22', readTime: '7 min', emoji: '🚲', tags: ['Utö', 'Cykling', 'Havsbastu'] },
  { slug: 'segling-nybörjare-guide', title: 'Segla för första gången – allt du behöver veta', excerpt: 'Drömmer du om att ta ut en segelbåt i skärgården? Här är en ärlig guide för den som aldrig seglat: kurser, hyrbåtar, leder och de vanligaste misstagen.', category: 'Aktiviteter', date: '2026-03-18', readTime: '9 min', emoji: '⛵', tags: ['Segling', 'Nybörjare', 'Hyrbåt'] },
  { slug: 'basta-badplatserna', title: 'De 12 bästa badplatserna i Stockholms skärgård', excerpt: 'Klippbad, sandstrand eller bastu vid vattnet? Vi har listat de absolut bästa badplatserna – från lättillgängliga dagsturmål till dolda pärlor ute i ytterskärgården.', category: 'Aktiviteter', date: '2026-04-08', readTime: '6 min', emoji: '🏊', tags: ['Bad', 'Badplatser', 'Sommar'] },
  { slug: 'vandring-orno-uto', title: 'Vandring i skärgården – bästa lederna på Ornö och Utö', excerpt: 'Stockholms skärgård är inte bara vatten. Ornö och Utö har markerade leder genom urbergslandskap och gammal skog som är värda varje steg.', category: 'Aktiviteter', date: '2026-02-28', readTime: '7 min', emoji: '🥾', tags: ['Vandring', 'Ornö', 'Utö', 'Natur'] },
  { slug: 'cykling-moja-gallno', title: 'Cykla i skärgården – guide för Möja och Gällnö', excerpt: 'Bilfria öar är perfekta för cykling. Hyr en cykel vid bryggan, packa en matsäck och utforska hela ön på ett par timmar. Här är de bästa öarna.', category: 'Aktiviteter', date: '2026-02-20', readTime: '5 min', emoji: '🚴', tags: ['Cykling', 'Möja', 'Gällnö', 'Bilfri ö'] },
  { slug: 'fiske-skargard-guide', title: 'Fiske i skärgården – leder, arter och bästa säsonger', excerpt: 'Abborre, gädda och havsöring väntar i skären. En komplett guide till sportfiske i Stockholms skärgård – var du fiskar, när och vad du behöver.', category: 'Aktiviteter', date: '2026-02-10', readTime: '8 min', emoji: '🎣', tags: ['Fiske', 'Sportfiske', 'Skärgård'] },
  { slug: 'gasthamnar-guide', title: 'Bästa gästhamnarna i Stockholms skärgård 2026', excerpt: 'Vi har besökt och betygsatt de 10 bästa gästhamnarna. Service, läge, faciliteter och pris – allt samlat i en guide för dig som planerar sommarens båttur.', category: 'Praktiskt', date: '2026-01-25', readTime: '8 min', emoji: '⚓', tags: ['Gästhamn', 'Båt', 'Övernattning'] },
  { slug: 'vinter-skargard', title: 'Skärgård på vintern – upplev islugnet', excerpt: 'De flesta undviker skärgården på vintern. Det är ett misstag. Stillheten, isfiskarna och de tomma bryggorna är en helt annan och fantastisk upplevelse.', category: 'Inspiration', date: '2025-12-15', readTime: '5 min', emoji: '❄️', tags: ['Vinter', 'Lugn', 'Skärgård'] },
  { slug: 'barnfamilj-skargard', title: 'Skärgård med barnfamilj – 8 tips för en lyckad tur', excerpt: 'Att ta ut hela familjen i skärgården kräver lite planering. Här är de bästa öarna, säkraste badplatserna och restaurangerna som faktiskt fungerar med barn.', category: 'Familj', date: '2026-01-15', readTime: '6 min', emoji: '👨‍👩‍👧‍👦', tags: ['Barnfamilj', 'Barn', 'Planering'] },
  { slug: 'svenska-hoar-sandhamn', title: 'Svenska Högarna – den yttersta förposten', excerpt: 'Längst ut i ytterskärgården: klippor, hav och en av skärgårdens absolut finaste naturupplevelser utan restauranger eller handel.', category: 'Öguide', date: '2026-03-05', readTime: '5 min', emoji: '🪨', tags: ['Svenska Högarna', 'Ytterskärgård', 'Naturreservat'] },
  { slug: 'grilla-naturhamn', title: 'Grilla i naturhamnen – regler, tips och bästa platser', excerpt: 'Vad gäller egentligen vid eldning i skärgården? Vi reder ut allemansrätten, när eldningsförbud gäller och de bästa platserna att grilla när reglerna tillåter.', category: 'Praktiskt', date: '2026-02-05', readTime: '5 min', emoji: '🔥', tags: ['Grill', 'Eldning', 'Allemansrätten'] },
  { slug: 'norrtelje-norra-skargard', title: 'Norra skärgården – Norrtelje och Singö', excerpt: 'Norrtäljes skärgård är mer rå och orörd än Stockholms. Singö, Väddö och Räfsnäs är ett annat tempo – lugnt, genuint och fortfarande inte turistifierat.', category: 'Öguide', date: '2026-01-20', readTime: '6 min', emoji: '🌊', tags: ['Norra skärgården', 'Norrtelje', 'Singö'] },
  { slug: 'packlista-bat', title: 'Packlista för båtturen – det du inte får glömma', excerpt: 'Oavsett om du tar ut en dagsbåt eller planerar en vecka i skärgården finns det saker du alltid behöver ha med. Vår kompletta packlista sparar dig från en dålig tur.', category: 'Praktiskt', date: '2026-04-01', readTime: '4 min', emoji: '🎒', tags: ['Packlista', 'Utrustning', 'Säkerhet'] },
  { slug: 'havsbastu-guide', title: 'Havsbastu i skärgården – de bästa platserna 2026', excerpt: 'Ingenting slår en rykande bastu vid havet med ett dopp efteråt. Vi har listat de bästa havsbastuplatserna i Stockholms skärgård.', category: 'Aktiviteter', date: '2026-03-10', readTime: '5 min', emoji: '🧖', tags: ['Bastu', 'Havsbastu', 'Avkoppling'] },
  { slug: 'segling-klassiska-leder', title: 'Klassiska seglarleder i Stockholms skärgård', excerpt: 'Stockholmsleder, Furusundsleder och Sandhamnsleden är ryggraden i skärgårdssegling. En guide till ledernas historia, svårighetsgrad och bästa hamnarna.', category: 'Segling', date: '2026-02-25', readTime: '9 min', emoji: '🗺', tags: ['Segling', 'Leder', 'Rutter'] },
]
