export type PostMeta = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  emoji: string
  tags: string[]
}

export const POSTS_META: PostMeta[] = [
  { slug: 'basta-restaurangerna-sandhamn', title: 'Restauranger på Sandhamn – lunch, middag, kafé och bar', excerpt: 'Var du äter på Sandhamn: Värdshusets pub som är öppen året runt, Seglarhotellet, Dykarbaren, Sands, bageriet, kaféerna och barerna – säsonger, bordsbokning och båten dit.', category: 'Mat & dryck', date: '2026-04-10', readTime: '6 min', emoji: '🍽', tags: ['Sandhamn', 'Restauranger', 'Lunch', 'Kafé'] },
  { slug: 'kajak-stockholms-skargard-nyborjare', title: 'Kajak i Stockholms skärgård – guide för nybörjare', excerpt: 'Paddla kajak i Stockholms skärgård: var du hyr kajak, vad allemansrätten säger om att gå i land och övernatta, fågel- och sälskyddsområden, tältplatser och utrustning för säker paddling.', category: 'Aktiviteter', date: '2026-03-28', readTime: '8 min', emoji: '🛶', tags: ['Kajak', 'Nybörjare', 'Paddling'] },
  { slug: 'dolda-parlor-moja', title: 'Möja – vandring, bad, museum och mat på ön', excerpt: 'Vad du gör på Möja i Stockholms mellersta skärgård: naturstigen genom Björndalen, bad enligt allemansrätten, Roland Svensson-museet, kyrkan från 1768, var du äter och hur du tar dig dit.', category: 'Öguide', date: '2026-03-15', readTime: '6 min', emoji: 'island', tags: ['Möja', 'Bilfri ö', 'Skärgård'] },
  { slug: 'bransle-ankring-skargard', title: 'Sjömackar i Stockholms skärgård – tanka och ankra', excerpt: 'Var du tankar båten i Stockholms skärgård: sjömackar från Grisslehamn och Rödlöga i norr till Nynäshamn i söder, Kryssarklubbens råd om säker tankning och vad allemansrätten säger om att ankra.', category: 'Praktiskt', date: '2026-03-01', readTime: '7 min', emoji: 'fuel', tags: ['Bränsle', 'Ankring', 'Planering'] },
  { slug: 'sommar-skargard-tips', title: 'Sommar i skärgården – bad, vandring, tält och kajak', excerpt: 'Tio saker att göra i Stockholms skärgård på sommaren: sandstrand, en etapp av Stockholm Archipelago Trail, kajak, sälsafari, bastu, fyr och dansbana – och reglerna för tält, eld och hund.', category: 'Inspiration', date: '2026-02-14', readTime: '4 min', emoji: 'sun', tags: ['Sommar', 'Tips', 'Inspiration'] },
  { slug: 'fjaderholmarna-dagstur', title: 'Fjäderholmarna dagstur – båt, mat och vad du gör på ön', excerpt: 'Dagstur till Fjäderholmarna från Stockholm: vilka båtar som går och hur lång tid det tar, Rökeriet, krogen och bryggeriet, hantverkarna, bad från klipporna och öarnas historia.', category: 'Öguide', date: '2026-01-30', readTime: '5 min', emoji: '⛴', tags: ['Fjäderholmarna', 'Dagstur', 'Stockholm'] },
  { slug: 'vaxholm-guide', title: 'Vaxholm dagstur – kastellet, staden och båt från Strömkajen', excerpt: 'Dagstur till Vaxholm: båt från Strömkajen eller buss 670, Vaxholms kastell och museet, kyrkan, Rindö redutt och Oscar-Fredriksborg, Bogesundslandet och var du äter vid hamnen.', category: 'Öguide', date: '2026-04-05', readTime: '6 min', emoji: 'building', tags: ['Vaxholm', 'Fästning', 'Dag- eller weekendtur'] },
  { slug: 'uto-guide', title: 'Utö guide – gruvorna, cykel, bad och båt från Årsta brygga', excerpt: 'Allt om Utö i Stockholms södra skärgård: Waxholmsbåten från Årsta brygga, gruvorna och väderkvarnen från 1791, cykeluthyrning, bad vid Ålö Storsand och Rävstavik, Utö Värdshus, gästhamnen och reglerna i naturreservatet.', category: 'Öguide', date: '2026-03-22', readTime: '7 min', emoji: '🚲', tags: ['Utö', 'Cykling', 'Havsbastu'] },
  { slug: 'segling-nyborjare-guide', title: 'Börja segla – så lär du dig segla i skärgården', excerpt: 'Så börjar du segla: seglarskola för vuxna, Seglarintyg 1 och 2, vilka krav som gäller för att köra fritidsbåt, de viktigaste väjningsreglerna och hur du hyr en segelbåt i Stockholms skärgård.', category: 'Aktiviteter', date: '2026-03-18', readTime: '9 min', emoji: 'sailboat', tags: ['Segling', 'Nybörjare', 'Hyrbåt'] },
  { slug: 'basta-badplatserna', title: 'Badplatser i Stockholms skärgård – sandstränder och klippbad', excerpt: 'Sandstränder, klippbad och havsbad i Stockholms skärgård: Trouville på Sandhamn, Björnö och Ingarö, Vaxholmsöarna och bad du når med Roslagsbanan, Saltsjöbanan eller buss. Fakta från kommunerna och Havs- och vattenmyndigheten.', category: 'Aktiviteter', date: '2026-04-08', readTime: '6 min', emoji: '🏊', tags: ['Bad', 'Badplatser', 'Sommar'] },
  { slug: 'vandring-orno-uto', title: 'Vandring på Ornö och Utö – etapper, slingor och båt', excerpt: 'Vandra på Ornö och Utö: Stockholm Archipelago Trails etapper på 34,1 och 18,4 km, var de börjar, Sundbyslingan, leden vidare till Ålö, bussen på Ornö och båtarna från Dalarö och Årsta brygga.', category: 'Aktiviteter', date: '2026-02-28', readTime: '7 min', emoji: '🥾', tags: ['Vandring', 'Ornö', 'Utö', 'Natur'] },
  { slug: 'cykling-moja-gallno', title: 'Hyra cykel på Möja och Gällnö – cykla i skärgården', excerpt: 'Var du hyr cykel på Möja och Gällnö, hur långa öarna är, var du badar och äter längs vägen och hur du tar dig dit med båt från Stockholm.', category: 'Aktiviteter', date: '2026-02-20', readTime: '5 min', emoji: '🚴', tags: ['Cykling', 'Möja', 'Gällnö', 'Bilfri ö'] },
  { slug: 'fiske-skargard-guide', title: 'Fiske i Stockholms skärgård – arter, platser och regler', excerpt: 'Abborre, gädda, gös, havsöring och sik i Stockholms skärgård: när och var de biter enligt Länsstyrelsens fiskeguide, var handredskapsfisket är fritt och vilka mått och fångstgränser som gäller.', category: 'Aktiviteter', date: '2026-02-10', readTime: '8 min', emoji: 'fish', tags: ['Fiske', 'Sportfiske', 'Skärgård'] },
  { slug: 'gasthamnar-guide', title: 'Gästhamnar i Stockholms skärgård – platser, service och bokning', excerpt: 'Gästhamnar i Stockholms skärgård från Grisslehamn till Nåttarö: antal gästplatser, djup, förtöjning, service och om platsen går att boka – hämtat från hamnarnas egna sidor.', category: 'Praktiskt', date: '2026-01-25', readTime: '8 min', emoji: 'anchor', tags: ['Gästhamn', 'Båt', 'Övernattning'] },
  { slug: 'vinter-skargard', title: 'Skärgården på vintern – båtar, is och vad som är öppet', excerpt: 'Vinter i Stockholms skärgård: Waxholmsbåtar året runt till Sandhamn, Möja och Utö, boenden och butiker med vinteröppet, och vad SMHI och Sjöräddningssällskapet säger om isen.', category: 'Inspiration', date: '2025-12-15', readTime: '5 min', emoji: 'snow', tags: ['Vinter', 'Lugn', 'Skärgård'] },
  { slug: 'barnfamilj-skargard', title: 'Skärgård med barn – flytväst, säkerhet och båtvett', excerpt: 'Barn i båten och vid vattnet i skärgården: vilken flytväst barn ska ha enligt Transportstyrelsen och Sjöräddningssällskapet, råd för små barn ombord, badvett, båtvett och 112.', category: 'Familj', date: '2026-01-15', readTime: '6 min', emoji: '👨‍👩‍👧‍👦', tags: ['Barnfamilj', 'Barn', 'Planering'] },
  { slug: 'svenska-hoar-sandhamn', title: 'Svenska Högarna – naturreservat längst ut i skärgården', excerpt: 'Svenska Högarna i Norrtälje kommun är Sveriges största marina naturreservat, cirka 19 nautiska mil öster om Möja. Så når du ögruppen, var du lägger till och vilka regler som gäller.', category: 'Öguide', date: '2026-03-05', readTime: '5 min', emoji: 'rock', tags: ['Svenska Högarna', 'Ytterskärgård', 'Naturreservat'] },
  { slug: 'grilla-naturhamn', title: 'Grilla i naturhamnen – eldningsregler i skärgården', excerpt: 'Får du grilla i naturhamnen? Allemansrättens regler för eldning, hur du tar reda på om det är eldningsförbud i Stockholms län och vad som gäller i naturreservat som Grinda, Finnhamn och Nåttarö.', category: 'Praktiskt', date: '2026-02-05', readTime: '5 min', emoji: '🔥', tags: ['Grill', 'Eldning', 'Allemansrätten'] },
  { slug: 'norrtelje-norra-skargard', title: 'Norrtälje skärgård – Arholma, Lidö, Väddö och Singö', excerpt: 'Norra skärgården i Norrtälje kommun: båt från Norrtälje hamn och Räfsnäs, Arholma och Lidö, Furusund och Blidö, Väddö kanal, Grisslehamn och Singö – med bad och gästhamnar enligt kommunen.', category: 'Öguide', date: '2026-01-20', readTime: '6 min', emoji: 'water', tags: ['Norra skärgården', 'Norrtelje', 'Singö'] },
  { slug: 'packlista-bat', title: 'Packlista för båten – bra saker att ha ombord', excerpt: 'Bra saker att ha i båten: säkerhetsutrustning, navigation, verktyg, mat och kläder – en checklista för dagsturen och veckan i skärgården.', category: 'Praktiskt', date: '2026-04-01', readTime: '4 min', emoji: '🎒', tags: ['Packlista', 'Utrustning', 'Säkerhet'] },
  { slug: 'havsbastu-guide', title: 'Havsbastu i skärgården – bastur vid hamnar och öar', excerpt: 'Här finns bastu vid vattnet i Stockholms skärgård: vedeldad bastu på Bullerö, bastu att hyra i Källviken på Grinda, Kryssarklubbens uthamn på Runmarö och gästhamnar med bastu från Furusund till Nynäshamn.', category: 'Aktiviteter', date: '2026-03-10', readTime: '5 min', emoji: '🧖', tags: ['Bastu', 'Havsbastu', 'Avkoppling'] },
  { slug: 'segling-klassiska-leder', title: 'Farleder i Stockholms skärgård – guide för seglare', excerpt: 'Farlederna in mot Stockholm via Sandhamn, Landsort och Tjärven enligt Sjöfartsverket, hur du läser sjömärkena, vad som gäller för segelbåtar i trång farled och gästhamnar längs lederna.', category: 'Segling', date: '2026-02-25', readTime: '9 min', emoji: 'map', tags: ['Segling', 'Leder', 'Rutter'] },

  { slug: 'midsommar-skargarden-2026', title: 'Midsommar i skärgården 2026 – 15 alternativ', excerpt: '8 destinationer på ostkusten och 7 på västkusten. Kollektivtrafik, tips och var du äter – komplett planeringsguide.', category: 'Guide', date: '2026-05-10', readTime: '14 min', emoji: '🌸', tags: ['Midsommar', 'Skärgård', 'Guide'] },
  { slug: 'packlista-skargarden', title: 'Komplett packlista för skärgården', excerpt: 'Kläder, mat & dryck, säkerhet, teknik, barn och segling. Allt samlat i en guide du kan bocka av innan du lämnar bryggan.', category: 'Guide', date: '2026-05-05', readTime: '8 min', emoji: '📋', tags: ['Packlista', 'Förberedelse', 'Guide'] },
  { slug: 'allemansratten-pa-sjon', title: 'Allemansrätten på sjön – vad som gäller på vattnet', excerpt: 'Var får du ankra, tälta och elda? Vad gäller om toalettavfall? Enkla svar på de vanligaste frågorna om allemansrätten till sjöss.', category: 'Guide', date: '2026-05-01', readTime: '7 min', emoji: '⚓', tags: ['Allemansrätten', 'Regler', 'Guide'] },
  { slug: 'waxholmsbolaget-guide', title: 'Waxholmsbolaget – komplett guide till båttrafiken', excerpt: 'Hur fungerar linjerna? Vilka hållplatser gäller? Är SL-kortet giltigt? Allt om Waxholmsbolaget samlat på ett ställe.', category: 'Guide', date: '2026-04-28', readTime: '9 min', emoji: '🚢', tags: ['Waxholmsbolaget', 'Transport', 'Guide'] },
  { slug: 'skargard-utan-bat', title: 'Skärgård utan båt – 10 öar du når utan eget fartyg', excerpt: 'Bilfärja, Waxholmsbolaget och SL – 10 konkreta förslag rangordnade efter tillgänglighet för dig utan båt.', category: 'Guide', date: '2026-04-25', readTime: '10 min', emoji: '🚌', tags: ['Transport', 'Kollektivt', 'Guide'] },

  // ── Strategiska SEO-artiklar (2026) ──────────────────────────────────────
  { slug: 'weekend-skargard-stockholm', title: 'Weekend i skärgården – sju öar med boende och båt dit', excerpt: 'Weekend i Stockholms skärgård: båt, boende och vad du gör på Grinda, Sandhamn, Möja, Utö, Gällnö, Ornö och Bullerö, med restider från Stockholm och reglerna för tält i reservaten.', category: 'Guide', date: '2026-07-28', readTime: '9 min', emoji: '⚓', tags: ['Weekend', 'Helgresa', 'Stockholm', 'Planering'] },
  { slug: 'sandhamn-guide-2026', title: 'Sandhamn guide – båt dit, Trouville, mat, boende och historia', excerpt: 'Allt om Sandhamn i Stockholms skärgård: båt från Strömkajen, Strandvägen och Stavsnäs med restider, Trouville och Sandhamnsstigen, restauranger och boende, Grönskärs fyr och öns historia som lotsplats.', category: 'Öguide', date: '2026-07-28', readTime: '8 min', emoji: 'sailboat', tags: ['Sandhamn', 'Guide', 'Restauranger', 'Segling'] },
  { slug: 'boende-skargard-2026', title: 'Boende i skärgården – vandrarhem, hotell och tältplatser', excerpt: 'Övernatta i Stockholms skärgård: STF-vandrarhem på Finnhamn, Möja, Gällnö och Svartsö, värdshus och hotell, Skärgårdsstiftelsens stugor, tältplatser och allemansrättens regler för tält.', category: 'Praktiskt', date: '2026-07-28', readTime: '7 min', emoji: '🏕', tags: ['Boende', 'Stuga', 'Camping', 'Övernattning'] },
  { slug: 'skargard-med-hund', title: 'Skärgård med hund – regler, båten och öar att besöka', excerpt: 'Ta med hunden till Stockholms skärgård: när hunden ska vara kopplad enligt Naturvårdsverket, vad som gäller i naturreservat, hund på Waxholmsbåten, hundbad och öar att besöka.', category: 'Guide', date: '2026-07-28', readTime: '6 min', emoji: '🐕', tags: ['Hund', 'Hundvänlig', 'Regler', 'Allemansrätten'] },
  { slug: 'vandring-skargard-guide', title: 'Vandring i Stockholms skärgård – leder och etapper', excerpt: 'Vandra i Stockholms skärgård: Stockholm Archipelago Trails etapper på Utö, Ålö, Ornö, Fjärdlång, Grinda, Möja och Sandhamn, kortare slingor, Bullerö och reglerna för hund, eld och tält.', category: 'Aktiviteter', date: '2026-07-28', readTime: '8 min', emoji: '🥾', tags: ['Vandring', 'Leder', 'Natur', 'Friluftsliv'] },
  { slug: 'naturhamnar-stockholm-skargard', title: 'Naturhamnar i Stockholms skärgård – regler och platser', excerpt: 'Naturhamnar i Stockholms skärgård: vad allemansrätten säger om att ankra, tvådygnsregeln i naturreservaten, Kryssarklubbens bojar och uthamnar samt naturhamnar som Länsstyrelsen pekar ut.', category: 'Segling', date: '2026-07-28', readTime: '7 min', emoji: '⚓', tags: ['Naturhamn', 'Segling', 'Ankring', 'Båt'] },
  { slug: 'grinda-guide-2026', title: 'Grinda guide – båt dit, Wärdshuset, gästhamn och bad', excerpt: 'Allt om Grinda i Stockholms skärgård: Waxholmsbåten från Strömkajen, Grinda Wärdshus och Framfickan, gästhamnen med 28 bokningsbara platser, bad vid Källviken, natur- och kulturstigen och reglerna i naturreservatet.', category: 'Öguide', date: '2026-07-28', readTime: '6 min', emoji: '🌿', tags: ['Grinda', 'Värdshus', 'Gästhamn', 'Guide'] },
  { slug: 'basta-utflykter-skargard-2026', title: 'Utflykter i Stockholms skärgård – elva öar och restider', excerpt: 'Utflykter i Stockholms skärgård: restid och vad som finns på Fjäderholmarna, Vaxholm, Grinda, Gällnö, Möja, Sandhamn, Utö, Ålö, Ornö, Fjärdlång och Bullerö, plus vilka biljetter som gäller.', category: 'Inspiration', date: '2026-07-28', readTime: '10 min', emoji: '🗺', tags: ['Utflykter', 'Tips', 'Stockholm', '2026', 'Inspiration'] },

  // ── Säsongsredaktionella artiklar (2026) ──────────────────────────────────
  { slug: 'host-i-skargarden-2026', title: 'Höst i skärgården – öar du når med båt i september och oktober', excerpt: 'Skärgården på hösten: öarna med båt året runt (Sandhamn, Grinda, Utö, Vaxholm), var du kan äta och bo efter högsäsongen, bastun och nationalparken på Bullerö och vad som stänger i augusti och september.', category: 'Inspiration', date: '2026-07-27', readTime: '6 min', emoji: '🍂', tags: ['Höst', 'September', 'Säsong', 'Tips'] },
  { slug: 'dagstur-skargard-fyra-timmar', title: 'Dagstur till skärgården – sex öar och båtarna dit', excerpt: 'Dagstur till skärgården från Stockholm utan egen båt: restid, båtar och vad som finns på Fjäderholmarna, Vaxholm, Grinda, Möja, Utö och Sandhamn, plus biljettreglerna på Waxholmsbåten.', category: 'Guide', date: '2026-07-27', readTime: '7 min', emoji: '⏱', tags: ['Dagstur', 'Stockholm', 'Kollektivt', 'Planering'] },
  { slug: 'eftersasong-skargard-oktober', title: 'Öppet i skärgården efter säsong – mat, båtar, bränsle och boende', excerpt: 'Vad har öppet i Stockholms skärgård i oktober och vintern? Lista med källa: pubar och butiker som har öppet året runt, båtlinjer som går hela året, sjömackar med automat och vandrarhem som tar emot gäster efter sommaren.', category: 'Praktiskt', date: '2026-07-27', readTime: '5 min', emoji: '🌿', tags: ['Oktober', 'Höst', 'Eftersäsong', 'Öppettider'] },
  { slug: 'skargard-barnfamilj-sommar-2026', title: 'Barnvänliga öar och bad i Stockholms skärgård', excerpt: 'Öar och bad för barnfamiljer i Stockholms skärgård: långgrunda sandstränder på Nåttarö, barnvänliga bad på Grinda, lekplatser vid Utö och Tenöbadet och barn gratis på Waxholmsbåten.', category: 'Familj', date: '2026-07-27', readTime: '8 min', emoji: '👨‍👩‍👧', tags: ['Barnfamilj', 'Sommar', 'Barn', '2026'] },
]
