export type GuideCategory = "Praktisk" | "Transport" | "Aktivitet" | "Mat" | "Säsong" | "Region"

export type FAQItem = { q: string; a: string }

export type GuideMeta = {
  slug: string
  title: string
  excerpt: string
  category: GuideCategory
  emoji: string
  readTime: string
  featured?: boolean
  fullContent?: boolean
  faqs?: FAQItem[]
}

export const GUIDES: GuideMeta[] = [
  {
    slug: "midsommar-skargarden-2026",
    title: "Midsommar i skärgården 2026 – 15 alternativ",
    excerpt: "8 destinationer på ostkusten och 7 på västkusten. Kollektivtrafik, vad du gör och var du äter – komplett planeringsguide.",
    category: "Säsong",
    emoji: "🌸",
    readTime: "14 min",
    featured: true,
    fullContent: true,
    faqs: [
      { q: 'Vad kostar det att fira midsommar på Sandhamn?', a: 'En dagstur med Cinderellabåten kostar ca 350 kr tur/retur. Boende på Sandhamn kostar 1 500–3 000 kr/natt per rum under midsommar. Räkna med att boka minst 3–4 månader i förväg för boende.' },
      { q: 'Behöver man boka biljett till Cinderellabåten på midsommaraftonen?', a: 'Ja, absolut. Cinderellabåten kör med full kapacitet midsommaraftonen och biljetter tar slut veckor i förväg. Boka via Waxholmsbolagets app eller hemsida så snart du bestämt dig.' },
      { q: 'Vilken ö är bäst för midsommar med barn?', a: 'Grinda är det bästa valet för barnfamiljer — kort restid (1h 45min), sandstrand, grunt vatten och ett genuint midsommarfirande med majstång. Alternativt Vaxholm (1h) om barnen tröttnar snabbt på resor.' },
      { q: 'Hur tidigt ska man boka boende inför midsommar i skärgården?', a: 'Minst 3–4 månader i förväg för Sandhamn, Utö och Grinda. Vaxholm och Möja är lättare att boka 4–6 veckor i förväg. Dagsturerna kräver bara biljettbokning — inget boende.' },
      { q: 'Kan man åka på dagstur utan övernattning på midsommar?', a: 'Ja, dagsturen fungerar utmärkt. Fjäderholmarna (25 min), Vaxholm (1h) och Grinda (1h 45min) är perfekta för dagstur. Kom tidigt — båtarna är fulla från lunch.' },
      { q: 'Är det skillnad på midsommar i Stockholm vs Bohuslän?', a: 'Bohuslän har klippor, räksmörgåsar och västkustkaraktär. Stockholm har de klassiska skärgårdsöarna med majstång och Waxholmsbolaget. Bohuslän är bättre för klippbad; Stockholm för öhoppning och segelbåtsatmosfär.' },
    ],
  },
  {
    slug: "packlista-skargarden",
    title: "Komplett packlista för skärgården",
    excerpt: "Kläder, mat & dryck, säkerhet, teknik, barn och segling. Allt samlat i en guide du kan bocka av innan du lämnar bryggan.",
    category: "Praktisk",
    emoji: "🎒",
    readTime: "8 min",
    fullContent: true,
    faqs: [
      { q: 'Behöver man flytväst i skärgården?', a: 'Flytväst är lagkrav för alla ombord på motordrivna fartyg och starkt rekommenderat vid paddling och segling. Barn under 15 år måste ha flytväst på sig när båten är i rörelse. Påföljd för brott mot kravet kan bli böter.' },
      { q: 'Vad är det vanligaste att glömma till skärgården?', a: 'Solskydd (UV-strålning är starkare på öppet vatten), vattentätt telefonfodral, en extra lager (det blir alltid kallare än man tror på kvällen) och kontanter (många skärgårdskrogar har instabil kortläsare).' },
      { q: 'Hur mycket vatten ska man ta med per person?', a: 'Räkna med 1 liter per person och timme i sol och värme, mer om du paddlar eller seglar aktivt. För en typisk dagstur: minst 2–3 liter per person. Sötvatten finns att fylla på vid de flesta gästhamnar men inte i naturhamnar.' },
      { q: 'Kan man hyra utrustning på öarna?', a: 'Ja, de flesta större öar (Utö, Grinda, Sandhamn, Finnhamn) hyr ut cyklar och kajaker. Dykutrustning och snorklingsset finns på ett fåtal platser. Hyra på plats är ofta billigare än att ta med egna saker på båten.' },
      { q: 'Vad ska man tänka på med packning om man åker med egna båt?', a: 'Packa i vattentäta säckar eller drybags. Tyngre saker placeras lågt och centrerat för stabiliteten. Ta med en liten dagryggsäck separat för landutflykter — du vill inte ta med hela packen varje gång du går iland.' },
    ],
  },
  {
    slug: "allemansratten-pa-sjon",
    title: "Allemansrätten på sjön – vad som gäller på vattnet",
    excerpt: "Var får du ankra, tälta och elda? Vad gäller om toalettavfall? Enkla svar på de vanligaste frågorna om allemansrätten till sjöss.",
    category: "Praktisk",
    emoji: "⚓",
    readTime: "7 min",
    fullContent: true,
    faqs: [
      { q: 'Hur länge får man ankra på samma plats?', a: 'Allemansrätten ger rätt att ankra eller lägga till på en plats i 1–2 nätter utan att be om lov. Vill du stanna längre bör du fråga markägaren. I naturreservat kan det finnas specifika regler som gäller framför allemansrätten.' },
      { q: 'Är det gratis att ankra i naturhamnar?', a: 'Ja, ankring i naturhamnar är i regel gratis via allemansrätten. Du betalar inget kajplatsavgift som du gör i gästhamnar. I vissa naturreservat finns dock avgiftspliktiga lägesplatser — kolla Länsstyrelsens webbplats för specifika reservat.' },
      { q: 'Var får man tälta i skärgården?', a: 'Du får tälta en eller ett par nätter på de flesta platser via allemansrätten. Undantag: naturreservat med tältförbud, privat tomtmark och strandskyddszon närmast bebyggelse. Kolla alltid skyltning på plats.' },
      { q: 'Vad gäller för toalettavfall på båt?', a: 'Det är förbjudet att pumpa ut orenat toalettavfall inom 12 sjömil från land i Sverige. Antingen töms tanken på en pump-out-station i gästhamn, eller används miljövänliga alternativ. Greywaste (disk- och tvättvatten) är i regel tillåtet att tömma.' },
    ],
  },
  {
    slug: "waxholmsbolaget-guide",
    title: "Waxholmsbolaget – komplett guide till båttrafiken",
    excerpt: "Hur fungerar linjerna? Vilka hållplatser gäller? Är SL-kortet giltigt? Allt om Waxholmsbolaget samlat på ett ställe.",
    category: "Transport",
    emoji: "⛴",
    readTime: "9 min",
    fullContent: true,
    faqs: [
      { q: 'Är SL-kortet giltigt på Waxholmsbolaget?', a: 'SL-kortet (månadskort, reskassa) gäller INTE på Waxholmsbolagets båtlinjer. Du behöver köpa separat biljett via Waxholmsbolagets app, hemsida eller ombord. Biljetten är prisvärd men du kan inte använda SL-appen.' },
      { q: 'Hur köper man biljett till Waxholmsbolaget?', a: 'Enklast via Waxholmsbolagets app (iOS/Android) eller på waxholmsbolaget.se. Du kan också köpa biljett ombord på båten — kontant eller kort. Ombordköp är något dyrare för sällsynta linjer.' },
      { q: 'Kan man ta med cykel på Waxholmsbolaget?', a: 'Ja, cyklar är välkomna på Waxholmsbolagets båtar. Det kostar en liten extra avgift (ca 50–80 kr beroende på linje och säsong). Cyklar lastas i fören — kontrollera kapaciteten för din specifika linje.' },
      { q: 'Hur tidigt bör man vara vid bryggan?', a: 'Räkna med att vara vid bryggan 5–10 minuter före avgång. På populära linjer under högsäsong (juli) kan båtarna bli fulla. Förboka biljett digitalt — det garanterar inte plats på alla linjer men möjliggör smidig ombordstigning.' },
      { q: 'Kör Waxholmsbolaget hela året?', a: 'Ja, men med reducerad tidtabell utanför sommarsäsongen (maj–september). Vissa linjer kör dagligen hela året, andra bara under sommarsäsongen. Kontrollera aktuell tidtabell på waxholmsbolaget.se för din linje.' },
    ],
  },
  {
    slug: "skargard-utan-bat",
    title: "Skärgård utan båt – 10 öar du når utan eget fartyg",
    excerpt: "Bilfärja, Waxholmsbolaget och SL – 10 konkreta förslag rangordnade efter tillgänglighet.",
    category: "Transport",
    emoji: "🚌",
    readTime: "10 min",
    fullContent: true,
    faqs: [
      { q: 'Kan man besöka skärgården utan egen båt?', a: 'Ja, absolut. Waxholmsbolaget trafikerar over 50 destinationer i Stockholms skärgård med reguljär båttrafik. Utö, Grinda, Vaxholm, Fjäderholmarna och Sandhamn nås enkelt utan eget fartyg.' },
      { q: 'Vilken ö är enklast att nå utan bil och båt?', a: 'Fjäderholmarna är enklast – 25 minuter med Strömma från Nybroplan/Slussen, avgångarna är täta och öppen hela sommarsäsongen. Vaxholm är näst enklast: Waxholmsbolaget och SL-buss 670 direkt från Stockholm.' },
      { q: 'Gäller SL-kortet på båtarna i skärgården?', a: 'SL-kortet gäller på Waxholmsbolagets pendelbåtslinjer inom SL-zonen (zon A+B), men INTE på de yttre öarna som Grinda, Sandhamn och Utö. För dessa krävs Waxholmsbolagets egna biljetter.' },
      { q: 'Kan man ta med cykel på Waxholmsbolagets båtar?', a: 'Ja, cykel tillåts på de flesta linjer mot en avgift på ca 60 kr tur/retur. Det är ett utmärkt sätt att utforska öar som Utö, Möja och Ingmarsö utan bil.' },
    ],
  },
  {
    slug: "vad-kostar-skargarden",
    title: "Vad kostar en dag i skärgården?",
    excerpt: "Biljetter, mat, boende – en realistisk budget för olika restyper.",
    category: "Praktisk",
    emoji: "💰",
    readTime: "5 min",
    fullContent: true,
    faqs: [
      { q: 'Vad kostar en dagstur till Grinda?', a: 'Båtbiljett tur/retur ca 400 kr. Lunch på Grinda Wärdshus ca 200–350 kr. Kajakhyrning ca 200–350 kr. Räkna totalt ca 800–1 100 kr per vuxen för en bekväm dagstur.' },
      { q: 'Vad kostar en natt i skärgården?', a: 'Vandrarhemsrum ca 350–550 kr/person. Stugor ca 800–2 500 kr/natt beroende på standard och ö. Hotellrum (Sandhamns Värdshus, Waxholms Hotell) ca 1 500–3 500 kr/natt. Tältning via allemansrätten kostar inget.' },
      { q: 'Är mat dyrare i skärgården?', a: 'Ja, räkna med 20–40% påslag jämfört med Stockholm. En enkel lunch med dryck kostar ca 175–250 kr, räksmörgås ca 185–275 kr. Ta med matsäck för att hålla nere kostnaderna – det finns picknickplatser på alla öar.' },
      { q: 'Kan man uppleva skärgården gratis?', a: 'Ja. Allemansrätten ger fri tillgång till mark och vatten. Många öar (Arholma, Möja, Svartlöga) har fria vandringsleder, badplatser och naturhamnar. Enda kostnaden är biljetten dit – och den ryms i SL-abonnemanget om du åker rätt linje.' },
    ],
  },
  { slug: "badtemperatur-skargard",      title: "Badtemperaturen i skärgården – säsong för säsong", excerpt: "När är vattnet varmt nog att bada? Månadsvis guide till havsbadets säsong.",              category: "Aktivitet", emoji: "🌡", readTime: "4 min", fullContent: true },
  {
    slug: "sl-kort-skargarden",
    title: "SL-kortet i skärgården – vad gäller?",
    excerpt: "Var är SL-kortet giltigt, var räcker det inte och vad kostar tilläggsbiljetten?",
    category: "Transport",
    emoji: "🎫",
    readTime: "4 min",
    fullContent: true,
    faqs: [
      { q: 'Gäller SL-kortet till skärgårdsöarna?', a: 'SL-kortet gäller på SL-bussarna till hamnterminaler (t.ex. buss 433 till Stavsnäs, buss 670 till Vaxholm) men INTE på Waxholmsbolagets båtlinjer ut till öarna. Du behöver separat biljett för båtresan.' },
      { q: 'Hur mycket kostar Waxholmsbolaget utöver SL-kortet?', a: 'Beroende på destination: Vaxholm ca 140 kr enkel resa, Grinda ca 200 kr, Sandhamn ca 220 kr, Utö ca 210 kr. Barn under 7 år åker gratis, 7–19 år betalar halv taxa. Köp biljett via Waxholmsbolagets app.' },
      { q: 'Finns det ett kombinerat kort för SL och Waxholmsbolaget?', a: 'Nej, det finns inget kombinerat kort. SL och Waxholmsbolaget har separata biljettsystem. Waxholmskortet (månadsabonnemang) kan vara lönsamt om du åker ofta, men är inte integrerat med SL-appen.' },
      { q: 'Gäller SL-kortet på Styrsöbolaget i Göteborg?', a: 'Styrsöbolaget i Göteborg är en del av Västtrafik, inte SL. Västtrafik-kortet gäller på Styrsöbolagets båtar till sydskärgården. SL-kortet gäller inte i Göteborg.' },
    ],
  },
  { slug: "dykning-snorkling-skargard",  title: "Dykning och snorkling i Stockholms skärgård",    excerpt: "Bästa platserna, vad du kan se och hur du hyr utrustning.",                                category: "Aktivitet", emoji: "🤿", readTime: "6 min", fullContent: true },
  { slug: "rakfrukost-skargard",         title: "Räkfrukost i skärgården – var och hur",           excerpt: "Den klassiska skärgårdsupplevelsen: nyfångad räka, majonnäs och knäckebröd vid bryggan.",  category: "Mat",       emoji: "🦐", readTime: "5 min", fullContent: true },
  { slug: "sjomatkrogar-guide",          title: "Sjömatskrogar i skärgården – bästa ställena",    excerpt: "Från Sandhamn till Smögen: restaurangerna som serverar havets bästa råvaror.",             category: "Mat",       emoji: "🦞", readTime: "7 min", fullContent: true },
  {
    slug: "hummersafari-bohuslan",
    title: "Hummersafari i Bohuslän – guide och säsonger",
    excerpt: "När öppnar hummerpremiären, var fiskar du och hur bokar du en guidad safari?",
    category: "Aktivitet",
    emoji: "🦀",
    readTime: "6 min",
    fullContent: true,
    faqs: [
      { q: 'När är hummerpremiären 2026?', a: 'Hummerpremiären 2026 är den 21 september (första måndagen efter 20 september). Fisket öppnar kl. 07.00. Fiskesäsongen löper till 30 november.' },
      { q: 'Kan vem som helst delta i hummerfiske?', a: 'Ja, du behöver bara ett sportfiskekort (gratis för fritidsfiske) och rätt utrustning. Max 6 burar per person. Hummern måste vara minst 9 cm från pannhorn till stjärt, annars ska den sättas tillbaka. Fiskelicens krävs inte utöver sportfiskekortet.' },
      { q: 'Var är bäst att fiska hummer i Bohuslän?', a: 'Kungshamn, Smögen, Lysekil, Fjällbacka och Grebbestad är klassiska hummerstäder med aktiva fiskare. Hummern lever på 5–50 meters djup längs klippkusten. De bästa fångstplatserna hålls ofta hemliga av lokala fiskare.' },
      { q: 'Hur bokar man en guidad hummersafari?', a: 'Boka via lokala fiskare och båtuthyrare i Bohuslän – exempelvis i Smögen, Kungshamn och Lysekil. Flera aktörer erbjuder paket med guidat fiske och hummerfrukost ombord. Boka i god tid – premiärveckans turer är fullbokade redan i juni.' },
    ],
  },
  {
    slug: "surstrommning-guide",
    title: "Surströmming – guide till den svenska traditionen",
    excerpt: "Historia, smakupplevelsen, hur du beställer och var du avnjuter den.",
    category: "Mat",
    emoji: "🐟",
    readTime: "5 min",
    fullContent: true,
    faqs: [
      { q: 'När är surströmmingspremiären?', a: 'Surströmmingspremiären firas traditionellt den tredje torsdagen i augusti. 2026 är det 20 augusti. Från och med den dagen är det tillåtet att sälja årets surströmming, och festivaler arrangeras längs norrlandskusten.' },
      { q: 'Hur äter man surströmming?', a: 'Traditionellt på tunnbröd med mandelpotatis, rödlök, crème fraîche och gräslök. Öppna burken utomhus (och helst under vatten) – trycket inne i burken kan spruta fiskspad. Serveras med kall öl eller snaps.' },
      { q: 'Var kan man köpa surströmming?', a: 'På välsorterade mataffärer och livsmedelsbutiker i norra Sverige från premiären i augusti. ICA och Coop har ofta surströmming i hela landet från slutet av augusti. Online-beställning fungerar via specialbutiker.' },
      { q: 'Varför luktar surströmming så starkt?', a: 'Fisken fermenteras i 6–12 månader i saltlake, vilket skapar flyktiga svavelföreningar. Lukten är betydligt starkare än smaken – de flesta som faktiskt smakar upplever att det är mer hanterbart än ryktet säger.' },
    ],
  },
  {
    slug: "skargard-host",
    title: "Skärgården på hösten – varför höst är bäst",
    excerpt: "Tomma öar, lövfärger och svamp – höstens argument för en skärgårdstur.",
    category: "Säsong",
    emoji: "🍂",
    readTime: "5 min",
    fullContent: true,
    faqs: [
      { q: 'Vilka öar är bäst på hösten i skärgården?', a: 'Utö, Ornö och Möja håller öppet längre på hösten än de flesta öar. Arholma och Svartlöga är fantastiska för höstvandring. Vaxholm fungerar hela hösten med stadsliv och öppna restauranger.' },
      { q: 'Kör Waxholmsbolaget på hösten?', a: 'Ja, men med reducerad tidtabell från september. Inneröarna (Vaxholm, Grinda) trafikeras dagligen. Ytterligare avlägsna öar kan ha sällsynta avgångar eller bara helgtrafik. Kontrollera tidtabellen på waxholmsbolaget.se inför varje resa.' },
      { q: 'Är det möjligt att bada i skärgården på hösten?', a: 'Vattnet håller 16–18°C i september och 12–14°C i oktober. Det är möjligt men friskt. Bastur finns på flera öar (Utö har havsbastu) och är en höjdpunkt på höstens skärgårdstur.' },
      { q: 'Vad ska man göra i skärgården på hösten?', a: 'Svampplockning (karl-johan och kantarell är vanliga), vandring utan folkmassor, havsbastu och att se lövfärgerna spegelbilden i havet. Rådjuren syns oftare på hösten. Ta med fiskespö – abborre och havsöring fiskas hela hösten.' },
    ],
  },
  { slug: "midsommar-bohuslan",          title: "Midsommar i Bohuslän – 7 alternativ",             excerpt: "Klippor, sillmåltider och midsommarstång vid havet på västkusten.",                       category: "Säsong",    emoji: "🌼", readTime: "8 min", fullContent: true },
  { slug: "sandhamn-vs-grinda",          title: "Sandhamn vs Grinda – vilken ö passar dig?",       excerpt: "Två skärgårdsklassiker med helt olika karaktär. En ärlig jämförelse.",                    category: "Region",    emoji: "⚖", readTime: "5 min", fullContent: true },
  {
    slug: "gotland-vs-oland",
    title: "Gotland vs Öland – stor semesterguide",
    excerpt: "Kalkstenraukar mot Alvaret, rosévin mot glasbruken. Vilken ö är rätt för dig?",
    category: "Region",
    emoji: "🗺",
    readTime: "8 min",
    fullContent: true,
    faqs: [
      { q: 'Vilken är bättre – Gotland eller Öland?', a: 'Det beror på vad du söker. Gotland är bäst för historia, matscen och Visby-stämning. Öland är bättre för cykling, barnfamiljer med bil och ett lugnare tempo. Gotland kräver färja; Öland nås direkt med bil via Ölandsbron.' },
      { q: 'Är Gotland dyrare än Öland?', a: 'Ja, Gotland är generellt dyrare. Färjan kostar 400–900 kr/person, boende i Visby är 20–30% dyrare än Ölands alternativ. Öland är ett prisvärdare val, särskilt för barnfamiljer med bil.' },
      { q: 'Vilket är bäst för barnfamiljer?', a: 'Öland har ett litet övertag: bilfri tillgång via Ölandsbron, Böda sand (20 km sandstrand) och cykelbanor längs hela ön. Gotland har också mycket för barn men kräver mer planering med färja och bil.' },
      { q: 'Hur lång är säsongen?', a: 'Gotland har en kort intensiv säsong (maj–september) med juli som absolut högsäsong. Öland är tillgängligt hela året via bron och har öppna sevärdheter även under höst och vinter.' },
    ],
  },
  {
    slug: "marstrand-guide",
    title: "Marstrand – komplett guide till fästningsstaden",
    excerpt: "Bilbåt, fästning, regatta och Marstrands bästa restauranger.",
    category: "Region",
    emoji: "🏰",
    readTime: "7 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Marstrand?', a: 'Kör till Koön (ca 6 mil norr om Göteborg) och ta bilbåten de sista 5 minuterna till Marstrand. Bilbåten går kontinuerligt och är kostnadsfri. Marstrand är bilfritt på ön.' },
      { q: 'Vad kostar det att besöka Carlstens fästning?', a: 'Inträde till Carlstens fästning kostar ca 100 kr/vuxen, ca 50 kr/barn. Guidade turer ingår under sommarsäsongen och ger en levande bild av fästningens historia.' },
      { q: 'När är Marstrandsregattan?', a: 'Marstrand Race Week hålls varje år i juli – det är en av Skandinaviens största segelregattor. Under regattaveckan är Marstrand extra folkfyllt, boka boende i god tid.' },
      { q: 'Vad är bäst att äta i Marstrand?', a: 'Räksmörgåsen vid kajen är ett måste. Marstrands restauranger lägger stor vikt vid lokalt fångad skaldjur – hummer, ostron och räkor dominerar menyn under säsongen.' },
    ],
  },
  { slug: "smogen-guide",                title: "Smögen – guide till klippornas stad",              excerpt: "Smögenbryggan, räksmörgåsen och klipporna – allt du behöver veta om Smögen.",             category: "Region",    emoji: "🦐", readTime: "6 min", fullContent: true },
  { slug: "naturhamnar-guide",           title: "Bästa naturhamnarna i Stockholms skärgård",       excerpt: "Ankringsplatser med svängrum, vindskydd och vacker natur. Vår topplista.",                 category: "Praktisk",  emoji: "⚓", readTime: "7 min", fullContent: true },
  {
    slug: "bohuslan-skargard-guide",
    title: "Bohuslän – guide till västkustens skärgård",
    excerpt: "Från Göteborg till Kosterfjorden: öar, hamnar, mat och transport.",
    category: "Region",
    emoji: "🌊",
    readTime: "10 min",
    fullContent: true,
    faqs: [
      { q: 'Vad är Bohuslän känt för?', a: 'Bohuslän är känt för hav, klippor, skaldjur och pittoreska fisklägen. Höjdpunkterna är Kosteröarna, Grebbestad (ostron och hummer), Smögen, Fjällbacka och Marstrand.' },
      { q: 'Hur tar man sig till Bohuslän utan bil?', a: 'Västtrafik kör bussar och tåg längs kusten. Från Göteborg tar det ca 1–1,5 timme med buss till Lysekil eller Smögen. Kosteröarna nås med färja från Strömstad.' },
      { q: 'Vilken är bästa årstiden för Bohuslän?', a: 'Juli–augusti för sol och bad. September för hummerpremieren (21 sep) och ostronstängning utan folkmassor. Oktober–november för stillhet och höststämning vid klipporna.' },
      { q: 'Är Bohuslän bättre än Stockholms skärgård?', a: 'Det beror på vad du söker. Bohuslän erbjuder vildare klippmiljöer, Västerhavet och Nordens bästa skaldjur. Stockholms skärgård har fler öar (ca 30 000), bättre kollektivtrafik och ett mer varierat landskap.' },
    ],
  },
  { slug: "norrtelje-guide",             title: "Norrtälje – porten till norra skärgården",        excerpt: "Stad, sommarmarknad och norra skärgårdens fridfulla öar. En helgguide.",                  category: "Region",    emoji: "⛵", readTime: "6 min", fullContent: true },
  {
    slug: "fjaderholmarna-guide",
    title: "Fjäderholmarna – dagstur 25 minuter från stan",
    excerpt: "Hur du tar dig dit, vad du gör och äter. Perfekt introduktion till skärgårdslivet.",
    category: "Region",
    emoji: "⛴",
    readTime: "5 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Fjäderholmarna?', a: 'Med Strömma från Nybroplan eller Slussen, tar ca 25 minuter. Avgångarna är täta under sommarsäsongen (maj–september). Waxholmsbolaget trafikerar också Fjäderholmarna från Strömkajen.' },
      { q: 'Kostar det att åka till Fjäderholmarna?', a: 'Biljetten med Strömma kostar ca 120–150 kr tur/retur. Det är inte inkluderat i SL-kortet. Entrén till ön är gratis.' },
      { q: 'Är Fjäderholmarna bra med barn?', a: 'Ja, Fjäderholmarna är ett av Stockholms bästa barnalternativ i skärgården. Närheten till stan, korta båtresan och aktiviteterna (hantverk, akvariet Estrange, glass) gör det till en perfekt familjedagstur.' },
      { q: 'När är Fjäderholmarna öppet?', a: 'Säsongen är maj–september. Under höst och vinter går begränsad trafik och de flesta restauranger och butiker är stängda.' },
    ],
  },
  { slug: "weekend-i-skargarden",        title: "En hel weekend i skärgården – så planerar du",    excerpt: "Vad packar du, var bor du och hur strukturerar du dagarna för maximal upplevelse?",       category: "Praktisk",  emoji: "🏕", readTime: "9 min", fullContent: true },
  { slug: "basta-oar-stockholms-skargard", title: "De 15 bästa öarna i Stockholms skärgård",      excerpt: "Från lättillgängliga Fjäderholmarna till avlägsna Svenska Högarna. Rankad lista.",         category: "Region",    emoji: "🏝", readTime: "10 min", fullContent: true },
  {
    slug: "vaxholm-guide-komplett",
    title: "Vaxholm – den kompletta guiden",
    excerpt: "Fästning, restauranger, shopping och hur du tar dig dit med Waxholmsbolaget.",
    category: "Region",
    emoji: "🏰",
    readTime: "8 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Vaxholm?', a: 'Pendelbåt 83/83X från Strömkajen tar ca 55 min. SL-buss 670 från Tekniska Högskolan T-bana tar ca 50 min och ingår i SL-abonnemanget. Med bil via E18 och Vaxholmsvägen tar det ca 40 min.' },
      { q: 'Är SL-kortet giltigt till Vaxholm?', a: 'SL-kortet gäller för bussresan (linje 670), men INTE på Waxholmsbolagets pendelbåt. Pendelbåten kräver separat biljett via Waxholmsbolagets app eller hemsida.' },
      { q: 'Vad gör man i Vaxholm på en dag?', a: 'Besök Vaxholms fästning (museum, guidade turer), promenera längs Hamngatan med sina trävillor, ät lunch på Waxholms Hotell med havsvy och utforska de lokala butikerna. Räkna med 4–6 timmar för en bekväm dagstur.' },
      { q: 'Är Vaxholms fästning värd ett besök?', a: 'Ja. Fästningen är ett av Stockholms läns bäst bevarade historiska monument från 1500-talet och har fantastisk utsikt över Mysingen. Nås med en liten roddbåt från hamnen (ca 20 kr). Öppen maj–september.' },
      { q: 'Kan man äta gott i Vaxholm?', a: 'Ja. Waxholms Hotell har en av skärgårdens bästa restauranger med havsvy. Hembygdsgårdens café serverar traditionell skärgårdsmat. Det finns även flera bagerier och caféer längs Hamngatan.' },
    ],
  },
  { slug: "landsort-guide",              title: "Landsort – skärgårdens sydligaste utpost",        excerpt: "Fyren, det unika klimatet och stillheten längst ut i södra ytterskärgården.",             category: "Region",    emoji: "🏮", readTime: "6 min", fullContent: true },
  {
    slug: "hyrbat-guide",
    title: "Hyra båt i skärgården – allt du behöver veta",
    excerpt: "Licenskrav, priser, bästa hyrbåtsbolagen och vad du bör fråga innan du bokar.",
    category: "Praktisk",
    emoji: "⛵",
    readTime: "8 min",
    fullContent: true,
    faqs: [
      { q: 'Behöver man båtkörkort för att hyra båt?', a: 'Det finns inget lagkrav på båtkörkort i Sverige för de flesta fritidsbåtar. Men hyrbåtsbolag kräver vanligen att du kan uppvisa behörighet – antingen SBF/SSRS förarintyg eller ett krav om att du genomgår en introduktion. Fråga alltid det specifika bolaget.' },
      { q: 'Vad kostar det att hyra båt i skärgården?', a: 'En enkel motorbåt kostar ca 900–1 800 kr/dag. En lite större övernattningsbåt kostar 2 000–4 500 kr/dag. Segelkryssare med 4–6 bäddar kostar 3 500–8 000 kr/dag. Boka tidigt för sommarsäsongen – de bästa båtarna är fullbokade månader i förväg.' },
      { q: 'Vad ingår vanligtvis i hyrbåtspriset?', a: 'Flytvästar, navigationshjälpmedel och grundutrustning brukar ingå. Bränsle är vanligen separat (du tankar upp och betalar igen vid återlämning). Kontrollera om försäkring med självriskreducering ingår – det är ofta värt att köpa till.' },
      { q: 'Var hyres båt bäst ut i Stockholm?', a: 'Populära hyrbåtsbolag i Stockholm är Båtbörsen (Djurgårdsbrunnsviken), Sealifecenter (Nacka), Bosses Båtuthyrning (Norra Djurgården) och flera bolag i Vaxholm. I Göteborg är Sjöstaden och Hisingen bra utgångspunkter.' },
    ],
  },
  {
    slug: "pendelbat-guide",
    title: "Pendelbåtar i Stockholm – guide till linjerna",
    excerpt: "Waxholmsbolaget, Strömma och privatlinjer: alla pendelbåtar och när de går.",
    category: "Transport",
    emoji: "⛴",
    readTime: "6 min",
    fullContent: true,
    faqs: [
      { q: 'Vilka pendelbåtslinjer finns i Stockholm?', a: 'Waxholmsbolaget driver flest linjer – till Vaxholm (83/83X), Lidingö, Djurgården, Nacka Strand och ytterskärgården. Strömma trafikerar Djurgården, Fjäderholmarna och turistlinjerna. SL-zonen täcker pendelbåtarna närmast stan.' },
      { q: 'Gäller SL-kortet på Waxholmsbolaget?', a: 'SL-kortet gäller på Waxholmsbolagets linjer inom SL-zonen A+B. Det inkluderar bl.a. trafiken till Vaxholm och närmaste öar. För yttre skärgården (Grinda, Sandhamn, Utö) behövs Waxholmsbolagets egna biljetter.' },
      { q: 'Hur lång tid tar båten till Vaxholm?', a: 'Pendelbåt 83 från Strömkajen i centrala Stockholm tar ca 55 minuter till Vaxholm. Det är den snabbaste vägen och går året om.' },
      { q: 'Hur bokar man biljett till Waxholmsbolaget?', a: 'Biljetter köps i appen Waxholmsbolaget, på waxholmsbolaget.se eller direkt ombord med kort. Årskortet "Skärgårdskortet" är lönsamt om du gör fler resor per säsong.' },
    ],
  },
  { slug: "seglingsklubbar-guide",       title: "Seglingsklubbar i Stockholm och skärgården",      excerpt: "Hitta rätt klubb, kurser och community för dig som vill börja segla.",                    category: "Aktivitet", emoji: "⛵", readTime: "5 min", fullContent: true },
  // ── Batch C: destinationer + praktiska guider ──────────────────────────────
  {
    slug: "aland-guide",
    title: "Åland – komplett guide till det svenska Finland",
    excerpt: "Autonomt örike, fri hamn, cykling och skärgård. Färja från Stockholm och allt du behöver veta för ett Ålandsbesök.",
    category: "Region",
    emoji: "🏝",
    readTime: "10 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Åland från Stockholm?', a: 'Med Viking Line eller Tallink Silja från Stockholm (Värtahamnen) till Mariehamn. Resan tar ca 10–11 timmar och erbjuds som nattfärja. Priserna börjar på ca 100–200 kr/person för en enkelbiljett.' },
      { q: 'Behöver man pass för att besöka Åland?', a: 'Nej, Åland är en del av Finland och EU. Svenskar behöver inget pass, ett nationellt ID-kort räcker. Åland har dock tullfri status (fri hamn) – cigaretter och alkohol kan köpas billigt ombord.' },
      { q: 'Vad kan man göra på Åland?', a: 'Cykla längs de välskötta cykelvägarna, besöka Kastelholms slott, bada vid sandstränderna i Bomarsund, utforska Ålands unika skärgård med hyrbåt eller kayak.' },
      { q: 'Vilket språk talas på Åland?', a: 'Svenska är det officiella språket på Åland trots att öriket är en del av Finland. Alla skyltar, menyer och service är på svenska.' },
    ],
  },
  {
    slug: "gotland-guide",
    title: "Gotland – komplett guide till Sveriges största ö",
    excerpt: "Visby medeltidsstad, raukar, sandstränder och sommarens hetaste matscen. Allt om Gotland sammanfattat.",
    category: "Region",
    emoji: "🏰",
    readTime: "11 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Gotland?', a: 'Med Destination Gotlands färja från Nynäshamn (ca 3 timmar) eller Oskarshamn (ca 3 timmar). Fly från Arlanda med BRA Airlines eller SAS tar ca 45 minuter. Boka färja 2–3 månader i förväg för sommarsäsongen – especiellt om du tar med bil.' },
      { q: 'Behöver man bil på Gotland?', a: 'Bil är praktiskt men inte nödvändigt. Visby är lätt att utforska till fots eller med cykel. Vill du se raukar, Fårö eller södra kusten behöver du bil eller buss. Hyrcyklar finns i Visby och passar utmärkt för dagsturer utanför stadsmuren.' },
      { q: 'När är bäst tid att besöka Gotland?', a: 'Juni och tidigt juli är bäst – varmt, grönt och folkmängden ännu hanterbar. Medeltidsveckan (2–9 aug 2026) är en unik upplevelse men Visby är fullpackat. Maj och september är lugna och vackra alternativ med öppna restauranger.' },
      { q: 'Vad kostar en resa till Gotland?', a: 'Färja tur/retur kostar 400–900 kr per person. Hyrbil på plats ca 600–1 200 kr/dag i högsäsong. Boende i Visby: 900–2 500 kr/natt. Räkna med 2 000–4 000 kr per person och dygn allt inräknat i juli.' },
      { q: 'Vad är raukar och var hittar man dem?', a: 'Raukar är naturliga kalkstenspelare formade av havet under miljoner år. De bästa rauk-platserna är Langhammars och Gamla Hamn på Fårö, Holmhällar i söder och Folhammar. Fårös raukar kräver tillstånd att besöka under häckningstid (april–juni).' },
    ],
  },
  {
    slug: "oland-guide",
    title: "Öland – guide till solens och vindarnas ö",
    excerpt: "Alvaret, Borgholm slott, Böda sand och cykelleder. Komplett guide till Öland – broförbindelsen och allt på ön.",
    category: "Region",
    emoji: "🌾",
    readTime: "9 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Öland?', a: 'Med bil eller buss via Ölandsbron från Kalmar – bron är gratis. Med tåg till Kalmar (ca 4h från Stockholm) och sedan buss 101 eller taxi till Borgholm. Ingen färja behövs – bron är öppen dygnet runt.' },
      { q: 'Behöver man hyra bil på Öland?', a: 'Bil är starkt rekommenderat. Öland är 137 km lång och kollektivtrafiken täcker inte hela ön. Hyrbil i Kalmar är billigast, alternativt i Borgholm. Cykel fungerar utmärkt i närheten av Borgholm och längs kustleder.' },
      { q: 'Är Ölandsbron gratis?', a: 'Ja, Ölandsbron är helt gratis för alla fordon. Den är 6 km lång och förbinder Kalmar med norra Öland vid Färjestaden.' },
      { q: 'Vad är Alvaret?', a: 'Alvaret är ett flackt kalkstenslandskap som täcker södra Öland och är UNESCO-världsarv sedan 2000. Det är ett unikt ekosystem med orkidéer, lavar och beteslandskap som inte finns någon annanstans i världen. Bäst att besöka maj–juni när blommorna blommar.' },
      { q: 'Vad är bäst att göra på Öland?', a: 'Cykla längs kusten, bada på Böda sand (Sveriges längsta sandstrand, 20 km), besöka Borgholms slottsruin och se Solliden (kungafamiljens sommarslott). Alvaret och fågelsjön Hornborga är höjdpunkter för naturintresserade.' },
    ],
  },
  { slug: "kosterarna-guide",            title: "Kosteröarna – guide till Sverige första marina nationalpark", excerpt: "Nordkoster och Sydkoster vid norska gränsen. Dykning, cykling, bilfria öar och Kosterfjordens unika marina liv.", category: "Region",    emoji: "🌊", readTime: "8 min",  fullContent: true },
  { slug: "missat-sista-baten",          title: "Missat sista båten – vad gör du nu?",               excerpt: "Råd, alternativ och lugn i en stressig situation. Övernattning, taxi och hur du tar dig hem om du missar sista avgången.", category: "Praktisk",  emoji: "⚠️", readTime: "5 min",  fullContent: true },
  { slug: "batkorkort-guide",            title: "Båtkörkort i Sverige – guide till sjömansmärket",   excerpt: "Vad krävs egentligen för att köra båt i Sverige? Sjömansmärket, kustskepparexamen och hur du tar körkortet.", category: "Praktisk",  emoji: "🎓", readTime: "7 min",  fullContent: true },
  { slug: "ingmarso-guide",              title: "Ingmarsö – guide till det bilfria livet i norra skärgården", excerpt: "Ingmarsö är en bilfri ö med vandringsleder, badplatser och ett riktigt skärgårdsliv. Transport, aktiviteter och praktisk info.", category: "Region",    emoji: "🌿", readTime: "6 min",  fullContent: true },
  { slug: "arholma-guide",               title: "Arholma – norra ytterskärgårdens utpost",           excerpt: "Startpunkten för Stockholm Archipelago Trail. Arholma är en av skärgårdens vackraste öar – och en av de svårast att nå.", category: "Region",    emoji: "🗺", readTime: "6 min",  fullContent: true },
  {
    slug: "hoga-kusten-guide",
    title: "Höga Kusten – guide till UNESCO-världsarvet",
    excerpt: "Världens högsta kust, Skuleskogen och djupa fjärdar. Komplett guide till sommarsemester längs Höga Kusten.",
    category: "Region",
    emoji: "🏔",
    readTime: "9 min",
    fullContent: true,
    faqs: [
      { q: 'Varför är Höga Kusten ett UNESCO-världsarv?', a: 'Höga Kusten har världens högsta landhöjning efter istiden – upp till 286 meter. Den dramatiska topografin med höga klippor, djupa fjärdar och isostatisk landhöjning är unik i världen.' },
      { q: 'Hur tar man sig till Höga Kusten?', a: 'Med tåg (SJ) till Kramfors eller Härnösand, sedan buss längs kusten. Med bil via E4 och sedan länsvägar. Från Stockholm är det ca 4–5 timmar med bil.' },
      { q: 'Vad ska man göra på Höga Kusten?', a: 'Vandra i Skuleskogen (Nationalpark), besök Slåttdalskrevan (30 m djup klippspricka), kör Höga Kustenleden, bada i fjärdarna och se solnedgången från Skuleberget (295 m).' },
      { q: 'Är Höga Kusten bra för familjer?', a: 'Ja, om barnen gillar natur och vandring. Skuleskogen har lättare stigar och Ångermanälvens mynning erbjuder fantastiska badplatser. Området är mindre turistifierat än kusterna längre söderut.' },
    ],
  },
  { slug: "fjallbacka-guide",            title: "Fjällbacka – guide till klippornas stad",            excerpt: "Kungsklyftan, Ingrid Bergman och Camilla Läckbergs hemstad. Allt om Fjällbacka på västkusten.", category: "Region",    emoji: "🪨", readTime: "7 min",  fullContent: true },
  { slug: "lysekil-guide",               title: "Lysekil – guide till Havets Hus och klipporna",     excerpt: "Havets Hus, klippbad, räksmörgåsar och kommunikationer till Lysekil på västkusten.", category: "Region",    emoji: "🐟", readTime: "6 min",  fullContent: true },
  { slug: "bornholm-guide",              title: "Bornholm från Sverige – guide till den danska klippön", excerpt: "Rökta sill, runda kyrkor och Hammershus. Hur du tar dig till Bornholm från Sverige och vad du gör när du är där.", category: "Region",    emoji: "🇩🇰", readTime: "8 min",  fullContent: true },
  { slug: "dalaro-guide",                title: "Dalarö – porten till södra Stockholms skärgård",    excerpt: "Historisk fortstäning, levande hamnmiljö och startpunkt för Ornö- och Utö-turer. Guide till Dalarö.", category: "Region",    emoji: "⚓", readTime: "5 min",  fullContent: true },
  { slug: "barplockning-skargarden",     title: "Bärplockning i skärgården – blåbär, lingon och hallon", excerpt: "Skärgårdens öar är fullspäckade med bär. Säsong, bästa öar och allt om bärplockning med allemansrätten.", category: "Aktivitet", emoji: "🫐", readTime: "5 min",  fullContent: true },
  { slug: "solnedgang-skargarden",       title: "Bästa solnedgångarna i Stockholms skärgård",        excerpt: "De vackraste platserna för solnedgång – vilka öar, vilken sida och vid vilken tid. En guide för fotografer och romantiker.", category: "Aktivitet", emoji: "🌅", readTime: "5 min",  fullContent: true },
  { slug: "ankra-sova-bat",              title: "Ankra och övernatta på båt i skärgården",           excerpt: "Bästa naturhamnarna, ankringstekniker, regler och hur du sover gott ute i öarna på din båt.", category: "Praktisk",  emoji: "⚓", readTime: "7 min",  fullContent: true },
  // ── Batch B: ö-guider + tematiska guider ───────────────────────────────────
  { slug: "moja-guide",                  title: "Möja – guide till skärgårdens egna stad",          excerpt: "Möja har butik, krog, cyklar och natur. Så tar du dig dit, vad du gör och varför Möja är mitt i skärgårdslivet.", category: "Region",    emoji: "🏝", readTime: "7 min", fullContent: true },
  {
    slug: "grinda-guide",
    title: "Grinda – komplett guide till familjeön",
    excerpt: "Grinda är skärgårdens barnvänligaste ö. Wärdshuset, sandstranden, kajakarna och kvällsbåten hem.",
    category: "Region",
    emoji: "🌿",
    readTime: "6 min",
    fullContent: true,
    faqs: [
      { q: 'Hur lång är resan till Grinda?', a: 'Ca 1h 45min med Waxholmsbolaget linje 11 från Strömkajen. Cinderellabåten tar ca 1h 20min under sommarsäsongen. Biljett kostar ca 200 kr enkel resa med Waxholmsbolaget.' },
      { q: 'Kan man övernatta på Grinda?', a: 'Ja. Grinda Wärdshus erbjuder rum och stugor. Det finns också ett vandrarhem och möjlighet att tälta på södra sidan av ön. Boende bör bokas långt i förväg – Grinda är fullbokat under hela sommarsäsongen.' },
      { q: 'Är Grinda bra för barnfamiljer?', a: 'Grinda är ett av skärgårdens allra bästa val för barnfamiljer. Ön har sandstrand med grunt vatten, kajakhyrning anpassad för barn, ett trevligt värdshus och är liten nog att utforska på en dag. Båtresan är lagom lång för de flesta barn.' },
      { q: 'Kan man bada på Grinda?', a: 'Ja, Grinda har sandstrand med grunt och varmt vatten på södra sidan. Det är en av de bättre badstränderna i Stockholms skärgård. Vattnet brukar hålla 20–22°C i juli och tidigt augusti.' },
    ],
  },
  { slug: "finnhamn-guide",              title: "Finnhamn – guide till norra skärgårdens pärla",    excerpt: "Vandrarhem, naturhamn och storslagna vyer mot ytterskärgården. Så planerar du ett Finnhamn-besök.", category: "Region",    emoji: "⛺", readTime: "6 min", fullContent: true },
  { slug: "nattaro-guide",               title: "Nåttarö – tältarens favorit i södra skärgården",  excerpt: "Nåttarö är känd för sitt campingområde och långa sandstränder. Guide till transport, boende och naturupplevelser.", category: "Region",    emoji: "🏕", readTime: "6 min", fullContent: true },
  { slug: "orno-guide",                  title: "Ornö – det stora, stilla alternativet",             excerpt: "Ornö är en av Stockholms skärgårds största öar men utan turistmassor. Vandrarleder, naturhamnar och tystnad.", category: "Region",    emoji: "🌲", readTime: "6 min", fullContent: true },
  { slug: "hund-i-skargarden",           title: "Skärgården med hund – regler, öar och tips",       excerpt: "Vad gäller för hund i skärgården? Var är hund tillåten, var krävs koppel och vilka öar passar bäst?", category: "Praktisk",  emoji: "🐕", readTime: "6 min", fullContent: true },
  { slug: "romantisk-weekend-skargarden", title: "Romantisk weekend i skärgården – bästa alternativen", excerpt: "Havsutsikt, värdshus och solnedgång från klippan. De bästa öarna och boendena för en par-weekend i skärgården.", category: "Praktisk", emoji: "❤️", readTime: "7 min", fullContent: true },
  { slug: "svampplockning-skargarden",   title: "Svampplockning i skärgården – säsong och platser", excerpt: "Kantareller, karljohan och trattkantareller väntar i skärgårdens skogar. Bästa öarna och säsongstips.", category: "Aktivitet", emoji: "🍄", readTime: "5 min", fullContent: true },
  { slug: "pingst-skargarden",           title: "Pingst i skärgården – öppna öar och första sol",   excerpt: "Pingst är startskottet för skärgårdssäsongen. Vilka öar är öppna, var håller de pingstfirande och vad kan du göra?", category: "Säsong",   emoji: "🌷", readTime: "5 min", fullContent: true },
  { slug: "foretagsevent-skargarden",    title: "Företagsevent i skärgården – guide och inspiration", excerpt: "Skärgården är den perfekta scenen för kickoff, AW och teambuilding. Öar, anläggningar och aktiviteter för grupper.", category: "Praktisk", emoji: "🏢", readTime: "7 min", fullContent: true },
  { slug: "digital-detox-skargarden",   title: "Digital detox i skärgården – öar utan uppkoppling", excerpt: "Öar med dålig täckning, inga tv-apparater och naturlig tystnad. En guide för dig som vill koppla bort ordentligt.", category: "Praktisk", emoji: "📵", readTime: "6 min", fullContent: true },
  { slug: "grinda-vs-finnhamn",          title: "Grinda vs Finnhamn – vilken ö passar dig?",        excerpt: "Grinda är familjevänligt med värdshus, Finnhamn är vandrarhem och vildmark. En ärlig jämförelse.", category: "Region",    emoji: "⚖", readTime: "5 min", fullContent: true },
  // ── Batch A: nya fullContent-guider ────────────────────────────────────────
  {
    slug: "stockholm-archipelago-trail",
    title: "Stockholm Archipelago Trail – komplett guide",
    excerpt: "270 km vandringsled över 20 öar från Arholma till Landsort. Utsedd till en av världens bästa upplevelser av TIME Magazine 2025. Etapper, transport och tips.",
    category: "Aktivitet",
    emoji: "🥾",
    readTime: "10 min",
    fullContent: true,
    faqs: [
      { q: 'Hur lång är Stockholm Archipelago Trail?', a: 'Leden är 270 km lång och sträcker sig över 20 öar från Arholma i norr till Landsort i söder. Normalt vandrar man leden på 12–20 dagar.' },
      { q: 'Måste man gå hela leden på en gång?', a: 'Nej, leden är uppdelad i etapper och kan vandras i valfri ordning. Varje ö nås med Waxholmsbolaget, så du kan enkelt kombinera etapper med pendling från Stockholm.' },
      { q: 'Vad kostar det att vandra Stockholm Archipelago Trail?', a: 'Vandringen i sig är gratis. Biljetter med Waxholmsbolaget tillkommer. Boende varierar – tälta är tillåtet (allemansrätten), men öarna har också vandrarhem och stugor till ca 300–800 kr/natt.' },
      { q: 'Är leden svår?', a: 'Leden är varierad – från lättgångna stigar till klipphäll. Den kräver grundläggande tältvandringskunskap, bra skor och att man kan navigera med karta och kompass på öar utan markerade leder.' },
    ],
  },
  { slug: "sup-paddleboard-skargarden",  title: "SUP och paddleboard i skärgården – guide för nybörjare", excerpt: "Ståndupp-paddling är skärgårdens snabbast växande aktivitet. Var du hyr, bästa platserna och vad du behöver veta för en säker tur.", category: "Aktivitet", emoji: "🏄", readTime: "7 min", fullContent: true },
  { slug: "o-luffa-guide",               title: "Ö-luffa i Stockholms skärgård – guide till båtluffarkortet", excerpt: "Waxholmsbolagets båtluffarkort låter dig hoppa på och av obegränsat i 30 dagar. Planera din fleröarsresa med konkreta ruttförslag.", category: "Transport", emoji: "⛴", readTime: "8 min", fullContent: true },
  {
    slug: "camping-talta-skargarden",
    title: "Camping och tälta i skärgården – komplett guide",
    excerpt: "Var du får tälta, bästa anläggningarna, allemansrättens gränser och vad du måste ta med. Konkreta råd för 13+ platser.",
    category: "Praktisk",
    emoji: "⛺",
    readTime: "9 min",
    fullContent: true,
    faqs: [
      { q: 'Får man tälta var som helst i skärgården?', a: 'Enligt allemansrätten får du tälta kortvarigt (1–2 nätter) på mark som inte tillhör trädgård eller brukas aktivt. Håll avstånd till närmaste bostad, lämna ingen skräp och följ eventuella lokala regler.' },
      { q: 'Vilka öar i skärgården är bäst för tälta?', a: 'Nåttarö, Gällnö, Östra Lagnö och Ornö är klassiker för tältare. Nåttarö har en etablerad tältplats med toalett och sophantering – perfekt för familjer. Ytterskärgårdens klippöar ger mer vildmarkskänsla.' },
      { q: 'Behöver man eld-/grillplats i skärgården?', a: 'Öppen eld är förbjudet på klipphäll och vid högt brandindex. Använd alltid medförd spritkök eller kol i upphöjd grill. Eldförbud gäller ofta juni–augusti. Kolla SMHI och länsstyrelsens information före resan.' },
      { q: 'Vad kostar det att campa i skärgården?', a: 'Viltcampning (allemansrätten) är gratis. Anvisade tältplatser kostar 100–250 kr/natt/tält. Campingplatser med service kostar 300–500 kr/natt.' },
    ],
  },
  { slug: "havsbastu-skargarden",        title: "Havsbastu i skärgården – de bästa platserna och hur du bokar", excerpt: "Vedeldad bastu med havsutsikt och kallt dopp efteråt. Bästa havsbastuplatserna i Stockholms skärgård, priser och bokningsinfo.", category: "Aktivitet", emoji: "🧖", readTime: "7 min", fullContent: true },
  {
    slug: "barnfamilj-skargarden",
    title: "Skärgård med barnfamilj – bästa öarna och praktiska tips",
    excerpt: "De bästa öarna för familjer, säkra badplatser, barnvänliga restauranger och hur du planerar resan utan stress.",
    category: "Praktisk",
    emoji: "👨‍👩‍👧",
    readTime: "8 min",
    fullContent: true,
    faqs: [
      { q: 'Vilken ö är bäst för barnfamiljer i Stockholms skärgård?', a: 'Grinda är ett toppval: barnvänligt värdshus, sandstrand, trampolin och korta promenader. Fjäderholmarna är bäst för de minsta (25 min från stan). Nåttarö och Utö passar familjer som vill ha mer naturupplevelse.' },
      { q: 'Är det säkert att åka med barn på Waxholmsbolaget?', a: 'Ja, Waxholmsbolagets båtar är säkra och välskötta. Barn under 7 år reser gratis. Bär alltid flytväst på barn under 12 år vid bryggor och ombord.' },
      { q: 'Vad kostar en familjedag i skärgården?', a: 'Räkna med 400–700 kr för en familj om 4 (2 vuxna + 2 barn) i biljetter. Mat och glass tillkommer. Med eget matsäck hålls kostnaden nere.' },
      { q: 'Hur gammal bör barnet vara för att skärgårdsresan ska fungera?', a: 'Redan från 1–2 år funkar dagsutflykter till Fjäderholmarna och Vaxholm. För övernattningsresor och öar med mer vandring rekommenderar vi 4+ år. Stockholm Archipelago Trail kräver minst 10–12 år.' },
    ],
  },
  {
    slug: "uto-komplett-guide",
    title: "Utö – komplett guide till södra skärgårdens kronjuvel",
    excerpt: "Transport, gruvhistoria, Utö Runt-leden, havsbastu, sandstrand och bästa restaurangerna. Allt du behöver för ett perfekt Utö-besök.",
    category: "Region",
    emoji: "🏝",
    readTime: "10 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Utö?', a: 'Med Waxholmsbolaget från Årstaberg (buss + båt, ca 2,5 h) eller från Nynäshamn (ca 1 h med båt). Buss 433 till Stavsnäs + båt är ett alternativ söderifrån. Färjan från Nynäshamn är snabbast.' },
      { q: 'Måste man ha bil på Utö?', a: 'Nej – Utö är bilfritt för turister. Ön har cykelhyra, och de flesta sevärdheter nås lätt till fots eller med cykel. Cykeln är faktiskt det bästa sättet att uppleva Utö.' },
      { q: 'Vad kostar övernattning på Utö?', a: 'Utö Värdshus kostar 1 500–3 000 kr/natt dubbelrum. Vandrarhem och stugor på ön kostar 400–900 kr/natt. Tältplatser finns från ca 150 kr/natt.' },
      { q: 'Vad är Utö mest känt för?', a: 'Utö är känt för sin havsbastu vid stranden, Utö Runt-cykelled (ca 12 km), jerngruvan (en av Sveriges äldsta), sandstranden Kobbarnsudde och det välrenommerade Utö Värdshus.' },
    ],
  },
  {
    slug: "sandhamn-komplett-guide",
    title: "Sandhamn – komplett guide till seglarnas ö",
    excerpt: "Stranden Trouville, seglarlivet, Cinderellabåten, bästa restaurangerna och vad som gör Sandhamn unikt bland skärgårdsöarna.",
    category: "Region",
    emoji: "⛵",
    readTime: "9 min",
    fullContent: true,
    faqs: [
      { q: 'Hur tar man sig till Sandhamn?', a: 'Snabbaste vägen: SL-buss 433 från Slussen till Stavsnäs (ca 55 min) och sedan Waxholmsbolaget linje 444 till Sandhamn (ca 35–45 min). Alternativt Cinderellabåten direkt från Strömkajen (ca 2h). Cinderellabåten kräver bokning under högsäsong.' },
      { q: 'Kan man övernatta på Sandhamn?', a: 'Ja. Sandhamns Värdshus är det mest kända alternativet. Det finns också Seglarhotellet och ett flertal privata stugor att hyra. Boka boende minst 2–3 månader i förväg för sommarsäsongen – Sandhamn är en av skärgårdens mest efterfrågade destinationer.' },
      { q: 'Är Sandhamn lämpligt för barnfamiljer?', a: 'Sandhamn är mer av en vuxendestination med seglarliv och aktiv stämning, men fungerar för familjer. Stranden Trouville är bra för barn. Det är folksamlat i juli – Grinda eller Utö kan passa bättre för barnfamiljer som vill ha lugn.' },
      { q: 'Vad är bäst att göra på Sandhamn?', a: 'Promenera runt byn, bada på Trouville-stranden, äta räkor vid hamnen och titta på seglarna i KSSS-hamnen. Sandhamns museum berättar om öns historia som lotsstation. Vandring runt ön tar ca 2 timmar och ger fin utsikt mot öppet hav.' },
      { q: 'Vad kostar Cinderellabåten till Sandhamn?', a: 'Ca 350–450 kr tur/retur beroende på säsong. Cinderellabåten ingår inte i Waxholmsbolagets ordinarie sortiment och är en separat produkt som drivs av Strömma. Biljett köps via stromma.com.' },
    ],
  },
  { slug: "vinter-i-skargarden",         title: "Skärgården på vintern – öppna öar, skridskor och stillhet", excerpt: "Vilka öar är öppna, hur du tar dig dit och varför vintern faktiskt är den bästa årstiden för rätt person. Praktisk guide.", category: "Säsong", emoji: "❄️", readTime: "8 min", fullContent: true },
  { slug: "fiske-i-skargarden",          title: "Fiske i Stockholms skärgård – guide till arter, platser och säsonger", excerpt: "Abborre, gädda och havsöring väntar i skären. Fiskeregler, de bästa platserna per art och vilken tid på året som ger mest.", category: "Aktivitet", emoji: "🎣", readTime: "9 min", fullContent: true },
  { slug: "cykling-skargarden",          title: "Cykla i skärgården – de bästa öarna och hur du planerar turen", excerpt: "Bilfria öar är skapta för cykling. Möja, Gällnö, Utö, Ingmarsö och fler – med cykelhyrningsinfo och konkreta rutter.", category: "Aktivitet", emoji: "🚴", readTime: "8 min", fullContent: true },
  // ── Batch D: Kräftskiva-serien 2026 ─────────────────────────────────────────
  { slug: "kraftskiva-skargarden-2026",   title: "Kräftskiva i Stockholms skärgård 2026 – guide till traditionen", excerpt: "Kräftpremiären är 5 augusti 2026. Var du håller kräftskiva i skärgården, vad du äter, hur du dekorerar och vilka restauranger som bokar fullt.", category: "Säsong", emoji: "🦀", readTime: "8 min", fullContent: true },
  { slug: "kraftskiva-bohuslan-2026",     title: "Kräftskiva i Bohuslän 2026 – klippor och kräftor vid Västerhavet", excerpt: "Bohuslän är kräftornas hemort. Guide till kräftskiva vid Västkusten – från Grebbestad till Smögen – med restauranger, traditioner och praktiska tips.", category: "Säsong", emoji: "🦞", readTime: "7 min", fullContent: true },
  { slug: "kraftskiva-gotland-2026",      title: "Kräftskiva på Gotland 2026 – midsommarnatt med kräftor", excerpt: "Kräftskiva på Gotland är en unik upplevelse. Guidade fisketurer, restauranger i Visby och hur du arrangerar din egen traditionsenliga kräftskiva.", category: "Säsong", emoji: "🏰", readTime: "6 min", fullContent: true },
  { slug: "kraftskiva-oland-2026",        title: "Kräftskiva på Öland 2026 – vid bryggan under lyktorna", excerpt: "Ölands långa kust och sommarnätter ger perfekta förutsättningar för kräftskiva. Guide till de bästa platserna och restaurangerna.", category: "Säsong", emoji: "🌾", readTime: "6 min", fullContent: true },
  { slug: "grebbestad-kraftskiva-2026",   title: "Grebbestad kräftskiva 2026 – landets kräftcentrum", excerpt: "Grebbestad är mer känt för ostron men kräftorna är lika viktiga. Guide till fisket, festerna och kräftsäsongen i Bohuslän.", category: "Region", emoji: "🦐", readTime: "6 min", fullContent: true },
  { slug: "kraftskiva-recept-meny",       title: "Kräftskiva recept och meny – allt du behöver 2026", excerpt: "Hur du kokar kräftor, klassisk kräftskivemeny, snapsvisor och dekoration. Komplett guide för en lyckad kräftskiva hemma eller ute i naturen.", category: "Praktisk", emoji: "🍽", readTime: "7 min", fullContent: true },
  // ── Batch D: Juli-serien 2026 ────────────────────────────────────────────────
  { slug: "juli-skargarden-2026-oar",     title: "Juli i Stockholms skärgård 2026 – de bästa öarna att besöka", excerpt: "Juli är skärgårdens högsäsong. Vilka öar som är öppna, vilka som är folkliga och vilka som ger lugn och ro. Rankad guide för semestermånaden.", category: "Säsong", emoji: "☀️", readTime: "9 min", fullContent: true },
  { slug: "juli-skargarden-2026-aktiviteter", title: "Juli i skärgården – aktiviteter, upplevelser och äventyr 2026", excerpt: "Från kajakpaddling till havsbastu och nattfiske. Allt du kan göra i Stockholms skärgård under juli månads ljusa nätter och värme.", category: "Säsong", emoji: "🌊", readTime: "8 min", fullContent: true },
  { slug: "juli-skargarden-2026-mat",     title: "Juli i skärgården – mat, krogar och sommarens smaker 2026", excerpt: "Räkfrukost vid bryggan, grillade gäddor och glasstruten på klippan. Guide till årets bästa matupplevelser i Stockholms skärgård i juli.", category: "Säsong", emoji: "🍤", readTime: "7 min", fullContent: true },
  { slug: "semestervecka-skargarden",     title: "En vecka i Stockholms skärgård – komplett dag-för-dag-guide", excerpt: "Sju dagar, sju öar och ett program som täcker allt från Vaxholm till Utö. Dag-för-dag-itinerary för den perfekta skärgårdssemestern.", category: "Praktisk", emoji: "🗓", readTime: "10 min", fullContent: true },
  { slug: "sommarlov-skargarden-barn",    title: "Sommarlov i skärgården med barn – 14 dagar av äventyr", excerpt: "Planering för en hel sommarlovsvecka med barn i skärgården. Öar med sandstränder, aktiviteter för alla åldrar och tips för att undvika köerna.", category: "Praktisk", emoji: "👦", readTime: "9 min", fullContent: true },
  { slug: "vad-gora-regn-skargarden",     title: "Vad göra i skärgården när det regnar – 15 tips", excerpt: "Regn behöver inte förstöra skärgårdsdagen. Museer, bastubad, stugor, inomhusaktiviteter och varför regnväder faktiskt kan vara mysigt.", category: "Praktisk", emoji: "🌧", readTime: "6 min", fullContent: true },
  { slug: "juli-bohuslan-2026",           title: "Juli i Bohuslän 2026 – sommarens bästa klippkust", excerpt: "Juli är Bohusläns hetaste månad. Smögen, Marstrand, Lysekil och de bästa insidertipsen för att ta sig dit och uppleva det bästa av västkusten.", category: "Säsong", emoji: "🪨", readTime: "8 min", fullContent: true },
  { slug: "juli-gotland-2026",            title: "Juli på Gotland 2026 – allt som händer på sommaron", excerpt: "Juli är Gotlands högsäsong. Medeltidsveckan, Visby restaurangscen, de bästa stränderna och hur du undviker folkmassan. Guide för sommaren 2026.", category: "Säsong", emoji: "🌻", readTime: "9 min", fullContent: true },
  // ── Batch E: Barnvänligt-serien ──────────────────────────────────────────────
  { slug: "barnvanliga-oar-bohuslan",     title: "Barnvänliga öar i Bohuslän – 10 bästa alternativen", excerpt: "Bohuslän har klippor och stränder som barn älskar. Guide till de tio bästa barnvänliga öarna och platserna längs Bohusläns kust.", category: "Praktisk", emoji: "🏖", readTime: "8 min", fullContent: true },
  { slug: "barnfamilj-gotland",           title: "Gotland med barnfamilj – guide till sommarons bästa", excerpt: "Gotland har medeltidsborgar, långa sandstränder och cykelvägar som passar hela familjen. Allt du behöver planera en perfekt barnfamiljesemester.", category: "Praktisk", emoji: "🏰", readTime: "8 min", fullContent: true },
  { slug: "barnvanliga-bad-skargarden",   title: "Barnvänliga badplatser i skärgården – grunt, tryggt och roligt", excerpt: "Grunda vikar, sandstränder och badplatser utan strömmar. Guide till de säkraste och roligaste badplatserna för barn i Stockholms skärgård.", category: "Praktisk", emoji: "🏊", readTime: "7 min", fullContent: true },
  { slug: "barnvanliga-batresor-skargarden", title: "Barnvänliga båtturer i Stockholms skärgård", excerpt: "Vilka båtturer passar barn bäst? Kort restid, underhållning ombord och barnvänliga destinationer. Guide till de bästa båtturerna med barn.", category: "Transport", emoji: "⛴", readTime: "6 min", fullContent: true },
  { slug: "barnvanliga-restauranger-skargarden", title: "Barnvänliga restauranger i skärgården – mat som hela familjen gillar", excerpt: "Restauranger med barnmeny, höga stolar och tålamod. Guide till de bästa barnvänliga matställena i Stockholms skärgård.", category: "Mat", emoji: "🍽", readTime: "6 min", fullContent: true },
  { slug: "barnvanliga-aktiviteter-skargarden", title: "Barnvänliga aktiviteter i skärgården – 20 tips", excerpt: "Klipphopp, kajak, sandslott och naturupptäckter. Allt barn kan göra i skärgården – organiserat och spontant. Guide för alla åldrar.", category: "Aktivitet", emoji: "🎯", readTime: "7 min", fullContent: true },
  // ── Batch E: Bad-serien ────────────────────────────────────────────────────────
  { slug: "basta-badplatser-bohuslan",    title: "Bästa badplatserna i Bohuslän 2026 – klippor och sandstränder", excerpt: "Bohusläns klippkust har Sveriges mest dramatiska badplatser. Från Smögens klippor till Varbergs sandstränder – guide till 15 toppalternativ.", category: "Aktivitet", emoji: "🌊", readTime: "8 min", fullContent: true },
  { slug: "basta-badplatser-gotland",     title: "Bästa badplatserna på Gotland 2026 – sandstränder och kalkstensklippor", excerpt: "Gotlands stränder är unika – kalksten, kristallklart vatten och lång säsong. Guide till de 12 bästa badplatserna på Gotland.", category: "Aktivitet", emoji: "🏖", readTime: "7 min", fullContent: true },
  { slug: "klippbad-skargarden",          title: "Bästa klippbaden i Stockholms skärgård – hoppa, dyk och njut", excerpt: "Gneisklipporna i skärgården är gjorda för bad. Guide till de bästa klippbadsplatserna – med rätt djup, fin utsikt och sommarlik stämning.", category: "Aktivitet", emoji: "🪨", readTime: "7 min", fullContent: true },
  { slug: "sandstrand-skargarden",        title: "Sandstränder i skärgården – komplett guide till alla sandstränder", excerpt: "Stockholms skärgård är inte känd för sandstränder – men de finns. Guide till alla sandstränder i skärgården och varför de är ovärderliga.", category: "Aktivitet", emoji: "🏝", readTime: "6 min", fullContent: true },
  { slug: "hemliga-badplatser-skargarden", title: "Hemliga badplatser i skärgården – undangömda pärlor", excerpt: "Bortom turistströmmarna finns badplatser som inte syns på kartan. Guide till de bäst dolda och mest ostörda badplatserna i skärgården.", category: "Aktivitet", emoji: "🗺", readTime: "6 min", fullContent: true },
  { slug: "bad-med-bastu-skargarden",     title: "Bad och bastu i skärgården – den perfekta kombinationen", excerpt: "Vedeldad bastu, kallt havsvatten och solnedgången bakom öarna. Guide till de bästa platserna där du kombinerar havsbad och bastu.", category: "Aktivitet", emoji: "🧖", readTime: "7 min", fullContent: true },
  // ── Batch F: Beslutsguider ────────────────────────────────────────────────────
  { slug: "uto-vs-sandhamn",              title: "Utö vs Sandhamn – vilken ö passar dig?", excerpt: "Utö är lugnt med gruvhistoria och havsbastu. Sandhamn är segling och folkfest. En ärlig jämförelse av skärgårdens två mest älskade öar.", category: "Region", emoji: "⚖", readTime: "6 min", fullContent: true },
  { slug: "marstrand-vs-smogen",          title: "Marstrand vs Smögen – Bohusläns rivaler", excerpt: "Marstrand är fästning och regatta. Smögen är räkor och klippliv. Vilket Bohuslän passar dig bäst?", category: "Region", emoji: "⚖", readTime: "5 min", fullContent: true },
  { slug: "gotland-vs-bohuslan",          title: "Gotland vs Bohuslän – stor semesterjämförelse 2026", excerpt: "Östersjöns kalkstensö mot Västerhavets klippkust. En grundlig jämförelse av Sveriges två hetaste sommardestinationer.", category: "Region", emoji: "🗺", readTime: "7 min", fullContent: true },
  { slug: "inre-vs-yttre-skargard",       title: "Inre vs yttre skärgård – vad passar dig?", excerpt: "Inre skärgården är grön och lättillgänglig. Yttre skärgården är dramatisk och avlägsen. Guide till vilken del som passar dig och dina förväntningar.", category: "Praktisk", emoji: "🧭", readTime: "6 min", fullContent: true },
  { slug: "dagstur-vs-overnight-skargarden", title: "Dagstur eller övernattning i skärgården – vad väljer du?", excerpt: "Dagstur ger mer flexibilitet. Övernattning ger solnedgång och morgondopp. Guide till hur du avgör vad som passar din resa.", category: "Praktisk", emoji: "🌙", readTime: "5 min", fullContent: true },
  { slug: "stockholm-vs-bohuslan-skargard", title: "Stockholms skärgård vs Bohuslän – vilken vinner?", excerpt: "30 000 öar mot klippkust och Västerhavet. En objektiv jämförelse av Sveriges två stora skärgårdar.", category: "Region", emoji: "🏆", readTime: "7 min", fullContent: true },
  // ── Batch F: Säsongsmotorer höst/vinter ──────────────────────────────────────
  { slug: "sensommar-skargarden-2026",    title: "Sensommar i skärgården 2026 – aug–sep när allt stämmer", excerpt: "Sensommaren är skärgårdens bästa tid. Havet är varmt, folk har åkt hem och naturen glöder i gyllene ljus. Guide till aug–sep 2026.", category: "Säsong", emoji: "🍂", readTime: "7 min", fullContent: true },
  { slug: "september-skargarden-2026",    title: "September i skärgården 2026 – varför det är årets bästa månad", excerpt: "September är skärgårdens bäst bevarade hemlighet. Varmt hav, inga turister och höstens färger. Komplett guide till september 2026.", category: "Säsong", emoji: "🍁", readTime: "7 min", fullContent: true },
  { slug: "host-bohuslan-2026",           title: "Höst i Bohuslän 2026 – ostron, klippor och havsluft", excerpt: "Hösten är Bohusläns bästa säsong. Ostronstangning premiär i september, klipporna i höstljus och lugnet efter sommarens folkmassor.", category: "Säsong", emoji: "🦪", readTime: "7 min", fullContent: true },
  { slug: "host-gotland-2026",            title: "Höst på Gotland 2026 – raukar, svamp och stillhet", excerpt: "Gotland i höst är helt annorlunda mot sommar-Gotland. Raukar i dimman, svampskog och mysiga restauranger utan kö.", category: "Säsong", emoji: "🍄", readTime: "6 min", fullContent: true },
  // ── Batch F: Regionala djupguider ────────────────────────────────────────────
  { slug: "karlskrona-guide",             title: "Karlskrona guide – UNESCO-världsarvet vid Östersjön", excerpt: "Karlskrona är ett av Europas bäst bevarade barockstäder och UNESCO-världsarv. Guide till örlogsstaden, skärgården och sommarsemestern i Blekinge.", category: "Region", emoji: "⚓", readTime: "8 min", fullContent: true },
  { slug: "varberg-guide",                title: "Varberg guide – fästning, surf och Hallandskust", excerpt: "Varberg är Hallands stoltaste stad med medeltidsfästning, Sveriges bästa surf och en unik kallbadshusupplevelse. Komplett guide.", category: "Region", emoji: "🏄", readTime: "7 min", fullContent: true },
  { slug: "borgholm-guide",               title: "Borgholm guide – Ölands sommarstad", excerpt: "Borgholm är Ölands levande sommarstad med slottsruin, marknad och nattliv. Guide till det bästa av Ölands huvudort.", category: "Region", emoji: "🏰", readTime: "7 min", fullContent: true },
  { slug: "tjorn-guide",                  title: "Tjörn guide – konst, klippor och bilfri skärgård", excerpt: "Tjörn är Bohusläns näst största ö med Nordiska Akvarellmuseet, magnifika klippbad och ett aktivt konstliv. Komplett guide.", category: "Region", emoji: "🎨", readTime: "7 min", fullContent: true },
  { slug: "visby-sommar-guide",           title: "Visby sommarguide – mer än medeltidsmuren", excerpt: "Visby är Sveriges mest välbevarade medeltidsstad och Gotlands hjärta. Sommarguide till ringmuren, restaurangscenen och de dolda hörnen.", category: "Region", emoji: "🏛", readTime: "8 min", fullContent: true },
  // ── Batch G: Resterande guider – alla serier ──────────────────────────────────
  { slug: "jul-skargarden-2026",          title: "Jul i skärgården 2026 – advent, öppna öar och stämning", excerpt: "Skärgården på vintern och i advent är ett helt annat landskap. Guide till öppna öar, julmarknader och vinterbastu under december 2026.", category: "Säsong", emoji: "🎄", readTime: "7 min", fullContent: true },
  { slug: "nyar-skargarden-2026",         title: "Nyår i skärgården 2026–2027 – fyrverk, öar och stämning", excerpt: "Nyårsfirande i skärgården med fyrverkeri reflekterade i havet. Öppna öar, hotell och tips för nyårsnatten ute bland kobbar och klippor.", category: "Säsong", emoji: "🎆", readTime: "6 min", fullContent: true },
  { slug: "pask-skargarden-2027",         title: "Påsk i skärgården 2027 – vårens första utflykt", excerpt: "Påsken är startskottet för skärgårdens värsäsong. Vilka öar öppnar, hur kylan sitter i havet och varför påskhelgen är underbar i skärgården.", category: "Säsong", emoji: "🐣", readTime: "6 min", fullContent: true },
  { slug: "valborg-skargarden-2027",      title: "Valborg i skärgården 2027 – vårfirande vid havet", excerpt: "Valborg den 30 april är en av skärgårdens festligaste kvällar. Brasor, sång och sommarens förkänning ute på öarna.", category: "Säsong", emoji: "🔥", readTime: "5 min", fullContent: true },
  { slug: "kajakpaddling-bohuslan",       title: "Kajakpaddling i Bohuslän – guide längs klippkusten", excerpt: "Västerhavet med sina klippor och sund är ett kajakparadis. Guide till de bästa paddlingsrutterna, hyrning och säkerhet längs Bohusläns kust.", category: "Aktivitet", emoji: "🛶", readTime: "8 min", fullContent: true },
  { slug: "vandring-gotland",             title: "Vandring på Gotland – de bästa lederna och turerna", excerpt: "Gotlands platta landskap är perfekt för vandring. Raukleder, kustleder och skogsstigar. Guide till de bästa vandringsupplevelserna på ön.", category: "Aktivitet", emoji: "🥾", readTime: "7 min", fullContent: true },
  { slug: "cykling-gotland",             title: "Cykla på Gotland – en dag, tre dagar eller en vecka", excerpt: "Gotland är en av Sveriges bästa cykelöar. Platt terräng, bilfria vägar och vackra vyer. Guide till rutter för alla ambitionsnivåer.", category: "Aktivitet", emoji: "🚴", readTime: "7 min", fullContent: true },
  { slug: "cykling-oland",               title: "Cykla på Öland – längs kust, alvar och vindmöllor", excerpt: "Öland är Sverige plattaste ö och ett av landets bästa cykellandskap. Kustleder, Alvaret och vandrarhem längs vägen. Komplett cykelguide.", category: "Aktivitet", emoji: "🚲", readTime: "7 min", fullContent: true },
  { slug: "snorkling-kosterhavet",        title: "Snorkling i Kosterhavet – Europas artrikaste marina miljö", excerpt: "Kosterhavets nationalpark har Europas artrikaste marina miljö. Sjöborrar, sjöstjärnor och koraller väntar under ytan. Guide till snorkling och dykning.", category: "Aktivitet", emoji: "🤿", readTime: "7 min", fullContent: true },
  { slug: "ostronstangning-bohuslan",     title: "Ostronplockning i Bohuslän – säsong, safari och guide", excerpt: "Bohuslän är landets ostronhuvudstad. Säsongen öppnar i september. Guide till ostronsafari, plockning och hur du avnjuter färska Västerhavsostron.", category: "Aktivitet", emoji: "🦪", readTime: "7 min", fullContent: true },
  { slug: "hyra-stuga-skargarden",        title: "Hyra stuga i skärgården – guide och prisjämförelse", excerpt: "Stugor i skärgården finns i alla prisklasser. Guide till de bästa uthyrningssajterna, vad du bör kräva och hur du hittar de bästa lägena.", category: "Praktisk", emoji: "🏡", readTime: "7 min", fullContent: true },
  { slug: "hyra-stuga-gotland",           title: "Hyra stuga på Gotland 2026 – guide och tips", excerpt: "Gotland har massor med stuguthyrning – allt från enkla lantgårdar till lyxvilla vid havet. Guide till bästa sajterna och perioder att boka.", category: "Praktisk", emoji: "🏘", readTime: "6 min", fullContent: true },
  { slug: "faro-guide",                   title: "Färö guide – Ingmar Bergmans ö och raukarnas landskap", excerpt: "Färö norr om Gotland är Ingmar Bergmans ö och hem till några av Nordens mest dramatiska naturformationer. Guide till raukar, stränder och stillheten.", category: "Region", emoji: "🎬", readTime: "7 min", fullContent: true },
  { slug: "ulvon-guide",                  title: "Ulvön guide – surströmmingens hemort i Höga Kusten", excerpt: "Ulvön i Höga Kusten är surströmmingens heliga land och en av Norrlands vackraste öar. Guide till transport, mat och upplevelserna.", category: "Region", emoji: "🐟", readTime: "7 min", fullContent: true },
  { slug: "grebbestad-guide",             title: "Grebbestad guide – kräftor, ostron och Bohusläns hjärta", excerpt: "Grebbestad är det mest genuina fiskesamhället i Bohuslän och hem till landets bästa kräftor och ostron. Komplett guide till Grebbestad.", category: "Region", emoji: "🦞", readTime: "7 min", fullContent: true },
  { slug: "stromstad-guide",              title: "Strömstad guide – nära norska gränsen och Kosterfjorden", excerpt: "Strömstad är Sveriges nordligaste kuststad och porten till Kosterhavets nationalpark och norska Strömstads-arkipelagen.", category: "Region", emoji: "🏴", readTime: "7 min", fullContent: true },
  { slug: "hano-guide",                   title: "Hanö guide – Blekinges ytterskärgård och ostindiefararen", excerpt: "Hanö är Blekinges mest dramatiska ö med rik historia kring engelska sjömän och ostindiefararnas tid. Guide till den lilla pärlans hemligheter.", category: "Region", emoji: "⚓", readTime: "6 min", fullContent: true },
  { slug: "bastad-guide",                 title: "Båstad guide – tennis, sommareliten och Bjärehalvön", excerpt: "Båstad är Hallands mest exklusiva sommardestination med world-class tennis, vackra klippor och Bjärehalvöns natur.", category: "Region", emoji: "🎾", readTime: "7 min", fullContent: true },
  { slug: "skargard-instagramguide",      title: "Skärgårdens vackraste platser – guide för fotografer", excerpt: "De bästa platserna för foto och inlägg i Stockholms skärgård. Solnedgångar, klipphällar och utsiktspunkter som fotografer och resenärer älskar.", category: "Aktivitet", emoji: "📸", readTime: "7 min", fullContent: true },
  { slug: "wellness-retreat-skargarden",  title: "Wellness och retreat i skärgården – lugn och återhämtning", excerpt: "Skärgården är den perfekta platsen för wellness och mindful-semestern. Yoga, meditationsleder och stillahavsanläggningar bland öarna.", category: "Praktisk", emoji: "🧘", readTime: "6 min", fullContent: true },
  { slug: "brollop-skargarden",           title: "Bröllop i skärgården – guide till drömbröllopet", excerpt: "Skärgården med havsutsikt och klipphällar är en av de vackraste bröllopsplatserna i Sverige. Guide till lokaler, transport och planering.", category: "Praktisk", emoji: "💍", readTime: "7 min", fullContent: true },
  { slug: "orust-guide",                  title: "Orust guide – Bohusläns största ö och båtbyggarnas hem", excerpt: "Orust är Bohusläns och Sveriges tredje största ö. Känd för sina varv, kustsamhällen och vackra klipplandskap. Komplett guide.", category: "Region", emoji: "⛵", readTime: "7 min", fullContent: true },
  { slug: "sensommar-bohuslan-2026",      title: "Sensommar i Bohuslän 2026 – klippor och ostron i aug–sep", excerpt: "Sensommaren förvandlar Bohuslän. Turisterna försvinner, ostronsäsongen öppnar och klipphällarna är tomma. Guide till aug–sep 2026.", category: "Säsong", emoji: "🍂", readTime: "6 min", fullContent: true },
]
